### ISSUE TITLE
USDC Integration - Processes

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#1]

**Comment by pellarboss** [comment]
[KYC+Standards+for+Reliance+-+v+1.3.pdf](https://github.com/pellartech/curate/files/6737629/KYC%2BStandards%2Bfor%2BReliance%2B-%2Bv%2B1.3.pdf)

Task 1 is to fully understand their KYC requirements, and align our KYC with what they need.
This means: 
* understand where the users are (USA or SA or?)
* understand what info we need to collect for where
* make changes to our current KYC process so it can be done

**Comment by DefiHunter** [comment]
Feedback from circle 

- KYC is not required, they prefer to keep it simple and just KYC Curate as a business. Thus Curate is in control of user KYC

- Chargeback, you were spot on Roy, 12-14 days is recommended

**Comment by pellarboss** [comment]
Correct, but between us, we need to decide what the KYC process is, and when to do it, this should be clearly agreed to with Circle.

Because if Circle is doing KYB for Curate, Circle will hold ALL of funds from ALL users if ONE user stuffs up. 

In the case of Dispute, if we had a good KYC process, the dispute is more likely to rule in our favour

Chargeback:
- how exactly do we do this?
- hold NFTs for 14 days before you can resell?
- or hold XCUR XC20 for 14 days before you can use / withdraw?
- what other potential loop holes are there to prevent someone from using a stolen credit card?

**Comment by DefiHunter** [comment]
Would  allowing users to use XCUR XC-20 but disable withdrawals work ?

**Comment by pellarboss** [comment]
No it wouldn't
you can circulate the funds using buy / sell / send (in the future)

you will essentially need to ask the user not to use XCUR, which kinda defeats the process of accepting usdc

i think the options are:
- negative experience for the person who deposit - no circulation for 14 days
- barrier for everyone - no withdraws without KYC, can't resell unless 14 days days after purchase
- hybrid, but might cause issue in dispute process if challenged - all users deposit with usdc, can't withdraw or sell unless 14 days passed

have a think about it and design something :)

**Comment by DefiHunter** [comment]
Initial User 

For Credit Card purchases - Full KYC required , Identification and proof of address

Initial limit $500 
- if after 2 weeks user doesn’t have a charge back, Limit is increased to $1000 , if no charge back then after 1 month limit is increased to $2000

Users who purchase with credit card cannot withdraw for 2 weeks, if charge back happens, user account is blacklisted and reported 

User is free to spend within the app, Curate to bear the costs of chargebacks but will take all measures to ensure its minimized

Curate to take an extra 0.5% processing fee for credit card purchases. 

Outsource KYC partner to Onfido 


Here's my thoughts on a solution 
Results - Best user experience 
Drawback - Managing bad debts

**Comment by DefiHunter** [comment]
No wthdrawl for 2 weeks of purchased funds with CC

**Comment by DefiHunter** [comment]
Non- KYC User

- All features excluding - Fiat Purchases/withdrawals - USDC on-chain is still allowed 

Full KYC User 

- Fiat Purchases with CC and withdrawals to Bank account 



To me the above would be the only difference

**Comment by DefiHunter** [comment]
Here are some resources we discussed to help you and your team learn more about working with Circle:
Circle Account Signup -- Free to use, 1-to-1 USD <> USDC -https://t.sidekickopen84.com/s3t/c/5/f18dQhb0S7kF8bq5d-W1K7Z1759hl3kW7_k2841CXdp3MQ0CLFt_T0dW2dykfZ4R4B__101?te=W3R5hFj4cm2zwW4hLZh_1JxwpMW3F9b_03Fbt5SW4cKJQM4hKDbGW3T1lc23T3Sdj4SZ_r1&si=8000000006231803&pi=ca9fbd62-2ccc-45ec-b1ed-d78700233279


Sandbox Signup -- Mirrors production environment, but with "fake" USDC

https://t.sidekickopen84.com/s3t/c/5/f18dQhb0S7kF8bq5d-W1K7Z1759hl3kW7_k2841CXdp3MQ0CLFt_T0dW2dykfZ4R4B__101?te=W3R5hFj4cm2zwW3___hS3zdYT6W43YGX13T2-JzW3JFvq33_rjjXf3P4fn404&si=8000000006231803&pi=ca9fbd62-2ccc-45ec-b1ed-d78700233279

Country Coverage

https://t.sidekickopen84.com/s3t/c/5/f18dQhb0S7kF8bq5d-W1K7Z1759hl3kW7_k2841CXdp3MQ0CLFt_T0dW2dykfZ4R4B__101?te=W3R5hFj4cm2zwW3H4THp3ZZnXLW49Rd2r3T2-JzW3JFvq33_rg_XW3Fd1BJ4hKKYcW49RLlR1Gy-r3w41YztQb732&si=8000000006231803&pi=ca9fbd62-2ccc-45ec-b1ed-d78700233279

API Docs

https://t.sidekickopen84.com/s3t/c/5/f18dQhb0S7kF8bq5d-W1K7Z1759hl3kW7_k2841CXdp3MQ0CLFt_T0dW2dykfZ4R4B__101?te=W3R5hFj4cm2zwW3H4THp3ZZnXLW49Rd2r3T2-JzW3JFvq33_rg_XW3Fd1Bw41YztXW3HcvCt41S2fpW3T2-Jz3JF3M-3b772&si=8000000006231803&pi=ca9fbd62-2ccc-45ec-b1ed-d78700233279

**Comment by pellarboss** [comment]
#144 implements USDC

**Comment by DefiHunter** [comment]
Lets rearrrange this to reflect the Phase 2 implementation of Circle 

- Fiat Withdrawls
