### ISSUE TITLE
Add item name and button link in emails

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#103]
For the you've been outbid emails and other emails we send let's add more info such as item title, a call to action button taking to the app etc

**Comment by DefiHunter** [comment]
Change text to - You've been outbid

Embed Deep link in email to product.

I.e Embed a button in the email, that the user can click on to go directly to the product in app

**Comment by pellarboss** [comment]
we can't do deep linking from email to app (currently at least)
lets just do name of the product for now
