### ISSUE TITLE
Faster live rates for XCUR when buying

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#108]
![20210708_110209](https://user-images.githubusercontent.com/51517619/124909286-2e75b100-dfe2-11eb-890d-bc7df036d397.jpg)

![20210708_110207](https://user-images.githubusercontent.com/51517619/124909290-2fa6de00-dfe2-11eb-9d72-4ab2a3100aa3.jpg)

Add a message on the preview page that although the best rate will be taken, rates will vary.

If possible can we make the rates refresh faster or add a timeout/refresh update?

**Comment by madtocc** [comment]
we are pooling the server at every 60s to refresh the rates. Do u want to reduce the time? Or maybe we can use a web socket to update the rates in real time

**Comment by curateproject** [comment]
Yes real time rates would be great please with still a disclaimer on that page to cover us in case of volatile markets

**Comment by pellarboss** [comment]
we fetch data from kucoin once every 45 minutes, we've changed this to 15mins

Marco, no need to increase poll on UI
