### ISSUE TITLE
P2P Marketplace 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#109]
P2P Marketplace : 

- Allow users to : 
 List products for sale, for a fixed price 
Users can purchase using XCUR, USDXC or ETH 

Curate to provide 
Escrow 
Same commission model as NFT marketplace 

Users to : 
Provide tracking information and are responsible for shipping 
- Picture of item upon receipt 
- Tagging to track status of shipments 

Open for discussion 
@curateproject pls provide any flows and frames we have already for this 

Im thinking we could add a new tab in app called "Physical marketplace"

Opening this up for discussion and to share ideas and thoughts

**Comment by toomingos** [comment]
There's definitely a good conversation to have about the layout and how we're displaying both markets on the app. What do you guys think about merging both together, whether it's the random, trending, and featured items pages? This will allows the user to have the power of choice because they can interact with the filters and tags. This way they can make their experience as they see fit.

In order for this to work I think we should add the following:
-Physical item tag
-Tags on the Approve/deny admin page so we can tweak it. i.e. if some random user puts art on a clothing piece we can tweak it.

**Comment by curateproject** [comment]
Physical Goods Marketplace:

Allow users to:
List products for sale, for auction and fixed price
Users can purchase using XCUR, USDXC or ETH

Curate to provide:
Escrow - hold funds as pending until buyer confirms goods are received
Same commission model as NFT marketplace

Seller Requirements:
Seller required to press 'item sent' once item is shipped and is then asked to upload receipt/proof of shipping with tracking number and carrier details (this plus the receipt is shared with the buyer), tracked/recorded delivery is a requirement (can not be unrecorded) to limit potential fraud.

Flow:
1. Buyer wins item (either on auction or via buy it now/fixed price)
2. Email and in-app notifications are sent to the seller and buyer of item sold
3. Seller receives pending funds in XCUR (which remain locked until the buyer confirms goods received as per below)
4. Seller ship items via recorded delivery in the real world, returns to app and goes to my profile 'sold items' tab and clicks on item then clicks 'Mark sent' where they are required to upload proof of receipt (and item packaging if they want but needs to be receipt) then enters the tracking number and courier name details (both these fields requirements)
5. Buyer receives email and in-app notification that item has been sent
6. Buyer confirms item received
7. Buyer and seller receives cash back reward
8. Both parties are invited to leave feedback, this shows on the 'My profile' page

Thoughts @toomingos @DefiHunter @madtocc @pellarboss

**Comment by pellarboss** [comment]
Phase 1 suggestion (so we can make Aug 30th)
- XCUR only for now
- fixed price sales for now
- to prevent fraud, how about set a max number of items that can be listed to be 3?
- the same verified flag is available
- no feed back mechanism in phase 1
- eveything else is ok

to be absolutely clear:
- seller lists item in xcur with photos, title, description
- buyer can browse items
- buyer can choose item and buys the item
- seller receives funds, locked, funds are deducted from buyer
- seller sends item, provide package information in app - tracking number + photo of parcel
- buyer receives item, mark as received
- seller funds unlocked <- we should impose a 2 week timeout after funds received - consider various scenarios where this could go wrong and have preventative resolutions in place
- both seller and buyer receives reward, xcur platform collects fee
- both buyer and seller's successful trade count increases by 1 - visible via profile

**Comment by curateproject** [comment]
Happy with everything you suggested above @pellarboss let's go for it!

**Comment by curateproject** [comment]
@pellarboss @DefiHunter thoughts on listing items on the p2p marketplace in USD as opposed to XCUR i.e when listing a price for sale ask for the starting auction or buy it now price in USD?

Will make it easier for non crypto users to list in USD is my thoughts

**Comment by curateproject** [comment]
Great job @madtocc @pellarboss - looking promising, just a 7 bugs/tweaks before we push it to production:

1. Reduce min characters to 50 for description
2. Add 'Countries Shipped To' on 'Sell Product' (add a drop down box of countries with these at the top: United States of America, United Kingdom, Canada, Australia, India)
3. For each country selected the seller needs to add an additional shipping price in XCUR which is displayed on the listing page
4. BUG: Stuck 'Review Purchase' page when trying to buy an item
5. Limit 1 sale per user for now (can you make this configurable in admin panel where we can set the max sale limit per user as a number and have this option disabled once we're ready to remove the restriction)
6. Let's stick with imposing a 2 week timeout after funds received for seller to prevent fraud/scams
7. Add quantity field when listing an item so sellers can sell more than 1

**Comment by pellarboss** [comment]
@madtocc lets do:
1 - reduce min char limitation
4 - resolve bug

5&6 i will create separate tickets on our internal 

2,3,7 - created 227 (for v3)

**Comment by madtocc** [comment]
1 4 are done

**Comment by pellarboss** [comment]
@curateproject what does this mean
> Let's stick with imposing a 2 week timeout after funds received for seller to prevent fraud/scams

Does it mean:
1. buyer buys item for 100 XCUR
1. seller does not send item? hence the 100XCUR is returned to buyer after 2 weeks? if seller does not send the item?

How about:
1. buyer buys item for 100 XCUR
2. seller ships item
3. buyer does not confirm receiving order - hence it should be auto release funds to seller after 2 weeks right?

**Comment by curateproject** [comment]
Hi @pellarboss this is what you wrote above:

_seller funds unlocked <- we should impose a 2 week timeout after funds received - consider various scenarios where this could go wrong and have preventative resolutions in place_

So the scenario:

1. buyer buys item for 100 XCUR
2. seller receives in-app notification and email of item sold
3. seller ships item and adds tracking number and uploads picture of receipt/tracking within the app
4.IF buyer does not confirm receiving order - funds should not autorelease (in case there are postal delays etc..) - we should add a message on the buyer 'Orders' page for the 'Shipped' section 'If 28 days have passed and you have not received the item, please contact support@curate.style;
5. If buyer receives item and confirms order, inapp notification/email is sent to seller confirming funds are unlocked

**Comment by pellarboss** [comment]
OK, in your scenario in case there is an exception, contact support right? maybe thats a better solution than auto fund release

**Comment by curateproject** [comment]
Yes @pellarboss let's not allow auto fund release as there may be reasons for delays (postal, strikes etc) or users trying to game/scam the system

A simple message like the one below on the buyer  shipped page will be fine:

'If after 28 days you have not received your item, please contact support@curate.style with your app email address and item details and we will investigate'

**Comment by pellarboss** [comment]
status update and new features planning:

> 1. Reduce min characters to 50 for description
done

> 2. Add 'Countries Shipped To' on 'Sell Product' (add a drop down box of countries with these at the top: United States of America, United Kingdom, Canada, Australia, India)
aim for next week

> 3. For each country selected the seller needs to add an additional shipping price in XCUR which is displayed on the listing page
aim for next week

> 4. BUG: Stuck 'Review Purchase' page when trying to buy an item
fixed

> 5. Limit 1 sale per user for now (can you make this configurable in admin panel where we can set the max sale limit per user as a number and have this option disabled once we're ready to remove the restriction)
planned for end of this week

> 6. Let's stick with imposing a 2 week timeout after funds received for seller to prevent fraud/scams
> 'If after 28 days you have not received your item, please contact support@curate.style with your app email address and item details and we will investigate'
allow users to raise support requests - planned for this week

> 7. Add quantity field when listing an item so sellers can sell more than 1 
planned for next week
