### ISSUE TITLE
Import NFTs

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#11]
Ability to receive a NFT from an external system

**Comment by DefiHunter** [comment]
Suggested deposit Flow 
**Deposit**
User Deposits NFT into his Unique ETH address


Masterwallet records this deposit and allocates NFT to user 

Masterwallet sends eth to user ETH address and "sweep"s NFT into Masterwallet 

**Withdrawl**

User inputs ETH address 
User requests withdrawal 
Masterwallet sends NFT to user external wallet

**Comment by DefiHunter** [comment]
@pellarboss Could we add this to sprint 5?

**Comment by DefiHunter** [comment]
Note to prevent Gaming of System, 

Only Imported NFTs and NFTs on the secondary market are available for withdrawal 

i.e User A mints NFT Z , User A then immediately tried to withdraw NFT Z = Denied
    User A Mints NFT Z, User A sells NFT Z to User B , User B can withdraw - Approved 
    User imports NFT , Can withdraw NFT at anytime 

@pellarboss note and let me know ur thoughts
