### ISSUE TITLE
BUG: Notifications not showing on iOS

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#110]
iOS users seem to not get in-app notifications, please can you confirm, since me and @DefiHunter haven't got any so far.

**Comment by madtocc** [comment]
can you elaborate? which notification you haven't received? So I can track if it was delivered or not?

Did you login with your user on Android or another phone/tablet?  I guess the notification is currently being sent only to the device you did your last login.

**Comment by madtocc** [comment]
just tested on Testnet and I did receive the notification on iOS
![IMG_0006](https://user-images.githubusercontent.com/12486417/125123992-cdc3a280-e0cd-11eb-9925-c75dc2402a6f.PNG)

**Comment by pellarboss** [comment]
please uninstall and reinstall the app again
please ensure your notification settings are turned on
