### ISSUE TITLE
BUG: Bid/Buy buttons not showing

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#111]
These two products don't have a bid/buy button available, one's on auction the other on a fixed price. Both are approved and active on the admin page.
![image](https://user-images.githubusercontent.com/86632157/125055200-dc469580-e09e-11eb-8a13-9e8d06b18901.png)
![image](https://user-images.githubusercontent.com/86632157/125055268-e8325780-e09e-11eb-9249-65d029dd1938.png)
![image](https://user-images.githubusercontent.com/86632157/125056428-2419ec80-e0a0-11eb-90e4-12d657fb5e14.png)
![image](https://user-images.githubusercontent.com/86632157/125056451-28460a00-e0a0-11eb-95be-544e698eb9b4.png)
![image](https://user-images.githubusercontent.com/86632157/125056466-2bd99100-e0a0-11eb-9304-0e471e362d8e.png)

**Comment by DefiHunter** [comment]
Roy , Please investigate

**Comment by pellarboss** [comment]
please provide URLs in the future for easier investigation.

https://admin.curate.style/product/175b4e4e045057f3466384d7/detail
https://admin.curate.style/product/ca08b23ac9daefba9f2d7ba0/detail

these two items are not set to be online, not available for sell, the owner has to "Sell" this item after buying it, do you want us to make it available for sell?

**Comment by pellarboss** [comment]
@toomingos @DefiHunter let us know

**Comment by toomingos** [comment]
Sounds good, sent it to the telegram mods

**Comment by toomingos** [comment]
![image](https://user-images.githubusercontent.com/86632157/125095657-52152600-e0cc-11eb-96b5-5565a47cd5b9.png)
Seems like he cant put them for sale

**Comment by madtocc** [comment]
Could he send a screenshot of the "My Nfts" including the particular nft of interest and another of the nft detail?
If he can't, could he let us know if under my nfts the current nft shows "On Sale XX XCUR" or "XX XCUR"

e.g
To me the "FEG LIFE" is offline, so the output should be "52 CUR" and upon click on the NFT the "Sell NFT" button is supposed to be there

**Comment by pellarboss** [comment]
we made it on sale now :)

**Comment by DefiHunter** [comment]
@madtocc @pellarboss , Another user has brought this issue to my attention rn, it seems to be recurring.

Could we get this dissected and solved as a priority pls 

They have noted it is ever since the latest update push to prod

**Comment by pellarboss** [comment]
@DefiHunter could you please provide more info? we can investigate further when we have a bit more details, ie name of the item?

**Comment by DefiHunter** [comment]
The users email is stepicxnft@gmail.com

I'll share more details as I receive
