### ISSUE TITLE
Easter Egg: Double Tap App Version number

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#114]
When double tapping the app version number the following MP3 below is played, feel free to cut down the mp3 if it's too big/long, just need the 'in it for the tech' bit mainly.

MP3 File:
https://drive.google.com/file/d/1A65RsSLGr9XGVzlzAdmlO7aTNUoAGt3G/view?usp=sharing

**Comment by madtocc** [comment]
Do you want to show a toast msg as well? If the phone is muted they won't hear it? How is the behavior, i.e should it play when menu is opened only or keep it playing till it ends?

**Comment by curateproject** [comment]
Yes a toast message/easter egg icon/audio icon to represent something is happening and playing so those on mute know to unmute.

The mp3 should play till it ends even if the menu is closed

**Comment by curateproject** [comment]
Great can't wait, can you send a production build today @madtocc ?

**Comment by madtocc** [comment]
yes!
