### ISSUE TITLE
UX Text Update: Tx History

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#115]
Can you make the following text updates on the tx history pages please:

https://tinyurl.com/yhlsq72n

https://tinyurl.com/ygoksww4

https://tinyurl.com/ye7xz74a

**Comment by curateproject** [comment]
And also add to the terms of service page:

Fiat T&C’s


1.5.4.15 Credit Refund Requirements 
A Merchant may establish its own credit refund policy, but must disclose it as specified in Section 5.4.2.5, Disclosure to Cardholders of Return, Refund, and Cancellation Policies 

A Merchant must not: 
l Accept payment from a Cardholder for the purpose of depositing funds to the Cardholder’s account 
l Process a Credit Transaction Receipt without having completed a previous retail Transaction with the same Cardholder 
These restrictions do not apply to: 
l The loading of value to a Prepaid Card that participates in the Visa Prepaid Load Service 
l In the US Region: The loading of value to a Prepaid Card or to another non-Visa-branded account that participates in Visa ReadyLink

To the extent possible, the Merchant must process a Credit Transaction to the same Payment Credential as used in the original Transaction. 
l If unable to process the Credit Transaction to the same Payment Credential, the Merchant may either:
 – Process the Credit Transaction to a secondary Payment Credential, if available, and if a Transaction Receipt or other proof of purchase exists, and either: 

▪ The original Payment Credential is unavailable (account is closed, transferred, reported lost/stolen). 
▪ An Authorization Request for the Credit Transaction2 to the original Payment Credential receives a Decline Response. – Refund the Transaction amount through alternate means (cash, check, in-store credit, or prepaid card), if any of the following conditions apply: 
▪ The Cardholder does not have a Transaction Receipt or other proof of purchase. 
▪ The customer is not the original Cardholder and is returning a gift. 
▪ The Cardholder claims that the Prepaid Card used for the original purchase has been discarded. 
▪ The Authorization Request for a Credit Transaction to the original or secondary Payment Credential receives a Decline Response. 

In the AP Region (Australia, New Zealand), Europe Region, US Region, US Territory: The Merchant must refund any surcharge3 assessed on the Transaction amount. For partial refunds, the surcharge3 amount must be pro-rated.

1.5.5.1 Prohibition of Minimum or Maximum Transaction Amount 
A Merchant must not establish a minimum or maximum Transaction amount as a condition for honoring a Card. 

This does not apply to a European Economic Area Transaction.

This does not apply to a Transaction initiated with a Credit Card issued in the US Region or a US Territory used at a Merchant Outlet in the US Region or a US Territory, as specified in Section 5.4.2, Conditions of Card Acceptance and Cardholder Rights

**Comment by madtocc** [comment]
Note was updated on the server side, so for now on it will display the name and the text provided. Part of this issue was done on #75 , let's try to keep stuffs on the same page and different things like the ToS update on another issue. 
Regarding the click on the NFT and redirect it will need some changes on the backend, since we don't the id anymore so I will create a new issue to support it #123
