### ISSUE TITLE
Sort marketplace by algorithm as default

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#121]
Can you default sort the marketplace by the following metrics:

- Bids
- Verified Badge
- Likes
- Views

Each metric will carry different weights.

Algorithm:
0.45*(bids)+0.25*(likes)+0.2*(views)+0.10*(badge)

**Comment by toomingos** [comment]
My suggestion for the formula would be:

0.4*(bids)+0.25*(likes)+0.2*(views)+0.15*(featured artists)

**Comment by curateproject** [comment]
> My suggestion for the formula would be:
> 
> 0.4*(bids)+0.25*(likes)+0.2*(views)+0.15*(badge)

Yes let's go with this @madtocc

**Comment by toomingos** [comment]
Im afraid the 0.15 on the badge might be too much of a boost, let me know what you guys think

**Comment by curateproject** [comment]
I've tweaked it

**Comment by pellarboss** [comment]
Conflict with #129

**Comment by DefiHunter** [comment]
Just to confirm if this is coming to light ?

0.45*(likes)+0.25*(bids)+0.2*(views)+0.10*(badge)

And this is the formula I would go with - I've swapped likes and bids - Since some items have fixed prices

**Comment by DefiHunter** [comment]
Old - Closing
