### ISSUE TITLE
[APP] Profile Discovery

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#124]
Users can discover other users

You can tap on other users in product detail to see their profile

You can tap my followers and my followings to see a list of users - follow insta's UX here 
tap, screen swipes left, show a list of users, tap back to go back to profile

In Product Listing, when you search for a term, if that term matches a user name, the user is displayed, see the mocked up UX
![Users](https://user-images.githubusercontent.com/24906507/126242732-4373f139-2039-4f89-b169-66e210b67260.png)

**Comment by curateproject** [comment]
Approved let's go ahead with this @pellarboss @madtocc
