### ISSUE TITLE
Manual Withdrawl Notification

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#131]
Send a Notification email when there's a pending withdrawal that needs to be manually approved to 

Moe@curate.style
Calum@curate.style
james@curate.style

**Comment by pellarboss** [comment]
we will send an email to "operations@curate.style"
this will avoid changes in the future
in google admin, you can create a group email (using groups), where you can distribute from Operations to any other emails

**Comment by DefiHunter** [comment]
That works, i will get the email setup

**Comment by curateproject** [comment]
@DefiHunter we may need to pay to setup a new email, @pellarboss could you have the email sent to support@curate.style as this what we all check on a daily basis

**Comment by DefiHunter** [comment]
Emails already setup

**Comment by DefiHunter** [comment]
Better to have this separate as too many people have acccess to support

**Comment by curateproject** [comment]
Hmm it might be better for support staff to actually see these emails if we use support@curate.style so staff can inform  myself or you to approve.

I want less reliance or yourself or me to check one inbox...

**Comment by DefiHunter** [comment]
Sounds good

**Comment by pellarboss** [comment]
Withdrawal notification is now in place
