### ISSUE TITLE
Agent User Accounts

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#133]
Option for admin to choose user as 'agent' which removing security (email code verification) when someone logs in from another IP address, as agent will be in different GEO/IP and share the account with the celeb.

**Comment by pellarboss** [comment]
could someone help to understand this ticket? we do not recommend operating an account on behalf of someone else
this will essentially mean you will pass credentials over email or chat, which is very insecure

a better way to do something would be: as user A do all the things you need to do, for example, create products, then create a ticket for us to assign which product to which user. We can even batch this once every week (we operate in a much more security), and there is no credentials sharing.

**Comment by DefiHunter** [comment]
Yes i agree 

 I Believe a sub account feature is more what we looking for 
I'll try mapping it out below 

Main Account can create sub accounts 

Main account can adjust a Royalty split and a revenue split with the sub account on a sliding scale 

Sliding scales:
Royalty split
0 -100 % of royalty

Revenue split

0-100% of revenue

**Comment by curateproject** [comment]
Yes like you said @DefiHunter
