### ISSUE TITLE
Enhancement - Affiliate Programme 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#136]
For every user you refer receive $15 in XCUR (That make a succesful purchase over $100)

All rewards to be received in XCUR
All referred users purchases to be above $100 each 

**Refererr**
Refer a 100 users that make a purchase , Receieve a $500 Bonus 

Refer a 1000 users that make a purchase - Recieve $3000 Bonus 

Refer 2000 Users that make a purchase - Receive $6000

Refer 5000 Users that make a purchase - Receive $15 000

Refer 10 000 Users that make a purchase - Receive $30 000 

Refer 20 000 users that make a purchase - Receive $60 000

Refer 40 000 Users that make a purchase - Receive $120 000

Refer 80 000 Users that make a purchase - Receive $240 000

**Referee**

Min purchase amount = $100 to qualify 

After your first purchase over $100 get $15 in XCUR 

After 50 - Recieve $75

After 100 Purchases - Recieve $150

After 250 purchases - $375

After 500 - Receive $750

After 1000 - Receive $1500

After 2000 purchases - $3000

After 5000 Purchases - $7500

After 10 000 Purchases - $15000

After 20 000 Purchases - $30 000

After 40 000 Purchases - $60 000

**Comment by DefiHunter** [comment]
Open for Discussion

**Comment by curateproject** [comment]
I'm happy with this @DefiHunter 

@pellarboss what's your thoughts?

**Comment by curateproject** [comment]
@pellarboss is this live in the APK @madtocc sent me?

**Comment by pellarboss** [comment]
does this conflict with the current affiliation / referral system, a different mechanism is deployed and agreed to.

**Comment by DefiHunter** [comment]
Its an enhancement - That adds more rewards when you refer more people

**Comment by DefiHunter** [comment]
Please confirm if this is live @pellarboss

**Comment by DefiHunter** [comment]
In that case @madtocc lets also update the text on the referral screen to reflect this - I feel a table format could be nice

**Comment by pellarboss** [comment]
moving out of 1.7

**Comment by DefiHunter** [comment]
To Clarify - User still gets initial $10 for their first purchase over $100 

This is an enhancement - meaning if a user refers a 100 users who make a purchase  over $100 each - They would receive the $500 bonus stated above
