### ISSUE TITLE
NFT Collection

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#14]
Ability to create a collection and add NFTs to that collection

**Comment by DefiHunter** [comment]
To have a "featured collections" section on the Home Page too

**Comment by curateproject** [comment]
My thoughts:

- Add a sub menu item under Home and Marketplace tabs: 'Collections'
- Collections will display all the NFTs listed as part of a collection
- Display them with the collection art work and not individual listings
- On mint page add new field 'Collection?' allowing the user to add NFT to a collection (create new or select existing collection they created) and upload cover art work for collection (keep size requirements uniform i.e set pixel dimensions)
