### ISSUE TITLE
OutBid Email - Deep Linking

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#141]
Include a page link to the item within the Outbid email that users can click on that takes them straight to the product 

![image](https://user-images.githubusercontent.com/72095738/127114971-76a9b180-751d-4da4-8474-b02631d64939.jpeg)

**Comment by pellarboss** [comment]
we can include product name in the email but not deep linking in this release
we can do more release on deep linking in next phase

**Comment by DefiHunter** [comment]
This tickets for deep linking - pls move this ticket to where you feel comfortable having it

**Comment by DefiHunter** [comment]
Keep this ticket open @pellarboss  and just move it to a milestone it can be done in

**Comment by DefiHunter** [comment]
@pellarboss

**Comment by DefiHunter** [comment]
Has this been completed ?

**Comment by eventang2015** [comment]
implemented code in staging, needs to run script .

**Comment by eventang2015** [comment]
generated sharing url for users,collections and products in production.
