### ISSUE TITLE
[USDC] - Phase 1 Implementation - Ver 2.0 Target 

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#144]
After examining Circle's API documentation, fund flow, this is our recommendation for Phase 1 implementation

Feature:
- enable user to recharge USDXC using Credit Card

End User Process - 1st time
- user clicks Deposit on USDXC in app
- completes credit card form, including billing address, cvv
- views pending message
- waits for some time
- receives notification that the funds are available to be used
- user can buy XCUR using USDXC

End User Process - 2nd time
- user clicks Deposit on USDXC in app
- user enters cvv again, enter amount (no need to reenter card details)
- views pending message
- waits for some time
- receives notification that the funds are available to be used
- user can buy XCUR using USDXC

End user is able to remove associated card details from Payment Details in settings

Server Process:
- System creates a card in Circle
- System charges the card created in Circle
- System checks every minute if the charge is complete
- If the charge is complete, release funds to user

Fund Flow States 
- Pending = credit card processing is in place 
- Completed = credit card charged
- Failed  = card charge failed 
- Settled = usdc is in your circle account

Need clarification with Circle (im already in conversation with Allison)
- Pending > Complete - hopefully this only takes minutes
- Complete > Settled - this will take 3-4 days

What do we do? Options:
1. Issue and lock tokens on Pending, unlock tokens on Complete - minutes - high risk
2. Issue all tokens on Complete - minutes - some risks, good user experience
3. Issue tokens on Complete, unlock only on Settled - this will take days, least risk, but worst user experience

----

To be 100% clear, these features are excluded
- USDC deposit 
- Wire transfer 
- USDC withdraw

After the above, we need to be 100% sure about KYC

**Comment by DefiHunter** [comment]
Lets go with Option 2

And then for user withdraw - we follow the 14 Day rule we discusssed prior

**Comment by pellarboss** [comment]
Decision made: User wears all fees (in slack)

**Comment by DefiHunter** [comment]
USDC deposit
USDC withdraw

Above 2 features are crucial to have too

**Comment by pellarboss** [comment]
USDC deposit and withdraw is now available
USDC ERC20 automatically gets converted to USDXC

**Comment by curateproject** [comment]
Thanks, shall we test in staging or production? i.e USDC deposit?

**Comment by pellarboss** [comment]
probably should test when production is ready, ie, when we are ready to deploy this release, we will make a production build ready for us first, so we can test some USDC deposit & withdraw

**Comment by DefiHunter** [comment]
Happy with that idea Roy - Lets setup the call with circle soon - If you happy feel free to send them over the build to test
