### ISSUE TITLE
Urgent - BUG - My Collection

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#146]
"Iv got a problem with my app I can't seem to view my full collection of NFTs. When I go to "my collection" it doesn't show more than 25 and that is filled with denied nfts when I started on the app. So problem I'm having I can't see everything"

- From user 

Seems to be a bug displaying all owned NFTs in the collection Tab 
See below video :

https://user-images.githubusercontent.com/72095738/127372162-bc76b951-ed74-481b-b947-1e5233aad45a.MOV

**Comment by curateproject** [comment]
Let us know your thoughts @madtocc

**Comment by madtocc** [comment]
The video shows the previous app v1.5.0, which didn't have load more items implemented under my collection. Current version 1.5.5 should have it. I'm just not sure if it is available in the released version (have to double check). We will release a new version soon with the selling/sold nfts included and with this fixed (the problem itself is fixed just maybe not released).

**Comment by pellarboss** [comment]
@DefiHunter - who is this user? please ensure we include user emails / keys in all future tickets, so we can take action immediately

**Comment by curateproject** [comment]
@DefiHunter please note to give email/keys going forward

@madtocc yes that would be great thanks

**Comment by DefiHunter** [comment]
USER EMAIL : chrisgiblinfx92@gmail.com

**Comment by pellarboss** [comment]
we have removed 10 denied NFTs for him, lets see if this addresses his issues

**Comment by DefiHunter** [comment]
Issue still persists 

See below screenshot and info from the same user 

Msg from User
"Hi Moe is any ETA on the issue log with Devs about resale of NFTs bug and that issue with my collection? It doesn't display anything at all now. Will delete and reinstall app to see if it helps"

![image](https://user-images.githubusercontent.com/72095738/127668762-b91ab902-5167-43a0-bcad-5a3ad0ba9221.jpeg)![image](https://user-images.githubusercontent.com/72095738/127668772-d1d15c63-38d1-418d-8fc4-02a5f08820d5.jpeg)

**Comment by madtocc** [comment]
@DefiHunter The update hasn't been released yet how did he test it? and apparently user didn't update his app to the latest version. Regarding the release the ETA is on Monday.
![image](https://user-images.githubusercontent.com/12486417/127670096-e8cee7a2-a9e7-401a-9559-6e1862eaf861.png)

**Comment by DefiHunter** [comment]
Okay I'll advise

**Comment by madtocc** [comment]
retrieved user products in the latest app. Can see his products
![image](https://user-images.githubusercontent.com/12486417/127671769-8bc6b940-eeb8-400f-9a75-7d326fe899c3.png)

**Comment by madtocc** [comment]
Ask him to update, to app 1.5.5
If there's any problem loading more the updated version on Monday will fix it
