### ISSUE TITLE
Bids section

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#147]
Can you add a section on the bidding page  which shows you the listings you've been outbid on?

We've had users who receive the email they've been outbid but they can't find which listing it was.![Screenshot_20210728-210342.jpg](https://user-images.githubusercontent.com/51517619/127388276-ca1dc25a-7d2b-4b65-bd2e-e6d7990ef22a.jpg)

**Comment by madtocc** [comment]
yes, I was thinking about including the OUTBID (RED) or WINNIG/HIGHEST BID (GREEN) on the list. is that ok?

**Comment by curateproject** [comment]
Yes that would be great
