### ISSUE TITLE
Resale NFT bug

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#150]
https://user-images.githubusercontent.com/86632157/127665177-4cbcc671-5609-4d1f-8d0e-14f8e01fc384.mp4

https://user-images.githubusercontent.com/86632157/127665181-ca3a1420-bf5a-4c06-9338-24b1d9dbd894.mp4

![IMG_0054](https://user-images.githubusercontent.com/86632157/127665186-eed37809-4251-4b61-a4bc-76e7738fe9a5.jpg)

**Comment by madtocc** [comment]
@toomingos, please ask the user to update his app. We have tons of changes at every release and I'm pretty sure we did some changes on the resale in the version 1.5.5. 
Suggestion to fix this kind of issue is #151
