### ISSUE TITLE
[APP] Force APP update to latest version

### ISSUE THREAD

**Issue by madtocc** [pellartech/curate#151]
We are having a lot of reports with outdated app versions. At every release we fix a lot of problems and I think we should have a force to update app, so such issues as #146 #150 and maybe others that are probably already fixed won't happen. In my opinion this feature will bring at least 2 huge benefits:

- If we have a major problem or any server change/discrepancy we can force the user to update the app and make this problem goes away for all users.
- users won't have old versions which can contain some bugs that are already fixed. This is a big problem since user still experience a problem that is already fixed and also may waste time trying to find a problem that might does not exist anymore

**Comment by curateproject** [comment]
I really like this idea @madtocc let's do this!
