### ISSUE TITLE
8 UX Minor Tweaks 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#152]
1. Default biometrics/PIN to every 30 mins for all new users
2. Change the text 'Enter your PIN' to 'Enter PIN'
3. Remove 'Buy. Sell. Mint' from My Collection page

4. Change the NFT layout to a dual grid when displaying the NFTs for 'More from user' section
5. Remove the 'BUY' next to the logo at the top on the Buy XCUR page and same for 'Settings' on the settings page
6. Allow MP4 video files to be played in the admin section for NFTs (approved, pending or denied)
7. Change 'Yay 🎉 ' to 'BOOM! 💥' and add under the status pending box 'We aim to review within 48 hours, you will be notified in-app and email once reviewed' 
8. On the profile page add a tab with the following for all users to see:
- NFTs sold
- NFTs minted

**Comment by DefiHunter** [comment]
James , more clarity on Point 4 pls- How would the referral button look ? And how would it differ from the share button ?

**Comment by curateproject** [comment]
Good point, for 4. Let's update the share icon URL to auto include the referral URL

**Comment by DefiHunter** [comment]
That may be weird as it may go completely unnoticed 

Best to keep it how it is now - until we find a better way to portray it

**Comment by curateproject** [comment]
That's the point we need to change it now not later..

@madtocc can you remove the 'my referral code' section from the profile and replace the profile share icon URL with the users referral URL and we'll inform the users once we're live

**Comment by DefiHunter** [comment]
Let’s discuss this and revert back to you

**Comment by DefiHunter** [comment]
Two questions
How would users share their profile then?
How would users know where to find their referral code ?
Pretend a new user signs up and doesn’t follow us on social media . How do
they find their referral code easily ?
What spotlights that it’s a referral code ?

If we can answer these I’m happy to do that
