### ISSUE TITLE
Enhancement - Collection Feature

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#153]
Ability to view the Total Volume Traded on a users profile which is = The total value of the profile owners artwork that is traded within the platform

i.e. if user A sells 10 NFTs for 10 XCUR = His total volume is 100 XCUR 
If user B now sells User A's NFT for 10 XCUR = User A gets 10 XCUR added to his volume 

Lets try and do the same for each individual NFT too and in the future expand to monitor collections like Opensea does

**Comment by DefiHunter** [comment]
Can we see an example of this feature live ? I can't seem to find it

**Comment by pellarboss** [comment]
Yep, in "User detail" page in admin 
see Total Volume
<img width="299" alt="Screen Shot 2021-10-08 at 2 27 37 pm" src="https://user-images.githubusercontent.com/24906507/136493641-3ec31fd9-4599-4372-945d-5ce5d310ff93.png">

**Comment by DefiHunter** [comment]
@pellarboss  This was suppose to be a change within the app so that users can see this info
