### ISSUE TITLE
Export NFT + Cross Chain

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#155]
User requests withdrawl for NFT 

inputs address (ETH, BSC, Polka) and clicks send 

- Admin panel to review NFT withdrawals 

Cross - Chain Withdrawls 

Rule of Thumb - NFTs minted on ETH 

If user requests withdrawl on BSC for example : 

NFT sent to "Wrapping address" - NFT is then minted on the corresponding chain and sent to the users BSC wallet 

If user wants to then go back to ETH and get the "Original" he has to deposit in app and request a withdrawl on ETH , to which then the BSC version would be locked and the ETH version sent to his address

To charge a fee : T.B.A 

Roy look forward to your thoughts on this and how best we could do it 

ETA : Sep/Oct

**Comment by curateproject** [comment]
Need to pass the fees onto the user withdrawing when minting on corresponding chains
