### ISSUE TITLE
[Admin] - Log Admin Approve / Deny Actions 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#156]
1. Log and display the admin email who approved/denied an NFT in the admin panel on the NFT key page
2. Show pending or rejected NFT count on owner key in admin panel
~~3. Can you add the dashboard stats (https://dashboard.curate.style/) on our admin homepage - we'd like to keep this private for now and only viewable by admins~~

**Comment by pellarboss** [comment]
putting #3 in to a separate ticket
