### ISSUE TITLE
API Keys Pull  - Admin Panel

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#157]
API keys to pull data from Admin Panel 

For example :

Pull data for : 

Date, Royalty , User ID and every transaction 

NFT Purchases 

XCUR Transfers 
XCUR Purchases 

Users

**Comment by pellarboss** [comment]
Most of the Data is available to be pulled today
You will need some basic understanding of API integration to do this
Let us know if you have technical staff that would like to call these APIs

That aside thou, CSV data is also available for download via Admin

**Comment by DefiHunter** [comment]
I usually do the API stuff, can it be pulled into a looker analytics tools ?
