### ISSUE TITLE
Extend auction by 5 minutes with every bid

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#158]
To prevent sniping, extend the auction by 5 mins after every bid is made.

We've had frustrated bidders lose out because of snipers, typically auctions extend for 5 mins after every bid to keep the auction fair.

Please can you add this feature Marco

**Comment by pellarboss** [comment]
just to add to this, extend only if time left is < 5 mins :)

**Comment by DefiHunter** [comment]
Yes thats correct PellarBoss

**Comment by curateproject** [comment]
Yes that's right @pellarboss thanks :)

**Comment by eventang2015** [comment]
@madtocc  fed done

**Comment by DefiHunter** [comment]
In staging ?

**Comment by madtocc** [comment]
yes
