### ISSUE TITLE
[APP] proof of work for NFTs  & Tag Limit

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#159]
**1. Verifying 1st Time Sellers**

For 1st time minters, after submitting the NFT, on the pending page add text 'To increase your chances of your NFT getting approved, please complete one of the below':

~~Connect your socials OR~~
Provide proof of work

The 'connect your socials accounts' allows the user to connect their Twitter or Instagram account with Curate - this shows in the pending NFT page for the user.
The 'Provide proof of work' allows the user to email their proof of work to support@curate.style - add a marker in the NFT pending admin page which shows the user selected this option so the admin knows to check the support@curate.style inbox.

~~**2. Existing NFT Sellers** Add an option in settings page ‘Connect socials’ allowing users to connect their twitter or instagram account (they need to verify via twitter/instagram APIs) this then gets displayed on their app profile page as an icon.~~

**3. Edit Tags in Admin and Limit 4 Tags per NFT**
Edit tags in admin for NFT (for pending and approved) and set max 4 tags per NFT on the app when minting

~~**4. For New Minted NFTs Request Properties/MetaData** Add  another description box called ‘MetaData’ allowing users to add on-chain metadata, display the metadata for the NFT on the listing/NFT page i.e just like opensea does for cryptopunks metadata/properties for example attributes/rarity~~ 
linked in #163

**Comment by pellarboss** [comment]
Please keep 1 feature per ticket

Removing Social integration to avoid delaying V2.0

Changes:
1 - For first time creator, add additional text in confirmation page
2 - Limit 4 tags in Minting

**Comment by curateproject** [comment]
Thanks @pellarboss  - For 1. I've added the below:

For 1st time minters who don't provide any of those 2 options (verify socials or email work) can you add a button on the pending NFT page in admin 'Send POW email' which emails the user the email below from support@curate.style:

-----

Hi (username),

	In order to reward and protect the artists and collectors of the NFT Community from counterfeited content and misuse of copyrighted content we require proof of work or ownership. 

For your first time minting we would appreciate if you provided two of the following options:

#1 Twitter Username
#2 Instagram Username
#3 Proof of Work:
Send Screen Recording of the development process.
Send Working File (Specific Softwares: Photoshop, Illustrator)
For Photography, provide a RAW file.

	After gathering two of the above please send the information and files to support@curate.style, we will review your submission. 

After reviewing, if your product submission is approved that means we have acknowledged the submission was likely a product of your work. If the product submission is denied that means you haven’t provided enough proof of work for us to be satisfied.

Note: We will only ask for Proof of Work one time. 

Products will still be reviewed after submission in the future.

Thank you for your understanding,
Team Curate.

-----

Once the POW button has been pressed in admin it'll be great if you can log this on the NFT so admins know to check the inbox.
