### ISSUE TITLE
[APP] Preload Avatars

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#16]
Change My Avatar, can you a selection of 4 pre-loaded avatars for users to select with one of them being chosen by default if they don't choose an avatar (I'll send 4 over to you when you're on this step).

@madtocc please build this feature and obtain 4 avatars from James

**Comment by curateproject** [comment]
Will get this sent over once ready

**Comment by pellarboss** [comment]
<img width="434" alt="Screen Shot 2021-06-23 at 8 59 38 am" src="https://user-images.githubusercontent.com/24906507/123010700-769dac80-d402-11eb-8445-3f7701bd7687.png">

layout recommendations
click on a new avatar will update the main avatar

**Comment by madtocc** [comment]
https://user-images.githubusercontent.com/12486417/123473269-b87b4e00-d5ce-11eb-821d-d6e7d528dc76.mp4
