### ISSUE TITLE
New MetaData Attribute

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#163]
When minting a new NFT, new attribute "Metadata"

Marco, please submit this field in Mint UI

Even, please add this attribute to server

linking #159

**Comment by eventang2015** [comment]
@madtocc new field: meta_data

**Comment by madtocc** [comment]
@curateproject could you please enlighten me:
- this field should show only for 1st time minters?
- Is it a required field or optional

**Comment by curateproject** [comment]
This is for all users and is a required field when minting an nft
