### ISSUE TITLE
Admin panel incorrectly showing wrong number of NFTs sold?

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#165]
In the user admin panel it shows an incorrect number of NFTs sold i.e they have listed less NFTs but have sold more.

Please see screenshot below:

https://www.awesomescreenshot.com/image/11634127?key=cc9de334e55c94a2f623a48b9e9ab7a9

**Comment by pellarboss** [comment]
in staging

**Comment by curateproject** [comment]
Thanks, to confirm shown number of NFTs sold and total XCUR sales count like currently but display it clearer i.e with XCUR next to the XCUR sales total

**Comment by curateproject** [comment]
@pellarboss can you add 'XCUR' to the field which represents xcur amount sold and add total number of 'products sold' count

**Comment by pellarboss** [comment]
<img width="276" alt="Screen Shot 2021-08-16 at 2 23 06 pm" src="https://user-images.githubusercontent.com/24906507/129511223-d41f8a19-b755-49b4-a7de-0d014d8e1b9c.png">

currently in staging

**Comment by curateproject** [comment]
@pellarboss this looks great!
