### ISSUE TITLE
Allow new owners of NFTs to add to the description when reselling the NFT.

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#168]
Add a new field after pressing resale "Add to description".

This new description shows under the existing description when it was minted.

For example:

Minters Original description

----

New owner's description: 6th August:

Hey guys this NFT has become super rare so selling it again

**Comment by madtocc** [comment]
Regarding the feature
do you want to include an owner description when reselling? is it unique or should it be appended? 
mint description:
AA

new owner description
BB

so it will show
AA
--
BB


if another user buys and resells with description CC
should it show like 
AA
--
BB
--
CC

or 

AA
--
CC

**Comment by curateproject** [comment]
AA
---
BB
--
CC

Like this please @madtocc 

Adding a new description each time the NFT gets listed again is optional not a requirement
