### ISSUE TITLE
NFT auction from the balance glitch not showing correct bid

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#169]
Hi there can you check why this NFT is displaying a bid which is not active?

![Screenshot_20210806-212543.jpg](https://user-images.githubusercontent.com/51517619/128567488-54f7de3a-f077-4c37-8ee7-d3faa9999796.jpg)

**Comment by pellarboss** [comment]
https://admin.curate.style/product/12fefdf8f3f733fddb9389e8/edit
779 <- one bid
780 <- current price

----

there might be a time where bid is placed but the price is not immediately reflected, that should refresh under a second thou, we will try to reproduce the issue

**Comment by curateproject** [comment]
In the screenshot the current price was lower the 1st bid.. we tried several times to refresh the page but the price still did not update.

This looks like the previous bid that one the auction when that big occurred so wondering if this got stuck..?

**Comment by pellarboss** [comment]
cant reproduce, maybe because the "parallel processing" issue occurred, lets monitor and see if this occurs again
