### ISSUE TITLE
[APP] Market Home - Grid Layout

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#17]
> Can you add a feature which allows the user to change the grid structure of the NFT marketplace page. Currently, I can see a 2x3 structure of NFT's on my page. It would be nice to perhaps see more at the same time such as 4x6

Please experiment with Layout changes

**Comment by madtocc** [comment]
3 columns does not seem to affect the card layout
![image](https://user-images.githubusercontent.com/12486417/122820737-51018d80-d2b2-11eb-8b31-811f49596564.png)
but 4 might
![image](https://user-images.githubusercontent.com/12486417/122820976-a342ae80-d2b2-11eb-9fc7-ab9ebea3581c.png)

**Comment by curateproject** [comment]
Great let's go with 3 as an alternative view option
