### ISSUE TITLE
Auction Winner Bug 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#170]
Buyer: cryptomatt83@gmail.com
Android OS Latest
App version 1.6.0b51

Buyer was refunded for 4 charges of 250 XCUR.

However, a total of 5 charges were made for his attempted purchase of "Curator Cat 0048".

The seller says he will relist it for me to buy, but I'm afraid I will be out 250 XCUR if I am charged again.

Update:

The owner relisted it and I tried to buy one more time. 

I was charged another 250 XCUR, but I wasn't able to buy the NFT.

It said "internal server error" in red after I confirmed my transaction.

I am now down a total of 500 XCUR after the last refund.

The seller is: chrisgiblinfx92@gmail.com

**Comment by pellarboss** [comment]
The reason why this happened is because the user entered an invalid referral code, this has been fixed. We now skip invalid referral codes.

**Comment by pellarboss** [comment]
Please let us know how you want us to balance the buyer & seller (ie, who to send funds to who)

**Comment by curateproject** [comment]
Can you reset the balances as if no purchase of the above NFT occurred so the seller can relist?

**Comment by pellarboss** [comment]
ok, just to be clear:

1. sending
250 (purchase amount) - 1.25 (reward) 
from master to cryptomatt83@gmail.com
033adc3eb84d1aa019588ef0a351b7789259f32c634865474d22a615187ea9d2dc

2. send
235 (sales proceeds) + 1.25 (reward)
from chrisgiblinfx92@gmail.com to master
035b775360240e99062ba8d0a7146ae153fcf1554b502f3547bd5786387a632aa5

will action now

**Comment by curateproject** [comment]
Thanks, will inform the parties involved
