### ISSUE TITLE
BEP20 Deposit Retrieval

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#171]
A user deposited XCUR BEP20 by accident
 
Address 0x6c769DdF7c64033e5ad1d6015a062335577b3555

Use email Jake.aquilina@gmail.com

Is it possible to retrieve and send back to the users BEP20 address?

**Comment by pellarboss** [comment]
We can give this a go, do you want to send it to:

A - Back to the source address
https://bscscan.com/tx/0x83cc548ee7294576495be19d326693b4d644badca3ca7874fecda87d78d29806
it seems like a master address on BSC...

OR 
B - To User's actual ERC20 address on XCUR App?
Do that, we will need someone to accept the BEP20 XCUR, and provide the ERC20 XCUR (54.616)
Do you guys have an BEP address what we can send it to?
Also, please send me some BNB so we can process this

**Comment by curateproject** [comment]
This is, the tx URL:

https://bscscan.com/tx/0x83cc548ee7294576495be19d326693b4d644badca3ca7874fecda87d78d29806

Let's do option 1 for now and send it back.

What's your BEP20 address? I'll get some BNB BEP20 sent for you to process the refund

**Comment by pellarboss** [comment]
sent back to the user
https://bscscan.com/tx/0xccdb805ebadb7b445118919021b9377b1a153efb7532294ac6113daf772116b9

**Comment by curateproject** [comment]
Thanks!
