### ISSUE TITLE
User not able to load transactions

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#172]
User email: chrisgiblinfx92@gmail.com
Android latest app version and OS

I've asked they uninstall the app, delete cache and and install again but still the same issues.

https://user-images.githubusercontent.com/51517619/128644772-12072228-cac7-4a9c-a4ea-807cf2f5e32c.mp4

**Comment by madtocc** [comment]
@curateproject 
could you please ask to user to verify if he can see the transactions now?

**Comment by curateproject** [comment]
I'll ask him now

**Comment by curateproject** [comment]
All fixed thanks

**Comment by madtocc** [comment]
Great! Closing the issue then. It was a data formatting issue.
