### ISSUE TITLE
3 Minor UX Tweaks

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#176]
Spelling mistake, change to: 'Check out this profile on Curate!'
![1](https://user-images.githubusercontent.com/51517619/128940939-5b8a6ff8-334b-4ffd-86ab-e7c6b3aa2a33.jpeg)

Add dashes next to each sub-menu item so it looks more like a submenu
![2](https://user-images.githubusercontent.com/51517619/128940941-143d113d-2e86-4b50-b66d-0e01e3ab5c5b.jpeg)

Add an '@' before the username as this is synonymous with usernames i.e twitter, instagram usernames etc. 
Later on I would like you to change the profile share URLs structure to curate.style/app/username which will it make easier for users to remember and share without the need to press the share button, also will make it easier for users when we have the desktop web app
![3](https://user-images.githubusercontent.com/51517619/128940942-a7163325-531e-4af3-a3a7-eac8afa89ffa.jpeg)

**Comment by madtocc** [comment]
Hey @curateproject @DefiHunter  , let me know if inverting the profile name with the username names does not look better
![image](https://user-images.githubusercontent.com/12486417/129097112-e37931a0-7c06-4655-bccf-08a131278a90.png)

**Comment by madtocc** [comment]
swap name with username and its style as well

 before it was:
**@username**
Name

**Comment by curateproject** [comment]
I think it should be

Display Name:
Username:
Bio:

Thoughts?

**Comment by madtocc** [comment]
as the picture above, right? I think it is better this way.

**Comment by curateproject** [comment]
Yes I like this :)
