### ISSUE TITLE
[APP] Product Detail - Zoom

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#18]
> I've noticed that when selecting on an item, the picture zooms in but doesn't give me the option to view the image full size. A picture viewer would be good in order to examine the full item, especially if you are buying an expensive NFT.

Please experiment with Zoom and further inspection

**Comment by curateproject** [comment]
Yes a click to maximize would be nice to have on the image viewer so users can view the entire picture

**Comment by madtocc** [comment]
https://user-images.githubusercontent.com/12486417/123726659-c21ee300-d866-11eb-99da-0cb9ee323b92.mp4
