### ISSUE TITLE
5 UX Tweaks

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#181]
1. For the profile page can you put the verification badge next to the display name and not username

2. Can you add a small 'NEW' text next to the 'Staking" Menu item

3. Remove the green colour from the 'Buy XCUR' menu item and keep default colour like the rest of the menu text

4. Default 'My NFT' Menu tab should be closed and not collapsed/open

5. Request their username choice on registration page and change text 'Your First Name' to 'Your Name'

**Comment by madtocc** [comment]
@curateproject, is it ok like this?
![image](https://user-images.githubusercontent.com/12486417/129378232-d55a7dee-5be5-4d83-8e32-ffb7242d63e2.png)

**Comment by curateproject** [comment]
This is great @madtocc can you send me a build to test?
