### ISSUE TITLE
PolkaDot integration 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#183]
User ability to Buy,Sell and Mint on the PolkaDot network (Same as BSC)

Mint NFT screen - User ability to chose which chain they would prefer to mint on

**Comment by pellarboss** [comment]
For this release, we will process DOT like ETH, allowing users to Deposit DOT and Withdraw DOT, and buy XCUR XC20 with DOT

@DefiHunter please confirm

**Comment by DefiHunter** [comment]
Confirmed - Would be nice if you could include an option to mint on Polkadot too at launch as described above

**Comment by DefiHunter** [comment]
Would users be able to deposit dot through its ERC-20 equivalent too ? The wrapped dot on ETH ?
