### ISSUE TITLE
Referral Bug - Text Update and Flow NB

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#184]
Pertains to both the referrer and referee

Users rewards to be $15 (NOT 15 XCUR) 

And purchase requirement is also $100 (NOT 100 XCUR) 

Same goes for enhancement - to denominate in $ due to price fluctuations

**Comment by pellarboss** [comment]
currently it is fixed with XCUR in the system, lets make it configurable in admin?

**Comment by DefiHunter** [comment]
Yes please 

And then we can just update the text in app to reflect $

**Comment by pellarboss** [comment]
this is now configurable in admin :)
