### ISSUE TITLE
Staking Page - Calculator

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#185]
Calculator on the staking page so that user can determine what he would earn 

Fixed Assumptions:

50 000 XCUR Reward Pool to be dripped according to shares through the year i.e. reward pool should last a year 

Variables 

, a = amount multiplier 
, t= Time
Size  = a= X*0.0001
Time  t=(D/30)*1.02
D= Days
X = # of Tokens staked 
StakeBoost - x1.5, x2, x3

Main Formula = 
Shares in Pool  = X(t+a)*StakeNFT

User shares in pool = (User Share)/(Sum of all Shares in Pool)
Total Pool size = (Sum of all Shares in Pool)

**Comment by pellarboss** [comment]
@DefiHunter can you create a wireframe for the page?

**Comment by DefiHunter** [comment]
Will try and whip something up

**Comment by DefiHunter** [comment]
See Below Roy 

Under Time drop down :
Hours
Days
Months
Years

Under Stakeboost dropdown. 

Platinum = x3
Gold= x2
Premium = x1.5

Assumtions we can make 
XCUR Size of pool = 50 000 XCUR
Share Size of Pool = lets assume 1 000 000


![3268250bf8e245d08a1351c4401f4c0b](https://user-images.githubusercontent.com/72095738/129525645-5dacde1d-e266-4bdc-a442-29ab72952cbf.png)

**Comment by DefiHunter** [comment]
Happy to hop on a call too to make sure we all on the same page

**Comment by madtocc** [comment]
@DefiHunter , need help to connect the dots. Let's try an example to try to make things easier:

Let’s say I want to stake 100 XCUR for 300 days with premium boost (1.5)

it would be:

t = time  = (300/30)*1.02 = 10.2
a = 100*0.0001 = 0.01
stakeNFT  = stakeboost? = 1.5
so it would be 100 (10.2+0.01)*1.5?
so the shares would be 1,531.50

so if the pool is the size of 1,000,000 and the reward is 50,000
This user would have 1,531.50 * 0.05 = 76.576 XCUR?
is it correct?

**Comment by curateproject** [comment]
Hi @madtocc I got the same answer when I followed the formula and your example making 76.576 XCUR correct but I will let @DefiHunter confirm to ensure we haven't missed anything.

@DefiHunter shall we ask Marco to make the formula configurable in admin i.e we can adjust the '1.02' number in the future etc..

**Comment by DefiHunter** [comment]
Yes correct - That would be his reward for a full 1 year of staking
