### ISSUE TITLE
[Operational] - Batch Minting

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#188]
**Propose:**
Use an updated more optimised ERC721 compatible smart contract
We will use this new contract for all future minting

On a daily basis, mint all approved products in a batch (max 100 items)
This will save gas fees significantly and also improve accuracy as well (since it is once success or fail)

**impact**
Previous mints will stay with the older smart contract - which should have no impact
If we want everything to be super clean, we can migrate older tokens to new the smart contract, but that has a cost (hundreds of new mints)

**Comment by DefiHunter** [comment]
Would Master wallet funds remain unaffected yes ?

**Comment by pellarboss** [comment]
impact:
- ETH in master account will be used for minting
- new smart contract is needed to facilitate batch minting

Gas Prices are super high at the moment, something to be aware of
