### ISSUE TITLE
Email Confirmation for Withdrawals - Security 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#191]
When a user withdraws money from the platform - Once requested on the app , user will receive an email to his registered email address where he has to confirm the withdrawl - After which the withdrawl will be sent to the admin panel for processing

**Comment by pellarboss** [comment]
we have added TOTP / MFA, is this still a requirement? (TOTP is a substantial better solution)
admin can also adjust withdraw review threshold to add a manual intervention if required

we have now made email verification mandatory on registration

**Comment by DefiHunter** [comment]
All good - an added level of verification may be helpful ? A lot of the
bigger guys implement this too

Thought a Roy?
