### ISSUE TITLE
Update in-app notification

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#193]
Remove the hash and replace it with the NFT name for NFT approval app notifications, see screenshot![Screenshot_20210818-001520.jpg](https://user-images.githubusercontent.com/51517619/129812655-54ff6539-99ca-4a9b-8727-2e2dc40a5b9d.jpg)

**Comment by pellarboss** [comment]
done in staging

**Comment by curateproject** [comment]
Thanks
