### ISSUE TITLE
Cant verify user on the admin panel

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#195]
When I click to verify this user, b722a56fbc1baef4662812ca7c744bd53b05, it just shows the loading screen forever. If I reload the page it shows that the user is still yet to be verified.

**Comment by pellarboss** [comment]
I presume the "verify user as seller" button?
this user is verified, and the button works in staging
can we reproduce this issue?

**Comment by toomingos** [comment]
This is a recurring issue for me when I try to verify the user, to give him a verified badge. After I click on the button it just shows me the loading page and it never loads. Had to get @curateproject to do it a couple of times, so that's probably why the user is already verified.
