### ISSUE TITLE
BUG - User Stuck Withdrawl 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#196]
Please see attached image below <img width="1078" alt="Screenshot 2021-08-19 at 16 32 18" src="https://user-images.githubusercontent.com/72095738/130087302-ec3b9025-afff-4e50-b854-57844bf806f8.png">
User requested withdrawl - Registered as completed on user end but nothing received or submitted to blockchain 

User Email : chris.randone.cr@gmail.com

**Comment by DefiHunter** [comment]
@pellarboss

**Comment by pellarboss** [comment]
Yes, verified, stuck ETH transaction
https://etherscan.io/tx/0xfc941fe5210d5fa7c56a63291d6608c7f2496e922319a4b555ee163e76092447

Hope it can complete soon

If it does not complete in a few hours, we will cancel the txn and do manual recon and resend
