### ISSUE TITLE
Date bug on NFTs

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#198]
See attached and the below message:

Hello everyone, I have a problem, I posted nft back on August 14, and every time I go to check whether they were approved or not, I see that I allegedly created them not on August 14, but on August 16

Probably this is an application error, if you click on nft that have not yet been confirmed, the download date of this nft is reset
![Screenshot_20210819-182819_Twitter.jpg](https://user-images.githubusercontent.com/51517619/130115984-70e0e248-b360-4dfa-b535-9f581df4f791.jpg)
The work has already been published, but it is still being written what was created today, although the work has already been several days

**Comment by pellarboss** [comment]
@madtocc please investigate which date was used
