### ISSUE TITLE
Add Admin Panel feature to list NFTs for users

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#199]
I have to list for sale big artists' products that I don't want to bother and have him go to the app and list it. The product key is  bb01655cf97978ac971dbc5d.

Meanwhile, I think this should be a feature on the admin panel, should be simple to add.

**Comment by pellarboss** [comment]
https://admin.curate.style/product/bb01655cf97978ac971dbc5d/detail is now available for sale

in terms of the admin feature, lets defer after v2 launch

**Comment by pellarboss** [comment]
@toomingos do you mean admins can create a NFT on behalf of another user?

How often does this occur? If not often, you can create one and our guys can set the Owner to whoever.

**Comment by toomingos** [comment]
Sounds good, that works for me
