### ISSUE TITLE
Elrond - Integration

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#20]
Ability to deposit and withdraws with EGLD

**Comment by DefiHunter** [comment]
Integration with these Chains to be done directly with X - Chain , All user Deposits from Elrond to be wrapped onto the X-Chain , subsequently a Wrapped XCUR to be created on the Elrond blockchain

**Comment by DefiHunter** [comment]
users can deposit with an EGLD deposit address 

Tokens get wrapped onto X-Chain

Enabling of EGLD (and WEGLD as payment option) 

Withdrawal onto the EGLD chain , Tokens from X-Chain get unwrapped and withdraw is executed on EGLD chain

**Comment by DefiHunter** [comment]
https://docs.elrond.com/developers/esdt-tokens/
