### ISSUE TITLE
Display formula and tweak text

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#200]
On staking page can you add the formula and the text "Paid Daily" at the bottom where I've marked in red and also change the text at the top to:

"Est. Yearly Rewards"

We're getting a lot of users ask how the rewards are calculated so this will save a lot of time.![Screenshot_20210821-220028.jpg](https://user-images.githubusercontent.com/51517619/130334727-60929bd6-0f13-4c2a-81d1-239e35cd7a0a.jpg)

**Comment by DefiHunter** [comment]
Formula is Incorrect 

				
Compound Interest Formula 	 Shares = Xe^0.05t*(StakeNFT)			
				
Total Pool Size = Sum of All Users Shares in Pool 				
				
User Reward in a year  = (Share)/(Total Pool size )*Treasury size 				
				
Show user their estimated return and % Return relative to investment				
				
		Days		
	Min Stake	0		
	Max	720		
				
				
t = Years	Step t 	1/365		
Convert to Days 				
e = Eulers constant				
				


This is the Staking formula
