### ISSUE TITLE
Referral Text Update 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#206]
On the Referral Page in setting update text to reflect - wherever it says 15 XCUR change to - $10 

and change anywhere where the treshhold of 100 is stated - to $100 - so 100 XCUR change to $100

**Comment by pellarboss** [comment]
the numbers are in XCUR? (ie, admin side you configure the xcur values)

**Comment by curateproject** [comment]
Yes, can you change XCUR to USD?
