### ISSUE TITLE
New page on app 'Latest Sales'

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#209]
Display the last 25 sales on this page showing:

1. NFT (with watermark)
2. NFT title
3. Sold price
4. Sold date
5. Sale type (auction or fixed price)
6. New owner

**Comment by pellarboss** [comment]
@madtocc please coordinate

**Comment by madtocc** [comment]
Would you like to add this as a new entry menu? We could Include under the weekly picks and show the 25 or maybe show a few and a show more button to navigate to the page?  like this just with the parameters you asked
![image](https://user-images.githubusercontent.com/12486417/133302578-41ff1819-1e02-4086-b32a-be6659276757.png)
