### ISSUE TITLE
Dashboard - Show number of iOS and Android Users

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#211]
Can you add a metric to dashboard.curate.style showing the breakdown of iOS and Android users with % share?

**Comment by pellarboss** [comment]
@madtocc can we get more device based info? if so, please send it in registration & logging for future tracking

**Comment by madtocc** [comment]
Yes, can send device info which os and phone model if it's q phone just let me know the param I need to send.
This would be for future app though. It is possible to know the number through the app store / Playstore or onesignal also have this info
