### ISSUE TITLE
Make Metadata not compulsory and bigger box

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#212]
Make metadata field on mint nft page optional and slightly bigger to allow more text

**Comment by pellarboss** [comment]
meta tags, how do we actually use them, for example, in other NFTs, in the actual json, we do:

"armour":"gold",
"sword":"lightning",
"boosters":yes

as meta tags
do we just allow users to add plain text, and we add it to the actual NFT?
could there be potential security flaws? ie, someone adding a piece of malicious code?

**Comment by curateproject** [comment]
Good question @pellarboss - 

I wanted to replicate the attributes/properties you see on collections like polkamons/punks that help determine it's rarity i.e the attributes which get added to the smart contract when minted

whatever you feel is the best way to allow sellers to add this info please can you advice - thanks

**Comment by pellarboss** [comment]
ok, i propose:
multi line meta tags, for example
attribute:value
eg: headwear:beanie

will get converted to the corresponding NFT values accordingly

@madtocc 
please add hint text to the textbox
```
attribute:value
attribute:value
```
below the textbox add "add attributes and its values in newline"
