### ISSUE TITLE
Grid View - NFT Approval/Denial Page

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#215]
Display Pending NFTs in a Grid view Style 

Within the grid view - Each Pending NFT will have a preview of the picture, along with a little info below it - followed by an approve and deny button 

If an admin wants more info they can click into it 

Lets try to have 40-50 NFTs per a page in Grid View 

Allow admins to switch freely from Grid view to list view

**Comment by DefiHunter** [comment]
If user defaults to list view - Once they approve/deny an NFT i, stead of taking them back to the page to see the whole list - Automatically redirect the user to the next pending NFT to approve or deny 

Admins can decide whether to use the list view or Grid view

**Comment by pellarboss** [comment]
Lets do the listview Approve > Next first, since that is easier to do, and that means you will get it in production sooner

**Comment by curateproject** [comment]
Ok let's try that first @pellarboss
