### ISSUE TITLE
Admin Panel Products Page: Add search by Owner Key and User's email

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#216]
We get a lot of people contacting us and they don't send the products' names, we should be able to search the pending products by owner key and the user's email

**Comment by pellarboss** [comment]
@eventang2015 lets link user's products form user's detail page
ie, Products Active: 0 Items is a link to user's products

**Comment by pellarboss** [comment]
we made it so user's products can be accessed via users profiles, doing it this way will allow greater flexibility
