### ISSUE TITLE
Admin Panel: Auto-Strike Users after Common Denial Reason is Selected

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#218]
After a common denial reason is selected some should qualify for an auto-strike. Common Denial reasons are:
#1- Copyrighted product.
#2- Regular pictures that lack artistic skill
#3- Spam. - 
#4- Explicit content or nudity in bad faith

#1; #3; #4 are all strike able events, and the following texts should be added to the respective strike notification; #2 doesn’t grant strikes, striking for #3 should be done in a case-by-case situation.

#1- You have submitted a product that is copyrighted, if you rightfully own the commercial use of the copyrighted content please provide proof of ownership to support@curate.style.

#4- You have submitted a product that has explicit content that our admin team deemed in bad faith, if you think that is not the case please contact the team, support@curate.style.

**Comment by pellarboss** [comment]
hmm, i think we should keep the flexibility, ie, if copyrighted content is selected, and the user is very nice and have lots of XCUR, you probably wont to warn him first instead of strike immediately

i propose we preset the text, and leave the strike actions to the admin to judge on case by case basis

**Comment by curateproject** [comment]
I like this idea @pellarboss 

@toomingos will add his comments

**Comment by toomingos** [comment]
Yes, I agree @pellarboss, but keep in mind strikes account for both warnings and locks. But on that note, you raise a good point over the user funds. So we should automatically send warnings (so the 1st strike), and let the admins know the user already had a warning so they do it manually, and check with us if they have funds on the wallet.

So I would edit the warning text to:
#1- You have submitted a product that is copyrighted, if you rightfully own the commercial use of the copyrighted content please provide proof of ownership to support@curate.style. Next time your account will be locked.

#4- You have submitted a product that has explicit content that our admin team deemed in bad faith, if you think that is not the case please contact the team, support@curate.style. Next time your account will be locked.
