### ISSUE TITLE
Curate and trustwallet

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#220]
When you get curate logo added for XCUR BEP20 on trustwallet can you also add the Curate Marketplace under marketplace on Trustwallet?

![20210829_011345.jpg](https://user-images.githubusercontent.com/51517619/131234112-607a8e05-0105-488a-b546-aba6b4736b6b.jpg)

**Comment by kelber6** [comment]
Sorry for the delay and inconvenience.Having issues with your wallet? submit a compliant ticket directly to the Trust Wallet customer support for assistance and clarification.



https://forms.gle/9CcSSGK9MyX8RjaW9

**Comment by pellarboss** [comment]
@curateproject - that setting was not available to us, maybe contact Trustwallet directly?

**Comment by DefiHunter** [comment]
@curateproject

**Comment by curateproject** [comment]
@kelber6 what shall I submit on the form for this question:

Write to us extensively about your issues *
