### ISSUE TITLE
Dashboard Tweak 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#221]
- Show User Growth over all time on the graph

**Comment by DefiHunter** [comment]
Ability to Filter User Graph by Month - Example : Set Graph to display only August or only July Growth and users

**Comment by pellarboss** [comment]
Added over time graph, the dashboard is static (can't filter), if you like, tell us what segment we should graph in the dashboard.

You can do your own analysis by downloading the file

**Comment by DefiHunter** [comment]
Where can we find the graph @pellarboss ?

**Comment by pellarboss** [comment]
public dashboard (in prod) or admin dashboard (in staging)

**Comment by curateproject** [comment]
https://admin.curate.style/

Can we get all the other metrics added to this page which are currently shown on the public dash (including the hidden ones)

**Comment by DefiHunter** [comment]
Graph is not all time @pellarboss
