### ISSUE TITLE
Additional Column - Admin Panel

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#222]
Add an additional Column on the NFT purchase tab for "Secondary market sale" - and then it would say Yes or No

If its a freshly minted NFT that sold - Then now 

If it was a sale on the secondary market - Then Yes

**Comment by pellarboss** [comment]
@DefiHunter could you tell us which page you would like to see this?
@madtocc please action

**Comment by DefiHunter** [comment]
On the NFT Purchases page pls

**Comment by toomingos** [comment]
NFT purchases:
-USD Value (Value pegged to time of purchase and XCUR value)
-Secondary Market Yes or No options

NFT products (All, pending, approved, and denied)
-Admin User who processed the product

**Comment by curateproject** [comment]
This is for the admin panel @pellarboss not the app
