### ISSUE TITLE
Create Telegram Bot to Track NFT sales on Marketplace

### ISSUE THREAD

**Issue by breaddog** [pellartech/curate#224]
Similar to the Twitter Bot,

Bot will tweet out transactions done on marketplace by listening for Transfer events, will update on Telegram.

Follow this template
(NFT title) bought for (price) $XCUR by (new owner last 6 address) from (seller last 6 address) with picture attached and link to the NFT

Bot should relay sales information to users which joins a designated channel
UncBot XCUR: https://t.me/uncbot_XCUR

**Comment by curateproject** [comment]
Hi @breaddog here are the login credentials for the twitter bot account:

user: curatebot
pass: CurateXCUR100

Please can you create the telegram bot and enable it to the same, thanks

**Comment by breaddog** [comment]
Hi @curateproject, the telegram bot after testing is able to send out messages to a designated channel, could we also get the telegram channel id to which the bot will be posting sales updates to?

**Comment by nevrending** [comment]
Hi @curateproject , just want to let you know that the password for the `curatebot` Twitter account is still good (I somewhat managed to log in). Perhaps it's best if you change it immediately.

**Comment by curateproject** [comment]
Sure will do, can you message me the password so I can login and change it?

**Comment by nevrending** [comment]
@curateproject I did not change it. Should still be the same as the one you posted above.
