### ISSUE TITLE
[P2P] Enhancements

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#227]
Shipping Prices consideration

Product quantity considerations

**Comment by curateproject** [comment]
- Ability for seller to edit the product description, title, images, video once approved
- Do not require 'confirm listing' under 'Active' once a pending item gets approved
- Ability to add 'quantity' to the listings

**Comment by curateproject** [comment]
@pellarboss @madtocc can we aim to get this done by the weekend please?

**Comment by madtocc** [comment]
> * Ability for seller to edit the product description, title, images, video once approved

We can add this but just out of curiosity what's is the point of approving then? If user can submit item X then after approval change to item Y.

**Comment by curateproject** [comment]
Good point, title can't be edited and only new descriptions can be added to the existing description and media images/video can be edited (will rely on our users/admins to report anything obscene) @madtocc
