### ISSUE TITLE
[Server] - Withdraw Tracking / Monitor

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#228]
Ticket for operational automation, to check if all withdraw is successfully completed

**Comment by DefiHunter** [comment]
@pellarboss  When doing this pls Recon any past withdrawls to ensure everything was paid as suppose to 


@curateproject  Pls let the community know that we are resolving the issue with withdrawls and it will be taken care of within the next week

**Comment by pellarboss** [comment]
yes, auto recon is the next top priority
