### ISSUE TITLE
Add API keys to Admin Panel

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#229]
Add API key for the following pages:
-Users
-ID Verification
-NFT product pages
-NFT purchases

**Comment by pellarboss** [comment]
we dont really provide API keys, all interactions are Token based instead
happy to show you guys how to query this data via API

**Comment by toomingos** [comment]
Any way we can get real-time data to excel sheets?

**Comment by DefiHunter** [comment]
Yes pls @pellarboss  - On our call next week I'd love to run through it with you - or any other time we both free

**Comment by DefiHunter** [comment]
@toomingos There is a way , we working on pulling the APIs directly to the sheets , After a call with Roy we should be all set :)

**Comment by curateproject** [comment]
Any update on this @pellarboss ?
