### ISSUE TITLE
Please investigate - Ledger Live

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#231]
Hey Guys - I received a reply from Ledger to submit Curate to be listed on their devices 

Can we please investigate - https://developers.ledger.com/docs/coin/general-process/

I believe we need to submit a pull request or something of the sort - Lets get the process going and ill ping them on my end 

https://developers.ledger.com/

**Comment by pellarboss** [comment]
Ledger Live theoretically is self custody, where XCUR is centralised (managed custody), this wont really work
