### ISSUE TITLE
Withdrawl Security Measure 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#238]
Users can only withdraw to whitelisted addresses - Whitelisted addresses to be added in setting - once added it needs to be confirmed through a verification email and user will receive an email saying that their whitelisted address has been updated 

Upon an update - User to wait 24hrs before requesting a withdrawl 

A user has experienced an account breach and as such had his funds taken - the above measure can prevent that 

Priority

**Comment by pellarboss** [comment]
we have added TOTP / MFA, is this still a requirement? (TOTP is a substantial better solution)
admin can also adjust withdraw review threshold to add a manual intervention if required
