### ISSUE TITLE
Bug list - 11 Sep

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#242]
Copy and Paste of XCUR deposit address is not working

**Comment by curateproject** [comment]
Number keyboard does not display when switching out and back onto the curate TOTP screen (i.e after checking Google authenticator for number)

Nor does it allow you to press the area to bring up the number keyboard

![Screenshot_20210911-205019.jpg](https://user-images.githubusercontent.com/51517619/132960427-27aafd72-53b3-4ab3-aa94-770d6425f691.jpg)

Also for UX reasons change the word 'TOTP' throughout the app to '2FA'

**Comment by curateproject** [comment]
Bug number 3 @madtocc @pellarboss 


This error occurs on the kyc page on iOS and
![20210912_004245.jpg](https://user-images.githubusercontent.com/51517619/132966174-c550ad5c-16e4-4ed7-b536-b9cce74205be.jpg)

**Comment by curateproject** [comment]
Bug 4

Postal code needs to be alpha numeric and not just numbers as below and change text to "Postal Code / ZIP code"

Also require kyc should be required to buy or sell on the P2P marketplace please

![Screenshot_20210912-004558.jpg](https://user-images.githubusercontent.com/51517619/132966219-4de6fda1-a50c-40c2-8c27-c5e1d6f2d6a7.jpg)

**Comment by curateproject** [comment]
Bug 5

I was able to purchase an item already sold and paid for on the P2P marketplace

Once an item is sold it should not allow anyone else to buy it

The listing can still shown on the marketplace but with a banner across it as sold over the thumbnail

Once the item is confirmed as goods received from the buyer, then the listing can get removed from the marketplace

![Screenshot_20210912-004836.jpg](https://user-images.githubusercontent.com/51517619/132966257-20ea07ae-2ba8-49af-be7d-3f1d93cfbb41.jpg)

**Comment by curateproject** [comment]
Bug 6

Negative likes can be achieved by spamming click the like button as a result listings with negative likes are showing on the homepage

**Comment by curateproject** [comment]
Bug 7

Users are able to create users via the api ( this could be avoided by adopting a google captcha step or email verification )

This is dangerous as someone could create a script and load the backend creating millions of bot users

**Comment by curateproject** [comment]
Bug 8:

User emails can still be shown via JSON in the api calls under 
followers
followed
auction bids (random?amount….)

And also the admin reviewers emails are being displayed after they approve an NFT:

This is returned as part of the response
“reviewer”: {
“Key”: “some key”,
“email”: “toomingos@gmail.com”
}

**Comment by curateproject** [comment]
From our white hacker:

I noticed you are blocking api calls now via tools like ‘postman’ 
This I see is done by cloudflare checking the headers ( I assume have not looked too deep into it )
But I can still make calls via a browser
However these are public data calls anyways for things like the market items so not too much of a worry but thought I would mention it too

- Let me know if this is also something you can patch @pellarboss

**Comment by pellarboss** [comment]
7 - we have throttle implemented in the firewall, this wont occur
8 - we will review all responses to ensure typical user doesn't see more information than they are suppose to, and if so, the information is masked
