### ISSUE TITLE
Add text to mint / sell page for both marketplaces

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#246]
Add the bottom of the page can you add the following text:

"**Example breakdown of commission:**

If your item sells for $100, curate takes a 4% commission i.e $4
The buyer and seller both received a 0.5% reward i.e $0.50 in XCUR each"

**Comment by madtocc** [comment]
Actually there's no error. It is correct... the fee is calculated based on the current input price so the user knows exactly fee... if your item sells for 0 XCUR you will receive 0. I have updated to the default to 100 if the value is empty.
