### ISSUE TITLE
Staking $XCUR in-app

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#247]
Once #244 is complete we'd like to enable our staking feature based on the formula currently on the staking page and ensuring we try to stick to APYs in the table in #244 

@DefiHunter can you add your comments please

**Comment by DefiHunter** [comment]
I would recommend only putting this live once x-chain integration is completed in KuCoin, unless we have another idea on how to fund  the staking ?

**Comment by curateproject** [comment]
I agree @pellarboss let's get bugcrowd audit done for early October - have we got a ticket for that?
