### ISSUE TITLE
Return XCUR from Testnet

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#25]
A user accidentally deposited XCUR in to testnet
explore how to return
0x923153f3958458aa27db1f03ad24f8f94d56719fb05100e48c4c8b0392e46e15

**Comment by curateproject** [comment]
This one too please (another user):

https://etherscan.io/tx/0x876a9bed11a8ab79683e2b64a4bc03ce50904fc923011c12b9d1c4102d71c98b

**Comment by pellarboss** [comment]
@curateproject progressing well
Please send some ETH to 0x349C2164d1600ce023B2C0BD83f59a98D6d6aBcb for the return
Please also let us know where to return the 10 & 11 XCUR to

**Comment by pellarboss** [comment]
both account's XCUR sent to the nominated address
0x8c9f3ae53aF473f3cDD306b8b8Cc84DdB85c6Cae

**Comment by curateproject** [comment]
This user deposited 196.3 XCUR during testnet

The Txid is:
0xd694b69504bca870379d32363817531895b46a096f9ac9c57f992735cac98b30

The Xcur walet address it was sent to is:
0xbfc9E75603Ff1E65217911bB19e775Ab693dFFB4

His erc20 Xcur address is:

0xc73ac877e8bae1ce9d312fb483f963288d21bad2

Can you check if this can be recovered?

**Comment by curateproject** [comment]
Return to this address please

0xc73ac877e8bae1ce9d312fb483f963288d21bad2

**Comment by pellarboss** [comment]
https://etherscan.io/tx/0xea9e19c10ca9c44ff43c15d655e0130e5b953fd9b2f12b234d03905c91ac435c sent
