### ISSUE TITLE
Referral page tweak

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#254]
Allow referral code to be copied to clipboard

Add a grace period of 72 hours for users who sign-up without entering the referral code (i.e add code in settings)

**Comment by pellarboss** [comment]
clipboard = ok

72 hour grace period:
- only applies to those that have not entered a code previously
- once a code is entered, it can not be changed (even if it is a mistake) - the reason is we can't allow edits since payment is issued once the code is entered
