### ISSUE TITLE
2 tweaks to P2P marketplace

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#255]
Can you add a message at the top of the p2p marketplace page:

"Currently in closed beta testing, not open to public as yet 👀"

And can you require KYXC is complete before buying or listing an item on the P2P marketplace (not NFT marketplace)

**Comment by curateproject** [comment]
@madtocc can you have this message editable and toggled on and off by admins via the admin panel settings, reason: so we don't need to submit another build to the app stores because we're looking to announce the p2p marketplace in the next few days so it'll be good if we can control this ourselves :)

**Comment by madtocc** [comment]
just the message or require the KYC?

**Comment by madtocc** [comment]
@curateproject  there will be an update in the end of the week for BEP20 and DOT we can change the message when sending the update. do you want to still have an editable message? let me know otherwise I will push the app now or we will have to implement this.

**Comment by curateproject** [comment]
Yes editable message please with option to display on and off in admin settings please
