### ISSUE TITLE
Add a ToS Check Box on Mint NFT page

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#258]
We should have the users read through the main common of denials first, before checking the ToS box and submitting an NFT.

Common Reasons for Denial
#1- Copyrighted brands, public figures, and elements. 
#2- Poor quality pictures are denied upon submission in order to have a healthier marketplace. i.e. regular selfie
#3- Spam.
#4- Explicit content or nudity in bad faith.

**Comment by toomingos** [comment]
**Updated**
We should have the users read through the main common of denials first, before checking the ToS box and submitting an NFT.

Common Reasons for Denial
#1- Copyrighted brands, public figures, and elements.
#2- Poor quality pictures are denied upon submission in order to have a healthier marketplace. i.e. regular selfie
#3- Spam.
#4- Explicit content or nudity in bad faith.

Buyer Disclaimer: We advise buyers to do their own research before buying the products, since the Curate team can only approve NFTs to the best of their knowledge based on the above and the item in question is genuine and authentic. Any dispute lies with the creator/seller of the item. Curate Groupt Ltd takes no responsibility for any item sold by their users on their marketplaces and as such can not be held responsible for authenticating or verifying items as genuine. Therefore limiting any liability, as such users are advised to carry out due diligence on all items traded on the marketplace.

**Comment by madtocc** [comment]
> **Updated** We should have the users read through the main common of denials first, before checking the ToS box and submitting an NFT.

Not sure if I understood correctly:

do you want to include Buyer Disclaimer in the ToS shown when minting? 🤔

> Buyer Disclaimer: We advise buyers to do their own research before buying the products, since the Curate team can only approve NFTs to the best of their knowledge based on the above and the item in question is genuine and authentic. Any dispute lies with the creator/seller of the item. Curate Groupt Ltd takes no responsibility for any item sold by their users on their marketplaces and as such can not be held responsible for authenticating or verifying items as genuine. Therefore limiting any liability, as such users are advised to carry out due diligence on all items traded on the marketplace.

**Comment by toomingos** [comment]
Yes let's add the disclaimer as well since we've been getting a lot of scams.

**Comment by toomingos** [comment]
My bad that would be on the buying screen

**Comment by toomingos** [comment]
Yes, watch out for the spacing in between numbers and "-".

also please add "poorly drawn doodles" on the "i.e. regular selfie" part
