### ISSUE TITLE
spelling mistake in email notification

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#269]
![2021-10-03 02 38 11](https://user-images.githubusercontent.com/51517619/135736504-7c8df4b6-9180-435f-b6d2-fdb3d4202ff7.jpg)

 (support and curate.style spelt wrong)

**Comment by pellarboss** [comment]
support is spelt correctly?

curate typo fixed

also XCURP is now renamed to XCUR (xcurp is an internal reference)
