### ISSUE TITLE
[Feature] - Minting Considerations

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#277]
**Background:**
#276 - Master account now "holds" imported NFTs
What shall we do with natively minted NFTs

----

**Option 1, ETH Batch Mint**
As users create NFTs, we batch mint them on ETH, on a nightly basis (to achieve a lower cost), in batches of 100, the contract can be super optimised (strip down features)
The cost of each mint could be drastically reduced
https://etherscan.io/tx/0x165ea068fba76e241cd0ca1b2601faba90699b9c67f4f966e1161b05aad79ef0
this is an example of batch mint, it could be 0.15ETH (at 37 gwei) per mint of 100, or 0.40ETH (at 100gwei) per mint of 100. 

It is a hefty cost, considering 10,000 NFTs, it will have a cost of 100 x 0.4 = 40ETH

Ways to recoup this cost is ask users to pay an export fee if they want to export.

----

**Option 2, ETH Batch Mint as an Option**
Ask users to pay minting cost in XCUR on mint if they would like an ETH based NFT
This solution is neither here nor there in my opinion, since it is a step between Option 1 and 3.

----

**Option 3, ETH Lazy Mint**
Unless it is an imported NFT, nothing gets minted until the NFT is exported
We mint the NFT on export and request the user to pay for the export costs
This is still a cost but could be recuperated from export fees

----

**Alternatives**
* User a different blockchain - ie, Polygon, BSC, Solana etc - personally, I think value of NFT drops off significantly when it is not on ETH
* Lazy & Batch Mint - batch mint nightly on those exported - personally, I think if a user is paying a fee for exporting, they would want immediate confirmation, not a wait for more than 24 hours

----

**Considerations**
Option 1 gives the biggest public trust, but I think will have the biggest cost, please financial model and see if is affordable.

Option 3 is a good alternative.

**Comment by DefiHunter** [comment]
Sounds good - In terms of business model - 

Lets charge users 50% of the general minting cost of an NFT - For example if the cost to mint on opensea is $100 right now. Curate would charge $50 

This fee should be dynamic and change as the minting cost changes for the network
