### ISSUE TITLE
[Feature] - Collections

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#278]
**Background**
Please read #276 and #277 
Creating collections is an important part of navigation, stats and rankings

**Collection Attributes**
* Title
* Description
* Items in Collection
* Logo
* do we want site, telegram, twitter etc? - ie, what purpose do they serve apart from taking users away from app?
* other sales stats which will follow in another ticket

**Imported NFTs**
- Collections is created automatically from the Imported Contract (only 721s will be supported from day 1)
- The user who imported the collections can not modify the collection
- Once the collection is created, only Admin can modify the Collection
- Reason is if I import one Ape, i should be able to modify the entire Ape collection
- Operational Staff should be able to modify Logo, Name etc etc 

**Curate NFTs**
- Has a dependency to 277
- Any users can create a collection and assign one of the NFTs they own in to the collection
- When you create a new NFT (in app), you can choose from your collections or a new collection
- When you create a collection, you are the owner of the collection, and hence you should be able to modify all collection attributes
- Admins can overwrite collection attributes via admin panel

**Comment by toomingos** [comment]
We need to revise the UX/UI for this feature, are we creating the Creator Hub/Studio Mode?
