### ISSUE TITLE
[Feature] - Minting & Attribute Changes

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#279]
**Background**
- Please read #276, #277, #278
- To align with attribute models defined by ERC721
- To fully utilise the "MetaTags" utilised previously

**Minting**
- Users have a better experience when working with "Meta Tags"
- Users can define up to 10 attributes in a grid, ie: color:Blue, type:Silver, strength:10
- If the NFT belongs to a Collection, the Collection will use these attributes as collection attributes, allowing for rarity calculations and filtering
- If you are minting an NFT with the same collection, the attributes names will prepopulated for you (no need to render color, type, strength etc) 
- Once an NFT gets minted in to a collection, it can't be changed (if changed, it will mess up attributes)

**Comment by toomingos** [comment]
Is the attribute limit a must?

**Comment by pellarboss** [comment]
nope there is real limitation, but without limitation, say 50 attributes is counter productive

**Comment by toomingos** [comment]
Right I agree, just predicting that in the future there will be collections coming in with more than 10
