### ISSUE TITLE
Withdraw DOT from binance issues 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#284]
A user got this error when he pasted in his curate DOT wallet address

![20211010_103241.jpg](https://user-images.githubusercontent.com/51517619/136690304-333ad971-c516-4538-a12e-823eb55635da.jpg)

Heres the translation;

the format of the pickup address is incorrect. please check the length and characters of the pick-up address and try again

**Comment by pellarboss** [comment]
Which user is this? could you please provide a bit more info?

**Comment by pellarboss** [comment]
Binance has a stricter polkadot formatting requirement (must be in polkadot relay chain as oppose to generic polkadot chain)

we have changed our addresses to conform, this is now in production.

DOT has a few particularities that are useful to know, please ensure the supporting staff are aware
https://github.com/pellartech/curate/wiki/DOT-currency
