### ISSUE TITLE
V4.0 UX Design Figma Link

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#286]
https://www.figma.com/file/vLAn16i0kh88ZB1kdvVNZI/Curate-v3?node-id=3167%3A4140

Hi @madtocc please use the figma link above and try to match the UX as close as you can to this (this was done by our designer, if you have any questions let me know)

**Comment by toomingos** [comment]
I thought UI/UX overhaul was in the V4 scope

**Comment by pellarboss** [comment]
Please provide UI UX when ready

**Comment by curateproject** [comment]
Figma link:

https://www.figma.com/file/7K8McIi4ZqToPLn2f1pLEF/Curate-v4?node-id=3167%3A4140
