### ISSUE TITLE
Complete Bugcrowd Audit

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#287]
Complete bugcrowd audit (they've already been paid) so we can integrate/list our mainnet token (XCUR XC20) with kucoin

**Comment by pellarboss** [comment]
waiting for bugcrowd to come back to us, chasing up now

**Comment by pellarboss** [comment]
Testing in progress, waiting for BugCrowd

**Comment by pellarboss** [comment]
finally done
recommended fixes are in production
