### ISSUE TITLE
Admin panel bug: Image compression issue

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#291]
Images uploaded through the **admin panel** are getting capped to 600px max width, which results in a pixelated image when user zooms in for both P2P and NFT mktplace

**Comment by pellarboss** [comment]
@curateproject can you please provide a URL on the product with this issue?
we would like to investigate further

**Comment by curateproject** [comment]
Will this action by @eventang2015 mean the apps show the full size image whenever an image is uploaded via admin?
