### ISSUE TITLE
[Feature] - Rankings Page

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#292]
Users pick between the different categories to be processed on the rankings table, users should be able to pick between:

-Creators: Account for minted and sold NFTs.
-Collections: NFTs under the same collection. (Default Category)
-Sellers: NFTs bought and sold by users.

On the page, we should see a table with the following metrics:
<img width="642" alt="Screenshot 2021-10-13 at 09 23 30" src="https://user-images.githubusercontent.com/86632157/137095753-43467694-5c0e-4725-9172-1edf5be7033e.png">

**Ranking**: Fixed Number list, always representing the order of the criteria selected.
**Total Volume**: Sum of the value of all transactions of the items.
**Market price**- Average of last 5 products sold
**Floor Price**: Minimum price available in the market for the collection
**Trending Collections Algorithm Creators**: 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost).

**Note: Trending Algos should be set for 14 days instead of 24hrs in the first couple of weeks in order to compensate for lower volume, this score will work better with time**

**Comment by toomingos** [comment]
Why can't we have this on V4? I thought this was a part of the Stats & Metrics Scope

**Comment by eventang2015** [comment]
@toomingos can you clarify this? 
top 10 creators/collections/sellers etc...?

![image](https://user-images.githubusercontent.com/28645146/155966424-1a6c5d66-d317-4839-85bc-ea9344a70f53.png)

**Comment by toomingos** [comment]
Yes ofc, so we thought about haing those 3 options so people can filter depending on their interests. For Collections it's pretty straight forward, you rank based on each collection. For Creators you rank users who minted and their primary market sale (the NFT 1st sale) . For Sellers is just general volume, so NFTs they sold and bought should go onto trading volume

**Comment by madtocc** [comment]
@toomingos Is the current version ok, or do we need to include something else? 
There are a couple of things on Figma that are not implemented. Can we create a new issue with the tweaks that are required? I think that the overall rankings page is ok. Let me know your thoughts.
