### ISSUE TITLE
P2P Marketplace Tweaks 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#297]
1. Add an 'Options/Variation' field when listing an item
2. Admin panel tweak: Add countries shipped to and price as well as the 'options/variation' field under product and make it editable by admin
3. Admin panel tweak: In settings under admin, ability to add warning message on the purchase P2P item page 'buyer disclaimer: international shipping times may vary'
4. ~~Add shipping price in the purchase box~~
5.~~Display your own country flag 1st on listing page and message if users country is not available 'Does not ship to your country'~~
6. ~~Show maximum 2 rows of country flags (if more countries are supported add a 'show more' button which expands)~~
7. Add option for continents and global option for sellers when selecting countries shipped to
8. ~~Typo on email sent to buyer after purchase 'please' spelt wrong~~
9. ~~On the 'BOOM' successe page once buyer has bought item, add following text 'The seller has been notified to ship the item, you will be informed once shipped and tracking info has been provided. There is nothing for you to do currently :)'~~
10.~~On 'BOOM' page for buyer once purchased an item, the back to home button should take users to the 'to be shipped' page~~
11. ~~on the 'to be shipped' page and product purchased page once a buyer has paid for it, it shows the buyer as the seller, please see below attached~~
12. text for in app notification for seller to be changed to: 'BOOM! Item sold: ITEM NAME. Please ship it as soon as possible

![orders page error](https://user-images.githubusercontent.com/51517619/137394170-8ca18061-a793-4001-9ca1-3fae614d90b7.jpeg)

13. ~~Goods received page: text edit:  I confirm I have received the following item: ITEM NAME - Funds will be released to the seller once marked as received. Any buyer and seller rewards will also be added after this.~~
14. Order shipped email, the only part to change is to remove the following text 'Please pay attention to the logistics information'
15. ~~Require KYC verification before users can enter details on the list item page as users are losing all their inputed listing info after having to go through KYC~~
16. Price items in USD not in XCUR when listing and bidding on an item on P2P marketplace

**Comment by curateproject** [comment]
Moved to January milestone, if the rest of these tweaks can be done for this month please

**Comment by eventang2015** [comment]
3,14 are done.

**Comment by pellarboss** [comment]
Everything apart from Geographic based Shipping is done.

Lets close this issue and open up a new one for regional shipping support (potentially to integrate with physical market place)
