### ISSUE TITLE
Ability to Tag NFTs in App

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#308]
Allow Admins to place a "Caution" tag on NFTs manually 

Goal - For users in the marketplace to be aware of what NFTs are of the above categories and prevent the continued sale of stolen and duplicate  work 

In the marketplace there could be like a rad tag across the top of the NFT in red that has the above written so that in app users are aware

**Comment by pellarboss** [comment]
@eventang2015 please add tag for Profile & Item
Please inform Marco once that is done and the new attribute

@madtocc please display a message if the product is Tagged
horizontal red bar, with an warning icon on left, showing, "⚠️ Please take caution trading with this seller"

**Comment by eventang2015** [comment]
@madtocc  new field - fraudulent on product and user

**Comment by TheOneXi** [comment]
Hi @pellarboss and @eventang2015 where in admin panel can admins add the caution tag onto NFTs and users?

**Comment by eventang2015** [comment]
there's a toggle button under the item key.
![image](https://user-images.githubusercontent.com/28645146/150317475-6fd97571-2e85-4f78-b4fa-8fbe30703093.png)

**Comment by TheOneXi** [comment]
@eventang2015 is this in staging? I can't find it on production app - can you push it live so I can see and send me the link to the item above so i can try?

**Comment by TheOneXi** [comment]
@madtocc and @eventang2015 can you confirm if this will be shown in the new build?

**Comment by madtocc** [comment]
app side yes.
