### ISSUE TITLE
[App] - Banner to Direct Deposit USDXC

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#309]
on Accounts page
under accounts, create a banner
the banner links to deposit USD using circle
the copy should read:
Deposit USD
with Visa, Mastercard
and a Card icon if possible

Attached Binance as an example
![tempFileForShare_20211021-092542](https://user-images.githubusercontent.com/24906507/138251426-23b453a2-0981-4064-8e0b-fba63a5f0420.jpg)

**Comment by Princeobinna** [comment]
Approve assets
