### ISSUE TITLE
Connect Wallet Feature (MetaMask/Wallet Connect)

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#314]
Add connect wallet button on purchase NFT or physical good page which allows users to connect their wallet via meta mask, trustwallet or wallet connect.

Users will have to pay the gas fees.

**Comment by TheOneXi** [comment]
Add MetaMask FAQ Page on website with buttons for staking, importing etc..

MM = Decentralised and seamless import/export and purchasing but cons not gasless and no rebates

**Comment by TheOneXi** [comment]
User connects MM and interacts with master wallet (xcur.eth) and pays the gas fees

**Comment by pellarboss** [comment]
as discussed, if a decentralised approach is needed (for metamask), where users keep custody, we should explore building a decentralised marketplace instead - eg defi vs cefi

moved to future milestone

**Comment by TheOneXi** [comment]
Integrate ZK rollups to offer low fee tx trading
