### ISSUE TITLE
Sharing Errors in Web App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#324]
Errors Showing:

**#1 - Cannot Share NFT's using Web App**
1. Log in to my account on web app and click MY PROFILE
2. Click my NFT
3. Click Share
4. **Expected Outcome:** Window showing option for Sharing (Twitter, instagram, messenger, copy-link, etc.)
   **Actual outcome:** Error appears : "error sharing" 

![Figure 1 Error Sharing](https://user-images.githubusercontent.com/93180831/140478643-7fec0f05-7f42-49a5-86fc-98f7177f4fb4.jpg)

**#2 Can't open link shared via mobile phone on web app**
1. Log in to mobile app
2. My Profile > My NFT
3. Share to Twitter
4. I open my twitter profile using my desktop
5. I click the NFT link shared on twitter
6.  **Expected outcome:** Link to the specific NFT product on Web App
     **Actual outcome:**  The link directs to the Curate website homepage:
https://curate.style/?product=44254ef013ba805e0b6a2b79

![Figure 2 Curate Home page](https://user-images.githubusercontent.com/93180831/140478664-efbcf881-2ea7-44ff-b124-21b424337eba.jpg)

**Comment by madtocc** [comment]
This is currently a problem that we face with web. We are working in re-routing the app + UI upgrade for v4.1 
This is the same issue as https://github.com/pellartech/curate/issues/249#issuecomment-961401632 can take a look at this comment for more details. Any type of share in app (product and profile) currently does not work for web.
