### ISSUE TITLE
Notification Bug

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#325]
I've recently logged in the Curate official app account to list the staking NFTs. I logged out and logged in my personal but still got a sale notification of the Curate account.

Curate account key: 25fad84b4a2553d8b0b9b3cac762cfab424b
My account key: 0f425074c0d72164cde6f5a033fed1e142ba

**Comment by pellarboss** [comment]
notification is reset every time you are logged in
it remembers the device (and sends directly to the device)

let us know how you would like to change the logic
