### ISSUE TITLE
 Cropped Instagram Link in User's Profile

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#328]
Error in linking Instagram profile with Curate Profile

**User details:**
email: olegz82@gmail.com
Curate profile:  @WillyWonkaART
Instagram  link:  https://www.instagram.com/willywonka.art/

1. Click Settings> Change my Details
2. Paste Instagram link https://www.instagram.com/willywonka.art/
3. Click Update profile
**Expected Result :** Active instagram link showing on user's Curate profile
**Actual Result:** https://www.instagram.com/willywonka  (incomplete instagram link, missing .art/) (edited)

**Comment by madtocc** [comment]
regex rule wasn't including the dot in instagram username, so it was trimming. It is fixed and it will be available in the next update.
