### ISSUE TITLE
"Sign in with Curate" API Key Integration

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#329]
In order to give the best user experience to the projects we work with we need to provide an easy integratable API Key for users to pull all the data they need from it's users. The users sign-in on the project's platform using their Curate Account like we normally sign in using our Google/Apple account.

![Sign in with Curate](https://user-images.githubusercontent.com/86632157/141649011-ddaee6c6-e890-49c7-8832-d6ddc7b0db88.jpeg)

**Comment by pellarboss** [comment]
instructions provided
