### ISSUE TITLE
[BUG] Weekly and Trending 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#330]
Users are gaming the weekly and trending by using auto clickers to go in and out an NFT to rack up views 

My recommendation -
A single user can only contribute a maximum of 1 View to the Weekly/Trending Per a day 
1 User = 1 View max per a day that counts towards weekly and trending

**Comment by pellarboss** [comment]
add some logic (potentially using redis)

if userkey_viewed (cache hit), ignore the request
if no cache, create cache, expire cache in 3 hours

**Comment by eventang2015** [comment]
ignore within 3 hours
