### ISSUE TITLE
[BUG] Visual Withdrawal screen

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#335]
Withdrew 1000 XCUR - I received the correct amount minus the fee however when checking the Tx history it shows "Fee: 0 XCUR"

Would be nice if we could update this so it displays the accurate figure

Image attached below - account email - moe@curate.style 

![IMG_7834](https://user-images.githubusercontent.com/72095738/142187892-f11edbc3-7bf0-42fd-8b74-5bbb163148ba.PNG)

**Comment by eventang2015** [comment]
@madtocc 
`{
    "type": "WITHDRAW_XCURP",
    "amount": 999,
    "fee": 0.16,
    "platform": "BSC",
    "destination_address": "0xE90cf333E77059e975510A7E0c855C740f38c1dc"
}`
