### ISSUE TITLE
BUG: NFT Denied shows under Collections

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#339]
The NFTs that were denied appear under Collections but not under my NFTs

App user: thepixelartnft@gmail.com
Device: iOS latest version

![photo_2021-11-20 23 34 01](https://user-images.githubusercontent.com/51517619/142743945-9acde45e-f532-46df-a2a9-d2b71ab497d1.jpeg)

**Comment by eventang2015** [comment]
hotfixed.
