### ISSUE TITLE
Dashboard Enhancements 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#34]
Make 'find user' also search user emails, usernames, names 

https://admin-stage.curateapi.io/users

**Comment by DefiHunter** [comment]
-Monitor  daily/monthly sales volume 
    - Total Entire app
     - Total Per user 


- Monitor average sale price 
-Monitor revenue generated in commission % 

-Monitor total expenses (Gas fees) covered by Master wallet


Analytics tab , With filters to be able to sort. E.g. per user and whatever else you can think of

**Comment by DefiHunter** [comment]
App metrics - 

Installs 
Uninstalls 
Active users ( Made a purchase within the past month) 
Weekly/daily/monthly new sign ups

**Comment by pellarboss** [comment]
Sales Metrics = OK
New Sign Ups = OK
Active Users = OK

App Metrics (Uninstall / installs) is obtained through APP stores (Google or Android)

**Comment by DefiHunter** [comment]
Commission 

Total  XCUR Commission earned for Curate 

Able to filter for 
Daily/Monthly/Yearly/All-time

**Comment by DefiHunter** [comment]
@pellarboss 

Could we prioritize this for sprint 5? 

Particularly 

- Sales volume and, 
- Commission earned by Curate

**Comment by DefiHunter** [comment]
Also 

Total value locked 

Total value of deposits in Curate app 

So that would be 

Total XCUR

Total ETH 

Total USDXC

**Comment by DefiHunter** [comment]
**Outlined below all the features**


_Hope its a little clearer_


Backend Admin Metrics to measure 

Sales Volume - (User A sells 2 NFTs to User B for 1000 XCUR each , Sale volume is 2000 XCUR, if User B now resells it for 2000 XCUR , total sales volume is 4000 XCUR)
Total overall for entire platform 
Total per a user 

	Ability to sort
	-Daily,monthly,Yearly,All time 

Total Gas fees spent by XCUR master wallet
Ability to sort
-Daily,monthly,Yearly,All time 

New sign ups
-Daily
-Weekly
-Monthly

Total XCUR Commission earned for Curate in XCUR as a result of NFT sales on platform 
Able to filter for
Daily/Monthly/Yearly/All-time

Total value locked (Total in master wallets and user wallets combined)
Total value of  all deposits in Curate app
-XCUR
-USDXC
-ETH

And maybe some graphics to see its increase over time

**Comment by curateproject** [comment]
also show:

- total value of all XCUR + ETH + USD individually on the app (held by users)
- total commission earn by curate (daily, monthly, yearly, all time, custom time period)

**Comment by curateproject** [comment]
Also @pellarboss and Marco can you fix this glitch where once an NFT is approved the page auto refreshes as right now it gets stuck on 'minting NFT':

https://www.awesomescreenshot.com/image/10498713?key=6d0caca395a98dbff25ede55883e1245

**Comment by curateproject** [comment]
@pellarboss is this now ready to view? I can't see any updates in the admin panel

**Comment by DefiHunter** [comment]
Please see my above comments and lets tackle in Sprint 6
