### ISSUE TITLE
Collection Page Improvements

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#340]
-Remove attributes from the collection page
-Move Profile picture
-Add share button
-Move Attributes section and replace them for Volume traded, number of items, number of owners, and floor price

![image](https://user-images.githubusercontent.com/86632157/142952479-bddfc503-4381-4d67-a73a-8a9ff3fb2966.png)

**Comment by toomingos** [comment]
Social media icons should be the same as the ones found on profile pages

**Comment by pellarboss** [comment]
@eventang2015 please return these info, please info Marco the payload for UI implementation
