### ISSUE TITLE
Include Transactions from June on the Total Volume Traded on User's Profile

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#342]
Include Transactions from June to reflect on the Total Volume Traded on User's Profile (as seen on attached image). The app currently shows the sales volume from September. 

![Screenshot_20211124-101749](https://user-images.githubusercontent.com/93180831/143159555-f084ce4a-ebb1-4e2d-b937-1b19535768e7.jpg)

**Comment by pellarboss** [comment]
@eventang2015 please script & calculate previous
