### ISSUE TITLE
Buy XCUR banner

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#347]
Add Buy XCUR banner with the same style as the deposit USDXC banner, since the path from USDXC to XCUR isnt as clear  for newcomers is not as clear as it should be, sicne they have to exit the page and find the buy XCUR one
![ticket](https://user-images.githubusercontent.com/86632157/143611757-1b7496e6-0ad9-4f0f-b0fd-2c62753cf515.png)
r

**Comment by toomingos** [comment]
Please find another icon for the banner, here's another suggestion for the layout
![1620 Stats Hopper @nft_hopper NFTs Wallet 24 0x z4 Followers Following 129 1,9K ALL NFTS SOLD MINTED 50K 12K $265K $107 4K #26 HOPPER - SHAMAN #37 HOPPER - CRUSADER 94K 10K 17 5K $88K 100K $550K #76 HOPPER - GOOGLY](https://user-images.githubusercontent.com/86632157/143612077-6e1d462f-8297-48e1-b46d-e4265ea05230.png)
ut

**Comment by madtocc** [comment]
![a](https://user-images.githubusercontent.com/12486417/144492205-1f8dcc56-6a24-40b0-9069-938ec5c5c6a4.jpeg)
