### ISSUE TITLE
Buy Product button for users with no funds

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#348]
Buy Product button for users with no funds should link users to the wallet page after they click it, and a pop up should show saying something along the lines of:

Your account's balance is empty, please deposit funds via an external wallet or deposit USDXC using your card.

**Comment by madtocc** [comment]
Added an alert box with options that can redirect the user.
![b](https://user-images.githubusercontent.com/12486417/144491960-f90dd278-7b90-4885-99f1-956d3a4247fd.jpeg)
