### ISSUE TITLE
[APP] Warn user before depositing DOT

### ISSUE THREAD

**Issue by madtocc** [pellartech/curate#352]
Auto prompts a modal when the user goes to "Deposit DOT", due to the "weird" DOT requirements.
It would be great if you guys could provide the text you'd like to show. Otherwise, let us know, so we can provide a technical text.

**Comment by pellarboss** [comment]
"Please note that the Polkadot network requires a minimum balance of 1 DOT, please ensure you deposit more than 1 DOT in to the account, if less than 1 DOT is received, the funds are automatically lost"
