### ISSUE TITLE
Allow Collection Description to have space between paragraphs

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#353]
An error when user tries to add description for a collection: He wants to create spaces between paragraphs but instead, it would show up as seen on the picture.

Click 3 bars on upper left corner > my NFT > Collections > Adding description to collection
![Screenshot_20211117_143237_app wallet curate (1)](https://user-images.githubusercontent.com/93180831/144194920-28167e0e-1902-4c70-8dcd-48b6fa969695.jpg)

**Comment by pellarboss** [comment]
See how new lines are parsed and returned, try to replace it with something else?
Let us know if we can do anything on the server side (replace characters like \n with something else)
