### ISSUE TITLE
Mint NFT UI/UX Change (2 step minting)

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#357]
I've redone the minting process and sent this to our front-end designer so he can add it to the Figma file as well.

The main idea is to streamline minting to anyone, fon the first page we load the gallery of the user and he picks the content of the NFT, while on the second he inputs the main details, clicking on the advanced tab to access all the other options.

On the advanced tab let's tweak a few things as well:

-Rename "Traits" to attributes.
-Add a "?" icon with an explanation to the following:
Metadata- Optional additional data that is registered on the Blockchain, not visible on the marketplace.
Proof of Work- Optional additional information to help us determine if you own the copyright license or if you're the creator of the artwork. Protecting buyers and sellers.
-When users click the collection tab, they should have the add button to create one so they don't need to go to the collection page.

Collection Creation tweaks:
-Add "?" to logo and background that when clicked shows a preview of that section of the collections page and mentions the sizes of the logo and background, i.e. Collections background-size: 1280 x 384 pixels

**Comment by toomingos** [comment]
[2 Step minting.pdf](https://github.com/pellartech/curate/files/7642455/2.Step.minting.pdf)
Here's a pdf file as an example of what we're aiming for

**Comment by pellarboss** [comment]
@madtocc please look at what you can implement
I presume this workflow creates multiple NFTs

**Comment by madtocc** [comment]
@toomingos could you clarify this? 
is the 2 step minting the one that is currently available in the app (you pick the picture(s)/video(s) first then add the details or it is a bulk creation (which is what @pellarboss is saying)?
