### ISSUE TITLE
Export NFT Page Tweak 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#359]
When trying to export an NFT - Display estimated Lazy Mint cost  Export cost 
If user approves lock funds and export NFT 

Currently it just says insufficient funds
![Image from iOS](https://user-images.githubusercontent.com/72095738/145400620-fe26dab6-f4ae-417a-bbdb-6b11b4b948c9.png)

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/148393132-4b7d0996-6446-47e8-a070-2c4a02035286.png)
