### ISSUE TITLE
Featured listings + Trending Now listings

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#36]
Add a featured section on the marketplace (listings featured enabled in admin) and trending now section (based on number of bids)

**Comment by DefiHunter** [comment]
Add-
Todays picks - Based on 24hr likes and Bids 
                     Formula (24hr Likes +24hr Bids)/2 
Lets show top 6

**Comment by DefiHunter** [comment]
Featured - Top 3 shown

Trending top 6 shown

Todays pick - Top 6

**Comment by DefiHunter** [comment]
Lets create a home page 

And design it similar to this 

So a new home age tab in the side menu 
![IMG_6311](https://user-images.githubusercontent.com/72095738/124351903-65704f00-dbfd-11eb-99bf-d9f6753c7eda.PNG)
![IMG_6312](https://user-images.githubusercontent.com/72095738/124351913-7de06980-dbfd-11eb-8c3b-4807d326aaf5.PNG)
![IMG_6314](https://user-images.githubusercontent.com/72095738/124351923-905aa300-dbfd-11eb-9c3b-a46ac52ee780.PNG)
![IMG_6313](https://user-images.githubusercontent.com/72095738/124351933-9c466500-dbfd-11eb-8729-79f2bda6ef66.PNG)


https://user-images.githubusercontent.com/72095738/124351890-56899c80-dbfd-11eb-9a19-ee569f43c9dd.mp4

**Comment by pellarboss** [comment]
how is Trending defined?
@curateproject @DefiHunter

**Comment by DefiHunter** [comment]
Trending - Item with the most views in a 24 hour window 

So if user a and user b click on item A and view it, that would be counted as 2 views

**Comment by pellarboss** [comment]
@DefiHunter actually James defined Trending as number of bids above - lets use that instead?

**Comment by DefiHunter** [comment]
# of bids would exclude fixed prices 

Lets go with # of views for Trending

**Comment by DefiHunter** [comment]
New tab in side menu called "Home"

This is where all this should be displayed

**Comment by DefiHunter** [comment]
@madtocc Feel free to get creative with this one too and work your UI magic

**Comment by curateproject** [comment]
Had a look at the APK you sent today @madtocc 

Can you do the following:

1. Reduce the size of these 3 sections, ideally 75% smaller.

2. Show the slogan and search bar at the top still

3. Can you rename today's picks to 'Weekly Picks:

I'll then have a look once the above is done and get back to you

**Comment by madtocc** [comment]
In the given layout they are large.
The height of the sections are sized in respect of the device height as the following: featured (35%), trending (30%), todays picks (30%). If you want to resize to 75% smaller, which is 1/4 of the current size it will need to have a different layout since the text itself + price + like will be bigger than the photo. So, maybe we could remove the title & price and overlap the price in xcur + the number of likes, or just the price?
or maybe add the same size and layout as we did for the results but with a fixed height?

**Comment by curateproject** [comment]
Can I see an example of both to compare @madtocc ?

**Comment by madtocc** [comment]
@curateproject 
something like this:
featured is the same as the weekly but weekly is slightly taller
trending is the option to show more items and as suggested before
![image](https://user-images.githubusercontent.com/12486417/125835308-4c529087-6a14-4d5d-a6e8-c903677e6089.png)

**Comment by DefiHunter** [comment]
Maybe make them all the same size as the weekly picks, even if it stretches over a page its fine if they have to scroll as i feel they'll like it , thoughts?

**Comment by DefiHunter** [comment]
Could i also see the original pic to compare? Don't think i received it

**Comment by madtocc** [comment]
![Screenshot_20210715-150731465.jpg](https://user-images.githubusercontent.com/12486417/125836432-cf16c34b-c5d4-4c65-a8e0-adc0bc18c07f.jpg)

**Comment by madtocc** [comment]
the three options is just to show different outputs. The idea is to pick one.

**Comment by DefiHunter** [comment]
Ah i see, in that case i really like the weekly picks layout

**Comment by madtocc** [comment]
since we have different aspect ratios, would you rather show the whole image or scaled. See an example below:
Featured = show whole image
Trending = fit to the height of the box
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 15 16 36](https://user-images.githubusercontent.com/12486417/125837538-28b028f0-853a-417d-91a4-45a0a79c8877.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 15 16 40](https://user-images.githubusercontent.com/12486417/125837557-3bc62982-6c06-4a00-b0f2-48016595fd4b.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-15 at 15 16 46](https://user-images.githubusercontent.com/12486417/125837563-f60a9d61-735d-47a9-804a-f52449546cd3.png)

**Comment by DefiHunter** [comment]
I prefer the trending wbu?

**Comment by madtocc** [comment]
I also prefer (seems more uniform) despite having the image cropped, but that's the price we have to pay allowing multiple aspect ratios 😅 
I will leave this as the option then... we can change it later
Thanks for the feedback

**Comment by curateproject** [comment]
@madtocc can you send me an updated APK with the updated uniform blocks above (try make it slightly smaller if you can)

**Comment by madtocc** [comment]
sure, @curateproject  like this is ok?
![image](https://user-images.githubusercontent.com/12486417/125846123-332c8ab4-ff5f-4d5e-a1e5-1043d0e43efa.png)

**Comment by DefiHunter** [comment]
@madtocc   could we place this on a new page called the "home" tab 
So above the "NFT Marketplace" there would now be a "Home" tab for all this info

**Comment by madtocc** [comment]
Yes, I can include it just let me know if you really want. Since home page = 3 sections + NFT marketplace. including a new item on the menu with almost the same isn't a little bit redundant? 🤔 
upon search or filter we can hide those 3 sections. lmk what you want

**Comment by madtocc** [comment]
or add a toggle "^" to hide them

**Comment by DefiHunter** [comment]
The home page would just be for Featured, trending and weekly picks

**Comment by DefiHunter** [comment]
And since it would be on its own page, lets try and scale the sizes up a bit, maybe 50%?

**Comment by madtocc** [comment]
so, home page = default page when app loads

Featured
Trending
Weekly picks

no search, no filter 

correct?

**Comment by curateproject** [comment]
To confirm @madtocc 

Can you create a new tab on the marketplace page where we default too called 'Home' which has the 3 new blocks (slightly larger as it's on it's own page now) and a 2nd tab called 'Marketplace' with the search bar at the top (as it is now)

**Comment by DefiHunter** [comment]
> so, home page = default page when app loads
> 
> 
> 
> Featured
> 
> Trending
> 
> Weekly picks
> 
> 
> 
> no search, no filter 
> 
> 
> 
> correct?

Perfect spot on

**Comment by madtocc** [comment]
ok, I will generate a new build with the updates.
later we can add author/owner on the card as well and if it is an auction the auction details such as time remaining and number of bids.

**Comment by curateproject** [comment]
yes great idea, perhaps try adding the title under the NFT for the new home tab and seeing if it looks better?

Look forward to the new build!

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/125852823-52b994c1-bf8f-4a28-988f-bd6e9c483a0f.png)
height is ok?

**Comment by curateproject** [comment]
![Screenshot_20210715-224419.jpg](https://user-images.githubusercontent.com/51517619/125861922-37d96f27-ff7a-4fcf-95b2-cc582421e5a0.jpg)

@madtocc where it says buy.sell.mint can you replace that with the 'Home' tab where the app defaults to on open.

Can you add a tab next to it 'Marketplace'

And remove the new menu item.

**Comment by curateproject** [comment]
Just to confirm @madtocc is this correct:

Featured = Manually selected by admins in admin panel (try keep this up to 10 at a time)
Trending = Views (10 will be shown)
Weekly picks = Manually selected by admins in admin panel (try keep this up to 10 at a time)

MARKETPLACE TAB
Marketplace page = algorithm we discussed here: https://github.com/pellartech/curate/issues/121

**Comment by DefiHunter** [comment]
Featured is nice as manual 

But for weekly picks lets think of a formula 

Using a combination of 
Views
Likes

**Comment by curateproject** [comment]
Let's keep weekly picks as manaully selected via admin @madtocc 

I've got plans for this as we rollout further
