### ISSUE TITLE
 Improve Withdrawal TXN Detail so that it shows  Txn Hash on etherscan/BSC

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#360]
Improve TXN Detail so opening the withdrawal shows Tx ID on etherscan/BSC

Current TXN Detail: Only Xchain Hash

For Improvement:  Show ID as Xchain HASH and hash be the etherscan or BSC hash

![Image from iOS](https://user-images.githubusercontent.com/93180831/145557819-87674791-2972-4252-afaa-de542186cf87.png)

**Comment by pellarboss** [comment]
@eventang2015 please document how to obtain this data for the related txns

**Comment by eventang2015** [comment]
add new field - external_txn in transaction, it's get from withdraw logs.
`            {
                "key": "3b8210802b5128dbadbb2d91b6f2df380c6823502b7fe564a9d62b48504ee84a",
                "owner": "035360160265a3e88d80a65205da27155089aa86acbb8874057cefddced7a81767",
                "created": "2021-09-24T09:34:06.844Z",
                "sender_account": "035360160265a3e88d80a65205da27155089aa86acbb8874057cefddced7a81767",
                "recipient_account": "021511aaa0939d8c1b5723c20ffd4385fa90788ceb63bd1c8b4e0a5739145dcd57",
                "amount": -1,
                "amount_num": -1,
                "symbol": "XCURP",
                "type": "WITHDRAW_XCURP",
                "hash": "ee07e21038010fa6cf11c816cbd600a1bfcd6ab672a33d60645c27673937f2d1",
                "block": "1757353",
                "signature": "3045022100cc68d54878685bae32fd5998bf9d962abd2224e494353ca2533577e9381bd9db022044d8531f62d7f123c7013e99406230147a1c549bd9c8a5553036f80639984409",
                "status": "COMPLETED",
                "fee": 0,
                "external_txn": "tsgtqggit"
            },`

**Comment by TheOneXi** [comment]
Did this get done @eventang2015 or @pellarboss ?
