### ISSUE TITLE
Index Data for user sales to get sales volume percentile

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#362]
Index Data for user sales  to get Data on:
Sales Volume Percentile 

(Basis/Criteria required for giving verified Badge to Curate Sellers, ie: seller must be in the 95th percentile with respect to sales volume)

**Comment by pellarboss** [comment]
@Catherineanne91 
so this data will be presented in the admin panel?
it will be used to inform admins when given Verified status?
