### ISSUE TITLE
Download NFT button for Owners

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#364]
The owners of an NFT product should be able to download the file so they can have it as their PFP on Twitter, for example. Gonna speak to Alexey about this so we can have it on our new UI.

Let's add a download feature on the "My NFT page"

**Comment by pellarboss** [comment]
investigate the best UX to do this? Maybe Long Press?
see how others have solved this issue?

**Comment by curateproject** [comment]
Long press would be fine, or maybe an inbox/down arrow icon indicating to download

**Comment by madtocc** [comment]
This is already implemented in the current app.
![image](https://user-images.githubusercontent.com/12486417/148392502-597dad85-54f3-4f13-96d5-e20b0866146a.png)
![image](https://user-images.githubusercontent.com/12486417/148392519-026cae3b-4599-4f06-826f-0239eaa26801.png)
