### ISSUE TITLE
[BUG] Master Wallet Bep -20 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#365]
Users trying to withdraw XCUR BEP-20 . despite having enough funds user withdrawals are getting notified insufficient funds 

Below are 2 users with the issue 

@Moe Carrim same case with
hanthienduc.96@gmail.com trying to withdraw 3087 XCUR (Master account has insufficient funds)
I asked him to try 1k but still the same error message

''Dear Curate,
in my wallet (032afe1a63154fde13a83337b39b5a1c38afa3ad29069b81256cd7c833dc1ddf71) I have Eth 0.01498816
and I would like to convert all in XCUR but my app (android) and also from web app (already try with all browser) I have always error
...
Unfortunately still I have problem,
My phone is MI9 App version v4.1.2b98 Android
I try to use web app also, with windows 10 firefox / chrome / Brave
My email is Fausto@fststudio.com
Thank you.''
@Tomás Domingos

**Comment by pellarboss** [comment]
When BEP XCUR Master doesnt have enough, it will show insufficient funds 
Please let us know if this is still persisting

The buy ETH txn is an ETH network issue, we have set the record back to pending, and it is now fully complete
