### ISSUE TITLE
Cant Check Status of Shipment in P2P marketplace 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#367]
![admin console](https://user-images.githubusercontent.com/93180831/147305010-7f207cea-17ce-4b97-aba6-4ce3e9db637d.jpg)

Issue: **Cant Check Status of Shipment**

Admin Panel > Orders

Clicking the Order keys (Left most column) would just keep "loading"

**Comment by eventang2015** [comment]
@Catherineanne91 it should be fixed. role issue.
