### ISSUE TITLE
Import NFT issue 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#369]
Previously a user was experiencing issues with exporting NFTs so I was testing and I did exported my stake boosting nft.

I imported it back but it's showing timeout 

Help please 

https://etherscan.io/tx/0xb5a7f843b15feba9511a60b8c0683c3ebf81e2cfa06bbb7965cd6dd711e84671

User: gadithomason1@gmail.com

Device: iOS v15.1

Latest version (v5)

**Comment by pellarboss** [comment]
exported NFTs will need to be manually imported again, we will investigate this first

**Comment by eventang2015** [comment]
I rest the product to approved. will implement logic in code.

**Comment by eventang2015** [comment]
it's now fixed in staging, will merge to production
