### ISSUE TITLE
NFT stake boost not recognised

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#372]
Email nilakshan91@gmail.com
Device android 11
NFT type platinum
Version: 5.0.1 (latest)

This user is not getting his stake boosting nft recognised, please can you investigate

**Comment by pellarboss** [comment]
New build is in review, it should fix this display issue.

Stake is correctly applied thou (boost is applied)

Please update to the latest version when it is live (113)

**Comment by madtocc** [comment]
Checked and the user does not own any boosted NFT.
Can you verify if he does? 
https://admin.curate.style/products/user/00c22a1c6e9c9116186e0ce978ee3eab6d6e/nft
