### ISSUE TITLE
Display total staked tokens on public and admin dashboard

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#373]
Display new metric on both dashboards

'Total XCUR staked'

**Comment by eventang2015** [comment]
implemented in staging

**Comment by curateproject** [comment]
great happy to push forward to production

**Comment by eventang2015** [comment]
it's now in production.

**Comment by curateproject** [comment]
I don't see it on the public dashboard @eventang2015 ?

https://dashboard.curate.style/

**Comment by pellarboss** [comment]
<img width="585" alt="Screen Shot 2022-01-13 at 1 50 47 pm" src="https://user-images.githubusercontent.com/24906507/149257220-9f3c8141-2e23-41d7-a5c9-fdacd64191f6.png">

its in admin, do we want it in dashboard also?

**Comment by curateproject** [comment]
Yes please in public dashboard too @pellarboss (apologies for not mentioning earlier)

**Comment by eventang2015** [comment]
merged to production https://dashboard.curate.style/

**Comment by TheOneXi** [comment]
@eventang2015 can you add a comma (,) to make it easier to view the numbers i.e 300,000.00 XCUR etc
