### ISSUE TITLE
Staking page tweaks

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#374]
1. Display staking rewards on staking page which get updated in real time (or daily if that's easier)

2. Display the stake boost multiple applied if a stake boosting NFT has been used for staking (currently the log on the staking page only shows the APY without any boost applied)

3. On the 'amount' field (when entering XCUR amount for the staking page) can you add a '50%' '75%' and 'Max' option to make it easier to enter the XCUR amount available instead of switching back to the wallet page to check the number of XCUR tokens

**Comment by eventang2015** [comment]
get stakes - `{{host}}/accounts/:key/stake` 
`{
    "total_count": 4,
    "total_pages": 1,
    "has_next_page": false,
    "current_page": 1,
    "item_count": 4,
    "items": [
        {
            "key": "14779a4e018bd308",
            "user_key": "a03c707e7e993313b7656f60957972e0648a",
            "account_key": "239bc03f1957a1d6a3c2419353ffd62d8b32",
            "symbol": "XCURP",
            "external": "03e2d5517c2a854c393599df1937a8e630944646e65c54cbf5363b856e2dc8fa2e",
            "amount": 100,
            "period": 60,
            "boost": 1,
            "apy": 5,
            "status": "active",
            "start_date": "2021-10-29T16:00:00.000Z",
            "end_date": "2022-12-31T15:59:59.999Z",
            "boost_product": null,
            "creator": {
                "key": "a03c707e7e993313b7656f60957972e0648a",
                "email": "test-019@test.com"
            },
            "interest_returns": 0.8252481,
            "created": "2021-12-31T02:37:11.735Z",
            "modified": "2021-12-31T02:37:11.735Z",
            "removed": false,
            "last_issue_date": "2021-12-31T02:39:01.526Z"
        },
        {
            "key": "2b09d50936b92a6a",
            "user_key": "a03c707e7e993313b7656f60957972e0648a",
            "account_key": "239bc03f1957a1d6a3c2419353ffd62d8b32",
            "symbol": "XCURP",
            "external": "03e2d5517c2a854c393599df1937a8e630944646e65c54cbf5363b856e2dc8fa2e",
            "amount": 100,
            "period": 3,
            "boost": 1,
            "apy": 5,
            "status": "completed",
            "start_date": "2021-12-21T16:00:00.000Z",
            "end_date": "2021-12-25T15:59:59.999Z",
            "boost_product": null,
            "creator": {
                "key": "a03c707e7e993313b7656f60957972e0648a",
                "email": "test-019@test.com"
            },
            "interest_returns": 0.04110152,
            "created": "2021-12-23T09:19:45.889Z",
            "modified": "2021-12-23T09:19:45.889Z",
            "removed": false,
            "last_issue_date": "2021-12-27T03:17:49.563Z"
        },
        {
            "key": "cb54feed906fb419",
            "user_key": "a03c707e7e993313b7656f60957972e0648a",
            "account_key": "239bc03f1957a1d6a3c2419353ffd62d8b32",
            "symbol": "XCURP",
            "external": "03e2d5517c2a854c393599df1937a8e630944646e65c54cbf5363b856e2dc8fa2e",
            "amount": 100,
            "period": 2,
            "boost": 1,
            "apy": 5,
            "status": "completed",
            "start_date": "2021-12-21T16:00:00.000Z",
            "end_date": "2021-12-24T15:59:59.999Z",
            "boost_product": null,
            "creator": {
                "key": "a03c707e7e993313b7656f60957972e0648a",
                "email": "test-019@test.com"
            },
            "interest_returns": 0.02739914,
            "created": "2021-12-23T09:19:39.149Z",
            "modified": "2021-12-23T09:19:39.149Z",
            "removed": false,
            "last_issue_date": "2021-12-24T07:10:56.979Z"
        },
        {
            "key": "8baef4b1d6a9847c",
            "user_key": "a03c707e7e993313b7656f60957972e0648a",
            "account_key": "239bc03f1957a1d6a3c2419353ffd62d8b32",
            "symbol": "XCURP",
            "external": "03e2d5517c2a854c393599df1937a8e630944646e65c54cbf5363b856e2dc8fa2e",
            "amount": 100,
            "period": 1,
            "boost": 1,
            "apy": 5,
            "status": "completed",
            "start_date": "2021-12-21T16:00:00.000Z",
            "end_date": "2021-12-23T15:59:59.999Z",
            "boost_product": null,
            "creator": {
                "key": "a03c707e7e993313b7656f60957972e0648a",
                "email": "test-019@test.com"
            },
            "interest_returns": 0.01369863,
            "created": "2021-12-23T09:19:20.664Z",
            "modified": "2021-12-23T09:19:20.664Z",
            "removed": false,
            "last_issue_date": "2021-12-24T07:10:51.067Z"
        }
    ]
}`
daily reard logs - `{{host}}/stakes/:key/`
`{
    "key": "14779a4e018bd308",
    "user_key": "a03c707e7e993313b7656f60957972e0648a",
    "account_key": "239bc03f1957a1d6a3c2419353ffd62d8b32",
    "symbol": "XCURP",
    "external": "03e2d5517c2a854c393599df1937a8e630944646e65c54cbf5363b856e2dc8fa2e",
    "amount": 100,
    "period": 60,
    "boost": 1,
    "apy": 5,
    "status": "active",
    "start_date": "2021-10-29T16:00:00.000Z",
    "end_date": "2022-12-31T15:59:59.999Z",
    "boost_product": null,
    "creator": {
        "key": "a03c707e7e993313b7656f60957972e0648a",
        "email": "test-019@test.com"
    },
    "interest_returns": 0.8252481,
    "created": "2021-12-31T02:37:11.735Z",
    "modified": "2021-12-31T02:37:11.735Z",
    "removed": false,
    "last_issue_date": "2021-12-31T02:39:01.526Z",
    "issue_logs": [
        {
            "key": "753ae900112d",
            "stake_key": "14779a4e018bd308",
            "principal": 100,
            "interest": 0.01369863,
            "interest_date": "2021-10-29",
            "txn": "df4f99fa6752235cf37d580dea30adc445a8e5576acd4ade831ead3747e5da6c",
            "created": "2021-12-31T02:39:01.041Z"
        },
        {
            "key": "bf45267e7367",
            "stake_key": "14779a4e018bd308",
            "principal": 100.01369863,
            "interest": 0.01370051,
            "interest_date": "2021-10-30",
            "txn": "a15044d2a2f5340bbbe02437ae4f0f276a7f86a820cec0cd9014dfc177854b5a",
            "created": "2021-12-31T02:39:01.054Z"
        },
        {
            "key": "4eb0091f8182",
            "stake_key": "14779a4e018bd308",
            "principal": 100.02739914,
            "interest": 0.01370238,
            "interest_date": "2021-10-31",
            "txn": "aaf3b4a4d1c893ef60987688f59538a9db6634cefa940e379a2257179e86dbbf",
            "created": "2021-12-31T02:39:01.064Z"
        },
        {
            "key": "166d30de984b",
            "stake_key": "14779a4e018bd308",
            "principal": 100.04110152,
            "interest": 0.01370426,
            "interest_date": "2021-11-01",
            "txn": "3619ac526be86a88d9a36f0463e8d242c3db08c53727f47f98d8b3cbe6deee85",
            "created": "2021-12-31T02:39:01.076Z"
        },
        {
            "key": "423f73cfffff",
            "stake_key": "14779a4e018bd308",
            "principal": 100.05480578,
            "interest": 0.01370614,
            "interest_date": "2021-11-02",
            "txn": "110dad3b829c88e0f4e0cb36c215b3ddb25b413b1384ced4212c64641318de04",
            "created": "2021-12-31T02:39:01.087Z"
        },
        {
            "key": "a64d4e2df3d5",
            "stake_key": "14779a4e018bd308",
            "principal": 100.06851192,
            "interest": 0.01370802,
            "interest_date": "2021-11-03",
            "txn": "9410f23ebb66234478d0d39a838858bd62ad683a38a467ce74fc5e25ad0fb4b1",
            "created": "2021-12-31T02:39:01.098Z"
        },
        {
            "key": "9538f175126a",
            "stake_key": "14779a4e018bd308",
            "principal": 100.08221994,
            "interest": 0.01370989,
            "interest_date": "2021-11-04",
            "txn": "55ac9401a706c433b644d8e5d7930b18505e05c8d210790931701cb858acc7c8",
            "created": "2021-12-31T02:39:01.108Z"
        },
        {
            "key": "f9582d57ac69",
            "stake_key": "14779a4e018bd308",
            "principal": 100.09592983,
            "interest": 0.01371177,
            "interest_date": "2021-11-05",
            "txn": "53688a442c361d1cd88b5ee812e3437b3faf9b54f22c8e702468f9d1cf3a74d1",
            "created": "2021-12-31T02:39:01.118Z"
        },
        {
            "key": "d8230a7d9908",
            "stake_key": "14779a4e018bd308",
            "principal": 100.1096416,
            "interest": 0.01371365,
            "interest_date": "2021-11-06",
            "txn": "8566f246e366db5a9d07580160d9f5b66c73d1b519e07f5ae8de74220983617e",
            "created": "2021-12-31T02:39:01.128Z"
        },
        {
            "key": "835c90d0670d",
            "stake_key": "14779a4e018bd308",
            "principal": 100.12335525,
            "interest": 0.01371553,
            "interest_date": "2021-11-07",
            "txn": "029069f404815e4c98b48f20d501b71cb9f441e908659725f8939ce8770090d6",
            "created": "2021-12-31T02:39:01.138Z"
        },
        {
            "key": "1109e9847c33",
            "stake_key": "14779a4e018bd308",
            "principal": 100.13707078,
            "interest": 0.01371741,
            "interest_date": "2021-11-08",
            "txn": "fa783efd0bfe68197452d2749f7f1239d74aab61db1765277f1a86cf2deeb819",
            "created": "2021-12-31T02:39:01.146Z"
        },
        {
            "key": "9f8927df9c0b",
            "stake_key": "14779a4e018bd308",
            "principal": 100.15078819,
            "interest": 0.01371929,
            "interest_date": "2021-11-09",
            "txn": "090a4a52178242efbf6824dad9e956dc4c5fe2eb2e7d6807eb1b57aed6618047",
            "created": "2021-12-31T02:39:01.156Z"
        },
        {
            "key": "a2c1acb7e78d",
            "stake_key": "14779a4e018bd308",
            "principal": 100.16450748,
            "interest": 0.01372117,
            "interest_date": "2021-11-10",
            "txn": "bb01b467cf3e8b7d35c51a59498206f2134111e51971b11b39be4b601b5a9f7c",
            "created": "2021-12-31T02:39:01.168Z"
        },
        {
            "key": "db81bd8a1e42",
            "stake_key": "14779a4e018bd308",
            "principal": 100.17822865,
            "interest": 0.01372305,
            "interest_date": "2021-11-11",
            "txn": "d6775a51da52509eb890bb51dcd9d371e3f67596d597ac0b075c606ebe3abba7",
            "created": "2021-12-31T02:39:01.177Z"
        },
        {
            "key": "55d82ffe6f85",
            "stake_key": "14779a4e018bd308",
            "principal": 100.1919517,
            "interest": 0.01372492,
            "interest_date": "2021-11-12",
            "txn": "bcc030954531c4f56840495f041f27e4e815fa33f8d16007af2af6de379a9627",
            "created": "2021-12-31T02:39:01.186Z"
        },
        {
            "key": "23d519a73ca5",
            "stake_key": "14779a4e018bd308",
            "principal": 100.20567662,
            "interest": 0.01372681,
            "interest_date": "2021-11-13",
            "txn": "dad4ea979ba03d9d832281dd1a69e7190c74e673eafd2966f973ff7cbe64c5db",
            "created": "2021-12-31T02:39:01.195Z"
        },
        {
            "key": "46d186921f26",
            "stake_key": "14779a4e018bd308",
            "principal": 100.21940343,
            "interest": 0.01372869,
            "interest_date": "2021-11-14",
            "txn": "f9fbb7ed1fdb378cf05e0d581426af80f09705774433c99927f92c83518b2c48",
            "created": "2021-12-31T02:39:01.204Z"
        },
        {
            "key": "3884d5b299e7",
            "stake_key": "14779a4e018bd308",
            "principal": 100.23313212,
            "interest": 0.01373057,
            "interest_date": "2021-11-15",
            "txn": "e34f88c8d589dba984d8c09b2c3b25cf8634f38ea3ffde58d16e69496ca8d107",
            "created": "2021-12-31T02:39:01.212Z"
        },
        {
            "key": "bf40cd11bf25",
            "stake_key": "14779a4e018bd308",
            "principal": 100.24686269,
            "interest": 0.01373245,
            "interest_date": "2021-11-16",
            "txn": "290fd38d43808fd997fa15902f0dcc76439c7f50be9e8a40ed78e3c052994a47",
            "created": "2021-12-31T02:39:01.222Z"
        },
        {
            "key": "8232d9f8af41",
            "stake_key": "14779a4e018bd308",
            "principal": 100.26059514,
            "interest": 0.01373433,
            "interest_date": "2021-11-17",
            "txn": "fd3d24cfcc623e2646a09ef7a1a9ad2b51f1f395838682b8b1792356317680a7",
            "created": "2021-12-31T02:39:01.230Z"
        },
        {
            "key": "6379e19ca757",
            "stake_key": "14779a4e018bd308",
            "principal": 100.27432947,
            "interest": 0.01373621,
            "interest_date": "2021-11-18",
            "txn": "954d854d8e832085b07b1ad1044451786ef2ba1dad9ab9af44f43e0f90688df6",
            "created": "2021-12-31T02:39:01.243Z"
        },
        {
            "key": "9cc8113cf702",
            "stake_key": "14779a4e018bd308",
            "principal": 100.28806568,
            "interest": 0.01373809,
            "interest_date": "2021-11-19",
            "txn": "84d802933b9aaab3c3c88d1b0ede80ec1f77ecdf84b75e93056900de22e066e6",
            "created": "2021-12-31T02:39:01.254Z"
        },
        {
            "key": "23f1c1b5828f",
            "stake_key": "14779a4e018bd308",
            "principal": 100.30180377,
            "interest": 0.01373997,
            "interest_date": "2021-11-20",
            "txn": "902174ccbebd3eb57aa88f577c76858d03cd64e01e10a4d1b6eb8d434465b1ed",
            "created": "2021-12-31T02:39:01.261Z"
        },
        {
            "key": "5dfda0528d67",
            "stake_key": "14779a4e018bd308",
            "principal": 100.31554374,
            "interest": 0.01374186,
            "interest_date": "2021-11-21",
            "txn": "c64cf3940e56a3998843dccf2e549d644d341c9cb307852d56c9366545fcf840",
            "created": "2021-12-31T02:39:01.270Z"
        },
        {
            "key": "3ed6e2af58ac",
            "stake_key": "14779a4e018bd308",
            "principal": 100.3292856,
            "interest": 0.01374374,
            "interest_date": "2021-11-22",
            "txn": "5f566d9a4f351f571a2ecf01f0b3cf315019bdf33bbd830c284c7d15f52630f3",
            "created": "2021-12-31T02:39:01.279Z"
        },
        {
            "key": "69337a497b21",
            "stake_key": "14779a4e018bd308",
            "principal": 100.34302934,
            "interest": 0.01374562,
            "interest_date": "2021-11-23",
            "txn": "481850ec5338902fee10654cd6718fa0151c2c6ed57d391a473683b25746019d",
            "created": "2021-12-31T02:39:01.286Z"
        },
        {
            "key": "c24c00a6e297",
            "stake_key": "14779a4e018bd308",
            "principal": 100.35677496,
            "interest": 0.0137475,
            "interest_date": "2021-11-24",
            "txn": "0bd1d21d100a49b5b8e209a7fb9171544debdff0343eb65dfdc04b0bfd21a4f4",
            "created": "2021-12-31T02:39:01.294Z"
        },
        {
            "key": "c1b077db5939",
            "stake_key": "14779a4e018bd308",
            "principal": 100.37052246,
            "interest": 0.01374939,
            "interest_date": "2021-11-25",
            "txn": "be5d4b3bf522e1b0e5585f7fe9feccd02879d0d15c7c86fb51cf81d511536a9d",
            "created": "2021-12-31T02:39:01.304Z"
        },
        {
            "key": "a892dcf1ce3f",
            "stake_key": "14779a4e018bd308",
            "principal": 100.38427185,
            "interest": 0.01375127,
            "interest_date": "2021-11-26",
            "txn": "363a056ad4ec9087a0c67e3291ce2bc1727c3fd38bc2304dcb0285440ba7620a",
            "created": "2021-12-31T02:39:01.311Z"
        },
        {
            "key": "bc922ac376cd",
            "stake_key": "14779a4e018bd308",
            "principal": 100.39802312,
            "interest": 0.01375315,
            "interest_date": "2021-11-27",
            "txn": "43d4bf22fb5c3f31078142c786081f136f34f57389a450ab1258d5bebacff38f",
            "created": "2021-12-31T02:39:01.318Z"
        },
        {
            "key": "611b3a1aca97",
            "stake_key": "14779a4e018bd308",
            "principal": 100.41177627,
            "interest": 0.01375504,
            "interest_date": "2021-11-28",
            "txn": "2e805c2ea651c602cd4900608924d3ae5428246e3a03d5f92b0e566fc67079be",
            "created": "2021-12-31T02:39:01.326Z"
        },
        {
            "key": "7f531067a5df",
            "stake_key": "14779a4e018bd308",
            "principal": 100.42553131,
            "interest": 0.01375692,
            "interest_date": "2021-11-29",
            "txn": "7b676ca29dd2539390f7ee6487a0d6b3a9db4d60b1a9f8648e25e858cb89d5ad",
            "created": "2021-12-31T02:39:01.332Z"
        },
        {
            "key": "ddd0525f9218",
            "stake_key": "14779a4e018bd308",
            "principal": 100.43928823,
            "interest": 0.01375881,
            "interest_date": "2021-11-30",
            "txn": "cbef04f3065f34f97e7ea0f3be5dd7344ce51eb7631c08ae229c9919a7f786e5",
            "created": "2021-12-31T02:39:01.339Z"
        },
        {
            "key": "85aa456e980e",
            "stake_key": "14779a4e018bd308",
            "principal": 100.45304704,
            "interest": 0.01376069,
            "interest_date": "2021-12-01",
            "txn": "cfd63d1c0f2f107be85f849ec399cd051ff75ba9fa2fb1c825b4eebc51a163c3",
            "created": "2021-12-31T02:39:01.347Z"
        },
        {
            "key": "e6245fdbfa94",
            "stake_key": "14779a4e018bd308",
            "principal": 100.46680773,
            "interest": 0.01376258,
            "interest_date": "2021-12-02",
            "txn": "e5de4485247b90c51fafb89479176a1a47b4791e2967ca5ec1e07bceed7418b1",
            "created": "2021-12-31T02:39:01.353Z"
        },
        {
            "key": "4427b7771ead",
            "stake_key": "14779a4e018bd308",
            "principal": 100.48057031,
            "interest": 0.01376446,
            "interest_date": "2021-12-03",
            "txn": "b2c9c871504d972eac44ac403093358fa3aeee42da261d4d0ccf1089bede9278",
            "created": "2021-12-31T02:39:01.360Z"
        },
        {
            "key": "0100eaa3f17c",
            "stake_key": "14779a4e018bd308",
            "principal": 100.49433477,
            "interest": 0.01376635,
            "interest_date": "2021-12-04",
            "txn": "5c16fa73003924b58071f79e2e1cff4ca735c7cffce56664ce2cbef780c905e2",
            "created": "2021-12-31T02:39:01.367Z"
        },
        {
            "key": "d66bddf8853e",
            "stake_key": "14779a4e018bd308",
            "principal": 100.50810112,
            "interest": 0.01376823,
            "interest_date": "2021-12-05",
            "txn": "7883242ffcfdd0a93ce945c3babebcf2096cfc1df697883a685caaf0b1e20aae",
            "created": "2021-12-31T02:39:01.373Z"
        },
        {
            "key": "a90ea92d6630",
            "stake_key": "14779a4e018bd308",
            "principal": 100.52186935,
            "interest": 0.01377012,
            "interest_date": "2021-12-06",
            "txn": "7559f048ca116e33e41c0f6e7cac198cfce0f7451c2cb58c5719819f4f86bf5f",
            "created": "2021-12-31T02:39:01.380Z"
        },
        {
            "key": "c22e103e9236",
            "stake_key": "14779a4e018bd308",
            "principal": 100.53563947,
            "interest": 0.01377201,
            "interest_date": "2021-12-07",
            "txn": "d0030ffb342f432ed85a6374c83a2be5eb8f972f4aa9f20df49e3e0d60bcf913",
            "created": "2021-12-31T02:39:01.386Z"
        },
        {
            "key": "1f9b4ec96450",
            "stake_key": "14779a4e018bd308",
            "principal": 100.54941148,
            "interest": 0.01377389,
            "interest_date": "2021-12-08",
            "txn": "ac9d462f7a0715bf2dfe8fdfc7659316bf5fc483fbf619256b9cda59230db3f9",
            "created": "2021-12-31T02:39:01.393Z"
        },
        {
            "key": "e8aaaf4a56d4",
            "stake_key": "14779a4e018bd308",
            "principal": 100.56318537,
            "interest": 0.01377578,
            "interest_date": "2021-12-09",
            "txn": "8fd9c334cd9cc925d27bcfbc017d36727062e63d50d119477de6dd2711cd47da",
            "created": "2021-12-31T02:39:01.400Z"
        },
        {
            "key": "5ecded269cd9",
            "stake_key": "14779a4e018bd308",
            "principal": 100.57696115,
            "interest": 0.01377767,
            "interest_date": "2021-12-10",
            "txn": "c162647940026717260da392183de3d59b5abb5c22d5c4ae11cc1483b63e063b",
            "created": "2021-12-31T02:39:01.406Z"
        },
        {
            "key": "defcdd1a26b2",
            "stake_key": "14779a4e018bd308",
            "principal": 100.59073882,
            "interest": 0.01377955,
            "interest_date": "2021-12-11",
            "txn": "2090647b6bd8b1486daa177edf279a84475b9add6205f873eda43f23d30f2e61",
            "created": "2021-12-31T02:39:01.411Z"
        },
        {
            "key": "42bd24af46f1",
            "stake_key": "14779a4e018bd308",
            "principal": 100.60451837,
            "interest": 0.01378144,
            "interest_date": "2021-12-12",
            "txn": "9b89b878c93d68687ae50ce9655c107fcaba7cfffd323be415e449035c0973b8",
            "created": "2021-12-31T02:39:01.417Z"
        },
        {
            "key": "c906028c2c12",
            "stake_key": "14779a4e018bd308",
            "principal": 100.61829981,
            "interest": 0.01378333,
            "interest_date": "2021-12-13",
            "txn": "119e579008ec2783d07c8541f5a1e40a5f3250e9acce89633a6e500831b43a1b",
            "created": "2021-12-31T02:39:01.424Z"
        },
        {
            "key": "6fba869763a5",
            "stake_key": "14779a4e018bd308",
            "principal": 100.63208314,
            "interest": 0.01378522,
            "interest_date": "2021-12-14",
            "txn": "03fafe9bc3fe93a2b96b6dbea660e16062a9cc3006d804ea5f60ed3061bf77c2",
            "created": "2021-12-31T02:39:01.429Z"
        },
        {
            "key": "db1973eacace",
            "stake_key": "14779a4e018bd308",
            "principal": 100.64586836,
            "interest": 0.01378711,
            "interest_date": "2021-12-15",
            "txn": "e7a44661bd16dcc15115046b88b0ec401a94e5e5bf599232d6fdfae024e04eb7",
            "created": "2021-12-31T02:39:01.437Z"
        },
        {
            "key": "e9a5e20fb064",
            "stake_key": "14779a4e018bd308",
            "principal": 100.65965547,
            "interest": 0.01378899,
            "interest_date": "2021-12-16",
            "txn": "a169a18ad68c6f9a5a585a4c994d6271c380e7a3ba80947b83a574693a71b55c",
            "created": "2021-12-31T02:39:01.443Z"
        },
        {
            "key": "f10fe1b6db44",
            "stake_key": "14779a4e018bd308",
            "principal": 100.67344446,
            "interest": 0.01379088,
            "interest_date": "2021-12-17",
            "txn": "75d95e7851f0a9f8c515e42ea8501ad5daaaac69fd1eea2a4047b87a442ff15d",
            "created": "2021-12-31T02:39:01.449Z"
        },
        {
            "key": "ef8311a69e37",
            "stake_key": "14779a4e018bd308",
            "principal": 100.68723534,
            "interest": 0.01379277,
            "interest_date": "2021-12-18",
            "txn": "cd0858ca67e904df18b7f7ce1b4906ece2e002edd0334616dff19a326e2197ef",
            "created": "2021-12-31T02:39:01.455Z"
        },
        {
            "key": "e3e05870b236",
            "stake_key": "14779a4e018bd308",
            "principal": 100.70102811,
            "interest": 0.01379466,
            "interest_date": "2021-12-19",
            "txn": "f39c430d196e2da24c8dbcc2cef64e88a724fb7750153463e967cf606f40911d",
            "created": "2021-12-31T02:39:01.461Z"
        },
        {
            "key": "1af9f432a922",
            "stake_key": "14779a4e018bd308",
            "principal": 100.71482277,
            "interest": 0.01379655,
            "interest_date": "2021-12-20",
            "txn": "c7fffcffc9ad318bf805086a3a6ba08a36c84e89b4b27e5b631c0ea5af79c617",
            "created": "2021-12-31T02:39:01.469Z"
        },
        {
            "key": "e3e2b3e1b49a",
            "stake_key": "14779a4e018bd308",
            "principal": 100.72861932,
            "interest": 0.01379844,
            "interest_date": "2021-12-21",
            "txn": "7eafee9d4f8bff40f574666f73fbf020fc24056c2b885c099bb24e87b65e5d45",
            "created": "2021-12-31T02:39:01.475Z"
        },
        {
            "key": "4ebe6f930e8a",
            "stake_key": "14779a4e018bd308",
            "principal": 100.74241776,
            "interest": 0.01380033,
            "interest_date": "2021-12-22",
            "txn": "c3355b4f8302754763c145471708ae3d06586b50dd5902d7536407eca4e06029",
            "created": "2021-12-31T02:39:01.481Z"
        },
        {
            "key": "0d1b1399cd52",
            "stake_key": "14779a4e018bd308",
            "principal": 100.75621809,
            "interest": 0.01380222,
            "interest_date": "2021-12-23",
            "txn": "fccd7185779edee776dbe7f1755175b0221e1bc7c100967512629e1f28c83ffc",
            "created": "2021-12-31T02:39:01.488Z"
        },
        {
            "key": "f6255c09d406",
            "stake_key": "14779a4e018bd308",
            "principal": 100.77002031,
            "interest": 0.01380411,
            "interest_date": "2021-12-24",
            "txn": "8cd3fa9ad5397deeed40d555140abb3177bc11079017cc6511a0256e01ed2d55",
            "created": "2021-12-31T02:39:01.494Z"
        },
        {
            "key": "8cdbb458c19e",
            "stake_key": "14779a4e018bd308",
            "principal": 100.78382442,
            "interest": 0.013806,
            "interest_date": "2021-12-25",
            "txn": "7643e2a7e9ccbd403dc6b5bb5802c890723d7b7ac332d30ddf644467f2d6de13",
            "created": "2021-12-31T02:39:01.503Z"
        },
        {
            "key": "ba1f04fe416e",
            "stake_key": "14779a4e018bd308",
            "principal": 100.79763042,
            "interest": 0.01380789,
            "interest_date": "2021-12-26",
            "txn": "d97909f1490806bb0dc202fd567efe797874950111e5de8c1d2513c559c34031",
            "created": "2021-12-31T02:39:01.517Z"
        },
        {
            "key": "ada90f7bec8f",
            "stake_key": "14779a4e018bd308",
            "principal": 100.81143831,
            "interest": 0.01380979,
            "interest_date": "2021-12-27",
            "txn": "5f2aba20ff2c9823e4ec294e5cdd24e259c0b835ced8b8ad3e96a0d2bd93f251",
            "created": "2021-12-31T02:39:01.525Z"
        }
    ]
}`

**Comment by curateproject** [comment]
Just waiting for 1. above to get done before I close the issue - any update yet @madtocc @pellarboss ?
