### ISSUE TITLE
ALGO Token Integration

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#375]
~1. Add ALGO import/export NFT feature~
~2. Add ALGO mint NFT feature~
3. Add ALGO token integration

**Comment by eventang2015** [comment]
envkeys:
1. add ALGO into PERMITTED_TRADE_COMMIT_TYPES
2. `    algo: {
        enabled: true,
        main_net: process.env.ALGO_MAIN_NET === 'true' || false,
        decimal: 6,
        api_key: process.env.ALGO_API_KEY || 'ZfA7EYxJs92f7x5TSrIAK9gowyGMf2yq50eu1z4m',
        api_endpoint: process.env.ALGO_API_ENDPOINT || 'https://testnet-algorand.api.purestake.io/ps2',
        indexer_endpoint: process.env.ALGO_INDEXER_ENDPOINT || 'https://testnet-algorand.api.purestake.io/idx2',
    },`

**Comment by madtocc** [comment]
currently available 
- Wallet
- Deposit, Withdraw
- buy XCUR
