### ISSUE TITLE
Desktop UX enhancement

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#378]
Update the desktop UX with the figma link below

**Comment by pellarboss** [comment]
require designs, see post on Slack
> could we get a figma on how the new UX looks like on the web page? can we ensure to:
> - get a look on how it looks like when things are stretched (horizontally)
> - do not introduce any new functionality or drastic UI changes please

please help us with obtaining figma

**Comment by curateproject** [comment]
Sure, will get Alex to design a figma file for desktop

**Comment by TheOneXi** [comment]
Still waiting from Alex (our designer) send us the figma link - will update you soon

**Comment by pellarboss** [comment]
@curateproject any updates on this?

**Comment by TheOneXi** [comment]
Yes @TheMad-J-Hatter will be providing a figma link in the new 1-2 days

**Comment by pellarboss** [comment]
duplicate with #387
