### ISSUE TITLE
Stake more than once?

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#379]
Would it be possible for existing stakers to deposit more XCUR into the app to stake (as a new separate stake) and shown on the staking page log?

The cut off for staking will be 31st January but if you can make this configurable in the admin panel (i.e set the date for no more users to start new staking sessions) = 31st March is when all staking should have ended

**Comment by pellarboss** [comment]
yes, you can create more than one stake 
you can not modify stake / since that record is permanent
but your boost can only be used once (as per requirements)

**Comment by eventang2015** [comment]
can disable stake on https://admin.curate.style/settings
