### ISSUE TITLE
NFT share button not working

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#380]
Share NFT button not working on iOS, please can you fix

**Comment by madtocc** [comment]
I'm able to share and open in both Android and iOS.
Please provide a video of the problem and the app version if you have this issue.

**Comment by curateproject** [comment]
When I open up a link it takes me the web app asking me to login

The web app is not really an issue except as we don't have guest view I'm stuck at the login page

It would be great if this is resolved with guest view or the link auto opens up the mobile app
