### ISSUE TITLE
12 Days of Xmas winners

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#383]
Please transfer the NFTs to these accounts:

Day six
prici.bambero@hotmail.fr
User name @Prici
https://admin.curate.style/product/0e461e4019a6c8b57462a0a7/edit
Day Seven
nisab1104200@gmail.com
@Nisabmoideen
https://admin.curate.style/product/5200802f49522bad5936961d/edit
Day eight
george.aldous@hotmail.com
Username : MaximumBean
https://admin.curate.style/product/ddd2e29dcad48893f3d04fb1/edit
Day Nine
https://admin.curate.style/product/be22196231250edeecb2aaa9/edit
thatwhichisnot33@protonmail.com
Day 10
https://admin.curate.style/product/28e6170390a6b7a9d879b9b0/edit
bitcoinmush@gmail.com
Day 11
https://admin.curate.style/product/dd649d3d1cabb4c68c4e8aa2/edit
ellisfolkes97@gmail.com
Day 12
https://admin.curate.style/product/6f7bde05fdc8fb9ab92984b2/edit

**Comment by eventang2015** [comment]
update all these produts ? is ok to update owner ?

**Comment by curateproject** [comment]
Yes update the owner for all these please, owners are different for each nft

**Comment by eventang2015** [comment]
6 users and 7 products ? missing one ?
