### ISSUE TITLE
Can you cancel this users staked tokens

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#384]
user: leeju09@naver.com

Can you cancel this users staked tokens (11.3k XCUR is currently staked) and move it back into his wallet as unstaked i.e like normal.

As he wants to stake again with more tokens which he just deposited.

Thanks!

**Comment by eventang2015** [comment]
I see he has 2 stakes
1st one:
` "amount" : 11289",
    "period" : 60,
    "boost" : 3,
    "apy" : 10,`
  2nd one:
  `"amount" : 50,
    "period" : 60,
    "boost" : 1,
    "apy" : 5,`

**Comment by eventang2015** [comment]
canceled his stakes
