### ISSUE TITLE
Update Desktop UX

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#387]
Alex (our designer is preparing a figma file to follow)

1. When showing the NFTs on desktop, can you add trailing lazy load so it only loads a small number of NFTs on each page i.e as the user scrolls down it loads the next set of NFTs

**Comment by TheMad-J-Hatter** [comment]
Hey @pellarboss and @madtocc, 

Please see the Figma link with the desktop UI designs. There are still a few comments that Alex is yet to complete but we are keen for you to begin and digest what we have so far. Any questions, please let me know. 

https://www.figma.com/file/5UZeEkCdlxEIRzpMsJXVvw/Curate-Website?node-id=352%3A31122

**Comment by madtocc** [comment]
How the UI will look (behave) in a narrower view, like on a phone, or when the user shrinks the window's width?

**Comment by TheMad-J-Hatter** [comment]
Hey @madtocc, good question. Alex is designing the same UI but for tablet as well however I'm unsure on how this will look when shrunk on a phone. I will have to ask Alex regarding this.

**Comment by TheMad-J-Hatter** [comment]
Hey @madtocc, Alexey is designing the phone and tablet versions for the desktop which should provide you with the answer of how the UI will look/behave if in a narrower view. I am pushing him to provide me with these designs by Friday or sooner. They should start appearing in the Figma link I provided in the comment above. 

Are you still able to progress with the dev work without these for now?

**Comment by TheMad-J-Hatter** [comment]
Hey @madtocc, Alexey has now finished the NFT Desktop designs which also include the tablet and mobile versions of the desktop. The figma link above has everything you need. 

How the development work is progressing please?

**Comment by pellarboss** [comment]
@TheMad-J-Hatter desktop is progressing, please review here
http://curate-web-stage.s3-website-ap-southeast-1.amazonaws.com/

this is essentially a complete rebuild, and will take a bit more time, i estimated 6-8 weeks initially, well underway
