### ISSUE TITLE
Decentralised Mint Page 

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#388]
Create a decentralised mint page allowing anyone to mint NFTs (1 of 1s or collections) across various chains (starting with ERC721s, 115s and SOL NFts on 1st launch) with a 75% reduction in gas fees to mint and allow users to pay using ETH or SOL i.e pay with ETH if minting on ETH and SOL if minting on SOL

The 25% will go to curates cold storage wallet, % to be written in the contract protocol

**Comment by pellarboss** [comment]
is this related to the Curate platform?
or is this a generic thing? (as per decentralised)

the solution we can build:
- ETH 721/1155
- 1:1 or batch
- batch minted every day (so heaps of gas saved)
- charge in eth (so sales proceed will go in to a curate wallet)

**Comment by DefiHunter** [comment]
This would be decentralised , Roy we could use 721b
