### ISSUE TITLE
Show different chain NFTs on the marketplace

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#389]
Add chain in Search filter with options ETH, Sol and Algo and All

All is default view of marketplace displaying all chain NFTs but add something to differentiate other chain NFTs to each other (i.e different colour text if NFT name of icon of chain on the thumbnail etc).

Whatever looks good in your view

**Comment by eventang2015** [comment]
@madtocc  append new param: `?chain=solana|algorand|ethereum` to the query params.

`
nft: {
        chain: {
            eth: 'ethereum',
            sol: 'solana',
            algo: 'algorand'
        }
    }`

**Comment by TheOneXi** [comment]
Got a screenshot of how this will look? @madtocc

**Comment by madtocc** [comment]
about the filter?
we can include this same icon in the nft card (if you want)
![image](https://user-images.githubusercontent.com/12486417/150592972-4d93b18f-71ac-4ccc-aa59-6aa7481223d1.png)

**Comment by TheOneXi** [comment]
Nice this looks but I also meant the marketplace, how it will look etc when scrolling through the marketplace with different chain NFTs

**Comment by madtocc** [comment]
we can show the icon (+label?) on the card? like on the image, next to likes or below likes?

**Comment by TheOneXi** [comment]
Yes I like that idea @madtocc 

Can you show me how it'll look in staging once ready?
