### ISSUE TITLE
NFT export to curate wallet issue

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#390]
App user: Bang95838@gmail.com
NFT name: Curate premium t shirt 9 of 10
App version: 5.0.1
Device: iOS iPhone 11
Receivers curate wallet address: 0x4dD5fA63a013875B6686646931c0829Ff2Ce4DDC

The user tried to transfer a curate NFT to another curate user (curate wallet address) but it didn’t arrive. 

Can you please help him complete the transfer if it's possible or send it back to him?

 Transaction hash #

0xb8439e798b3bd27c0440044278dfd0385f9857517bd19fe8f2bd58bd3ae5b818

**Comment by pellarboss** [comment]
thats not how transfers work...

we will try to recover the token if possible

**Comment by pellarboss** [comment]
token recovered
1 - sent user some ETH
2 - transferred the Token to master
3 - sent remaining eth back to master
4 - adjusted record in xcur

**Comment by curateproject** [comment]
Hi @pellarboss the sender is saying the NFT is not back in his account?

**Comment by eventang2015** [comment]
it's imported by another user ?https://admin.curate.style/product/c7a92d33f5933311e05b6ed6/detail

**Comment by eventang2015** [comment]
import log:
`"userkey" : "9800f3f816812d8274d54f924a14fa8b379b",
    "contract_address" : "0x0c4bae424deaa9be96bb0998524bc91e1903d794",
    "token_id" : "1632690433",
    "type" : "ERC721",
    "chain" : "ethereum",
    "state" : "imported",`

**Comment by eventang2015** [comment]
NFT name : Premium T-shirt NFT - 9 of 10 
owned by another user :  https://admin.curate.style/product/9114786243add489dec6f8fb/detail

**Comment by pellarboss** [comment]
The user does not own the NFT
