### ISSUE TITLE
Import SOL NFT Bug

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#391]
A user is trying to import a SOL NFT into curate however they are pasting their phantom wallet address

I told them, they need to paste their NFT contract address - where can they find this i.e where on solbeach: https://solanabeach.io/address/6nssrF4sbeD2y8cw7S3u6C4En8net5jJK9yx8vCMEcN8

![Screenshot 2022-01-13 at 12 29 34](https://user-images.githubusercontent.com/51517619/149331051-c2d37cc1-cd83-43e9-9141-95f70e0cdfe1.png)

**Comment by TheOneXi** [comment]
The same user updated on iOS to v5.2.1 but is still getting the same error when entering his token address for the SOL NFT:

![Solana ](https://user-images.githubusercontent.com/51517619/150318007-833aed8f-5509-4d51-8df5-1c26ba387057.jpg)

![ktIT1BF1](https://user-images.githubusercontent.com/51517619/150318165-abed654b-752b-4db4-b097-579c359024e8.jpg)

@pellarboss @madtocc

**Comment by madtocc** [comment]
Are you sure it is updated?
Copied the address and it does not show invalid address to me. Could you ask him to send a video showing the app version and trying to import?
https://user-images.githubusercontent.com/12486417/150337102-2b303be6-1633-4ede-a09b-561661e6ed71.MOV

**Comment by TheOneXi** [comment]
Yes sure I think it's him I'll check

**Comment by TheOneXi** [comment]
The above user is now v5.2.1

They've successful sent the sol NFT 

This is the tx hash:

3z7D5vLshHn93iNQBFwWhKiu8GKy9v9aSRWZATTEcqpu

**But they do not see the imported solana NFT in their profile even though it's in the curate custody wallet.**

Can someone help and fix this and also prevent this happening again?

@pellarboss

**Comment by pellarboss** [comment]
the user MUST send the NFT to the Curate Custody wallet (SOL Master)
the user has not done this yet... (he still has the NFT)

**Comment by eventang2015** [comment]
@curateproject seems this token https://solscan.io/token/6nssrF4sbeD2y8cw7S3u6C4En8net5jJK9yx8vCMEcN8 didn't send to master SOL address https://solscan.io/account/3z7D5vLshHn93iNQBFwWhKiu8GKy9v9aSRWZATTEcqpu
please let him send the token to **3z7D5vLshHn93iNQBFwWhKiu8GKy9v9aSRWZATTEcqpu** and then create an import log, input 
the token address **6nssrF4sbeD2y8cw7S3u6C4En8net5jJK9yx8vCMEcN8** as the contract address in App.

**Comment by TheOneXi** [comment]
The user has said it's gone from his phantom wallet and should be in his curate wallet ending in 3z

![20220125_123824.jpg](https://user-images.githubusercontent.com/51517619/150978756-c358d40c-2417-44e9-96c3-4b2c507f7c23.jpg)

@eventang2015 @pellarboss

**Comment by eventang2015** [comment]
@curateproject is this token https://solscan.io/token/6sBLQx2XRV77CHJoZqXUP4jdYPVp6n6N8acziWqrJHci ?
could he add an import log ? input 6sBLQx2XRV77CHJoZqXUP4jdYPVp6n6N8acziWqrJHci as the contract address in App.

**Comment by TheOneXi** [comment]
![Screenshot 2022-01-25 at 15 36 19](https://user-images.githubusercontent.com/51517619/151008103-074d26a9-5d07-410e-a393-8b4a52be3c78.png)


Here's what the user said @eventang2015 

Can you advice please?

**Comment by eventang2015** [comment]
yes, I see  a pending import log now.
but I wonder if our server ip is blocked by solana rpc
`"message":"Too many requests from your IP, contact your app developer or support@rpcpool.com."`

**Comment by TheOneXi** [comment]
What shall I tell the user for now @eventang2015 @pellarboss ?

**Comment by pellarboss** [comment]
that Solana is experiencing issues, and there is nothing we can do, we've escalated to Solana, and they haven't given us a response.

@curateproject generally, across the board, Solana is struggling to keep up with Curate's requests, user base & keeping on erroring out

**Comment by TheOneXi** [comment]
Hi @pellarboss were you able to find a solution for the SOL RPC issue?

Let me know so I can update this user

**Comment by TheOneXi** [comment]
Hi @pellarboss has this been fixed?

The user still can't see his important sol nft

**Comment by eventang2015** [comment]
@curateproject https://admin.curate.style/product/25516dfd76085d92c1c0d2b6/detail 
imported

**Comment by TheOneXi** [comment]
Hi @eventang2015 the user still can't see his imported SOL NFT, here is the video he sent me:

https://user-images.githubusercontent.com/51517619/152812176-6dc67744-0148-41b2-862a-846a87e384c8.MP4

**Comment by eventang2015** [comment]
@curateproject it's imported but denied by an administer. I've re-approved it now.

**Comment by TheOneXi** [comment]
Thanks the user now see's it

Can you remove it from the collection though? Not sure how it got added in that

Also can we add some UX so we can display to users that this is a SOL NFT? @eventang2015 @madtocc i.e display sol icon for this nft on the NFT page and marketplace page


![20220210_150002.jpg](https://user-images.githubusercontent.com/51517619/153434796-8bb6acf6-b99b-4f34-8f41-6e6b4140efab.jpg)

**Comment by eventang2015** [comment]
imported NFTs are in Curate collection (auto created). the acture owner is Master Wallet.

**Comment by TheOneXi** [comment]
@pellarboss can we remove this auto collection creation when importing an NFT?

As in this case, this SOL NFT isn't part of a collection and is just a 1 of 1

Also the NFT gets displayed with 10 XCUR as price and the importer can’t lower it i.e to 5 XCUR for example - can you remove this limitation?

**Comment by eventang2015** [comment]
@curateproject removed collection for this item.
 you can update **Mint Min Amount** on admin setting page.
 remove  auto collection creation for both SOL and ERC721 ?

**Comment by pellarboss** [comment]
I think leave ERC721 as is

When SOL is imported, remove auto Collection creation

**Comment by eventang2015** [comment]
done.
