### ISSUE TITLE
Set up SPF on our Emails to prevent getting picked up as spam

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#394]
Can you add the SPF record value from Google and update the record in Cloudflare so that emails sent from curate.style are not picked up as spam/phishing emails.

Here's a guide to get the SPF record value from google:

https://support.google.com/a/answer/33786

Let me know if you need access to google workspaces first.

**Comment by doles2** [comment]
The updated SPF record now includes the Google workspaces content

`v=spf1 +ip4:67.225.160.82 include:mailgun.org include:_spf.google.com ~all`
