### ISSUE TITLE
Add 'Collections' and 'Recent' tab to marketplace menu

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#395]
Collections tab:
Display the featured collections first at the top followed by all other collections sorted A to Z (perhaps seperate the featured collections somehow on the list)

Recent tab:
Display the recently listed NFTs for sale (not pending or rejected NFTs) from most recent at the top

**Comment by TheOneXi** [comment]
Also when selecting the collection tab from the search menu can you auto show the featured collection list before entering any text in the search field i.e autopopulates the blank area like the screenshot below 

![Screenshot_20220119-192025_Google Play Store.jpg](https://user-images.githubusercontent.com/51517619/150199883-6dd024bd-d9f3-4c96-a8e8-42b2a898cc68.jpg)

If the search results return no results, can you display a message 'No results for that search' for all tabs and then show a list of NFTs/collection and P2P items from the all section (just so we show something) with a header 'Unrelated results shown below'

**Comment by TheOneXi** [comment]
Hi @madtocc can you show a screenshot of how this is looking? Would like the 'collection' tab next to 'featured' and 'recent' tab before last sales tab
