### ISSUE TITLE
UX Tweaks for the app

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#399]
1. Can you make the 2 blocks solid and not transparent for the Deposit USDC and Buy XCUR button
3. Add option on wallet page to switch token display from list to board/grid view (see image attached) - default view should be grid

![Grid view](https://user-images.githubusercontent.com/51517619/149768561-8f33abe9-427a-4d94-b034-a6ec9b3490b2.jpeg)

**Comment by TheOneXi** [comment]
![20220202_120218.jpg](https://user-images.githubusercontent.com/51517619/152150337-5fc89630-dd26-4258-ac05-5fc40bc5f202.jpg)

Here's another example

Be great to get this done next @pellarboss @madtocc

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/152394967-dd21c472-d822-40f6-aef1-7aadf282d69e.png)

**Comment by TheOneXi** [comment]
This looks great @madtocc 

If you can set grid as the default and have an option to select list view

**Comment by TheOneXi** [comment]
![IMG-20220204-WA0007.jpg](https://user-images.githubusercontent.com/51517619/152525708-625bae48-118f-489d-88a2-de80699ec071.jpg)

Something like this with a toggle to switch between list view and grid view (grid will be default)

@madtocc

**Comment by madtocc** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-02-14 at 18 42 14](https://user-images.githubusercontent.com/12486417/153951262-539d78ef-c1fd-4e08-b625-a4202b1142ff.png)
![Simulator Screen Shot - iPhone 13 - 2022-02-14 at 18 42 08](https://user-images.githubusercontent.com/12486417/153951277-604b0db9-13f3-40bd-ba40-85c5bb8d37ce.png)
![Simulator Screen Shot - iPhone 13 - 2022-02-14 at 18 42 05](https://user-images.githubusercontent.com/12486417/153951280-86d63a51-3062-4d25-90c1-7746e8d2ec61.png)
