### ISSUE TITLE
iOS not reflecting image changes

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#400]
I think that the ‘changes’ to your photo in the iphone are not taken into account on the app. Therefore the latter NFT was a different color (darker). 

I tried to make the picture exactly how I wanted and screenshotted it. When minting it, it gives the whole printscreen (not the square I took out), so either way the ‘additions’ to a photograph (on the iphone) are not taken into account.

---

The above is from an iOS user who is saying their image becomes darker once uploaded on Curate - is this due to compression/buffering to reduce load time or is it something else?

Below are 2 images, the brighter one is the original on his iPhone gallery and the darker once is a screenshot he took once it was uploaded and approved on Curate app.

![NFT darker](https://user-images.githubusercontent.com/51517619/149841675-700edeaa-d5c6-4b75-ab21-7823ecb80119.jpg)
![Original image](https://user-images.githubusercontent.com/51517619/149841677-2b670708-db9e-47b7-903c-f7150952202c.jpg)

**Comment by TheOneXi** [comment]
Let me know what you find @madtocc @pellarboss

**Comment by madtocc** [comment]
to me, it's the exact same output...
![Simulator Screen Shot - iPhone 13 - 2022-02-15 at 12 15 35](https://user-images.githubusercontent.com/12486417/154091403-63ddc586-d574-48d9-b99b-3c88537ccf8d.png)
![Simulator Screen Shot - iPhone 13 - 2022-02-15 at 12 15 44](https://user-images.githubusercontent.com/12486417/154091432-05baf014-c9a5-426f-b11c-a369344cef62.png)

**Comment by TheOneXi** [comment]
No worries then let's ignore this for now
