### ISSUE TITLE
User Details in Admin Panel: Show USDC Equivalent of XCUR Sold and Total Volume

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#401]
Show USDC Equivalent of XCUR sold and Total Volume in User Details (Admin Panel)

![USDC xcur](https://user-images.githubusercontent.com/93180831/149964376-6fa4e0c9-ee6b-41bc-9c4a-b597fc3639d2.jpg)

**Comment by eventang2015** [comment]
now it's in staging

**Comment by TheOneXi** [comment]
Can you push to production? @eventang2015
