### ISSUE TITLE
User imported NFT with wrong token ID

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#406]
User: Domantasr@inbox.lt

The user imported the NFT below but put the wrong token ID on the curate import page

He put token ID as 0318

Correct token ID is 318

https://etherscan.io/tx/0x6ff1e0cb4c34e8c2c010177be9ee5dd9455e0f92cc3dce34510520e937a87e5f

**Comment by eventang2015** [comment]
https://opensea.io/assets/0x05febf6a40a672854b3549f2b814e9a9946e6cc7/318
https://opensea.io/assets/0x05febf6a40a672854b3549f2b814e9a9946e6cc7/0318
they are the same.
the imported item token id is `"nft_token_id" : "318",`

**Comment by TheOneXi** [comment]
User sees the NFT now but can't sell it, below is a screenshot of what he sees, can you help @pellarboss 

![profile](https://user-images.githubusercontent.com/51517619/151540700-e5981b2a-13aa-41f0-8b8d-f8599bbc2c31.jpg)
![list NFT](https://user-images.githubusercontent.com/51517619/151540707-318f9dca-62a9-48bc-bc7e-f464ed58a419.jpg)
