### ISSUE TITLE
Error during THETA withdrawal

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#407]
User cannot proceed with THETA withdrawal

To Reproduce:
1. Go to Wallet 
2. Click Theta > Withdraw
3. Enter External Theta address, Amount to withdraw
4. Click "verify withdraw"
5. User enters 2FA key

Current Behavior:
Error showing "The request failed due to a validation error"

Expected behavior:
User proceeds with verification and complete withdrawal

User Email: jesusmarugan2001@gmail.com
Android, Updated app

![2 (4)](https://user-images.githubusercontent.com/93180831/150141457-aba077af-7c69-45de-a524-97b074bfaa7d.jpg)

**Comment by TheOneXi** [comment]
The same user is now getting the following error after updating to v5.2.1 when trying to withdraw his THETA:

@pellarboss 

![tfuel](https://user-images.githubusercontent.com/51517619/150320733-f900a2a6-06d0-4580-8bde-863a777d75bf.jpg)

**Comment by eventang2015** [comment]
hotfixed.

**Comment by TheOneXi** [comment]
Will this fix take place in a new build or shall I ask him to try again?

**Comment by TheOneXi** [comment]
The user is still facing the issue in the current build.

I see @eventang2015 said above this has been fixed so will this fix be in the next build or should it be on the current one @pellarboss @madtocc ?

**Comment by madtocc** [comment]
It should be fixed in the current release. Do you know what type of error he is receiving?

**Comment by TheOneXi** [comment]
![theta](https://user-images.githubusercontent.com/51517619/154336451-af11991c-3e7e-4dba-9af3-0927980be49b.jpg)

This is the error he gets when he tries to make Theta withdrawal

Note: He doesn't have any TFUEL

**Comment by madtocc** [comment]
@eventang2015 please take a look when you can.

**Comment by eventang2015** [comment]
@curateproject send theta requires tfuel coins as net fee.

**Comment by TheOneXi** [comment]
Can you add a message on the error screen and on the withdrawal page for theta withdrawals that TFUEL is required as gas and you can mention how much TFUEL is required
