### ISSUE TITLE
Twitter bot missing sales:

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#408]
https://twitter.com/CurateBot

But our telegram bot is working fine:

https://t.me/+_pzyJgJ5BcNiMTE1

The Twitter bot misses some sales

It gets reported from the telegram bot correctly but the Twitter bot misses some.

Below is an example of a tx missed

![Screenshot_20220119-203720_Telegram X.jpg](https://user-images.githubusercontent.com/51517619/150209808-9ccde0e3-359e-4bdb-98c7-6f6b7005618b.jpg)

**Comment by breaddog** [comment]
hi @curateproject , did you receive anything in your email from twitter developer regarding anything related to api usage recently?

ive also checked the developer's portal and nothing out of the ordinary that incidates there are issues, as mentioned below it might be either a rate limitation or an api endpoint limitaiton on twitter's end

**Comment by pellarboss** [comment]
Currently works ok
https://twitter.com/CurateBot

Twitter probably have a rate limitation?

**Comment by TheOneXi** [comment]
Nothing in my emails, perhaps rate limit?
