### ISSUE TITLE
Hide NFT's minted and owned by a user locked by Admins

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#409]
Stolen NFT are being sold in the platform.
When a user/seller is locked, all the NFT's the user minted and own should automatically  be hidden in the marketplace to keep another user from buying the stolen-sold NFT's.

**Comment by eventang2015** [comment]
@Catherineanne91 when admin strick an user（exclude warning）, update all his NFTs offline and reset to pending status?

**Comment by eventang2015** [comment]
set locked user's all products denied and offline.
