### ISSUE TITLE
2FA Validation Error during Withdrawal (iOS & Android)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#411]
User cannot proceed with withdrawal due to 2FA validation ERROR

1. Go to wallet
2. Click XCUR 
3. Click Withdraw
4. Type withdrawal details and click Verify withdraw
5. Asks for 2-Factor Authentication
6. User types the correct code but shows Validation Error

Expected outcome:
2FA successful; user completes withdrawal

User email: yaansinlee@hotmail.com
iOS 
latest apps version 5.2.1b123 iOS.

Another user experiencing thesame issue:
user email: femnueln2004@gmail.com
Android
 App version V5.2.1b124 Android

**Comment by madtocc** [comment]
fixed @Catherineanne91, please confirm

**Comment by Catherineanne91** [comment]
yaansinlee@hotmail.com tried to withdraw xcur and **confirmed its fixed.**

**Comment by Catherineanne91** [comment]
@madtocc Another Error when withdrawing SOL

Error when Withdrawing Solana


To reproduce
1. Go to Wallet
2. Click Solana
3. Click Withdraw
4. Enter Sol Address, Amount to withdraw
5. Click verify withdraw
6. Enter 2FA key
7. Error Appears; "Request failed due to validation Error"


Android
App version: 5.2.1
Device: Redmi note 7

Email: juniargayuhc@gmail.com

![Screenshot_2022-01-21-20-15-11-057_app wallet curate](https://user-images.githubusercontent.com/93180831/150781224-de2e88e0-81f3-4013-8315-d6b4f4455811.jpg)
