### ISSUE TITLE
Add bell icon to profiles

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#412]
Add a bell icon to profiles to allow others to get notified via in-app notification whenever the creature lists an new NFT or physical goods item for sale.

I.e. A notification bell for subscribers to get informed of the latest drops etc

**Comment by eventang2015** [comment]
> POST `{{host}}/users/:key/subscribe`  
> DELETE `{{host}}/users/:key/subscribe`
> GET `{{host}}/users/:key/subscriptions`
> GET `{{host}}/users/:key/subscribed`

**Comment by madtocc** [comment]
@curateproject this is for only the users you are following like that notification bell on youtube? or you can subscribe to notifications without following?
