### ISSUE TITLE
Add collection tab on profile 

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#414]
Add collection tab on profile for users who have created a collection

If no results display a message saying that 

![20220123_133014.jpg](https://user-images.githubusercontent.com/51517619/150680883-a1a7e5ef-d334-4b49-b4d6-4c1e1df9cfba.jpg)

**Comment by madtocc** [comment]
Hey, @curateproject, it is a little bit weird to have the about within the NFTs page, so I have moved it above the tab bar. Also, I have renamed the about to NFTs + fixed the text padding.
![image](https://user-images.githubusercontent.com/12486417/150858528-66458fe8-9874-4f85-bd87-7ec042357cbe.png)

**Comment by TheOneXi** [comment]
This is great I agree :)

Just to confirm have you also added the collections tab? I see it in your screenshot but it wasn't mention so just want to confirm

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/150859002-6bcd4e2f-344d-45f3-8fe5-b4d23288c228.png)
