### ISSUE TITLE
Blank screen when making a bid

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#416]
**Describe the bug**
When trying to make a bid on an auction it leads to a blank screen

**To Reproduce**
1. Go to an NFT on auction
2. Try to place a bid
3. Blank screen will show

**Expected behavior**
It should not show a blank screen and either confirm the bid if sufficient funds or display insufficient funds message

**Screenshots**
![blank screen](https://user-images.githubusercontent.com/51517619/150773912-f023d86a-7eff-4bb1-9c44-0a4ebe6e0334.jpg)

**Smartphone (please complete the following information):**
iOS 11
App version 5.2.1b123

**User ID**
jack@jmconcreteco.net IOS 5.2.1b123

The NFT Auction in question:

https://go.curate.style/nft/348696341adf74808be9214a

**Comment by Catherineanne91** [comment]
@madtocc , iOS user experiencing similar problem

 arthurmj@live.com
