### ISSUE TITLE
User Cannot Mint JPEG (iOS)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#417]
User cannot submit JPEG for minting

1. Go to profile
2. Click 3 bar icon (lower right)
3. Mint NFT
4. Select JPEG
5. Type Details (Title, Description, Price, Proof of work, etc,)
6. Submit for Approval
7. Error Shows "ERROR- only support jpg.jpeg,gif,svg,mp4,, mov"

Expected Outcome:
Should show Success and Waiting for Approval

The following users experience this problem:

shubham17nainiwal@gmail.com
V 5.2.1
iphone SE 2020

eliwolfwood@gmail.com
V 5.2.1
ios

khalilgibran33@icloud.com
Device: IPhone 11 Pro
App Version: 5.2.1b123 iOS

ch_waqas81@yahoo.com
App version: 5.2.1b123
iOS

ayoub98money@gmail.com
V.5.2.1b124
iOS

amani.kwider@icloud.com
V 5.2.1
ios

![unnamed (3)](https://user-images.githubusercontent.com/93180831/150782699-8ce98964-ff11-461b-8da8-329b04493e0a.jpg)

**Comment by madtocc** [comment]
@eventang2015 sometimes iOS returns extension in uppercase could you check the extension without being case sensitive? I removed the heic extensions for the current staging build.

**Comment by eventang2015** [comment]
@Catherineanne91  I think it's fixed in prod.
