### ISSUE TITLE
Set up FB Pixel and FB App Token

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#418]
Can you help set up Facebook pixel:

 https://developers.facebook.com/docs/app-review

And also an app token in the iOS and Android apps:

https://developers.facebook.com/docs/facebook-login/access-tokens/

Let me know what requirements you need

**Comment by TheOneXi** [comment]
Let me know if you have any questions @madtocc

**Comment by madtocc** [comment]
@curateproject  @DefiHunter 
Can you elaborate on what kind of events do you want to track?

Also need:
Ad Account IDs. You can get your ad account IDs from your [Ads Manager](https://www.facebook.com/ads/manager/accounts/).
If you also have a business account, in Authorized Businesses, add your [Business Manager](https://business.facebook.com/)[](https://developers.facebook.com/docs/app-events/getting-started-app-events-android#) ID. You can find your Business Manager ID in the URL of your Business Manager.
