### ISSUE TITLE
[Admin] User Locking / Banning Changes

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#42]
Please can you add a strike option in user section in admin panel:

1 strike = shows their email/ID in admin as yellow and warning email sent i.e you have a strike for the following reason (+ admin comments)

2 strikes = shows their email/ID in admin as red and warning email sent i.e you have a 2nd strike for the following reason and your account is now locked for 7 days (+ admin comments on reason) + lock/ban for 7 days.
2 strikes = show red

3 strikes = shows their email/ID in admin as dark red and warning email sent i.e you have a 3rd strike for the following reason and your account is now locked indefinitely (+ admin comments on reason) + lock/ban indefinitely.

----

Also add a notes section on the user account in the admin panel user section allowing admins to add notes on the account i.e 'watch this user carefully, he's minting copyrighted content etc'

**Comment by curateproject** [comment]
Enable options for lock account:

7 day lock
1 month lock
Permanent lock/ban

**Comment by curateproject** [comment]
Please can you add a strike option in user section in admin panel:

1 strike = shows their email/ID in admin as yellow and warning email sent i.e you have a strike for the following reason (+ admin comments)

2 strikes = shows their email/ID in admin as red and warning email sent i.e you have a 2nd strike for the following reason and your account is now locked for 7 days (+ admin comments on reason) + lock/ban for 7 days. 
2 strikes = show red

3 strikes = shows their email/ID in admin as dark red and warning email sent i.e you have a 3rd strike for the following reason and your account is now locked indefinitely (+ admin comments on reason) + lock/ban indefinitely.

**Comment by pellarboss** [comment]
Lets ensure one issue addresses one thing

is 3 already addressed in another ticket? ie royalties?

**Comment by DefiHunter** [comment]
Yes lets keep this as locking

**Comment by DefiHunter** [comment]
Could everyone move their comments to the appropriate tickets @curateproject @pellarboss

**Comment by DefiHunter** [comment]
I cannot find this feature in the panel, @pellarboss could u send a screenshot of it in action?

**Comment by pellarboss** [comment]
@DefiHunter in staging mate
