### ISSUE TITLE
Error in Changing Avatar Image

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#421]
Error in Changing Avatar Image

To reproduce:
1. Go to Profile
2. Click Avatar (upper left)
3. Click Avatar to Change image
4. Upload JPEG image
5. Error shows (see image)

Expected outcome:
Should be able to change avatar in jpeg format

File extension jpg
Device android
App version 5.2.1

Email egotria22@gmail.com

**Comment by pellarboss** [comment]
lets support JPEG as well as JPG

**Comment by eventang2015** [comment]
fixed.
