### ISSUE TITLE
Edit Reason For Denial in Admin Panel 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#422]
Add more information for the first reason for denial (Copyrighted product). So the list of denial reasons should look like:

- **Copyrighted Product - To validate the ownership, please submit the detailed Proof of Work (i.e. multiple different layers, colors, and the sketch, presented in different screenshot)**

- Regular Pictures lack artistic skill and quality will be denied upon submission in order to reward real artists and have a healthier marketplace

- Spam- you have submitted more than the allowed number of products in one go. in order not to spam both the marketplace and submission processing operations, we have to deny your submissions

- Explicit Content or nudity in Bad Faith

- Insufficient funds to parallel mint on Ethereum Network

**Comment by eventang2015** [comment]
hotfixed.
