### ISSUE TITLE
2FA Keeps Timing out for ETH withdrawal

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#425]
2FA keeps timing out and error message appears when encoding 2FA pin for ETH withdrawal

To reproduce issue:

1. Go to wallet
2.  Click Ethereum
3.  Click Withdraw
4.  Enter external ETH address and amount to withdraw
5.  Click verify withdraw
6.  App asks for 2FA - Enter 2FA code
7.  2FA keeps timing out and error message appear

Expected outcome:
Should be able to proceed withdrawal after encoding 2FA code

![eth withdrawal](https://user-images.githubusercontent.com/93180831/151120397-5e9fc09f-9091-4199-a569-d9338e2bf913.jpg)

abs84@hotmail.com
5.5
iOs

**Comment by eventang2015** [comment]
yes  he has insufficient funds in remote wallet https://etherscan.io/tx/0xda72984b3cb6b6e91585c967abeb1f7aa1210bc8a08f6365fb396f8251e4f68f
we will send him 185.19500786 XCUR, and I will adjust his eth balance locally.
@pellarboss FYI

**Comment by eventang2015** [comment]
synced his eth balance https://admin.curate.style/accounts/96b5bf406da5cbd4d82080b94e25fbb46df2
sent him xc20  https://admin.curate.style/accounts/eb2ccba982e8a56226d77da5afba53a5d2e4
@Catherineanne91
