### ISSUE TITLE
User Cannot Deposit USDC via Credit Card

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#426]
User cannot deposit USDC via CreditCard - a white screen appears when user clicks 'deposit'

To reproduce:

1. Go to wallet
2. Click deposit usdc
3. Enter amount
4. Click 'Deposit'
5. A white screen shows up

Expected outcome:
Clicking deposit should lead to page that requires user to fill in credit card details. 

![271961297_355428782779984_5039983987403530837_n](https://user-images.githubusercontent.com/93180831/151122980-22ee7f33-c139-4a89-ac96-a86bf85aa973.jpg)

Android 5.2.1
Email: abtilson@gmail.com

**Comment by madtocc** [comment]
Please update to latest version: 5.3.0; All blank screen issues Should be fixed
