### ISSUE TITLE
Allow Creator to Change Collection Name and Transfer NFT's within collections

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#427]
Additional features for collection:

1. An option for creator to rename his existing Collection
2. Enable creator to remove and NFT from a collection and transfer to another collection

**Comment by pellarboss** [comment]
1 - only if the collection is created by that user (not imported), ie you shouldn't rename BAYC to something else
2 - only if the destination collection is also created by the same user

@eventang2015 please facilitate backend first
@madtocc can do the UI after

**Comment by TheOneXi** [comment]
agree with your points for both 1 and 2 @pellarboss 

looking forward to seeing this feature go live
