### ISSUE TITLE
Wallet does not Load 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#428]
Wallet does not load (Only shows total Balance)

To reproduce
1, Go to wallet
2. The page only shows Total Balance

Expected outcome
Should show Wallet Balance for: Xcur, SOSx, USDC, Ethereum, DOT, etc. 

5.2.2b125 iOS
Email: moecarrim@curate.style

![Image from iOS (2)](https://user-images.githubusercontent.com/93180831/151157846-db1d709a-444e-4b23-b284-0949d97329f3.png)

**Comment by madtocc** [comment]
@eventang2015 please take a look. Accounts are taking too long to load > 10s. Maybe it is related to the SOS since it didn't happen before.

**Comment by pellarboss** [comment]
I will have a look at optimising performance
