### ISSUE TITLE
Mint NFT page tweaks

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#43]
Add a description text minimum i.e 100 characters and  Title minimum i.e 4 characters 

And add minimum reserve price required for all NFTs i.e $10

**Comment by pellarboss** [comment]
Lets set min price as 10 XCUR (since price is in XCUR and not in USD)

**Comment by madtocc** [comment]
https://user-images.githubusercontent.com/12486417/123850056-eb378600-d8ef-11eb-9278-4702fd10d736.mov
