### ISSUE TITLE
Staked XCUR does not show

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#431]
User staked 8500 XCUR in addition to 98 XCUR already staked.
When user go to MY STAKES in the XCUR app, it does not show  the staked 8500 XCUR but only shows 98 XCUR twice

Email: mstanlake@upwellhealth.com.au

Android
updated version

![2 (6)](https://user-images.githubusercontent.com/93180831/151349341-23c186ac-098f-4698-9b62-eca7ecb1277b.jpg)

**Comment by madtocc** [comment]
@Catherineanne91  please include the version number. Otherwise it will be difficult to know if it really is the latest version. Btw this is not the last version 😅

**Comment by Catherineanne91** [comment]
i understand. Sorry for that. Will update this asap

**Comment by madtocc** [comment]
No problem at all @Catherineanne91, this is just to track if the problem is already fixed or still persists. Thank you!

**Comment by Catherineanne91** [comment]
@madtocc 

This User updated his app
v5.3.0b125

Now it is showing "account does not exist" on the staking page

![Screenshot_20220127-224424_CURATE](https://user-images.githubusercontent.com/93180831/151365681-76f4829d-83b3-4682-9454-2128b98a1cf5.jpg)

**Comment by madtocc** [comment]
Oh, I guess I found an issue. 
For now could you please ask the user to click on XCUR account then on Staking? or wait till his accounts show up?

**Comment by Catherineanne91** [comment]
alright, thank you, @madtocc

**Comment by madtocc** [comment]
related to https://github.com/pellartech/curate/issues/430
The issue has been fixed and will be available in the next update. If users found this issue please instruct them to wait for accounts to load before clicking on staking on the accounts page or ask them to click on staking under XCUR account details.
Thank you

**Comment by Catherineanne91** [comment]
thank you
