### ISSUE TITLE
Questions for Roy

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#432]
Could you help us reply to these questions from a dev thats working on a NFT collection. We trying to do an exclusive drop on Curate where they mint directly onto our custodial ETH wallet.
1. Is the target address contract ?
1.1 If so it should naturally know how to handle erc721. So I could omit onERC721Received?
2. How will it be handled afterward?
2.1 3 core function were written in manner that deeply integrated with ‘owner’ property.

With the API key, can NFT projects use it to send funds from their Curate account to other Curate Users?

Another thing that I want to understand is that if we can utilize our API key for users to interact with the minting apps of the collections websites

**Comment by pellarboss** [comment]
1 the target address is an account (not a contract)
1.1 since it is an account, it does not need to have receiveable capabilities

2.  i dont know the question... the nft just resides on the master / custody wallet

> With the API key, can NFT projects use it to send funds from their Curate account to other Curate Users?
Curate's API can allow sending of funds

> Another thing that I want to understand is that if we can utilize our API key for users to interact with the minting apps of the collections websites
sorry i dont understand the context & question

**Comment by toomingos** [comment]
@pellarboss 

About this one "Another thing that I want to understand is that if we can utilize our API key for users to interact with the minting apps of the collections websites". We need to find a way to have users minting on the collections website, the mint section, with their Curate account and the API key integration

**Comment by pellarboss** [comment]
Yes, using the APIs provided One can Mint an NFT
