### ISSUE TITLE
Add "For sale tag"

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#434]
We should add a listed tag for the NFTs that are listed for sale on the marketplace page, collection pages, user pages, etc...

Currently is only on "My Profile page"
![IMG_AFF6DE20CC0A-1](https://user-images.githubusercontent.com/86632157/151562101-9265a6a9-53aa-4136-950c-42c9dcdf6157.jpeg)

**Comment by toomingos** [comment]
Added to Jan V5.5, you guys can push it to Feb if is too late for it now

**Comment by madtocc** [comment]
Marketplace only lists on sale items, so that it would be redundant (but I can add if you want)
We can add the tag on collections & user profiles.
