### ISSUE TITLE
Can't create collection

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#436]
App version 5.2.2b125 iOS
User key: 25fad84b4a2553d8b0b9b3cac762cfab424b

Cant create a collection, keeps on loading for minutes
![IMG_90121CE0FAD9-1](https://user-images.githubusercontent.com/86632157/151566655-19b12efc-2d54-4b93-b991-9b54c79f05e6.jpeg)
.

**Comment by madtocc** [comment]
does the collection show up under your collections?

**Comment by pellarboss** [comment]
@toomingos please provide all the assets used in the creation
Please always ensure we provide ways to produce issues in future issue reporting
