### ISSUE TITLE
Feedback from v5.5 (9 tweaks before pushing to production)

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#437]
1. Can you add the wallet icon to the bottom muggy

2. Can you show all collections A-Z at the end of the featured collections on the collections tab (this way users can browse and discover new collections)

3. I'm trying to update my twitter handle but I keep getting this error (can you also make it easier to enter the IG and Twitter username by just requiring the handle/username and not the full URL)

![Screenshot_20220129-143345_CURATE.jpg](https://user-images.githubusercontent.com/51517619/151665741-da428bd3-40ad-49b9-b4cd-021ae4a4f147.jpg)

4. Allow collections to be verified via admin panel, this will show a blue verified badge next to the collection name on this page:

![Screenshot_20220129-150000_CURATE.jpg](https://user-images.githubusercontent.com/51517619/151665888-0ba3923b-e332-4ef3-9e2a-cbd97b45f03c.jpg)

5. Can you add an icon or symbol to show and differentiate NFTs in a collection which are for sale and which are not. For an example add a 'sale' icon on NFTs for sale when on the collection page

6. Add a back button to go back to switch between generic and OpenSea on the import page, right now I have to go back a page to choose between the two

7. Unable to bring up keyboard to type in OTP code when doing a fiat deposit, for example on screen below you're unable to type the OTP (even though it's recieved fine)

![20220129_224422.jpg](https://user-images.githubusercontent.com/51517619/151680010-9e4da456-0857-4a78-8c4c-2bf25fe33dd1.jpg)

8. ALGO conversion into XCUR and ALGO causes the following errors (internal server error is when trying to withdraw algo)

![20220130_204547.jpg](https://user-images.githubusercontent.com/51517619/151717222-e612ce3e-d720-40f1-817d-17b4c749900a.jpg)

![20220130_204550.jpg](https://user-images.githubusercontent.com/51517619/151717223-ac49c6f5-0593-4f9c-a864-db05c9f34e8c.jpg)

In this example the user details are below:

App email: merttbingoll@gmail.com
Curate version: v5.3.0b125 
Device: Android

**Comment by TheOneXi** [comment]
Any update on this @pellarboss and @madtocc 

Once the above 8 tweaks/bugs are resolved we can push to the production

**Comment by madtocc** [comment]
@curateproject I'm not being able to reproduce 7 here. Is anyone else facing this issue?
I suggest next time, create individual issues and link them into this new one. I don't know what the app version of this issue is (by the picture, I can deduce it is on Android).
![image](https://user-images.githubusercontent.com/12486417/151973196-5ede2a90-9176-449a-b404-11e9a2150522.png)

**Comment by TheOneXi** [comment]
Ok will create an individual bug request next time for 7

**Comment by eventang2015** [comment]
https://admin.curate.style/users/0c3abf01324a399ca65312b530eb406b665b is James too, I renamed it to James-WRX

**Comment by TheOneXi** [comment]
ah thanks @eventang2015
