### ISSUE TITLE
Error in Withdrawing Algorand

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#438]
01-310122

Error in Withdrawing Algorand

To reproduce issue:
1. Go to account
2. Click Algorand
3. Click Withdraw
4. Type withdrawal details (address, amount to withdraw) 
5. Click Verify withdraw
6. Enter 2FA

Error appears (as shown)

![-d6k46h](https://user-images.githubusercontent.com/93180831/151765484-b1322785-be10-4ad3-ac6e-aca7973f3654.jpg)

Expected outcome:
Should proceed to withdrawal after entering 2FA pin

Android version is v5 3.0b125 
merttbingoll@gmail.com curate mail address

**Comment by eventang2015** [comment]
@Catherineanne91 `Error: Network request error. Received status 400: TransactionPool.Remember: transaction RKJDBKY6S7JH27BL4SMAH7GKIWUQKLEZSLVIFRWYYJPIH2UEJVNQ: account I72ECPNR5L4S3ZVOPZDZTPKVXQ4S4YIIOJUS3HFHNOCJ5CMUHSWMDPKNGQ balance 9360 below min 100000 (0 assets)`
so the minimum withdrawal amount after ducucting net fee of ALGO is 1 Coin.
will merge into production soon.
@madtocc FYI.
