### ISSUE TITLE
Search box wont load the keyboard

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#439]
When I go to the search bar, click on it and get to the search page. Once I'm on the search page I can't load the keyboard while tapping the search box repeatedly. 

https://user-images.githubusercontent.com/86632157/151777439-f0c48dbc-5249-41ef-b802-e2ac2786480a.MP4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: 5.5.0b126 

**User ID**
user key 25fad84b4a2553d8b0b9b3cac762cfab424b
user email jmshkm@icloud.com

**Comment by toomingos** [comment]
Still happening, I need to open the app again to make It work´

**Comment by madtocc** [comment]
I tried to reproduce here on Simulator and two physical iPhones, and I could not reproduce this.
Can you provide more information about the phone used and the iOS version?

When reporting a bug, the device should state the actual device, and the OS is the version of the operating system, not the version of the app.
e.g.
- Device: iPhone 13
- OS: 15.2.1
