### ISSUE TITLE
NFT Proof Of Work Preview on stats page

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#440]
We want to add a way for buyers to preview the proof of work submitted by the creators. Making the POW public gives a higher level of transparency to the platform and hence provides the potential buyers additional information prior to completing a purchase. This also transfers the accountability to the buyers as Curate can only provide transparency but cannot guarantee and has not verified authenticity.

Requisites:

1- Add the "Make Proof of Work Public" option on the mint advanced settings.
2- Add "Proof of Work" section on NFTs and Collections pages where we load the preview of the PoW submitted, just like when our admin team previews it on the admin panel.
3- Add the following disclaimer below the preview: "This Proof-of-Work (POW) was submitted by the creator and made available willingly to achieve a higher level of transparency. Curate Group Ltd takes no responsibility for any item sold by their users on their marketplaces and as such can not be held responsible for authenticating or verifying items as genuine. Therefore limiting any liability, as such users are advised to carry out due diligence on all items traded on the marketplace"

**Comment by pellarboss** [comment]
@eventang2015 please set up the APIs to facilitate this, let @madtocc know when it is done (and assign to him when ready)

**Comment by eventang2015** [comment]
@madtocc  item.pow_public (bool)
