### ISSUE TITLE
Make an Offer 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#442]
Allow buyers to make an offer on all NFTs including ones that are not available for sale

Logic required:
1. Buyer should have funds available in wallet for an offer to be made
2. Funds are locked once an offer is made and pending (to prevent spamming offers from same user)

Seller can chose to accept, reject or counter the offer (offer and counter-offers should auto-reject after 72 hours of no answer)

**Comment by pellarboss** [comment]
@eventang2015 please have a think about the logic and design APIs as you see fit

**Comment by pellarboss** [comment]
buyer could navigate to anyones profile

item could be: online + for sale OR online + not for sale

for online & not for sale, the buyer can make an offer
this will lock buyer.XCUR

if seller accepts offer, sale will complete

if buyer cancels offer, funds are unlocked

buyer should be able to query all products on offer
(UI should be able to list all products that I have offered)

**Comment by eventang2015** [comment]
@madtocc  apis are implemented.  please check postman

**Comment by TheOneXi** [comment]
Just to confirm @madtocc can an offer be made all NFTs even if not for sale? As I don't see it available for the bored apes or punks (we would like offer enabled if possible) @pellarboss

**Comment by madtocc** [comment]
Yes, James, you can make an offer to any nft. As long as it is not for sale. 
from https://github.com/pellartech/curate/issues/442#issuecomment-1041090149
> for online & not for sale, the buyer can make an offer

Currently, you can't make an offer to the bored apes or the punks since it is not deployed to production only for staging.

**Comment by TheOneXi** [comment]
What about an NFT currently on sale (buy it now or auction)?

Can we enable make an offer for those too? @madtocc

**Comment by madtocc** [comment]
sure

**Comment by TheOneXi** [comment]
Great thanks
