### ISSUE TITLE
Featured NFT not showing

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#443]
I have featured this NFT and it seems like it's not showing, https://admin.curate.style/product/dfcfb38d20c2d4859f08771a/detail

**Comment by eventang2015** [comment]
@curateproject 
https://federation.curateapi.io/products/featured?limit=10 
shows 
Note:  only show 10 featured nfts and order by last modified time

**Comment by TheOneXi** [comment]
Can we increase the limit to 20 @eventang2015 for featured, trending and weekly pics? @madtocc

**Comment by eventang2015** [comment]
@madtocc I updated the limitations to 20 in fed.

**Comment by madtocc** [comment]
@eventang2015 I haven't set a limit to any request regarding featured, trending, weekly picks. So you can set the limit on the server-side (I know this would gonna happen someday)
