### ISSUE TITLE
Remove sale icon on auction ended NFTs 

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#444]
Really like the new sale icon on NFTs for sale

But it should only be on NFTs which are actively for sale i.e listed for sale as buy it on now or on an auction not on items where the auction is finished 

This is also affecting the floor price number on collections as it's accounting for items for sale but with auctions ended which needs to be removed

**Comment by madtocc** [comment]
App side tag resolved.
@eventang2015  please remove the auctions ended from floor price. 
i.e., only return the ones that are online && approved. If they are an auction, they must be active as well.
