### ISSUE TITLE
Verify ID button not working on Admin Panel

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#445]
To verify users who claim that their ID verification keeps failing, admins will verify user manually from the admin panel. 
The Verify ID button is not working

To reproduce
1. Go to admin panel -https://admin.curate.style/
2. Go to Users
3.  Find User with problem in ID verification
4.  Click VERIFY ID
5.  A loading page keeps showing without any confirmation that ID has been verified 

![Verify ID_error](https://user-images.githubusercontent.com/93180831/152124977-64c100cc-91ca-4435-b5e7-6faab4e55920.jpg)

Expected Outcome:
User Details should show, 'Verified ID : YES'

**Comment by eventang2015** [comment]
added auth key for customer service admin
