### ISSUE TITLE
BSC withdrawl issue

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#446]
**Describe the bug**
When a user withdraws xcur on Bep-20 network above the manual approval threshold  and the master wallet has insufficient funds,admins are still allowed to approve it and if approved the transaction goes into a locked state and the user funds are not sent but removed from his account 

**To Reproduce**
1. Go to 'wallet'
2. Click on 'xcur'
3. Withdraw xcur over 2000 xcur and approve on admin panel 

**Expected behavior**
If there are insufficient funds and even if an admin approves it.  The user should receive an error message to try another network 

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version Latest and all prior 

**User ID**
user key 
user email Ayaansinlee@hotmail.com

**Scanner URL**
N.A 
**Additional context**

**Comment by pellarboss** [comment]
user funds processed

@eventang2015 please investigate how to prevent this from occurring in the future, ie if Master does not have enough, dont allow approval.
If master is misaligned with remote, please look at how to stay in sync better (implement watch dog)
