### ISSUE TITLE
PRIORITY Circle issue

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#447]
Circle has reported fraud , let's please investigate 

Further details can be found in the circle slack channel . 

Affected user email who I have now locked but have seen he withdrawn funds 

Please investigate and respond to circle 

Message from circle 

Hi Curate Team, 

My name is Chris from the Circle Risk Team. During our daily transaction monitoring, the following users were found due to fraud concerns:

nimustaphaismail@gmail.com
nasirushehu4383@gmail.com

Some fraud concerns noted during review are listed below: 
Brand new users with no prior history and newly created email addresses
Jumping transaction amounts ranging from $1 to $499.50
Both users have issuer and billing info from NG, they are also using similar IP addresses and cards with the same issuer identification number
Please see transaction details in attachment. 

Please kindly look into these users and let us know if you are able to confirm fraud. If you can share any additional information regarding verification done on your end, this would be greatly appreciated. If you are unable to verify these users, we recommend refunding the successful payments ASAP to avoid chargebacks. 

Feel free to let us know if you have any questions. 

Thank you, 
Chris

**Comment by pellarboss** [comment]
nimustaphaismail@gmail.com
was able to purchase since its ID was verified by Jumio correctly
record posted to slack

nasirushehu4383@gmail.com
was able to purchase since its ID was verified by Jumio correctly
record posted to slack

**Comment by pellarboss** [comment]
nimustaphaismail@gmail.com
auwalaminuauwal12@gmail.com
are both verified by Jumio

@madtocc please raise an issue with Jumio when you can, lets see what Jumio says

**Comment by pellarboss** [comment]
jumio has confirmed these ids are real

as a precaution, circle has been instructed to remove all NG sourced cards
