### ISSUE TITLE
Add sales bot our discord server

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#448]
Same as telegram but also added to our discord server

Let me what details you need. Here is the invite link:

https://discord.gg/E9NGYfxHgK

**Comment by breaddog** [comment]
Hi @curateproject,

Could I get a channel id for the discord channel which you intend for the bot to send updates to please? This could be a new channel that is designated for sales transactions for example.

We are testing the bot in staging and will provide an invite link for the bot later on for the server.

To get the channel ID for Discord
- User Settings (Cog on the bottom left)
- Advanced
- Enable Developer Mode
- Create a new channel you intend on having the bot send updates to
- Right click the channel on the sidebar and press Copy ID

![image](https://user-images.githubusercontent.com/46518750/155051183-b2482c62-2081-4917-b9d9-a9ec6cd2c675.png)

Here is a sample notification from the bot
![image](https://user-images.githubusercontent.com/46518750/155069580-562b328f-3552-41c7-85c6-063073ce9f87.png)

**Comment by TheOneXi** [comment]
Here it is @breaddog 

947585540251856906

**Comment by breaddog** [comment]
Thank you, 

Please invite the bot to your server through the following link, the permissions have been setup so the bot can only send messages to the supplied channel id.

https://discord.com/api/oauth2/authorize?client_id=943397596456685618&permissions=2147535936&scope=bot

If you would like to change the channel the bot will be providing updates to, please provide a new channel id and we can change the destination for you.
