### ISSUE TITLE
Inaccurate information showing on Collection Metrics

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#451]
A user's collection metrics is showing inaccurate information

User email: **atelier.codybayne@gmail.com**
iOS  (using both ipad and iphone, shows the same error)
5.5

**#1 Momento Mori**
Collection Link:
https://admin.curate.style/collections/07209a862da4949720dcee9b

- Should show 50 pcs, not 45
- The collection should show 12 owners, not 4
- Total Volume should show 300 (12 pcs sold for 25 XCUR) , not 100

![272542461_311518130992579_7596237244069820798_n](https://user-images.githubusercontent.com/93180831/152542853-a6629ec1-0af6-4031-8a50-624c822e2fe0.jpg)

**#2 Skater gurl**
Collection Link:
https://admin.curate.style/collections/9d19d8727b2141ad3110310e

- Collection should show 100 pcs, not 96
- The total volume should show 325 (7 pcs for 25xcur, 3 pcs for 50 xcur)

![247967456_478137373926927_5048003863439088821_n](https://user-images.githubusercontent.com/93180831/152543060-cc2910ac-a100-4e7d-894b-bd1eb0ff99bc.jpg)

**#3 Skater Boi**
Collection link:
https://admin.curate.style/collections/d4d0a2fc254e95ad4d3a6d49

- It only shows 1 owner (Collection is sold out)
- It should show 100 pcs , not 7
- Volume is >1100 XCUR. not 130

![272722291_471676461156990_8903268606541699239_n](https://user-images.githubusercontent.com/93180831/152542520-3f540d58-c5b6-446f-8329-03c8ad9d4995.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91  I quried from db
https://admin.curate.style/collections/07209a862da4949720dcee9b only 45 itmes in this collection
https://admin.curate.style/collections/9d19d8727b2141ad3110310e  96 items 
https://admin.curate.style/collections/d4d0a2fc254e95ad4d3a6d49 7 items

**Comment by eventang2015** [comment]
currently, the volume = total value of orders sold not total NFTs price
