### ISSUE TITLE
Change Denial Reason for NFT's in the Admin Panel

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#452]
The following changes are made
1. added email address  for regular photos
2.  edited the reason for regular photos for a "less offensive" statement that often upsets users

New reasons should  be:

1. **Copyrighted Product - To validate the ownership, please submit the detailed Proof of Work, applying all of the layers separately in the software, taking screenshots of each layer applied at the time**

1. **The picture did not meet the criteria of artistic skill. If you believe this is a mistake, please email us at support@curate.style.**

1. Spam- you have submitted more than the allowed number of products in one go. in order not to spam both the marketplace and submission processing operations, we have to deny your submissions

1. Explicit Content or nudity in Bad Faith

1. Insufficient funds to parallel mint on Ethereum Network

**Comment by eventang2015** [comment]
@Catherineanne91  updated.
