### ISSUE TITLE
Help prevent our weekly email newsletter (sent via mailchimp) not end in spam

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#453]
Hi @pellarboss just hoping you can help prevent our emails ending up in spam.

We do a weekly newsletter from support@curate.style sent via mailchimp to all our users

You recently added an SPF cname record in cloudflare DNS which fixed the spam issue with our curate.style emails but just wondering if you're able to help with the mailchimp newsletter?

Thanks

**Comment by TheOneXi** [comment]
Found this article, may this can help:

https://www.inboxally.com/blog/mailchimp-emails-going-to-spam-how-to-fix-and-avoid-it#:~:text=One%20of%20the%20possible%20reasons,from%20your%20domain%20via%20Mailchimp.

**Comment by doles2** [comment]
Updated the SPF and DKIM records to include mailchimp servers

**Comment by TheOneXi** [comment]
Hi @doles2 we just tested it again (sent an email via mailchimp) and it landed in spam.

I saw this message from Gmail which can help fix this:

To reduce the chances of messages from your domain being sent to spam or being blocked by Gmail, follow the general best practices in this section.

Set up valid reverse DNS records of your IP addresses that point to your domain.

Ideally, send all messages from the same IP address. If you must send from multiple IP addresses, use different IP addresses for different types of messages. For example, use one IP address for sending account notifications and a different IP address for sending promotional messages.

These are the delivery IPs from Mailchimp:

Delivery IPs:
205.201.128.0/20
198.2.128.0/18
148.105.0.0/16

Can you have another look @doles2 ?

**Comment by TheOneXi** [comment]
@doles2 I think I found the issue, we need to authenticate the domain on mailchimp

can you provide me the following info on the screenshot below to authenticate the domain on mailchimp

![Screenshot 2022-02-10 at 13 38 40](https://user-images.githubusercontent.com/51517619/153419378-5e83a9e7-4872-4a10-a1de-0809fc94454e.png)

**Comment by doles2** [comment]
Ok this is updated, please let me know if it helps the spam issue

**Comment by TheOneXi** [comment]
Hi @doles2 can you send me the above cnames to enter in MailChimp so I can authenticate the domain?

**Comment by doles2** [comment]
should be okay now @curateproject ?
