### ISSUE TITLE
P2P Product not showing on app

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#461]
Recently when going through the whole UX for the P2P, I have found out that, after being approved, my P2P product isn't showing on the profile P2P tab and when I search for it as well

product: https://admin.curate.style/product/92a2f86011c13ab9f008d146/detail

![IMG_1628](https://user-images.githubusercontent.com/86632157/153025443-c0722db0-cea6-4781-a097-6f9cffeb2a4f.PNG)
![IMG_1629](https://user-images.githubusercontent.com/86632157/153025455-f1dccb31-ff46-4c14-a7b3-d45eaa1da0bf.PNG)

![image](https://user-images.githubusercontent.com/86632157/153025887-b56ca768-af19-4574-b894-e3c3b6efa05c.png)

**Comment by eventang2015** [comment]
@toomingos It's not online.
@madtocc have button to set it online in app?

**Comment by madtocc** [comment]
Yeah, it should be able to do it in the app but it was not loading the p2p products under profile. I fixed this yesterday. It will be available in the next version build > 128
