### ISSUE TITLE
Recover Funds: User Deposited USDC to Curate Wallet on BEP20

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#462]
Recover Wrong Deposit : User deposited USDC to Curate on BEP20

TXN:
https://bscscan.com/tx/0x4e2b185a0107d0bdaf151203a676be3218868a43ed1cb56bca7b1c62eb50fec9

Email: mhr9900@hotmail.com
Token: USDC
Amount: 4,284 USDC

**NOTE: Charge the user 10%, to recover the funds**

https://curateorg.slack.com/archives/C02E00EH68N/p1644209857160819?thread_ts=1643633724.156039&cid=C02E00EH68N

**Comment by pellarboss** [comment]
@Catherineanne91 where do we send it back to?
(please ensure you include this in the future)

**Comment by Catherineanne91** [comment]
User wants to send it to : 0xEDD5c58D32b1B0Fd197800DbC0D153f831718EF5

**Comment by Catherineanne91** [comment]
@pellarboss user wants to send it to : 0xEDD5c58D32b1B0Fd197800DbC0D153f831718EF5

(Yes, will make sure this information is included in future, similar issues)

**Comment by pellarboss** [comment]
3854 sent to 0xEDD5c58D32b1B0Fd197800DbC0D153f831718EF5
rest sent to xcur master
