### ISSUE TITLE
User wants to access his account created on Curate Beta App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#465]
1. User created an account on the BETA APP  with the email: psturm79@gmail.com
2. User receives an email that his NFT named HODL was SOLD (_On Tue, 21 Dec 2021 at 18:53)_.  
3. There is no NFT named "HODL" in the admin panel that is created by psturm79@gmail.com (see image below for email received by user)

![HODL](https://user-images.githubusercontent.com/93180831/153593593-44d20d4e-189b-499c-8249-dfd850179651.jpg)

4.User wants to log in but can no longer access with his current version of the app.
5. User creates a new account, with the same email, psturm79@gmail.com on February 6 2022 and complains that he cannot find his Sold NFT nor the XCUR from his sales. 
5. The psturm79@gmail.com found in admin panel is the account he recently made (February 6 2022)

User email: psturm79@gmail.com
Version/OS: 5.5ob128 iOS

**Comment by madtocc** [comment]
Beta App = staging, everything is fake, so there's no real value. He won't be able to login into staging anymore since this is closed for team testing purposes. 


Product can be found here:
https://admin-stage.curateapi.io/product/1259b4642e3a21591d35b4b8/detail
