### ISSUE TITLE
Reduce the min required to convert SOL into XCUR

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#467]
Can you reduce the minimum requirement of 1 SOL when trying to buy/convert it into XCUR in the app

For example as 1 SOL currently = $90 can you reduce the minimum to 0.1 SOL when trying to convert it into XCUR

Can we do the same for other tokens in the app i.e reduce the amount required when buying/converting into XCUR

**Question:** Is there a need for a minimum? If not can we can remove the minimum for all tokens when trying to convert into XCUR?

**Comment by eventang2015** [comment]
implemented in staging, waiting for merging

**Comment by TheOneXi** [comment]
Thanks just a question @pellarboss 

Question: Is there a need for a minimum? If not can we can remove the minimum for all tokens when trying to convert into XCUR?
