### ISSUE TITLE
Add recommened dimensions when uploading collections or profile image

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#468]
Add a tooltip or some text recommending the dimensions in pixels for the collection banner/background, profile image and NFT image

i.e the collection banner looks to be 1920 x 680 pixels and the profile picture a square (300x300), not sure on the NFT image

But if you add some recommended guidance on the size dimensions that will really help creators create the exact image (esp for the collections banner) without it getting stretched or distorted

**Comment by madtocc** [comment]
Collection Banner - The collection banner depends on the screen's width; phones, tablets, and monitors have different sizes. We are fitting the image to the width (not scaling, unless the image is too small), so the output will be dependent on the width (if there's more room, it will show more). I don't know where you have experienced stretching or distortion, do you care to elaborate? See an attached example from OpenSea. The aspect ratio is somewhat what you mentioned ~3:1. If you want to display a fixed size, we can change that to a limited size, but larger screens will have it scaled or with some margin.

https://user-images.githubusercontent.com/12486417/154085785-4873b954-38b5-4e6b-8166-39c16843b1e4.mov

NTF - There are no size restrictions from the beginning; not sure if you want to add any. Please let me know.

Profile pic - They are cropped by the user and show the exact output. I don't see any reason to display a tooltip for that.

**Comment by TheOneXi** [comment]
Can we try a 3:1 pixel ratio fixed for the collections banner and add a text tool tip so creators can design the right size?
