### ISSUE TITLE
Deposit length

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#469]
Deposits of XCUR on the ETH & BSC network is really slow.

Below is a deposit I made over 1hr ago, in that time it still has not reflected into my xcur wallet.

How often is the wallets syncing ? From my understanding it's suppose to be every 15minutes-30min max right ? 

Tx hash for reference 

https://etherscan.io/tx/0x1ffcec6e9afcb070bbd3f6dc1d672c216097a1860a931f55a82e37730a6c8466

User account - moecarrim@curate.style 

Let's make it such that deposits don't take longer than 15-30min to reflect

**Comment by eventang2015** [comment]
fixed.

**Comment by pellarboss** [comment]
we implemented a method to deter spammers (to increase speed for active users)
which is to lower the priority for synchronisation for less active accounts

we have reverted this method, so accounts like Moe's will be synchronised faster
