### ISSUE TITLE
Kongdo Club Reveal

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#470]
We have a collection that dropped 50 NFTs with us and they are still showing the pre reveal metadata. I wanted to understand how can users that own them can refresh the metadata since I thought there was a button to do so. Need to understand if this is doable, if not we need to talk to the NFT collection team and time a reveal. 

User Key: 7022f92f1706bbcd8c1ed71dfdfa36655bfe

Import Log (NFTs from the collection): https://admin.curate.style/products/user/7022f92f1706bbcd8c1ed71dfdfa36655bfe/import/logs

**Comment by pellarboss** [comment]
oh, there is currently no method for fetching meta data

Task 1
@eventang2015 please refresh Kongdo's meta data 

Task 2
lets make this an admin thing (admin can click on a product to get its new metadata)

**Comment by eventang2015** [comment]
implemented in admin site. 
@madtocc public endpoint - POST : `/products/:key/meta/refresh`

**Comment by eventang2015** [comment]
@toomingos  Added a button 'refresh meta data' on product detail page. 
but I don't find more attributes from OS.
