### ISSUE TITLE
Show information of the products under each collection in the Admin Panel

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#471]
Currently When Admin clicks Collection> Specific Collection (ie Skater Boi), it only shows the Name, Description, Feature (or Not),  Logo and Background

See image below:
![collection info](https://user-images.githubusercontent.com/93180831/153884426-d15ddb5a-f835-4be0-b3ee-a53184cb8b34.jpg)

it will be helpful for admins to have a preview of the products under each "edit collection page" in the admin panel

See image below:

![information collection](https://user-images.githubusercontent.com/93180831/153885148-397dcfa2-525a-4df3-8e00-e255716031b9.jpg)

**Comment by eventang2015** [comment]
implemented in staging.
