### ISSUE TITLE
Solana NFT Export Error

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#472]
Solana NFT Export Error

To reproduce:

1. Go to Profile > Export NFT
2. Select NFT to Export 
3. Select Chain (Solana)
4. Type External account address

SHows: ERROR Export Product Failed

![Image from iOS (13)](https://user-images.githubusercontent.com/93180831/154221224-f59cbb50-d063-4247-8745-fa5d88db070d.jpg)

Name of NFT: Silly Billys 022
External Account Address: EXeSheN8uQaQnDD78fGVDgtixK6ZoQWkhfHT2qgVSwkW
Email: bradley00reed@gmail.com
v5.5.0b128 Android

**Comment by eventang2015** [comment]
@Catherineanne91  can he try again? we're using quicknode pro instead of ankr rpc.

**Comment by eventang2015** [comment]
@Catherineanne91  NFT: Silly Billys 022 - https://admin.curate.style/product/62685a1702c570981363e437/detail
 owner is https://admin.curate.style/users/3cf0cd74b7239610d5b8ffd4066199d163f8  
and woozy00woo@gmail.com have no SOL coins .
https://solscan.io/account/7HRf8fe57x1cTiwHWDqH9sTQ5NMtHmgbrLPRruot7WUj
I didn't find a user with [bradley00reed@gmail.com](mailto:bradley00reed@gmail.com) in system.
