### ISSUE TITLE
Curate API Key Minting App Interoperability

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#474]
We're looking to skip the whole process of making Collections importing NFTs onto the Curate app in order to sell them. We want users to be able to Sign in with their Curate Account on the Collections website in order to, mint on Pre-sale and Public Sale onto their Curate accounts.

We would need your technical guidance to put together an easy guide on how to set up the API Key for minting interoperability as well, interested to hear your thoughts on how we should put it together so an average NFT collection developer can easily set it up.

**Comment by toomingos** [comment]
@pellarboss do we need to move this to March? Just need to know what we should add to a doc, we'll set up everything else

**Comment by pellarboss** [comment]
@toomingos as per #484 - you can mint that way :)
so theoretically this ticket is complete.

For any additional development (if required), we wont have the capacity to take it on in this milestone (Feb).

**Comment by toomingos** [comment]
Ok got it, thanks
