### ISSUE TITLE
Floor Price

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#476]
The collection floor price stat is accounting for every item when in reality it should be the cheapest item listed
![IMG_1670](https://user-images.githubusercontent.com/86632157/154481886-44d022be-801a-43ae-8b5a-46663768c63b.PNG)
![IMG_1669](https://user-images.githubusercontent.com/86632157/154481901-4c97245d-f56f-4698-bd90-6d4a1df0d400.PNG)

**Comment by eventang2015** [comment]
using new statisitics
