### ISSUE TITLE
Edit Attributes bug

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#477]
The only user that should be able to **edit the attributes of an NFT is the original creator, and he can only do it if owns it and it hasn't sold yet!** Right now any owner of NFT can edit the attributes

Here's a screenshot of NFT I bought
![IMG_363F3E37DCE6-1](https://user-images.githubusercontent.com/86632157/154482486-2c67fba6-c668-466e-9a1f-013c4de75da6.jpeg)

**Comment by eventang2015** [comment]
@madtocc implemented in federation(staging).
you can check - if( item.owner  ==  current_user.key && item.userkey ==  current_user.key ) then display the edit button.
