### ISSUE TITLE
Delete User's NFT  Collections but keep all NFT's

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#478]
User Email: 
ilovemjjackson23@gmail.com

User wants to delete the Collections but keep the NFT's. He wants the NFTs to be available on this profile and on the marketplace but not under any collection

Collection #1:
Insomnia (4 items)
https://admin.curate.style/collections/f905a2da306117d7cc630b20

Insomnia #1
Insomnia #2
Insomnia #3
Insomnia #4

Collection #2
https://admin.curate.style/collections/59a217cda79bdcf1104e7ea5

Legion 7 items:
Legion #1
Legion #2
Legion #3
Legion #4
Legion #5
Legion #6
Legion #7

Collection #3
Oribit 
https://admin.curate.style/collections/d564a672a5d15f6d642def8b

Oribit#1
Oribit #2
Oribit #3
Oribit #4
Oribit #5
Oribit #6
Oribit #7
Oribit #8
Oribit #9

**Comment by eventang2015** [comment]
@Catherineanne91  done. updated those collection to removed=true, updated those products collection to null.
