### ISSUE TITLE
Create Collection form failing to load Gallery 

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#479]
**Describe the bug**
Create Collection form failing to load Gallery and to complete the collection, as the complete button doesn't register

**To Reproduce**
1. Go to create collection form
2. Click on the gallery and complete 

**Expected behavior**
Loads photo gallery

**Screenshots**
https://user-images.githubusercontent.com/86632157/154533941-028effaf-e3e4-4df3-8062-bcbecec89ec9.mp4

**Smartphone (please complete the following information):**
 - Device: iOS
 - Version 5.5b128

**User ID**
user key 8184ef68640704b8151bf7db55cd601fd14a

**Comment by madtocc** [comment]
It seems like the user clicked on the Camera button, not on the Gallery (that's why it popped the camera and didn't open the gallery). If the user clicks outside the options, it pops the modal.
I am able to take a photo and open the gallery as usual in the latest version (5.5b128).
