### ISSUE TITLE
2FA Bug

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#480]
**Describe the bug**
When tries to complete the 2fa he opens a blank screen

**Screenshots**

https://user-images.githubusercontent.com/86632157/154534932-e9f1292c-8e8e-4c39-b240-4f464f72734e.mp4

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: 5.5b128
 
**User ID**
user key 8184ef68640704b8151bf7db55cd601fd14a

**Comment by madtocc** [comment]
Fixed, it will be available in the next version.
The user still can set up the 2FA, he needs to go settings ->2FA setup
