### ISSUE TITLE
Featured NFT in the Admin Panel does not show in the App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#481]
NFT is featured in the Admin panel by clicking Product Detail> Feature
but NFT does not show in the "featured" items in the app

NFT:
https://admin.curate.style/product/628055b38756a24e5273ab0d/detail
![mark jenkins](https://user-images.githubusercontent.com/93180831/154542272-42a3edb0-26b0-4075-acb5-22a5b5dd9c6d.png)

**Comment by eventang2015** [comment]
it's not featured. 
I set it to featured now.
