### ISSUE TITLE
User Cant Withdraw Solana nor Use Solana to Buy XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#483]
1. User tries to withdraw SOL: App shows "Transfer Fail"
2. User tries to use SOL to buy Xcur: App shows "internal server error"

5.5, iOS
user Email: rene.korss@gmail.com

**Comment by eventang2015** [comment]
@Catherineanne91 I tried do a withdraw and commit.  
https://solscan.io/account/6fKhRu2UVejrctktW9tKfn5Firu4pPVQBXTk7GwV99Hk
withdraw ：https://solscan.io/tx/3wSLMB6Ps2gTmM8ziywjbiyvkKwH8o9hiJrSA2K6sFTGs9Nm3EQsHKfFq1iTzZssfYX644wxnHYd5feDG5bicRpw
commit : https://solscan.io/tx/4qq88wnrZAoBgH5b5CKkZbyc6agBYAEfaYVRrGRkM5itaebdhqma8mzr63bbqy2VTDvop9WSH49AGpx8NvT4nrqL
I got an error when calling sol network, tried again and it was successed :
`Send SOL Error - fromAddress:6fKhRu2UVejrctktW9tKfn5Firu4pPVQBXTk7GwV99Hk,toAddress:8grYUZCzmVMHhGxx2nBqtEHW2fb18dcczUGBefN3bad8,amount:0.099995, error:failed to send transaction: Transaction simulation failed: Blockhash not found`
so, can let users try again in a few minutes later ?
