### ISSUE TITLE
API Key Questions (ongoing)

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#484]
This is a message from a collection that wants to mimic the minting app experience with our API key:

"We have to make the following logic on our web page: the user chooses the amount of NFTs to mint and clicks on the mint button. 
This action should charge the user and then mint NFTs after successful payment. As I understand the algorithm on our web page should be the following:
1) Make a Register User API call to get an Auth token to use other Curate API calls [https://federation.curateapi.io/users](https://t.co/4ePZzhxixS)
2) Create a Product (it equals to Mint the NFT) with [https://federation.curateapi.io/products](https://t.co/Hvu5UPH80m)
3) Charge currently authenticated user to buy this NFT with https://federation.curateapi.io/products/:key/buy API call"

**Comment by pellarboss** [comment]
correct, it will be charged automatically as users mint, but the user wont have funds, here is another flow to consider:

Say the Site is ABC
1. ABC creates a user - abc_user
1. abc_user creates all the products from ABC
1. funds are deducted from abc_user

This process will save ABC from managing all many user's account and their token management will be much easier (since you only need to manage one token)

**Comment by toomingos** [comment]
They've cameback and said: 

I have one more question regarding Create Product request's payload:
1) "main_image" is the url of NFT image, right? Can we use URLs from Pinata then? (https://gateway.pinata.cloud/ipfs/bla-bla-bla.png)
2) What is the way to add image metadata to the product? Every image in our collection has its metadata with traits and things. We also store metadata on Pinata

![image](https://user-images.githubusercontent.com/86632157/155107362-54314eff-2808-4dc1-8d29-c3566f364030.png)

**Comment by pellarboss** [comment]
1 - the main image is a HTTP POST (when you upload the file) - this is not a IPFS link (we need the file)
2 - include "attributes", here is an example
```
attributes: [{
    "key": "color",
    "value": "red"
},{
    "key": "color",
    "value": "yellow"
}]
```

**Comment by toomingos** [comment]
Thank you!

**Comment by toomingos** [comment]
From another collection:

"I'm getting 403 Forbidden error when i run this code. I guess there is missing API key for complete the request. I changed data part with my own credentials"

var axios = require('axios'); 
var qs = require('qs'); 
var data = qs.stringify({ 
  'email': '[john.smith@gmail.com](mailto:john.smith@gmail.com)', 
  'password': 'Test123'  
}); 
var config = { 
  method: 'post', 
  url: 'https://federation.curateapi.io/users/login', 
  headers: {  
    'Content-Type': 'application/x-www-form-urlencoded' 
  }, 
  data : data 
}; 
 
axios(config) 
.then(function (response) { 
  console.log(JSON.stringify([response.data](http://response.data/))); 
}) 
.catch(function (error) { 
  console.log(error); 
});

**Comment by pellarboss** [comment]
@eventang2015 please provide API example in curl

**Comment by eventang2015** [comment]
@toomingos no need to use qs.stringify() 
here is a piece of code , and it works for me .
`const axios = require('axios')
const instance = axios.create();
instance.defaults.baseURL = 'https://federation.curateapi.io';
instance.defaults.headers.post['Content-Type'] = 'application/json';
instance.defaults.headers.post['Accept'] = 'application/json';

async function login() {
    const payload = {
        "email": 'john.smith@gmail.com',
        "password": "Test123",
    }
    // const data = JSON.stringify(payload) this will work also
    try {
        const resp = await instance.post(`/users/login`, payload)
        console.log(resp.data)
        return resp.data;
    } catch (error) {
        console.log(error.message)
    }
}

login()`

**Comment by toomingos** [comment]
<img width="742" alt="Screenshot 2022-04-20 at 13 22 32" src="https://user-images.githubusercontent.com/86632157/164229398-87339fe5-7e59-4755-96e0-18926ec9c9d4.png">

Can you guys help me with this?

**Comment by pellarboss** [comment]
To log in to the system, you have to have valid credentials (email / password)

The example above is an example, but not an actual user account, please substitute the account (email / pass) with a real account

The piece of code above logs the user in to the system, just FYI

also, please ensure we dont share credentials in a ticket, just being mindful of security

**Comment by toomingos** [comment]
<img width="737" alt="Screenshot 2022-04-21 at 09 56 02" src="https://user-images.githubusercontent.com/86632157/164418746-7552fe3f-6879-471a-9024-8beccda149f2.png">


Seems like it didn't work, could you help me with that?

Also, is there a way we can have a communication channel on telegram?
