### ISSUE TITLE
Error Appears when  withdrawing ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#486]
01-210222

Email: t.quang@me.com
Version/OS: 5.5.0b128 iOS on an iPhone 11

Description: User can not withdraw ETH (error Occurs after encoding authetnicator pin)

To reproduce:

1. Go to Account
2. Click Eth
3. Click Withdraw 
4. input external Ethereum and amount to withdraw
5. Enter Authenticator App pin > click complete withdraw

Error Appears: (see image below)
![unnamed (4)](https://user-images.githubusercontent.com/93180831/154949151-f04621b6-15a2-42f2-b9f1-17938edb10e3.png)

Expected outcome: should be able to complete transaction after verifying 2FA app

**Comment by pellarboss** [comment]
please double check if this is resolved in V6
