### ISSUE TITLE
Process NFT Import in Bulk

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#487]
Can you process 10 NFT imports please:

The below NFTs were sent to xcur.eth:

https://etherscan.io/tx/0xde661b3294e1680916c9d4ef8b4b618e70befe05ffe70b89db47435659826420

Token ID from 146 to 155

Contract address is: 0xDBfC52812538eea9Bf7Ab44aF1D4d37b596255DA

User email: admin@btfd.quest

Royalty : 6%

Will update with collection to be added to soon

**Comment by eventang2015** [comment]
imported, will update Royalty on edit page after imported

**Comment by eventang2015** [comment]
Done

**Comment by TheOneXi** [comment]
Can you add these NFTS to the collection: 'BTFD Chads' @eventang2015

**Comment by eventang2015** [comment]
done
