### ISSUE TITLE
Change Automated Email Sent to Users when Admins give a Warning Strike

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#488]
Currently, When  admins give a strike to the user, he automatically receives an email about it with the reason.

Let us make changes in the email that users receive, so they know if they are given a strike, they need to email back to us. (See image below).  Add the phrase "**If you believe this is a mistake, please e-mail us a proof-of-work at support@curate.style"** after the strike reason.

![2 (1)](https://user-images.githubusercontent.com/93180831/155251081-0136bd5b-8674-4b8c-a960-fa201254c715.png)

**Comment by eventang2015** [comment]
implemented in staging.
