### ISSUE TITLE
Move NFT to a user's collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#489]
User requests to move his minted NFT named **Hey it's Irish** to his collection **"First42"**

Product key: https://admin.curate.style/product/afff412335f59586fcb6f1aa/detail
Collection: https://admin.curate.style/collections/5642f265f5d0446c4cecb07e
User: homerread@gmail.com

**Comment by eventang2015** [comment]
Done @Catherineanne91
