### ISSUE TITLE
Tokenomics

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#490]
Below as discussed Roy 

new token
deploy on ETH / BSC = OK
bridge contract = OK
site for interaction with bridge contract = OK
Token & Liquidity migration to New Smart contract (BSC & ERC - 20)

**Comment by DefiHunter** [comment]
Updated Plan 

Deploy on BSC 
Token & liquidity migration on BSC (Old to New) 
Bridge contract - XCUR ETH Old -> XCUR BNB New and vice versa 
Site for interaction - migration.curate.style

**Comment by TheOneXi** [comment]
Option to unstake tokens from 31st March until 14th April

**Comment by DefiHunter** [comment]
Deposit bonus - 10% Bonus from migration day for users who deposit funds into the curate app. 
Bonus funds are locked for one month on the platform and not spendable. 

Open to deposits on bep20 and erc20
