### ISSUE TITLE
Delete Collection "Footazo"

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#494]
user email:  muharremyayla0077@gmail.com
User wants to delete the collection "Footazo"
Collection: https://admin.curate.style/collections/2b7593865832cb39731578e4

There are currently no NFTS in the collection but can't be deleted  from the Admin Panel (see image below)

![footazo](https://user-images.githubusercontent.com/93180831/156153723-d1b0fd80-cf99-497a-b453-78a1bbeca756.jpg)

**Comment by eventang2015** [comment]
oh, there're 9 denied items in this collection. fixed in staging.
collection is removed.
