### ISSUE TITLE
User Can't type decimal point when buying XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#500]
The app does not allow the user to enter decimal point when trying to buy XCUR using Solana

To reproduce: 

1. Go to wallet
2.  Click XCUR > BUY
3.  Select Solana
4. Enter "0.9"

User cannot enter 0.9 

Email: costaricaman@hotmail
OS/version: 5.5.0b128 iOS

https://user-images.githubusercontent.com/93180831/156315355-4171d95a-5a22-4cc2-918a-89644f2a8b9c.MP4

**Comment by madtocc** [comment]
Oh, it took me a while to find the issue. We are using decimals with dot format and the user probably has a number formatted with comma. I fixed this and it will be available in the next update. What the user can do for now is change his system language to a language that uses a dot as decimal places (like English - US).

**Comment by TheOneXi** [comment]
@Catherineanne91 take note
