### ISSUE TITLE
Can't edit description in a User's NFT from the Admin Panel

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#501]
User wants to change description to: 

x-curfire #19

[ ♂ = ▲ ]
[ ♀ = ▼ ]

created by Weerasak Uthong ( Outvivi )

Nothing Happens when Trying to change the description from the Admin Panel

https://admin.curate.style/product/816ac8a9c3446639c3ebae92/edit

**Comment by eventang2015** [comment]
@Catherineanne91 I updated the description 
`"description" : "x-curfire #19\r\n\r\n[ ♂ = ▲ ]\r\n[ ♀ = ▼ ]\r\n\r\ncreated by Weerasak Uthong ( Outvivi )",`.
I think it's because the minmum price in system is 10 XCUR
