### ISSUE TITLE
User cannot deposit via creditcard

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#503]
02-030322

User can not deposit via creditcard
email: curatenft123@outlook.com

To reproduce: 

1. Go to wallet 
2. Click usdc
3. Click deposit > Card Deposit
4. enter amount 
5 Enter creditcard details > Click complete purchase
6. Error appears as shown

![image (19)](https://user-images.githubusercontent.com/93180831/156519542-28b8e4cb-9bce-4872-a842-6fef4b06aeec.png)

Expected outcome: 
Should be able to complete transaction after 2FA authenticator

ios v5.50b18

**Comment by pellarboss** [comment]
USDC is currently disabled
