### ISSUE TITLE
Admin User Panel - Filter Button

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#506]
**Describe the bug**
We would like a simple way for the admin team to select and delete users' accounts. This will be achieved by filtering users by strike type. 

**To Reproduce**
1. Go to 'https://admin.curate.style/'
2. Click on 'Users'
3. See options tabs (All Users, Verified, Not Verified etc.)
4. We want another 'Filter' tab for this enhancement. 

**Expected behavior**
1 - Filter accounts based on strike type
2 - Ability to select multiple accounts and have a select all button
3 - Delete (This deletes all accounts, collections, and NFTs from our platform and makes them no longer visible)
4 - The deleted accounts go into an 'Archive Deleted' for 30 days, after this, they are permanently deleted. This gives the admin team the ability to restore an account if required.

**Screenshots**
See attached. [](url)
<img width="752" alt="Filter dropdown position" src="https://user-images.githubusercontent.com/88379508/157072345-ff4eff97-e248-41f2-b6db-a04f4ae03811.png">

**Comment by pellarboss** [comment]
Hmm, mass delete button is dangerous
should we add the delete button to the profile page? only for super admins?
bear in mind, a delete will freeze all assets belonging to a person, it should be used with care

adding a filter for "Strike" is very doable

**Comment by TheMad-J-Hatter** [comment]
Hey Roy, 

This is exactly what is needed imo. 

I don't think a delete per profile is the right way to go, it will take too long considering there are loads of spam accounts with stolen NFTs. So perhaps this 'mass delete' feature is only available to super admins (as mentioned) and you can only delete when the accounts are on their final strike? i.e. Filter by Strike 4 > delete button becomes availiable. 

1. Warning
2. Lock for one week
3. Lock for one month
4. Lock indefinitely 

We have a huge issue with stolen NFTs that are remaining on the marketplace which can be purchased by our community. What's more, we also have an issue with a huge % of collections that are empty. This is not good for a user to view collections with nothing in them.

**Comment by pellarboss** [comment]
@TheMad-J-Hatter 
i think there is a ticket for automatic collection deletion
when a user is locked, their NFTs are taken out of the market - from @Catherineanne91 

mass delete is ok per suggested, lets implement - @eventang2015

**Comment by eventang2015** [comment]
added a new list page - https://admin.curate.style/strikes
