### ISSUE TITLE
Creator needs to airdrop his NFT's to other Curate Users

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#509]
Creator wants to airdrop NFT's to his followers after his giveaway. He needs assistance in transferring to the following users, the following NFTs':

Winner #1:
https://admin.curate.style/users/463fbc5d6f707b1ae9547175159e58df48ac
NFT: 
https://admin.curate.style/product/62685a1702c570981363e437/detail

Winner #2
https://admin.curate.style/users/42579a0107c9978a732fce419944e4fd15fe
NFT:
https://admin.curate.style/product/897157752aa4155ba2141281/detail

Winner #3
https://admin.curate.style/users/2e2dadf292f7808a4671a76d43ebdbe68a04
NFT:
https://admin.curate.style/product/bdf75a59f7c92748bbda8cf2/detail

Winner #4 
https://admin.curate.style/users/0c13c6b9c7ed86ed6aedf1ad6e8093949ba5
NFT:
https://admin.curate.style/product/7ac7ba8e1e63799d54c77627/detail

Creator: https://admin.curate.style/users/3cf0cd74b7239610d5b8ffd4066199d163f8

**Comment by eventang2015** [comment]
@Catherineanne91 done.
