### ISSUE TITLE
Marketplace Default Sorting

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#51]
Can you sort the marketplace listing by random as default 

Also can you add 2 sections to the marketplace page

1. 'Trending' sorted by likes + bids
2. 'Featured' which shows listings enabled for featured in admin

**Comment by pellarboss** [comment]
Even - can random sort be paged?

please:
- create a random sort - ignoring the paging issue
- create a trending sort
- add a "featured" / "unfeature" button in product detail
- add a feature sort

Marco - implement UI when Even has done the backend

**Comment by pellarboss** [comment]
Duplicate with #36
