### ISSUE TITLE
Users experience poor resolution of NFT's in mobile app

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#510]
Users complain that sometimes, the NFT's in the app will show poor quality. 
User OS: Android v5.50b128

Sample of NFTs showing poor resolution at the screenshot below:

![photo_2022-03-08_09-30-47](https://user-images.githubusercontent.com/93180831/157431815-1d6be4f3-e537-48ef-8edf-b6700df55f1a.jpg)

![Screenshot_2022-03-08-09-31-59-686_app wallet curate](https://user-images.githubusercontent.com/93180831/157431877-6a075330-ce1c-477b-a155-6da918bb6b30.jpg)

**Comment by madtocc** [comment]
I don't see any quality issue on footazo on my phone. They are not even the same pictures... This is probably outdated.
![image](https://user-images.githubusercontent.com/12486417/158458408-bda09ea7-860d-4af1-b4b3-a3311e779b7f.png)

We are currently using a thumb-sized image to display the list of NFTs. It is being expanded, so this is causing a tiny image being expanded causing distortion. The thumb-sized image is used to improve the loading speed and avoid bandwidth consumption, the actual image is only loaded when the user clicks on the NFT.
So there are 2 options in my head atm:
- Increase the size of the thumb = + bandwidth and slower loading
- create another thumb for expanded = it will have to load the image again when switching expanded/compact view.

Please let us know what do you want to do or if you have another suggestion.
