### ISSUE TITLE
Staking - Auto-renew & compound feature for new staking model

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#511]
**Describe the feature**
To create two new features for the new staking page in-app.  

1. The user has the ability to select an auto-renew check box to re-list their staked XCUR. Currently, there is only a manual 30 days lock-up without the ability to renew. 
2. A second check box will also be available to compound their XCUR rewards into the next 30-day staking round (if auto-renew is selected).

**Comment by eventang2015** [comment]
for incomplete stakes, user can select option to auto re-new for 30 days and only once?

**Comment by TheMad-J-Hatter** [comment]
If I understand your question, if the user is currently staking or not, they should be able to toggle the auto-renew on or off. If switched on, the 30-day staking will commence again automatically. 

For example, in the attached image from Nexo, they have a check box to allow an auto-renew. As long as the auto-renew is selected, the staking will continue to roll-over month after month. 

A second check box should allow the user to compound the interest gained into the next 30-days of staking. 

<img width="317" alt="Screenshot 2022-03-14 093638" src="https://user-images.githubusercontent.com/88379508/158145315-eb91123f-3129-42d7-8533-2774bc509a70.png">
