### ISSUE TITLE
BSC Migration 

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#516]
**Migration page wireframe**
https://whimsical.com/migrate-curate-21LJ6dXDcFeeBrRSJshBzF

**Layout**
We will implement following this layout
https://finance.curate.style/

**Mechanics**
Users will have their bonus tokens locked?
They can claim it in 30 days of time?
ie: if migrate 10K XCUR on Apr 2nd, they can get 10K XCUR immediately, then come back and get their bonus on May 2nd?

**Comment by DefiHunter** [comment]
*Mechanics*
Users will have their bonus tokens locked?
Yes

They can claim it in 30 days of time?
Yes

ie: if migrate 10K XCUR on Apr 2nd, they can get 10K XCUR immediately, then
come back and get their bonus on May 2nd?\

yes this example is correct
