### ISSUE TITLE
NFT Offer automatically accepted without being accepted by user.

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#518]
**Describe the bug**
Someone made an offer on the Gold Backback Stake Boosting NFT (5 of 5) and the Curate app accepted this offer without the user approving this sale.  

The user in question is george.aldous@hotmail.com, and he received an email from Curate saying that he had received an offer on his NFT (see screenshot). He lives in Canada and had not received the app store update for Curate version 6.01. He is still running version 5.5 (see screenshot) and therefore could not see the offer on his NFT in-app. A few days went by and he received an email saying that the offer had gone through and he had sold the NFT. George still can't see this feature so unsure how the sale was even possible. 

**Screenshots**
![b7ef4414-28c6-44ec-92fb-685d680c5d02](https://user-images.githubusercontent.com/88379508/158218295-da83cd77-e6ac-4eb9-a3d8-159eb3716411.jpg)

![dd808ac6-d353-447a-bdca-9a1f2747e709](https://user-images.githubusercontent.com/88379508/158218719-aa61d9cb-37c0-4149-89db-e5ef1a2e5ff6.jpg)

![ac625403-e104-442d-9449-d451eb394bfb](https://user-images.githubusercontent.com/88379508/158219210-67a84bce-b4c3-40fd-ac24-e534de7a9f9a.jpg)

![6cacfee4-cf10-4bd0-b5db-e20766b8f75c](https://user-images.githubusercontent.com/88379508/158219251-28a477f7-5379-48e3-b912-f773fc738018.jpg)

**Smartphone (please complete the following information):**
 - See screenshot

**User ID**
user key
User email: george.aldous@hotmail.com

**Scanner URL**
https://scan.curate.style/txn/4477334778714f02525fdfe36532e2db39f34b94f7e9a0922cf2139e0305e768

**Comment by eventang2015** [comment]
@TheMad-J-Hatter that's because someone made an offer against that item. and the owner will receive a notification email.
`
    "userkey" : "0740746316924703dfb90aa3d43d6db6f097",
    "chatname" : "mhr9900",
    "avatar" : "avatars/avatar.jpg",
    "amount" : NumberDecimal("500"),
    "symbol" : "XCURP",
    "notes" : null,
    "status" : "canceled",
`

**Comment by TheMad-J-Hatter** [comment]
Hey @eventang2015 , thanks for your response. I don't think you understand the issue.

An offer was made on an NFT from User 1, however, User 2 did not approve.

The offer was automatically accepted but NOT by User 2. This is an issue, please can you look into this. 

@pellarboss

**Comment by eventang2015** [comment]
I mean 'mhr9900' made an offer against the NFT, and system sent an notification email to the owner. (once there's an new offer, the owner will receive a notification email)
actually, 'mhr9900' canceled the offer and purchased the NFT at 750 XCUR.
here's the purchase logs:
https://admin.curate.style/product/27a8dca1e59f73ae4e1c238b/detail

**Comment by TheMad-J-Hatter** [comment]
Ahhh I understand now, thanks for explaining @eventang2015. So although Mhr9900 canceled the offer, george.aldous@hotmail.com wasn't aware as there was no email that let him know the offer was canceled. This might actually be a good enhancement to include?? 

So although the NFT was purchased at 750 XCUR (full asking price), george.aldous@hotmail.com only received 683 XCUR +3.75 XCUR reward; this was why he thought that the offer had been accepted automatically. 

The royalty is 5%  (37.5 XCUR) so I'm unsure what other hidden charges we add onto the sale. Please can you quickly explain why 67 XCUR has been subtracted rather than 37.5 XCUR for this sale?

**Comment by madtocc** [comment]
The users currently can see the canceled offers in-app.
I think you forgot about the curate fee, which is 4%

The math seems to be correct to me:
Royalty = 5%
Txn Fee = 4%
rebate = 0.5%
750 - 37.5 - 30 + 3.75 = 686.25

**Comment by TheMad-J-Hatter** [comment]
Hey @madtocc, I guess this was the initial issue. iOS update had not reached Canada for some reason and he was stuck on V5.5. Therefore could not see the Offers section, hense the confusion.  

Thanks for the breakdown, I was completely forgetting the commission of 4%. Thanks. 

Issue closed.

**Comment by eventang2015** [comment]
currently, if seller has staking , calculates the fees against discount models. otherwise calculate the fees against settings.product_transfer_fee (5%).
