### ISSUE TITLE
NFT's not showing in Owner's Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#519]
User Imported a collection from Opensea to Curate

NFT Collection: Neo Tokyo Punks
Contract: https://etherscan.io/address/0xc65969df2bfd633bf72ef69f5c47756b6884f8f3
Import Date: March 11 2022

**Issue:**
- The user does not see the NFT's when he goes to his profile> collections (see image below)

![image (20)](https://user-images.githubusercontent.com/93180831/158438124-c18fa0ce-5528-4e76-b8aa-d3b27cbac41c.png)

- When other users visit his profile, nothing shows under  "collection"
(see image below)

![275455068_290079379923676_848270979197642289_n](https://user-images.githubusercontent.com/93180831/158438204-af623bda-579c-47aa-8af6-7fdb6c927dd7.jpg)

- When you click the NFT (profile> NFT > specific NFT, ie NeoTokyoPunks 414), 
 it shows that it belongs in the collection "Neo Tokyo Punks"

![275587103_535384704576532_3298905116436322478_n](https://user-images.githubusercontent.com/93180831/158438262-87801625-851c-430e-aa86-09a868672c64.jpg)

**Expected Outcome:**
- Owner should see the NFTs under "Collections"

OS: webapp
Useremail: neotokyopunks@protonmail.com,

**Comment by madtocc** [comment]
@eventang2015 please take a look.
Imported NFT, created a collection but the owner is not assigned, double-check, please.
```
{
    "key": "0099cc496097902ac50e39c5",
    "contract_address": "0xc65969df2bfd633bf72ef69f5c47756b6884f8f3",
    "owner": null,
...
}
