### ISSUE TITLE
[Admin] - Product Detail Page Details

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#52]
1. When rejecting an NFT allow admins to add a comment which is displayed to the artist in the app next to the rejected NFT
2. Show user emails instead of keys on the NFT/products page
3. Allow admins to adjust % commission from default for a specific user

**Comment by pellarboss** [comment]
OK, Even please include User Email & Name in Product Detail

1 - I will create a new ticket on this
3 - excluded for now - might be related to royalty conversation
