### ISSUE TITLE
New Staking Round Details

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#522]
All previous staking sessions automatically end on 31st March 0:00 UTC and rewards issued to wallet balance

New deposits open 1st April at 0:00 UTC (24 hours later)

- 30 day locked staking 
- Option to auto-renew and compound as per issue #511 
- New tiered yields to come into place based on the amount of XCUR tokens **staked** not just XCUR held in wallet (to prevent users gaming the system) - see table below for updated yields per tier (please can you update the changes for the tiers shown in the app too)
- The tier level shown on the wallet page should also update based on the amount of tokens staked (by default everyone is on standard) i.e if you have someone with 25,000 XCUR tokens in their wallet but they do not stake them they will **not** receive the diamond tier status (which offers 20% APY staking yield and 0% commission) 
- Stake boosting NFTs still apply
- Rewards issued to wallet balance if auto-renew is not selected

![Staking Yields](https://user-images.githubusercontent.com/51517619/158524886-3d9eee86-0070-4ebb-b526-76ad3161c410.jpeg)

**Comment by TheMad-J-Hatter** [comment]
Hey @pellarboss and @eventang2015, a comment connected to this issue. The new staking mobile screen still says 60 days instead of 30 and it doesn't seem to be recognising my stake boost NFT.
