### ISSUE TITLE
Increase the number of maximum NFTS to show on Trending,  Weekly Picks, Featured NFT's

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#523]
Increase the number of NFTS to show on Featured, Trending and Weekly Picks from 10 to 20 NFT's

**Comment by pellarboss** [comment]
please ensure it doesnt conflict with #508

**Comment by Catherineanne91** [comment]
@madtocc , @eventang2015  please include for Featured NFT's (updated the ticket)
so Featured, Trending, and Weekly Picks can be max 20

**Comment by eventang2015** [comment]
all limits are 20,  https://github.com/pellartech/curate/issues/508 -- to show items of verifed users.
