### ISSUE TITLE
Users having problem with uploading MP4 and JPEG to Mint

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#526]
**UPLOADING MP4:**
User email:  woozy00woo@gmail.com
user app version:  v.6.0.1b137 Android

To reproduce issue:
1. go to profile
2. go to mint NFT
3.  Upload file and fill in details (price, description, title, etc.)
4.  Click submit for approval
5. User is stuck in the "loading" page for approval
(see image below)
![276075112_999486957408046_2558665572090085810_n](https://user-images.githubusercontent.com/93180831/159201587-1b403ca8-6041-4ed2-9750-69e3197fbee4.jpg)

Expected outcome:
User should be able to see the "BOOM" page where user is notified to wait for approval.

User needs help in minting the following:

Title: #01 - Chill Out - Standard Edition 
Description: Chronic Cards 
Series: 01
Card: 01
Edition: Standard
Attributes:
Series: 01
Card: 01
Edition: Standard

Title: #01 - Chill Out - Silver Edition 
Description: Chronic Cards 
Series: 01
Card: 01
Edition: Silver
Attributes:
Series: 01
Card: 01
Edition: Silver

Title: #01 - Chill Out - Trippy Edition 
Description: Chronic Cards 
Series: 01
Card: 01
Edition: Trippy
Attributes:
Series: 01
Card: 01
Edition: Trippy

LINK FOR THE NFT's: 
[https://www.dropbox.com/sh/x1prq5zm4062qkd/AADL2uihITlGj8PJd90ITmqea?dl=0](https://www.dropbox.com/sh/x1prq5zm4062qkd/AADL2uihITlGj8PJd90ITmqea?dl=0&fbclid=IwAR2XBm0QEoP-2EhEp1XmGanh6hYP6GWpS-Kb8zPdKu8GyaWnxNag_EGT8BU)

UPLOADING JPEG:
User: [costaricaman@hotmail.com](mailto:costaricaman@hotmail.com)
App version: v.5.5 ios

same error as above, stuck in the "loading" page upon clicking "submit for approval"

**Comment by eventang2015** [comment]
did he create the NFTs? we can help to upload MP4 in admin site and see how it goes.

**Comment by Catherineanne91** [comment]
@eventang2015 

He created the NFT's without the mp4

 CC#01 - Chill Out (trippy)
https://admin.curate.style/product/72fb17b1f4e9c1e9ee380f3d/detail

 CC#01 - Chill Out (silver)
https://admin.curate.style/product/209d048be1cb043d5082eee0/detail

 CC#01 - Chill Out (standard)
https://admin.curate.style/product/81a458714de36a4f3fe2fc07/detail

**Comment by eventang2015** [comment]
@Catherineanne91  uploaded for him
@madtocc can you check App? it works in admin site.

**Comment by Catherineanne91** [comment]
@eventang2015 , @madtocc 

User still having problem uploading MP4' can we help him?

Batch 1:
https://www.dropbox.com/sh/4vfwo6mmumwnodg/AADrKyX78EUYZG_nnc6igGLpa?dl=0
NFTS:
https://admin.curate.style/product/78ec814b32daa5f0b12e7acc/detail
https://admin.curate.style/product/b5ba2a00108e42d3a3d71a02/detail
https://admin.curate.style/product/8e6461874ca7c13fbe6107d6/detail


Batch 2:
https://www.dropbox.com/sh/3ch638upg8n6ncq/AACgIY7W98LUSKzyrGiXCE4Ya?dl=0
NFTs:
https://admin.curate.style/product/36057245d90d5aa5fad13def/detail
https://admin.curate.style/product/6ac82e126ff8bf55243aca33/detail
https://admin.curate.style/product/93722a11d304f0ee294fa11e/detail

**Comment by madtocc** [comment]
Are you able to reproduce this issue as well, @Catherineanne91? I can't reproduce this.
To me, it uploads without any problem.
https://admin-stage.curateapi.io/product/7154fe1cc20fbe38d2e1b136/detail
https://admin-stage.curateapi.io/product/c3c959fba27c0baadc33fc99/detail

**Comment by Catherineanne91** [comment]
@madtocc , the user confirms he still cant upload the mp4. he tries updating, uninstall-re-install
![woozy](https://user-images.githubusercontent.com/93180831/163577365-b29f73c9-eae5-4364-8d0c-c1cdf01bbec4.jpg)

can we help him upload the mp4's above?

**Comment by Catherineanne91** [comment]
https://curateorg.slack.com/archives/C02QYSM7EJC/p1650270064644459

**Comment by Catherineanne91** [comment]
@pellarboss  @madtocc 

Tried both S10+ Phone
and samsung S7 tablet
Android  v7.1.2b154

Can we help him upload the mp4 above?

https://user-images.githubusercontent.com/93180831/165683472-1fb9cbff-dd13-4200-8f48-fddf4e6f31e4.mp4


https://user-images.githubusercontent.com/93180831/165683893-6435185d-6187-4724-87d8-679b32c7e32d.mp4
