### ISSUE TITLE
User Can’t Buy XCUR nor withdraw SOL on iOS

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#527]
Description: User can’t trade nor withdraw SOL 

**To reproduce:**

**Withdraw:**
Go to Account>SOL
Withdraw
Fill external SOL address, amount to withdraw
Click verify withdraw
Error shows: “transfer fails”

**Trade to XCUR:**
Go to account > XCUR
Click "Buy"
Use SOL, add amount SOL 
Click Review Purchase
Click Verify Purchase
Error shows: “Internal server error”

Users experiencing issues:

[rene.korss@gmail.com](mailto:rene.korss@gmail.com)
costaricaman@hotmail.com

OS: v6 iOS

Video of error:

https://user-images.githubusercontent.com/93180831/159303675-69cf8c35-ab7d-44a0-9600-e965be7e9561.MP4

**Comment by eventang2015** [comment]
wrong balance  in sytem. I will check data tomorrow.
https://admin.curate.style/accounts/69a8f39eaab16bdf70d60c35e6db911c9a6c 
https://solscan.io/account/HqU7J8rWkcWN5QgfegwPtHpbpc5UWtDkwb7pvLW8TkiP
https://admin.curate.style/accounts/ed518134b9a60c0f3a701cf96a721d14eb02
https://solscan.io/account/A1zpLfVUchTXHsZjeUX2WP72AacHb7FEeUCKPj8Ho14H

**Comment by eventang2015** [comment]
corrected account's balance - https://admin.curate.style/accounts/ed518134b9a60c0f3a701cf96a721d14eb02 
imported a withdraw txn - https://solscan.io/account/A1zpLfVUchTXHsZjeUX2WP72AacHb7FEeUCKPj8Ho14H

**Comment by eventang2015** [comment]
synced a commit transaction for account - https://admin.curate.style/accounts/69a8f39eaab16bdf70d60c35e6db911c9a6c

**Comment by Catherineanne91** [comment]
@eventang2015  @pellarboss 

Users above has been resolved.

new user experiencing similar problem:

Can't purchase XCUR with SOL in app
ios

Email: bradenbennett55@yahoo.com
App version: v7.1 ios

To reproduce:'
Go to account > XCUR
Click "Buy"
Use SOL, add amount SOL
Click Review Purchase
Click Verify Purchase
Error shows: “Internal server error”
![unnamed (1)](https://user-images.githubusercontent.com/93180831/164626566-d5339f2e-08a4-4542-8482-8ab7791b17b8.png)
![unnamed (1)](https://user-images.githubusercontent.com/93180831/164626583-4c344c50-d5f2-4ee2-9518-fadac1f6ba58.png)

**Comment by eventang2015** [comment]
re: https://github.com/pellartech/curate/issues/527#issuecomment-1106100181
synced commit txn.
