### ISSUE TITLE
Transfer User's NFTs's to Another Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#528]
**User email:** 
 artabstract100@gmail.com

User wish to transfer the following NFTS:
Skull Humanoid Style # 23 
Skull Humanoid Style # 24
Skull Humanoid Style # 25
Skull Humanoid Style # 26
Skull Humanoid Style # 27

From Curator Curate Cards Collection (https://admin.curate.style/collections/8d3cf12595f08cca73298721)

To:
Humanoid Clubhouse:
(https://admin.curate.style/collections/8bda93ea1fa20c3a5603238a)

**Comment by eventang2015** [comment]
Done
