### ISSUE TITLE
User's Collections Disappeared after 2FA Reset

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#529]
**Issue:**

After the user’s 2FA was successfully reset,  all his NFT’s below are automatically set to “denied” status and is currently not visible in his profile:

https://admin.curate.style/product/3410223c96b70856ff5a58fc/detail

https://admin.curate.style/product/c2cd9ef832935ec6882cd0b4/detail

https://admin.curate.style/product/fff501e47dc44371f77bfee3/detail

https://admin.curate.style/product/bc2ee2ff3b7ab31d46431e64/detail

https://admin.curate.style/product/419f5e486334b42c19076a24/detail

Only the recent purchase was left visible:

https://admin.curate.style/product/8fcd81dbf44244c7dce19e89/detail

Android user
v601b137
User: 877f1aa4fe78b32d1ff8f158a90050ef1252
 dernbeckdon@gmail.com

**Comment by eventang2015** [comment]
@Catherineanne91 I checked logs, the user locked by you and unlocked by kjssss62@gmail.com.
lock user - will update his Nfts to 'denied', you can reset Nfts to pending status and re- approve on product detail page .

**Comment by Catherineanne91** [comment]
thank you, @eventang2015
