### ISSUE TITLE
Royalties

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#53]
On the mint NFT page allow the seller to set a royalty up to 10% for all future sales (in the smart contract in case the NFT is withdrawn and sold on a secondary marketplace)

**Comment by pellarboss** [comment]
there is no Royalty built in for ERC721
once the NFT is out of the marketplace, we are no longer able to control royalties (incentives for users to be kept in the system)

Calculations:
- XCUR 100 sold price
- 10% = XCUR 10 for creator
- 5% = XCUR 5 master takes the fee
- XCUR 85 = for seller
- XCUR 0.5 = for seller rebate
- XCUR 0.5 = for buyer rebate

to get this in to 4.1 (monday), should have a FIXED value for royalties, do you guys want to propose something? say 3%, 5% or 8%?

**Comment by pellarboss** [comment]
capturing requirements

On Mint - the creator can select if the sale will incur a 2.5% royalty payment.
This payment will only be applied in secondary sales.

**Comment by pellarboss** [comment]
Marco:
in Mint, new Textbox: Royalties
default 0
validation: empty / 0 OR 1-10, support 1 digit, ie 2.5% is ok, -1% or 11% is not ok 2.51 will be rounded to 2.5

on Item Mint API call
do not pass this param if 0 or empty
pass the rounded number / 100, meaning 0.05 or 0.023, round 0.0251 to 0.025 (3 decimals)

in item detail, show "Creator Royalty: 2.5%"

**Comment by curateproject** [comment]
Can you make the royalty 10% not 2.5%

**Comment by DefiHunter** [comment]
For Monday could we keep it fixed at 2.5% if possible pls
