### ISSUE TITLE
Circle re enabled with 3DS

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#531]
Hey Roy and Marco 

As discussed let's bring circle back online 

Before we do let's enable the 3DS feature , also known as 3D secure . This will help reduce the number of chargebacks and fraud attempts as banks usually deny a refund if 3DS was used in the payment process 

So to summarize we shall support 3 payment methods 

Moonpay
Circle
Stripe

**Comment by eventang2015** [comment]
enabled.
