### ISSUE TITLE
Add Ability for Admins to Remove Tags Assigned by Users When Minting NFTs

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#533]
**Current Situation:**
Users tag their products to several categories to which their minted NFT's do not belong. This will result to poor search results when using the new filter feature of the app. 

**Solution:**

Allow admins to review tags assigned to a product and remove those that do not match their NFT's category.
This will be shown below the NFT, different color , distinguishable from the approve/deny buttons. 
![tags admin](https://user-images.githubusercontent.com/93180831/159978067-ef4c563c-5e82-4995-a4d3-94371d4b55cb.jpg)

**Comment by eventang2015** [comment]
![image](https://user-images.githubusercontent.com/28645146/165260147-147722dd-c45f-451b-adaf-b57a843f99a2.png)
can edit tags on detail page.

**Comment by Catherineanne91** [comment]
Hi @eventang2015 , is it possible that we are able to remove inappropriate tags while reviewing the NFTS?

the edit tags feature on detail page for now can do the job.
