### ISSUE TITLE
Change  Royalty and Price of all 70 minted NFTs by NeoTokyo Punks

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#535]
Owner: https://admin.curate.style/users/31fece84eb1c71b53ab9c11f8ccb46cb9a09
User email: neotokyopunks@protonmail.com

Change All Royalties of all NFT's by the user to 8.5% 
Change Price of all NFT's to 30 XCUR

**Comment by eventang2015** [comment]
@Catherineanne91  updated.
