### ISSUE TITLE
Imported NeoTokyoPunks NFT's do not show in the Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#536]
The same error occurred from https://github.com/pellartech/curate/issues/519

After importing 70 more NFTs, the newly imported NFTS do not appear inside the Collection:
https://admin.curate.style/collections/0099cc496097902ac50e39c5
Where, only 18 NFTs (first batch of imports) appear in the Collection (see image below)
![275939479_295868675993767_8387446001547469154_n](https://user-images.githubusercontent.com/93180831/159997057-73615813-9dfd-43bb-a837-ac0be76426ee.jpg)

The rest of the imported NFTs is in his profile under "NFTS'

![275953151_438162338080974_3908395182791920007_n](https://user-images.githubusercontent.com/93180831/159996992-4f4b2c4b-06c2-4ba9-a531-6e676152cd36.jpg)

**Solution:**
Transfer all the NeotokyoPunks NFT to the Collection "NeoTokyoPunks"

NFT Collection: Neo Tokyo Punks
Contract: https://etherscan.io/address/0xc65969df2bfd633bf72ef69f5c47756b6884f8f3
user: https://admin.curate.style/users/31fece84eb1c71b53ab9c11f8ccb46cb9a09

**Comment by eventang2015** [comment]
@Catherineanne91  updated.
