### ISSUE TITLE
Imported NFT page enhancement

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#537]
**Describe the enhancement**

**Expected behavior**
I'd like to see changes to the NFT Import page: 

1. Allow users to create and add their imported NFTs to a collection straight away. The user should be able to create a collection name and add a cover picture to it from the import page. This will mitigate any intervention from the devs later on.
2. Allow users to assign tags to their imported NFTs from the import page. Currently, there are no metadata tags assigned to imported NFTs which will not show when another user filters their results via tags i.e. Trading Cards, Virtual World, Gaming etc. This will add usability and add to a positive user experience. 

**Screenshots**
<img width="227" alt="image" src="https://user-images.githubusercontent.com/88379508/160106446-a4638210-d275-4e68-bc08-544f2247a92e.png">

**Comment by pellarboss** [comment]
@madtocc please explore this requirement
see what tags we can pull from OpenSea API also

**Comment by madtocc** [comment]
> 1. Allow users to create and add their imported NFTs to a collection straight away. The user should be able to create a collection name and add a cover picture to it from the import page. This will mitigate any intervention from the devs later on.

I really don't think this is a good idea, but we can implement it as you wish, of course. I suggest a deeper discussion here if you want. We can chat if it is easier.
Currently, you can only import 1 NFT, which means: the user transfer NFT to the curate custody address, server pull the new ones, and add to the user who imported.
The collection Image and background image are pulled from Opensea collection directly it does not need any user interaction. This handles the collection. So if a user already has an nft in the collection it will be under that collection.
If you allow the user to create a collection for each nft imported this can cause a huge mess. Let's say that you, roy, james and me have a cryptopunk and we import to curate. If each one of us create a collection the 4 NFTs that are from a collection will be from a different collection. That's one of the multiple reasons why we shouldn't allow users to put NFTs into a Collection nor edit them. Another reason is that you will loose automation of the imported nfts, if you want to import another NFT from the same collection you will have to either select a collection or re add it; Another reason is that you can create misleading collections:
I can create cryptopunks collection and add those 2
https://opensea.io/assets/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/2891
https://opensea.io/assets/0x31385d3520bced94f77aae104b406994d8f2168c/3160
ppl might be fooled thinking the last one is a cryptopunk and you guys can get into some trouble.

> 2. Allow users to assign tags to their imported NFTs from the import page. Currently, there are no metadata tags assigned to imported NFTs which will not show when another user filters their results via tags i.e. Trading Cards, Virtual World, Gaming etc. This will add usability and add to a positive user experience.


Here we can use the same tags and add those tags to our search tag filter.

@TheMad-J-Hatter  let me know how do we proceed here.
