### ISSUE TITLE
Master Account ( Custody) enhancement 

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#542]
Improve the Amount displayed figure on the Master account in the admin Panel to show: 

- Amount Owed to User 

-Total Amount in Wallet 

- Net Balance  ( Total - Owed) 

ACCURACY IS NB :P 

For example:

XCUR: Should show what is owed to our users in our platform as well as a separate figure that shows the Total Amount in the XCUR in the  wallet   

This way we can see our Assets vs our Liabilities. For example if the total is more or less than what is owed 

This should be replicated for all supported coins within the Curate app. e.g.ETH,  ALGO, Theta, DOT, SOL etc.

**Comment by eventang2015** [comment]
@DefiHunter please review admin dashboard.
