### ISSUE TITLE
In-app notifications for events

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#543]
The following events should trigger an in-app notification

- New follower
- New like
- New offer
- Offer rejected/accepted on buyer side
- New bid
- Item sold
- Auction ended unsold

Each event can be toggled on and off in a new page under settings.

**Comment by eventang2015** [comment]
@madtocc  PUT `/users/:key/notifications`
post payload:
`{
      new_coin: 'true' | 'false',
      new_follow:,
      new_like: ,
      new_offer: ,
      offer_rejected:,
      offer_accepted: 
      new_bid: ,
      item_sold:
      auction_ended_unsold: ,
}`
