### ISSUE TITLE
App Wallet - Update Metis and Skale logos 

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#544]
**Describe the bug**
Please update the logos in the wallet for Metis and Skale. 

**Screenshots/Files**
[skl metis.zip](https://github.com/pellartech/curate/files/8361369/skl.metis.zip)
![photo_2022-03-28_10-20-56](https://user-images.githubusercontent.com/88379508/160367636-623283ea-f39b-4adb-a88c-4e4e0dba2bd4.jpg)

**Comment by eventang2015** [comment]
only a few users have Metis and Skale accounts, will create accounts for all users on Mar 31st.

**Comment by TheMad-J-Hatter** [comment]
Hey @eventang2015, thanks. As long as the logos are included in the next app update on March 31st, that's perfect.
