### ISSUE TITLE
Put a sold NFT to a Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#546]
Creator wants SOS # 36 (Punk Edition 1/10) to be under the collection SOS Punk Edition

Owner: https://admin.curate.style/users/0e44fcaf6005a31f62e7570a5dbe5c0698c1
Creator: https://admin.curate.style/users/478b97c9f1ba27b053e53073e7347472c064

Collection: https://admin.curate.style/collections/8d819c0b23db287d50600128
NFT: https://admin.curate.style/product/c3f4871706f692d02bee5747/detail

**Comment by eventang2015** [comment]
done
