### ISSUE TITLE
Users stakes not unlocked after scheduled unlock time

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#547]
Users claim their funds are not unlocked to their wallet after scheduled unlock time for their stakes

USER # 1
https://admin.curate.style/users/32a56c37cc323e1ea786c99dcb59a3a6d241

Email ID: [Krisrobin.kr@gmail.com](mailto:Krisrobin.kr@gmail.com)
App Version: v6.1.Ob141 Android

Stake Below: 
![2](https://user-images.githubusercontent.com/93180831/160415546-f3c5b464-c36f-4ef2-addb-c392b05dd945.jpg)

USER # 2
https://admin.curate.style/users/166dfc2492e7a437d8f81a4f211860d0414e

Email :  dhooley02@hotmail.com
Stake Below:
![image0](https://user-images.githubusercontent.com/93180831/160416810-76086016-6484-4ef3-861b-b8ca933e397e.png)

**Comment by eventang2015** [comment]
it usually ends the next day.
