### ISSUE TITLE
User Stats does not show accurate Numbers

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#548]
User Volume Stats seem to show wrong figures
Volume = 2747

Product Sold: 111 XCUR
Product Sold In USDC: 147.3 USDC
Product Bought: 181 XCUR
Product Bought In USDC: 240.19 USDC

User: https://admin.curate.style/users/3cf0cd74b7239610d5b8ffd4066199d163f8

![276082637_342735194566195_2369288647026835085_n](https://user-images.githubusercontent.com/93180831/160433667-c363aaac-9fee-49ca-af89-b19a368667b4.jpg)

**Comment by madtocc** [comment]
@toomingos reported this issue. The correct amount of volume in USD has been fixed, and It will be shipped in the next version this week. **That's why we should always create issues, saving time on both sides.**
