### ISSUE TITLE
A user's purchased NFT did not arrive on his account

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#549]
An NFT is purchased by USER A,   gonzaloalonso241101@gmail.com but the NFT did not arrive in his account, and instead, NFT is currently owned by USER B  mmm265418@gmail.com

USER A's purchase appeared on Curate twitter BOT:

https://twitter.com/CurateBot/status/1508066421548679168?t=VE_ZEoLoD9GIJ9w9uVKnXA&s=19

![277008204_299008925646901_2399623730734041310_n](https://user-images.githubusercontent.com/93180831/160437755-3264a443-90a0-463c-8414-b5b89a03d379.jpg)

The purchase log shows  gonzaloalonso241101@gmail.com as the buyer
https://admin.curate.style/products/purchase/525e0b313593ec6765fd9193/detail

**NFT:** https://admin.curate.style/product/71e1a63d43c6742e8ef34dc7/detail

**USER A:**
https://admin.curate.style/users/358544fb661cae6f99aff14f91fdbe4d761a

**USER B:**
https://admin.curate.style/users/fc87135a6390ec6e65a2f2a1829c54fcd4e8

**Comment by eventang2015** [comment]
@Catherineanne91 it's double sales, I'll do a refund.
the 2 purchase time difference is on the milliseconds level.
2022-03-27T13:00:23.938Z  and
2022-03-27T13:00:24.290Z

**Comment by eventang2015** [comment]
refund 15 XCUR to https://admin.curate.style/users/fc87135a6390ec6e65a2f2a1829c54fcd4e8
