### ISSUE TITLE
User Can't purchase XCUR using his ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#550]
User Can't purchase XCUR using his ETH

To reproduce:
1. Go to Accounts
2 Click XCUR
3. Buy XCUR
4. Select Eth, input ammount
5. Review Purchase
6. Clickk Verify Purchase
7. Error Shows (see image below)

![s](https://user-images.githubusercontent.com/93180831/160563613-046af254-cc9e-4cf1-bae1-aff6cbd01dcb.jpg)

Email: giannilari@inwind.it.

Verios APP 6.10b141 iOS
Tel Apple Iphone 12 pro
Xcur deposit address
0xcD89637E1a830d801CA58389Afe908955A01e58a
ETH deposit address
0x13766A235FCEbCfc813c042313C1b8d5d14Fbf46''

**Comment by eventang2015** [comment]
https://etherscan.io/address/0x13766A235FCEbCfc813c042313C1b8d5d14Fbf46
https://etherscan.io/tx/0x29f29575e821607e3d56203bcf5275e91dd2a09ac9fa31dd122b49ec28869b1f
https://admin.curate.style/accounts/18905a2ded43b88bc78d2387ce4df8053be5
seems txn 0x29f29575e821607e3d56203bcf5275e91dd2a09ac9fa31dd122b49ec28869b1f was succeed, I will re- sync this txn.

**Comment by eventang2015** [comment]
SYNCED .
