### ISSUE TITLE
User Can't Withdraw ETH and Purchase XCUR with ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#551]
User Cant Withdraw ETH.

To reproduce:
1. Go to account
2. Click Eth > withdraw
3. Enter Address and amount to be withdraw
4. Click Verify Withraw

Error Shown:
![Screenshot_٢٠٢٢٠٣٢٩-١٠٤٣٠٠_CURATE](https://user-images.githubusercontent.com/93180831/160785816-8a3d2d76-358a-4358-845e-deed45bf58e6.jpg)

![Screenshot_٢٠٢٢٠٣٢٩-١٣٥٥٠٧_CURATE (1)](https://user-images.githubusercontent.com/93180831/160785874-43222a8e-dc01-4204-96c1-0a3349f57a92.jpg)

User Cant Purchase XCUR with ETH

To reproduce:
1. Go to account
2. Click XCUR> Buy XCUR
3. Use ETH, Enter Amount
4. Review Purchase
5. Proceed Purchase (2FA input)

Error shows:

![Screenshot_٢٠٢٢٠٣٢٩-١٤٠٨٠١_CURATE (1)](https://user-images.githubusercontent.com/93180831/160786252-09588dc0-de60-43ee-8359-c79e9187a750.jpg)

User: 

https://admin.curate.style/users/0740746316924703dfb90aa3d43d6db6f097
ETH locked:  https://admin.curate.style/accounts/29e136a40205f519ddc9a5ececd0b356856c
OS: Android v6.01b137

**Comment by eventang2015** [comment]
https://etherscan.io/tx/0xa8a68f34b4f811d8dba77d41b5bd13afd265ec1c33542aa1bf9645e21ed99dae is dropped.
will re-sync this txn ; https://etherscan.io/tx/0x33a0dd877513e93304e1e3ee8614f8ea5f807a9d4dc515dba5f30f603d4b190c

**Comment by eventang2015** [comment]
commit txn is completed: [0x33a0dd877513e93304e1e3ee8614f8ea5f807a9d4dc515dba5f30f603d4b190c](https://etherscan.io/tx/0x33a0dd877513e93304e1e3ee8614f8ea5f807a9d4dc515dba5f30f603d4b190c)
