### ISSUE TITLE
Offer notification and log out bug

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#552]
**Describe the bug**
1. Offer notification received for an account I was currently signed out from. I have access to my personal Curate account and the Curate Official account (James'). 
2. Log Out button in-app does not work on Andriod. I have to clear the app (swipe up to close not uninstall) from mobile for the app to sign me out. (Andriod app version 6.1.0b141)

**Expected behavior**
1. For only notifications to be pushed for the account you are signed in for. 
2. The Log Out button to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/160839266-3157281f-d55d-4eea-ae82-1fdc24c6568f.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Andriod
 - Version 11

**Comment by madtocc** [comment]
Notification I have set to unsubscribe manually when logging out, I haven't tested deeply tho. looks like it is fixed.
Log out was not popping the settings page, it is fixed in the newest version. No need to clean the cache, you just had to hit the <- button.

**Comment by TheMad-J-Hatter** [comment]
Ok sweet. Thanks Marco!
