### ISSUE TITLE
Multiple transactions of 400 XCUR and NFT does not show in Buyer's Account

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#553]
There are multiple transactions of 400 XCUR in a users account from a purchase of an NFT that was not received.

The NFT being purchased is in auction
User was not notified he won the auction

NFT is Gold Cap 2 of 5 : https://admin.curate.style/product/09d494111db257101d530464/detail
Current owner of the Gold Cap:  bang95838@gmail.com

user email: [Craiglistakount2013@gmail.com](mailto:Craiglistakount2013@gmail.com)
App: Android v6.01b137
The user's wallet :
https://admin.curate.style/accounts/f213925716a73cc79d7f9cce44349de6cac4

![photo_2022-03-30_09-33-25](https://user-images.githubusercontent.com/93180831/161010450-76091aac-9a06-42d2-ad19-33c5c22e4bec.jpg)
![photo_2022-03-30_09-27-31](https://user-images.githubusercontent.com/93180831/161010499-a49fa41b-071c-455d-b1ef-3157ea09affd.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 refunded and resolved. there was a bug in bot.
