### ISSUE TITLE
Tier and staking doesn't update

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#554]
My stake ended a few weeks ago (I even withdrew my XCUR so it's not in my wallet)

However it still shows the previous stake as active and the tier is gold but instead I should be on standard tier and have the staking amount showing zero

Please see video below, my app email address is jmshkm100@gmail.com and I'm on v6.1 and on Android

https://user-images.githubusercontent.com/51517619/161013974-c1329e8e-81d1-4869-865f-073328020eb2.mp4

**Comment by eventang2015** [comment]
@madtocc  resolved in app ?

**Comment by madtocc** [comment]
Yes, updated the endpoint
