### ISSUE TITLE
Double Transaction - User purchased the same NFT Twice

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#555]
User purchased thesame NFT twice

Transactions:
https://scan.curate.style/txn/e382445d32a3c9af3fb111704df4f955e4bb2ea4a70b687800ea2f66af69e6b4

https://scan.curate.style/txn/e7d091e6213e6c7f2f676d0c0f5bda6bf48071e9419781a3716e353b231d13ea

Item: 53f190b0d746b11898ac4600

User: https://admin.curate.style/users/086ecd33784ec7d77d6eb0e93d44a2742038

ACTION: Please refund User with the duplicate transaction
![image](https://user-images.githubusercontent.com/93180831/161016728-a63cd84b-efca-43a0-917e-8057e6a5185a.png)

**Comment by eventang2015** [comment]
refunded.

**Comment by Catherineanne91** [comment]
Another user experiencing thesame issue @eventang2015 
![Screenshot_2022-03-29-15-36-38-051_app wallet curate](https://user-images.githubusercontent.com/93180831/161232093-2a028d31-4e18-4048-9d07-302190373a4d.jpg)
![Screenshot_2022-03-29-15-39-47-118_org telegram messenger](https://user-images.githubusercontent.com/93180831/161232124-a1e15481-ac3a-4ba4-9fd8-b3a36a1fc19c.jpg)
![Screenshot_2022-03-29-15-52-44-666_app wallet curate](https://user-images.githubusercontent.com/93180831/161232162-eca6acbc-9918-42e1-82bc-23d98671f94e.jpg)


NFT
https://admin.curate.style/product/ad370b8dc86bcd20844139c6/detail

**Comment by eventang2015** [comment]
resolved.
