### ISSUE TITLE
A user has no import button on his app

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#556]
Issue:
A user has no import button on his app (see image below)

![Image from iOS (1)](https://user-images.githubusercontent.com/93180831/161415437-07f58813-c48f-4583-ba06-fdf322cdf2c7.jpg)

User Email:
[justinpat18@gmail.com](mailto:justinpat18@gmail.com)

iOS version 6.1.0b141 iOS

**Comment by madtocc** [comment]
This is not a bug. iOS users must have xcur into their account to import an NFT
