### ISSUE TITLE
User Can not accept an offer for his NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#557]
Issue: User cannot accept offer. 
Error shows: "You can not make offer to your own product"

itsasuan@gmail.com

NFT: https://admin.curate.style/product/5d58fa84f813cfe5e9eab33f/detail

App version: 6.01b/ android
![photo_2022-03-31_22-16-36](https://user-images.githubusercontent.com/93180831/161415998-18d0dca0-1bb5-44a5-afde-c783ba3b21a8.jpg)

**Comment by eventang2015** [comment]
it's fixed.
