### ISSUE TITLE
Admin panel is not working properly 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#558]
When Reviewing NFTs, 

A reviewed NFT will appear again on the product list with a pending status.

**Comment by Catherineanne91** [comment]
@pellarboss , @eventang2015 , Admins app bug is getting worse. 
NFTs reviewed on 2021 are returning to pending and is being reviewed again by some admins 
(NOTE: these NFTS were not returned to pending by admin)

![IMG_20220411_105832](https://user-images.githubusercontent.com/93180831/162664611-63b46c36-ff7d-440d-b49c-c8b974dd90e3.jpg)

**Comment by eventang2015** [comment]
needs admin to review after creator updating NFT.

**Comment by Catherineanne91** [comment]
hi @eventang2015 , Can you please check if all these users updated their NFT
they appear to be pending for review, but checking, some admins have already reviewed it before. 

NFT: https://admin.curate.style/product/43686625b69d021004e7b561/detail
Reviewer:  gadithomason1@gmail.com

NFT:
https://admin.curate.style/product/bd2c8832cd9141249ae9ed10/detail
Reviewer:  nekogang8@gmail.com

NFT: https://admin.curate.style/product/58abfda7776cdb0a453ddc15/detail
Reviewer:   nekogang8@gmail.com

https://admin.curate.style/product/85b804fd65c16f02b5b93804/detail
Reviewer : nekogang8@gmail.com

https://admin.curate.style/product/4f3d0d2f986b5b0fdbf6dbaf/detail
Reviewer: gadithomason1@gmail.com

https://admin.curate.style/product/249c2494eaf17603b5209541/detail
Reviewer: gadithomason1@gmail.com

https://admin.curate.style/product/1da27b498ab17c34ed84bf86/detail
Reviewer: catherineanneporter@gmail.com

https://admin.curate.style/product/0118299967c83582b90b5b1c/detail
Reviewer: catherineanneporter@gmail.com

https://admin.curate.style/product/1e9c57520471847ae55473bb/detail
Reviewer: catherineanneporter@gmail.com

https://admin.curate.style/product/5faa45247ccc97aea8688a56/detail
Reviewer: gadithomason1@gmail.com



These are a few that I took note of, but theres a lot of them right now, If so, is it possible to not send them to pending when creators edit the name or description to unsold NFT's? Just dont allow edits to NFTS that has an existing /active offfer. 


https://github.com/pellartech/curate/issues/513#issuecomment-1097484682
