### ISSUE TITLE
User's NFT is Lost

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#559]
User claims that his Minted NFT titled Moon and projectnakamoto has successfully been minted. But he can't find it any more in his account. 

The NFT Moon can be found in the user's account from the admin panel but can't find projectnakamoto

User: https://admin.curate.style/users/e77fc553030c3992fa25f3144ea660d84ac5
iOS v6

**Comment by eventang2015** [comment]
imported from other markeplace ? 
if not, can him re -create projectnakamoto ? I didn't find it .
