### ISSUE TITLE
User Can't Withdraw Using the QR Code

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#560]
User: https://admin.curate.style/users/756f0937c9c0cf5ceb973084ea7ef821ea7b

User tries to Withdraw XCUR through BSC

To reproduce

1. Go to account
2.  Go to Xcur > Click withdraw
3. Click the scan icon at upper right corner

User can get the scanner up but when he points it at the QR Code provided from either metamask ro kucoin, the phone just vibrates and closes the QR code scanner without entering the address

**Comment by pellarboss** [comment]
@madtocc please see if you can reproduce this issue

@Catherineanne91 if possible, please provide OS version and App versions

**Comment by Catherineanne91** [comment]
@madtocc  

Just got update from user

Device: iOS
App version: v7.1
hes using iphone SE 2020 version

**Comment by madtocc** [comment]
Thanks, @Catherineanne91. We have identified the issue and it will be fixed and shipped in the next update.
