### ISSUE TITLE
User Can Not  Register with his email 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#561]
User tries to register with an email:

filippo@perego-net.com

Error shows invalid email

See screenshot below
Note: user email is not registered in the app

![277826276_282393290750025_4089046939759158798_n](https://user-images.githubusercontent.com/93180831/161712365-169c02a9-3b44-454d-8493-7f4d1ad63f76.jpg)

**Comment by eventang2015** [comment]
can he use another email address ? gmail ,outlook,icloud etc..

**Comment by madtocc** [comment]
the character "-" is not allowed after the @. I can fix it on the next update. Meanwhile, we can create an account for him (and he updates the password and pin) or he can use another e-mail.
