### ISSUE TITLE
User can't buy XCUR with SOL (Android)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#562]
Description:
Error occurs when user tries to buy XCUR using SOL in app

To reproduce:
1. go to account
2. Click XCUR > buy xcur
3. Use: Choose SOL, enter amount and Review Purchase
Error occurs:

![Solana](https://user-images.githubusercontent.com/93180831/161961570-bb403eca-f0de-495f-aa90-94052eda839d.jpg)

User Email: jpbhanu@gmail.com
V7.0.2b148

**Comment by eventang2015** [comment]
@Catherineanne91 https://solscan.io/account/5ZktcHgmrXpeHBw7ZQNwujwnH28Mu6ABdkquZkG1ZAYt
seems there're 3 commits haven't synced.

**Comment by eventang2015** [comment]
https://admin.curate.style/accounts/db5931b3d1dcffa2386ee4607067f7b1c5de
added the 2 txns.
https://solscan.io/tx/4tfLxvZ94E7F1WA7v92uohN2WRTVP18Dm8pXJXyPTCbVrQ7SFLYaZkmAaTZzrsnP1S6epkv8sj4seY286meBKtu7
https://solscan.io/tx/qpMK32WRtNdNdU1bCHoDTLmJAEGLhqp3LjDny8cfjAXJugi319mDBwvzK7NirgyTYriuWr2krupAfvkzd5Sp34r
