### ISSUE TITLE
User Can't Buy XCUR in app or Deposit XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#563]
User can't buy XCUR and Deposit XCUR

User Email: soldrinksnft2021@gmail.com
iOS V7

To reproduce (Buying XCUR)
1. Click Account
2. Click XCUR
3. Click Upper right button, BUY XCUR
4. The app would show a blank page

![image (1)](https://user-images.githubusercontent.com/93180831/162076898-b3055574-843c-4745-8afd-2160de8eb898.png)

EXPECTED OUTCOME: The page should contain details as shown below:

To reproduce Depositing XCUR
1. Click Account
2. Clic XCUR > Deposit
3. The app does not show the wallet address, instead it shows "0"
see image below:

![SOL deposit](https://user-images.githubusercontent.com/93180831/162077091-1f57bdbd-b894-4965-90fa-e3302e290acd.jpg)

EXPECTED OUTCOME: the address should show below the QR Code

**Comment by pellarboss** [comment]
seems like the user abandoned registration mid way (hence the accounts were not fully created)
please ask the user to recreate an account
