### ISSUE TITLE
Users received notifications of Log-in Attempts

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#566]
Two users are receiving automated emails from Curate (see attached). But they both claimed that they have not tried logging in multiple times due to wrong log in details. 

baldwinp@mac.com
vlorand@gmail.com

These two users received the same notification
![image0 (3)](https://user-images.githubusercontent.com/93180831/162146134-3eb4f7dd-9edc-47a8-8488-03d3ab5bae13.png)

**Comment by pellarboss** [comment]
@Catherineanne91 this kinda means the system is working as intended
I would suggest users resetting their password following reset instructions on the web site
Users can also check their security details from the security log section in the app
