### ISSUE TITLE
Platinum Booster is not Working for A user's stake

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#567]
Platinum booster is not Working

User has a platinum tshirt NFT (3x) but Boost value shows 1

1. leeju09@naver.com
2. v7.0.2b148 Android
3. Platinum booster (x3)  

stake: https://admin.curate.style/stakes/3137e9ee04e4e130

![sd](https://user-images.githubusercontent.com/93180831/162148148-2c70abaa-72b2-4369-9533-4af10e3008c3.jpg)

![2 (1)](https://user-images.githubusercontent.com/93180831/162148160-bbc80fa7-b701-41c4-b47e-453ca471e4c9.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 it's been fixed in production for new staking. 
(I have ran reawards script yesterday， it's hard to adjust reward amount, so if he want a staking boost =3, can he stake a new one? )

**Comment by Catherineanne91** [comment]
@eventang2015 , Another Case


Stake booster does not work for user's stake

https://admin.curate.style/stakes/d134cb063a5f7992
Email:  gadithomason1@gmail.com

NFT stake booster: https://admin.curate.style/product/df4030ca7de43b4b8377ebf6/detail

**Comment by Catherineanne91** [comment]
@eventang2015 , Can we help this user unstake his current Staked amount? 
so he can use the funds for the new stake, this time with a working NFT booster
