### ISSUE TITLE
User Staking Info is Not Showing Accurate values

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#568]
User Staking Info is Not Showing Accurate values

Users staked amount is 	2577.41
bluemolson@gmail.com
https://admin.curate.style/stakes/ba24b22959f92b9d

But it showing 6746 XCUR
![2 (2)](https://user-images.githubusercontent.com/93180831/162163588-9be40d37-1821-4163-9416-0aba56b8b088.jpg)

Android
V7

**Comment by madtocc** [comment]
@Catherineanne91, I fixed this on last week's update, and iOS didn't receive it yet.
