### ISSUE TITLE
User's imported NFT shows bad quality in Curate App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#571]
User imported NFT but shows bad quality in the app

![Image from iOS](https://user-images.githubusercontent.com/93180831/162393783-07f1d229-d586-48c9-91b8-58b806112814.png)

Imported collection: 
https://admin.curate.style/collections/adca9c7d0bee74335d37a1fa
Username:  jehuty27@gmail.com

**Comment by eventang2015** [comment]
resolved.
