### ISSUE TITLE
Sold NFTs not published in Curate Twitter Bot

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#572]
User: https://admin.curate.style/users/61096b758786c27f9a5d2fe30d5f42dc502b
 Email: falezler2013@hotmail.com

His Sold NFTS: 
https://admin.curate.style/product/959026ca76267e0933a65cb6/detail
https://admin.curate.style/product/58eed3a1fd7659d7a3e5d958/detail

Did not appear in  Curate Twitter Bot when sold

**Comment by eventang2015** [comment]
i suppose twitter bot's limitation.
