### ISSUE TITLE
User deposit BNB into XCUR Address

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#573]
Help user recover funds: User deposit BNB into XCUR Address

Email david.debuck@hotmail.com

Txn hash https://bscscan.com/tx/0xc8f738c61b44509a96ecad0f883c36157e5336605737eb5bdc1085d18d74acb7

Amount 1.19bnb

refund wallet bsc address 0xDddcc9D25a306E75C504E6069005891adE79789c

**Comment by eventang2015** [comment]
@Catherineanne91 
sent : https://bscscan.com/tx/0x10ae7a3a6b8f96d9d13a7c465dde77fc0a3dbf908614206ed1cf6a858665618f
