### ISSUE TITLE
Update Tags and purchase option for Imported Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#574]
FOR METAHEROES COLLECTION:

1. Update tags in Exported Collection

Add tags to all NFTS in the Collection Metaheroes Club
Collection: https://admin.curate.style/collections/adca9c7d0bee74335d37a1fa

Please add the following tags:

Art
Collectables
Virtual WorldArt

2. Some NFTS only have "Make OFFER" option. 
Please make all NFTS have "BUY NOW" purchase option 

SOME NFTS: 

![277824814_691820315489385_5227999658784822693_n (1)](https://user-images.githubusercontent.com/93180831/162901294-eb5462da-471e-4eac-9615-8c6f90c88b3a.jpg)

HOW ALL NFTS IN THIS COLLECTION SHOULD LOOK LIKE:

![278048835_559140102278544_6116891923290302131_n (2)](https://user-images.githubusercontent.com/93180831/162901526-eea60679-fbb8-4c6a-91ae-9860efe6568f.jpg)

**Comment by eventang2015** [comment]
updated.
