### ISSUE TITLE
User Wants to Unstake Funds with NFT Booster

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#575]
A user tried to stake but the app wouldn't allow him to stake more than 50k
(April 8,2022)

When user tried to stake again  133825.5xcur (April 1102022) he was able to successful stake the amount

User's stakes:
https://admin.curate.style/stakes/5514c793f789976a
https://admin.curate.style/stakes/15727a1ae594cb07

User wants to unstake both active stakes and stake again with  133825+50000

Email: [lacic.bojan@gmail.com](https://admin.curate.style/users/b0873927ff89d1287e18d1adec4103f5f97f/detail)

**Comment by eventang2015** [comment]
@Catherineanne91  Done
