### ISSUE TITLE
Improve Filter in Search Tool

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#576]
Searching for keyword with applicable tags does not show results
For example: Searching for Metaheroes Collection NFT
1. Type Meta
2. Add filter with tags applicable to the collection
3. click search
None of the Metaheroes Collection shows in the result

Please watch video (skip to 0:51)

https://user-images.githubusercontent.com/93180831/163086563-5b4a6f54-75a3-4103-af7b-d70d36b8ddd2.mp4

**Comment by eventang2015** [comment]
@madtocc search tags?

**Comment by madtocc** [comment]
You are searching for the term "metaheros"
the name of the NFT is "metaheroEs" with an E

**Comment by pellarboss** [comment]
search only is made on whole word with the same spelling (not similar words)

**Comment by Catherineanne91** [comment]
@eventang2015 , @madtocc 
at 0:51 of the video

if search word is typed "META"

and set the filter to NFTS from ETH network + Filter (tags, virtual worlds, art, collectibles) - it is not working 
it should be able to show metaheroes since we already updated the tags for this collections:
https://github.com/pellartech/curate/issues/574
