### ISSUE TITLE
User's 60-day Stake rewards stopped issuing before end date

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#577]
Rewards stopped issuing after March 29 2022 (Last issue)
Stake is due to end on April 26 2022 but status said completed (it is a 60 day stake, created on Feb 24 2022)

Staked amount: 4000
Email:  ramis@live.ca

https://admin.curate.style/stakes/82f1c17e00b54de0

**Comment by eventang2015** [comment]
@Catherineanne91 the last staking event is ended,  James confirmed that.

**Comment by Catherineanne91** [comment]
Thanks Even.
