### ISSUE TITLE
How long do offers remain active for?

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#581]
This offer below is from 29th March.

Just curious how long offers remain active for?

I thought after 72 hours they get auto rejected?

![Screenshot_20220413-223318_CURATE.jpg](https://user-images.githubusercontent.com/51517619/163274181-85ab4215-7389-4777-b769-8081aa1396fe.jpg)

**Comment by eventang2015** [comment]
added in bot, offers expire after 72 hours.
