### ISSUE TITLE
User Cant Purchase XCUR with ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#582]
User email  teacher997@gmail.com
OS: android, V701b146

An error appears when user tries to buy XCUR with ETH 
Error shows: Error Request Timeout

To reproduce:
1. Go to wallet
2. XCUR
3. Buy Xcur
4. Choose ETH>Enter Amount>Review Purchase
5. Enter Pin to proceed purchase

**Comment by eventang2015** [comment]
@Catherineanne91 https://admin.curate.style/accounts/7cf5a7c1e7e1e3395551cc5c6f8c84510445
the user had a commit order on Apri 3rd.  BUT bot marked the txn failed.
it's now synced .
