### ISSUE TITLE
Xcur Staked and Stake Rewards are not showing in user's app

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#586]
User: d.g.eatmon@gmail.com
Description:
User's stake is not showing in his Staking Details
His latest Rewards is not showing (Last Issu date is April 13 2022)
Stakes: [https://admin.curate.style/stakes](url)

![unnamed](https://user-images.githubusercontent.com/93180831/163566159-d9ec3c24-6e14-4f09-b7bb-909931e12b22.png)

![2 (1)](https://user-images.githubusercontent.com/93180831/163566271-3fd22a6b-7812-45d8-8c22-1387aabba709.png)

OS: iOS V7.1

**Comment by eventang2015** [comment]
resolved
