### ISSUE TITLE
Staking bug on iOS?

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#588]
iOS device
App version: v7.1
App email: Michael.mendoza88@outlook.com

User has a 1.5x stake boost NFT but is only able to get 12% APY staking instead of 15%

Can you have a look please? 

![20220418_060104.jpg](https://user-images.githubusercontent.com/51517619/163757137-c8bc5a37-8e5f-471f-a541-39ae42f99251.jpg)

**Comment by eventang2015** [comment]
stake amount  =>500 and <1500, bronze tier, apy =12%

**Comment by TheOneXi** [comment]
Yes bronze is 12% APY but what about his 1.5x stake boosting NFT? Shouldn't this be 12 x 1.5 = 18% APY?

**Comment by eventang2015** [comment]
dailyInterest =( (stakeAmount + totalRewards) * stakeApy * stakeBoost) / 365

**Comment by TheOneXi** [comment]
Shouldn't it follow this rule:

tier APY * stake boosting NFT multiplier?

i.e 12% APY (bronze tier) * 1.5x stake boosting NFT (premium NFT stake boosting)

@eventang2015 @pellarboss

**Comment by eventang2015** [comment]
@curateproject the APY on the page = tier's APY.
will multiply by boost value in the calculation formula.
Formula :  ( (stakeAmount + totalRewards) * stakeApy * stakeBoost) / 365
eg: staked =1500, AYP=10% ,boost =1.5X
day 1 - rewards = (1500+0) *10% * 1.5 / 365 = 0.61643836
day 2 - rewards = (1500+0.61643836) *10% * 1.5 / 365 = 0.61669169
day 3 - rewards = (1500+0.61643836 + 0.61669169 ) *10% * 1.5 / 365 = 0.61694512

if boost = 1X 
day 1 - rewards = (1500+0) *10% * 1 / 365 = 0.41095890
day 2 - rewards = (1500+0.41095890) *10% * 1 / 365 = 0.41107149
day 3 - rewards = (1500+0.41095890 + 0.41107149 ) *10% * 1 / 365 = 0.41118412

and you will find :  0.61643836/0.41095890 ≈ 0.61669169/0.41107149 ≈0.61694512/0.41118412 ≈1.5

**Comment by TheOneXi** [comment]
I see if the calculation needs to be simply the APY of the tier multipled by the stake boost NFT

Thoughts @pellarboss ?

**Comment by pellarboss** [comment]
the math is right 

the same math is used in the calculator / table

the calculation is
APY x TIER - we are aligned with you on this
just divided by 365 to get the daily rate (since we issue daily)

the first part just takes in to consideration the principle and the past reward (compound)

**Comment by TheOneXi** [comment]
Hi @pellarboss I understand the math is right, I'm just wondering if we can display a message on the staking page to explain this. As you can see from the users question below it's kinda throwing me, i'm not sure what to reply, any ideas what we can do Roy?

From user:
_Quick question: if you get the standard 10% staking and apply the 1.5 boost from a curate NFT, would the new APY be 15% Or is my math wrong?
I ask because I’m currently staking with a 1.5 boost and it says I’m staked at 12% (see pic below):_

![O9JwCnN_](https://user-images.githubusercontent.com/51517619/164544730-fe0556a8-c80b-4a29-bbe3-76995e87f208.png)
