### ISSUE TITLE
User's Active Stake is not Showing Current Stake on XCUR Staking page

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#589]
Stake: https://admin.curate.style/stakes/c47c703f7fa729ca
user email: gonzaloalonso241101@gmail.com

![received_1358293454596686](https://user-images.githubusercontent.com/93180831/163781382-f3ce1572-2230-45b7-a0ca-90d5f1b6882e.jpeg)
![received_388889683095362](https://user-images.githubusercontent.com/93180831/163781392-10a55300-03e1-4521-86ea-d62ead0cd1a1.jpeg)

Staked amount L 204.89 xcur

**Comment by madtocc** [comment]
@Catherineanne91 please ask the user to check the My Stake now. 204.89 is supposed to show now for this user.

**Comment by eventang2015** [comment]
@Catherineanne91 confirmed ?

**Comment by Catherineanne91** [comment]
user confirmed. thanks
