### ISSUE TITLE
BUG? XCUR purchases using ETH

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#59]
Tried purchasing XCUR using ETH but a few issues and tweaks to be made please:

Balance doesn't update with new XCUR tokens - if we waiting for a sync can you put a notice message there so the user knows to wait or like a pending tx on transaction history

**Comment by curateproject** [comment]
Also the preview and final confirmation had different amounts of XCUR as attached, can you try to make these either identical or add a notice message that actual amount will vary when getting a live rate etc
![Uploading Screenshot_20210629-000728.jpg…]()

**Comment by curateproject** [comment]
![Screenshot_20210629-000758](https://user-images.githubusercontent.com/51517619/123716430-74a87300-d872-11eb-96f1-86f3e9ecf828.jpg)

**Comment by pellarboss** [comment]
your purchase is now successful
https://admin.curate.style/commits

linking to #44 for confirmation messaging
