### ISSUE TITLE
Transfer an NFT to a User's Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#590]
Transfer the NFT:
https://admin.curate.style/product/edc1c4dd609d98939b297ae5/detail

To this Collection:
https://admin.curate.style/collections/86c1145695dcf0d07f29624b

Email: prantik.sonu@gmail.com

**Comment by eventang2015** [comment]
updated

**Comment by Catherineanne91** [comment]
Thank you even
