### ISSUE TITLE
Add logo on Trustwallet for new BEP20 Token

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#593]
Can you update our logo on Trustwallet for the new BEP20 XCUR token:

Our new BEP20 token:
https://bscscan.com/token/0xd52669712f253cd6b2fe8a8638f66ed726cb770c

Trustwallet logo procedure:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by madtocc** [comment]
please review @curateproject @pellarboss 
https://github.com/madtocc/assets/commit/163cf7d15fbfab799d94c391443f39228a111bf8

**Comment by TheOneXi** [comment]
Yes working great thanks
