### ISSUE TITLE
User's Royalty Changed from 2.5% to 0.03%

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#594]
This NFT's royalty was changed (unintentionally, by admin) from 2.5% to 0.03%. Now, the admins have set it back to 2.5% but have already sold a product with a royalty of 0.03%. 

Can we send the user the royalty he should have received at 2.5%? 

Email: juniargayuhc@gmail.com
product: https://admin.curate.style/product/3dc391a340a33338dfb66916/detail

**Comment by eventang2015** [comment]
how much ? send him from master account?

**Comment by Catherineanne91** [comment]
Owner keyy:478b97c9f1ba27b053e53073e7347472c064

1st Sale:
Sold Date: Nov/06/2021 12:56:39  
Price: 5
Royalty - 0.025
Executed Royalty Royalty - 0.52% 
Expected Royalty - 2.5%
To refund: 0.125-0.025  = 0.1

2nd Sale
Sold Date: Nov/06/2021 12:56:39  
Price: 50
Royalty - 0.015
Executed Royalty Royalty - 0.3% 
Expected Royalty - 2.5%
To refund: 1.25-0.015 = 1.235

3rd Sale
Sold:Apr/14/2022 09:57:05 
Price 350  
Royalty - 0.105, 
Executed - 0.03%  
To refund:  8.75-0.105 = 8.645

TOTAL FOR REFUND TO THE USER  = 9.98 XCUR

**Comment by eventang2015** [comment]
sent 9.98 
https://scan.curate.style/txn/4850222f865a5b61ac5c31c1557ec41e3e3a4cd8870b247e7d6239b705c9ba5b
