### ISSUE TITLE
Refund user for cost incurred when minting on ETH chain

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#595]
NFT was Minted on ETH Chain, Initially Approved by Admin but Changed to Denied Status due to Copyright Reasons.

Owner: https://admin.curate.style/users/e77fc553030c3992fa25f3144ea660d84ac5

NFT:
https://admin.curate.style/product/677389d1be54632efe9946d4/detail

Please refund user for the fees incurred when minting on ETH

**Comment by eventang2015** [comment]
@Catherineanne91  refunded. https://scan.curate.style/txn/ea7a1bf311f50552a9b024205bccf669a4f7ba533bb51c52c0f6c18ccae27062

**Comment by Catherineanne91** [comment]
thank you
