### ISSUE TITLE
Users Staking Rewards are not Updating Daily

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#597]
Users Staking Rewards are not Updating Daily

**User no. 1**
Issue: Rewards are not showing/updating daily, last reward was on April 22, 2022

create date: April 21 2022 - 957 xcur - https://admin.curate.style/stakes/9af8b4c4155b1f8e
Create date - APril 21 2022 - 523 xcur -https://admin.curate.style/stakes/289a3f6e77e312c4

Email:  mario.dragicevic7@gmail.com

**User no.2**

Rewards stopped showing since April 19 2022

Create date: April 13 2022 - staked amount -	184136.72 https://admin.curate.style/stakes/684080c027eb1c64
Email: lacic.bojan@gmail.com

**Comment by eventang2015** [comment]
@Catherineanne91 this ticket is done.
