### ISSUE TITLE
Purchase NFT does not show in the User's Account

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#598]
Purchase NFT does not show in the User's Account

User A purchased Style of Skul #201 NFT.
In the Admin panel Ownership Logs, it shows UserA is the current owner
Transaction is shown below:

![Screenshot_20220424-140603](https://user-images.githubusercontent.com/93180831/165096096-1be1312b-176a-4163-a294-97534b29c6c7.png)

However, in the Curate app, it shows that Style of Skul #201 is owned by another User B

NFT: https://admin.curate.style/product/4c90df8cdd6579a6cda20907/detail
User A:  jy_inv@hotmail.com
UserB:  mmm265418@gmail.com

User A details: 
App version: v7.1.2b156
Operating system: Android

**Comment by eventang2015** [comment]
@Catherineanne91  the 2 orders purchased at the same time, 2022-04-24T13:00:09.469Z VS  2022-04-24T13:00:09.479 I will refund the second order.

**Comment by eventang2015** [comment]
refund txn for user [mmm265418@gmail.com](mailto:mmm265418@gmail.com)  https://scan.curate.style/txn/bce1672a20aa9b93c9263513f24dd21119e2278e85ca2cef230eba8a1a87cec3

**Comment by Catherineanne91** [comment]
refunds received
