### ISSUE TITLE
User has not received funds from his trust wallet (BEP20 transfer)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#599]
eyadmahmood33@gmail.com
v7.1.2b156 Android

User withdraw 10 xcur to his trust wallet and has not received the funds yet (BEP 20)
Shows completed in the app:https://scan.curate.style/txn/2df0506297b76824dd78a5b527c9b26e4e3f36fe8d6b970fd29bbc722bd2b253

Transaction Hash: 0xbfef30229af85af248e1af355ea3f8f8104249754c7db6162602fb8ed1e4f3d7

Trust wallet Address:  0x9cc3990F39F457807323389150B763CB37Bc192A

**Comment by eventang2015** [comment]
it's completed~!?
https://bscscan.com/address/0x9cc3990F39F457807323389150B763CB37Bc192A#tokentxns
