### ISSUE TITLE
Error Appears when Purchasing USDCthrough Moonpay

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#600]
Email ste.huang3@gmail.com
v7.1.2 ios

The following error shows when User tries to deposit usdc through Moon pay
![image0 (1)](https://user-images.githubusercontent.com/93180831/165098039-169bf8a6-c707-4308-891f-445e9644e557.png)
![image1 (2)](https://user-images.githubusercontent.com/93180831/165098044-02b62936-e935-4dd5-bd59-8109aae5c75b.png)

**Comment by Catherineanne91** [comment]
@pellarboss , @eventang2015 

Same error with Circle Credit Card Deposit

https://user-images.githubusercontent.com/93180831/165249298-246dc20c-c30e-4136-8d56-08be2e24a818.mp4

**Comment by madtocc** [comment]
we had a problem in the app that was fixed already regarding the USDC account. However, the Apple version didn't receive this fix I will submit an update to fix this. 
I'm pushing an update to iOS store. On iOS it will only work after the update.
