### ISSUE TITLE
Include Commission Fee in NFT Refund

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#607]
Include Commission Fee when executing refund through the Admin panel 

![refund button](https://user-images.githubusercontent.com/93180831/166164362-5bd4e7a6-48e5-44c9-8e8b-a406c88a4329.jpg)

**Comment by eventang2015** [comment]
will refund commission fee ,royalty fee and rewards now.

**Comment by Catherineanne91** [comment]
Thanks @eventang2015
