### ISSUE TITLE
User Can't Sell nor Update an NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#608]
Issue: 
User can't do any operation for this specific NFT: , update, sell, etc.

NFT: 
https://admin.curate.style/product/5de6d7d5992a9b26d7b542e0/detail

Owner key:
a7214b914c10b4b0557cefb36526964d57bd

Verios APP 7.1.3b157 iOS
Tel Apple Iphone 12 pro

![SCur3](https://user-images.githubusercontent.com/93180831/166198351-0e82322f-1f25-442c-a3a6-ff90b7402ced.jpeg)

**Comment by eventang2015** [comment]
@madtocc owner can resell and update item in app?

**Comment by madtocc** [comment]
Yes. Not sure why the owner options haven't showed up for this user 🧐

**Comment by Catherineanne91** [comment]
What do you suggest we can tell the user? Can we just ask him to reupload?

**Comment by madtocc** [comment]
Tell him that we are investigating and will fix this.. We will try to fix this and will let you know once resolved

**Comment by Catherineanne91** [comment]
Thank you @madtocc , this bug is only for this NFT though, no other reports with the same issue
