### ISSUE TITLE
Creator wants to remove the soldout collection from his Profile

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#610]
User wants to Hide the Collection from his Profile (the NFTS from this collection has already been sold out)

He does not want it to appear from his profile anymore. 

The Collections:

https://admin.curate.style/collections/d87dbd021fac07429c7d1191
https://admin.curate.style/collections/3ea837a30430ab741011651b
https://admin.curate.style/collections/08a0fc4f63648344e1dde4f0
https://admin.curate.style/collections/8ea8c069ecd3d86ff960d2ba

![279388932_523245752676886_1505216742248744414_n](https://user-images.githubusercontent.com/93180831/166876441-77eea27e-adac-457e-8d76-b37be671a990.jpg)

USER: https://admin.curate.style/users/02f2c9a0a1a313adfeb37d3e589b5de771f4

**Comment by eventang2015** [comment]
assigned owner = null
