### ISSUE TITLE
Rewards not released past Stake End date

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#612]
Email: se7s2000@gmail.com
Stake Details: https://admin.curate.style/stakes/0062512921ed6289

Note: User claims that he did not enable auto-renew (Cant confirm this from the admin panel)

Stake End date: May 5 2022

**Comment by eventang2015** [comment]
@Catherineanne91 this stake should be unlocked tomorrow. the rewards were interrupted for a few days. I will keep an eye on it.

**Comment by Catherineanne91** [comment]
Other users whose funds are still locked past scheduled end of stake


muthamizh87@gmail.com 
https://admin.curate.style/stakes/b1240577d6c536b0

gadgetgadget070@gmail.com
https://admin.curate.style/stakes/dc6be85c5532fc2a

bluemolson@gmail.com
https://admin.curate.style/stakes/2007fbea511f65e7 (DUE TO END TODAY)

limamdahi1@gmail.com
https://admin.curate.style/stakes/70ec912049b1c7f8
