### ISSUE TITLE
User can't unlock XCUR after Cancelled Offer

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#613]
User cancelled all his 3 offers on different NFTs. Instead of getting 35 XCUR he only received 15 XCUR
Email:  tariqmalik1938@gmail.com

https://admin.curate.style/product/c5c0a1eec64921b94a1c8cd3/detail
OFFER: 5 XCUR

https://admin.curate.style/product/2deb6d6f487cf02d1481c6e5/detail
OFFER: 10 XCUR

https://admin.curate.style/product/e978a5f9c14cbf6870b80e19/detail
OFFER: 20 XCUR

**Comment by eventang2015** [comment]
@Catherineanne91  unlocked for him.
