### ISSUE TITLE
Set a Minimum Price for NFT's

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#614]
The following NFTs are sold for 0 XCUR where buyers get purchase rewards for spending nothing. 

There should be a minimum price of at least 5 XCUR ( both for fixed price and minimum Bid should not be allowed to be zero XCUR)

https://admin.curate.style/product/fb4d8413433d07af066d2977/detail

https://admin.curate.style/product/878913cbf1fc1c26c604ef79/detail

**Comment by eventang2015** [comment]
fixed. using the Mint Min Amount = 10 in settings.
