### ISSUE TITLE
Set listing prices in USD 

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#616]
As the price of XCUR is very volatile (causing our seller to adjust their price of NFTs on sale) can you replace the XCUR price listing with USD 

i.e on the mint page when listing an item for sale for auction or buy it now can you change the price currency from XCUR to USD

Thanks

**Comment by eventang2015** [comment]
fixed. using the Mint Min Amount = 10 in settings.

**Comment by eventang2015** [comment]
@madtocc implemented usd_price in staging
