### ISSUE TITLE
User accidentally sent ETH to his XCUR address

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#617]
User accidentally sent ETH to his XCUR address
Email: [aaronwillis@bigpond.com](mailto:aaronwillis@bigpond.com)
Transaction link:
https://etherscan.io/tx/0x3ea5a6f98e64bb4f47a6a0133e9e266cfcd5d72434b246bcac7c50e4734387aa
Amount:  0.55 ETH ; 19:56 AEST on the 06/06/2022
XCUR Wallet address:  0xa69d5Ab276121747c2f6487f98B81ED8aBF59A4b

Can we retrieve his funds?

**Comment by eventang2015** [comment]
sent back https://etherscan.io/tx/0x64df0eb01b0c7211e8b7ba5056176358fb6641eb2dbb47418ae0dbe442832b1d
