### ISSUE TITLE
Curate Dashboard is not Updating

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#618]
Its been showing thesame values for days both in admin panel:

https://admin.curate.style/
dashboard.curate.style

![dashboard 1](https://user-images.githubusercontent.com/93180831/167552561-bc05675a-2a52-4dd0-8cf6-4ef5df31d2cf.png)

**Comment by eventang2015** [comment]
rebooted bot and now it works.

**Comment by Catherineanne91** [comment]
Thank you , @eventang2015
