### ISSUE TITLE
Lost all NFTs in-app wallet with update v7.2

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#619]
**Describe the bug**
Updated the app to the latest android v7.2, and all NFTs in my wallet have disappeared. 

**Screenshots**
![](https://files.slack.com/files-pri/T01SARMTAQP-F03EA4QRM71/screenshot_20220509-163520_curate.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Andriod 12

**User ID**
joeverlaque@gmail.com

**Comment by eventang2015** [comment]
https://admin.curate.style/users/01877dc13e1e133948f738a13e2d64885198
some locked this user ? 
his NFTs all denied.
https://admin.curate.style/products/user/0d130b05f6fb7b18d8887755e454bda9be1b/nft
do you want me reset them to approved? @TheMad-J-Hatter  @Catherineanne91

**Comment by eventang2015** [comment]
is the user one of you ? I see James updated this user as an admin , then locked and unlocked the user.

**Comment by TheMad-J-Hatter** [comment]
Thank you @eventang2015 , issue is fixed and yes the user was me. 

All is working now.
