### ISSUE TITLE
[SYSTEM] Consolidate ERC20 XCUR

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#62]
to discuss process on consolidating ERC20 to master

**Comment by pellarboss** [comment]
Objective:
- get xcur in to master 
- use lower gas fees
- only do this for worthwhile accounts

Proposed
- manual process, running on demand, for example, run it weekly, and if good / needed, run it more often
- only do this for accounts with more than ## xcur <- Moe suggest amount
- master ETH account pays for gas fees

Fundflow
- master ETH sends ETH to user account, ETH amount = how much it costs to send ERC20 + ETH fee
- user account sends XCUR to master XCUR = exhaust ETH fees

**Comment by DefiHunter** [comment]
Thoughts on a 10 XCUR minimum ? my thinking is anything below that can be circled back to at a later date. maybe in a mass clean up . 

Im happy with the fund flow

**Comment by DefiHunter** [comment]
To determine -

Use lowest possible gas fees and slowest speeds

**Comment by DefiHunter** [comment]
In a future update we should automate this
