### ISSUE TITLE
Error when withdrawing USDC

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#620]
Error occurs when trying to withdraw USDC to external wallet

to reproduce:

1. Go to wallet
2. Click usdc
3. click withraw
4. fill in external usdc address and amount to withdraw 
5. click verify withdraw
6. follow verification prompts

Error shows:
![photo_2022-05-10_19-39-23](https://user-images.githubusercontent.com/93180831/167718019-b25fd6d9-9ecd-4acd-af17-33deef4684de.jpg)

**Comment by eventang2015** [comment]
rebooted bot and synced master's balance.
