### ISSUE TITLE
User Can't buy XCUR with SOL

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#621]
User Can't buy XCUR with SOL

To reproduce:

1. Go to wallet
2. click xcur > buy
3. Choose Sol
4. Enter. amount > Review purchase
5. Follow verification prompts

Error shows:

Internal Server Error

Android 
V712b154
[gavinjones2020.tinder@gmail.com](mailto:gavinjones2020.tinder@gmail.com)

**Comment by eventang2015** [comment]
https://admin.curate.style/accounts/59dec111eb31d727f076fd2492ae13606f5f
https://solscan.io/account/4xuRfNDDWMBMBgA2DPgf8vigJJ9ws4kvg9QQ6SsYHZ4j
his has no balance
