### ISSUE TITLE
User Can't Log in the App (Not Blocked on Admin panel)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#622]
User can't log in the app (not blocked on Admin panel)

User receives a prompt that he is locked from using the platform 

Not locked in the Admin panel

User: https://admin.curate.style/users/73c81003a8e18c599d86d892c6f2a99ed108
![unnamed](https://user-images.githubusercontent.com/93180831/168009507-1616e05a-3c4b-43e2-8a53-27b7b954c721.png)

**Comment by eventang2015** [comment]
he logged in recently.
