### ISSUE TITLE
Error when Trying to Accept an OFFER

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#623]
THe following error shows when a user tries to accept an offer on his NFT:

Users with similar problem:
benschachts@gmail.com
pandaverse26@gmail.co
![2](https://user-images.githubusercontent.com/93180831/168009968-770ddda2-633b-4bae-9385-4d9c61655f90.png)
m

**Comment by eventang2015** [comment]
@Catherineanne91 can you let the users try again ? just pushed to production.
