### ISSUE TITLE
The App Displays "SERVER ERROR" when User Tries to Log in

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#624]
The information needed:
Email App:
[maheralsiddiqi.coin@gmail.com](mailto:maheralsiddiqi.coin@gmail.com)
Version App:
V7.2
Mobile Device:
Android - Huawei Mate 20 Pro

USER Cannot log in the app , it shows the error below:
![2 (4)](https://user-images.githubusercontent.com/93180831/168227534-368010b5-2ec6-4478-b728-4c6b0b6ccec7.jpg)

NOTE: User is registered in the app, no lock/strikes

**Comment by eventang2015** [comment]
@Catherineanne91  can you let the user try again and log the login time ? 
I can check logs and feedback.

**Comment by Catherineanne91** [comment]
Another user experiencing thesame problem.


Same problem 
07.57 AM
04:57 utc
mhr9900@hotmail.com



No response from
[maheralsiddiqi.coin@gmail.com](mailto:maheralsiddiqi.coin@gmail.com)

**Comment by Catherineanne91** [comment]
vasibshaikh179@gmail.com  - another account
![Screenshot_2022-05-15-17-51-12-11_328ee62e69e3c4a023eeeb2fbe723d58](https://user-images.githubusercontent.com/93180831/168739602-e0ed497b-158e-4fe4-8173-2963cd15d53c.jpg)
