### ISSUE TITLE
Diamond Tier user not showing correct Tier and Commission rate on Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#626]
email: muthamizh87@gmail.com
Amount in wallet:  67975.54480783
locked:  23411.82127486
Tier: Diamond

Issue: App shows the user is Tier platinum with 1% comission fee 

User:  leeju09@naver.com 
Tier: Diamond

Issue: His wallet shows he is platin

**Comment by eventang2015** [comment]
RE: 
Tier: Diamond , required  tokens:25000 
so [muthamizh87@gmail.com](mailto:muthamizh87@gmail.com) tier: Diamond is correct.
