### ISSUE TITLE
User's stake still locked after 30 Rewards

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#627]
User:  su93r3pico@gmail.com
Staked: 2199.46

Stake has completed 30 rewards last May 12 (4 days ago) and funds are still locked:

https://admin.curate.style/stakes/794c70ee0eac49f6

**Comment by eventang2015** [comment]
unlocked for him.

**Comment by Catherineanne91** [comment]
unlocked - confirmed with user
