### ISSUE TITLE
Refund Buyers from Physical Goods Marketplace

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#628]
The following users needs to be refunded as they made an order before the prices were updated. 

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/93180831/168855206-6ef21f73-09ca-422b-9092-2f0c7dbbc21b.png">

Amount in XCUR to be refunded beside their email: 

cwebb02+curate@gmail.com -- 12.5 
tuan.h.thach@gmail.com -- 25
kagan.cbci@gmail.com -- 12.5
nisab1104200@gmail.com -- 25
tuan.h.thach@gmail.com -- 25

**Comment by eventang2015** [comment]
done
