### ISSUE TITLE
Send  $50 in XCUR  to 20 Giveaway Winners

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#629]
https://twitter.com/curateproject/status/1526156902773792768?s=20&t=lZ6v6j1b31eIAuVq4bsVVQ

Please Send $50 worth of XCUR to the following users:

@Augustine_Block-augustineblock001@gmail.com

@OrilionNFT - ilovemjjackson23@gmail.com

@styleofskull -  juniargayuhc@gmail.com

@manowar1995 - alammanowar7@gmail.com

@NetbitNFTs - captainbits@gmail.com

@ReliveCurate -Krisrobin.kr@gmail.com

@TheShermi -shertrades@gmail.com

@baskentliemre06 -baskentliemre06@gmail.com

@MykePayn3 - mykedj123@gmail.com

@VAM_PUNK - khoirul270702@gmail.com

@halikarnas001 -akincinuh@hotmail.com

@BeastCryptoPunk - have not reached out yet

@crypto_jannie - have not reached out yet

@PandaneseNFT -  pandaverse26@gmail.com

@The_cyb1 - achmadfaizin86@gmail.com

@cryptounicorn13 - neeraja.anandamyle@gmail.com

@mugengang -vhio1526@gmail.com

@IshaanYaduvir - jpbhanu@gmail.com

@DatDudeDoza - Michael.Mendoza88@outlook.com
 
@2basiic - davidtipan1@outlook.com

Note: I will add e-mails of users once they DM curate support twitter for their email addresses

**Comment by eventang2015** [comment]
done, sent 376 XUCR to the above users

**Comment by Catherineanne91** [comment]
@eventang2015 

please add these two more winners

sandeep15sharma2001@gmail.com
sandeep29sharma2001@gmail.com

**Comment by eventang2015** [comment]
> @eventang2015
> 
> please add these two more winners
> 
> [sandeep15sharma2001@gmail.com](mailto:sandeep15sharma2001@gmail.com) [sandeep29sharma2001@gmail.com](mailto:sandeep29sharma2001@gmail.com)
@Catherineanne91 sent
