### ISSUE TITLE
 User can can't proceed with Circle USDC Deposit

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#630]
When trying to deposit USDC via Circle,
User can't type anything on the app when it opens the bank log in page. 
![2 (5)](https://user-images.githubusercontent.com/93180831/168922620-7c754fa2-14cd-4ab6-b036-17c85246aa71.jpg)

[grazvydaspp@gmail.com](mailto:grazvydaspp@gmail.com)

**Comment by eventang2015** [comment]
@madtocc can you take a look ?  issue of webview ?
