### ISSUE TITLE
 User  can't proceed Exporting Solana NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#631]
User: homerread@gmail.com
User Can not Export to Solana Wallet

User tries to export the ff NFT:
https://admin.curate.style/product/6f9d37e20d2a02c08f1a27d8/detail

To reproduce:
1. Go to NFT above
2. Click "Export NFT"
3. Select "Solana"
4. User pastes Solana wallet address
The app shows:

"Export product failed"
![Screenshot_20220516-151334](https://user-images.githubusercontent.com/93180831/168924943-68462582-974d-4576-845d-4a2f1fc11c9a.jpg)

![Screenshot_20220516-151336](https://user-images.githubusercontent.com/93180831/168924955-226c0ff8-7028-4286-8631-97c5c5475a65.jpg)

**Comment by eventang2015** [comment]
it's a not solana NFT, I'll check the chain in code.
