### ISSUE TITLE
User Can't Purchase XCUR with ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#632]
User Can't Purchase XCUR with ETH. To reproduce:

1. Go to wallet

2. Click XCUR > Buy XCUR

3. Select ETH > Enter amount ETH to use for XCUR purchase

4. Click REview purchase

5. Click Verify Purchase

Error Occurs:

"Type 'Null' is not a subtytpe of type 'String' in type cast"

User: Tangle_wood123@yahoo.co.uk

https://user-images.githubusercontent.com/93180831/168978754-47e2752b-8e45-459a-9977-8aac64fd7ff1.mp4

**Comment by eventang2015** [comment]
@Catherineanne91 should be insufficient balance in eth wallet，I aligned his eth balance.
https://etherscan.io/address/0x7478565f63a10985f5578a43925a4b8d7e351849
https://admin.curate.style/accounts/1df77e5a18c890f9b316152b1131d60e27bf
