### ISSUE TITLE
In-app Governance

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#633]
**Describe the feature**
This is the new and much requested, Governance section within the Curate app. This will allow in-app users to vote on proposals set by Curate or Diamond Tier XCUR holders and give Curate the ability to fund community-based decisions from our community governance reserve.  

**Expected behavior**
To vote, users must be Bronze level or above and votes will be based on the amount of XCUR a user holds. 100 XCUR = 100 Votes, 10,000 XCUR = 10,000 votes. 

You must be Curate or Diamond tier to propose a vote. This proposal will most likely need a space in the admin panel for Curate to manage, amend and approve if required. 

Proposals will be open for 15 days and during this time, any new XCUR coming into accounts will not be allowed to be included in the vote. i.e. If a user has 10,000 on the day the proposal is launched, and deposits another 5,000 XCUR within the 15-day period, their vote strength will only be 10,000. This is to stop users from voting, withdrawing, and depositing to another account just to vote again.

**Screenshots and UI**

https://www.figma.com/file/7K8McIi4ZqToPLn2f1pLEF/Curate-v4?node-id=5147%3A14008

https://user-images.githubusercontent.com/88379508/169081614-b0843546-4dd7-47d0-a7b4-08f4ee443edb.mov

https://user-images.githubusercontent.com/88379508/169081642-4301929d-44b5-4cfb-83b3-b7f82f992f0e.mov

**Additional context**
The tiers will require updating as the XCUR price is drastically different now. This will be a different logged issue.

**Comment by TheMad-J-Hatter** [comment]
Hi @pellarboss, please can you provide us information on where the Governance development is currently? 

When can we expect to test this new environment? I'm hoping that the development will be finished end of Q3. 

Please confirm.

**Comment by pellarboss** [comment]
> Hi @pellarboss, please can you provide us information on where the Governance development is currently?
> 
> When can we expect to test this new environment? I'm hoping that the development will be finished end of Q3.
> 
> Please confirm.

we have not yet started on this feature, will aim to start this next week

**Comment by TheMad-J-Hatter** [comment]
Thanks for the update @pellarboss. 

Please let me know if you require anything else from ourside.

**Comment by eventang2015** [comment]
@TheMad-J-Hatter can you clarify this ?
1. create governances in admin site
2. list governances in app
3. voting in app 
4. You must be Curate or Diamond tier to propose a vote >  is it related to available balance or staking amount ？
for example , diamond level 
```
{
    "key" : "5c53d54f4573b1c8",
    "level" : 6,
    "tier" : "diamond",
    "required_tokens" : NumberDecimal("25000"),
    "apy" : 20,
    "voting_rights" : true,
    "proposal_submission_rights" : true,
    "commission_fee" : NumberDecimal("0"),
    "created" : ISODate("2022-03-25T08:53:49.692Z")
}
```
5. transfer xcur to ?

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015, apologies for the late reply. 

1. Correct, we will need a governance section in the admin panel that allows us to create each section of the governance proposal. I.e. Title, options, descriptions for those options, etc. Everything we'd need as per the figma design.

2. Correct, governances will be shown in-app

3. Correct, voting will also be done in-app

4. Correct, you need to be a Diamond tier user in order to propose a vote. There will be a cost associated to proposing a vote as well. This will prevent submitting several proposals. The diamond tier user will be able to propose based on available and staked balance. 

5. Transferring what XCUR? 
- XCUR paid for the proposal should be sent to Curate official account. 

Please note: 
A user can only vote with their available balance from the date the proposal went live. Any additional XCUR deposited into any account after the proposal went live will not be counted. This is to stop people from withdrawing and depositing in a different account to vote again and manipulate the result.
