### ISSUE TITLE
User Can't Deposit USDC through MoonPay

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#634]
User Can't Deposit USDC through MoonPay

I'm on IOS version 7.2.0b160
Email: nonregla@gmail.com

User is promoted with this message when he tries to buy USDC from Moonpay.
![unnamed (1)](https://user-images.githubusercontent.com/93180831/169461372-f23f9e48-5c7b-4fbf-a605-ac1a7bd43e2b.png)

User has pending orders from his bank account
![unnamed](https://user-images.githubusercontent.com/93180831/169460858-d9a4a776-d803-4484-973c-15ac3c364f60.png)

**Comment by eventang2015** [comment]
should deposit USD to master account : 0x03D3049c50a2dDeD5425717e3cec338AE5542EeB
