### ISSUE TITLE
User's stake is completed but funds are still locked

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#635]
Amount: 1614.26
user: mrcook804@gmail.com
Stake: https://admin.curate.style/users/b6bbf179efc11dcc688413a6414640409fdb/detail

**Comment by eventang2015** [comment]
staking is completed yesterday.
https://admin.curate.style/accounts/0fdf2873398653f128b500317a770f78c8f8

**Comment by Catherineanne91** [comment]
@eventang2015  i checked with the user, 

he said in an email today that only 800 is unlocked

however it appears that its all unlocked from the admin panel

https://admin.curate.style/users/b6bbf179efc11dcc688413a6414640409fdb

**Comment by eventang2015** [comment]
I unlocked the 2 completed stakes amount  for him.
