### ISSUE TITLE
User can't withdraw ETH to his external wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#636]
User can't withdraw ETH to his external wallet

User: alialmuqbali@gmail.com
Amount: 3 ETH

User have tried several times but the funds bounces back to his curate wallet

https://admin.curate.style/users/8b5f3dc9bc017600919d00e4811811034a55

**Comment by eventang2015** [comment]
there're 2 commit orders failed by bot, I reset them to pending.

**Comment by eventang2015** [comment]
the 2 commit orders are completed .

**Comment by eventang2015** [comment]
https://admin.curate.style/accounts/0b6ff99ca9e8f5ff61b3d877f0e58ba4f981
