### ISSUE TITLE
10% Deposit bonus still locked after deadline!

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#637]
**Describe the bug**
It appears that the 10% deposit bonus has not been unlocked for many if not all users included in the migration snapshot. This is a matter of priority as we have already had backlash for the XCUR not being released on time. 

**Screenshots**

![](https://files.slack.com/files-pri/T01SARMTAQP-F03H11ED24W/smartselect_20220526-204403_curate.jpg)

**Comment by TheMad-J-Hatter** [comment]
![SmartSelect_20220526-204403_CURATE (1)](https://user-images.githubusercontent.com/88379508/170618699-f0444dcf-9987-40fb-bb52-27cd35eaf9e7.jpg)

**Comment by eventang2015** [comment]
@TheMad-J-Hatter we have issued bonus, please note.
