### ISSUE TITLE
User's Deposit Via Circle Did not Arrive

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#638]
The user used circle to buy 250 usdc, but they never arrived, yet the amount was taken from his bank account
Did not arrive to his wallet yet:

https://admin.curate.style/accounts/e2ab1360ee471fc2820359204ac76243353f

User:
https://admin.curate.style/users/0740746316924703dfb90aa3d43d6db6f097
Mhr9900@hotmail.com

Android v7.1.2b1

![photo_2022-05-27_20-40-48 (1)](https://user-images.githubusercontent.com/93180831/170919826-c9e3b193-f327-4061-8e70-394de59d8939.jpg)

**Comment by eventang2015** [comment]
resolved.
