### ISSUE TITLE
Whitelist User (Submitted ID for Verification)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#639]
User: neeraja.anandamyle@gmail.com

User has been blocklisted automatically by our security. She has already submitted ID and self-photo for verification. 

Please whitelist user

**Comment by Catherineanne91** [comment]
User  IP Address:  151.254.241.227

**Comment by doles2** [comment]
Added user's IP address to bypass the Country's blocking

@Catherineanne91 - please ask the user to check

**Comment by Catherineanne91** [comment]
neeraja.anandamyle@gmail.com - is unblocked on JUne 1  but now blocked again 

@pellarboss @doles2

**Comment by doles2** [comment]
I have attempted to fix, we should consider unblocking the country, if it is safe to do so @Catherineanne91
