### ISSUE TITLE
Add Terms of Service section

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#64]
Can you add a terms of service section in the app, add the following text please:

Terms of Service:

1.No explicit content or nudity in bad faith.

2. No counterfeited content. If you own an NFT you need to send it to your wallet, in order to respect the artist’s work and not double sell.

3.Regular pictures that lack artistic skill and quality will be denied upon submission in order to reward real artists and have a healthier marketplace.

4. Spam submissions will be denied and users can have their account locked as a result.

5. These terms may update without notice.

Updated July 2021.

**Comment by pellarboss** [comment]
Marco - separate page, accessible through Settings

**Comment by curateproject** [comment]
Also add

6. Curate Groupt Ltd takes no responsibility of any item sold by their users on their marketplaces and as such can not be held responsible for authenticating or verifying items as genuine. Therefore limiting any liability, as such users are advised to carry out due diligence on all items traded on the marketplace. 

7. Pending withdrawals or payment disputes are processed on a manual case by case basis at varying times although we aim to process them as soon as possible.

**Comment by curateproject** [comment]
One more to add please

8. The curate team can only approve NFTs to the best of their knowledge based on the above and the item in question is genuine and authentic. Any dispute lies with the creator/seller of the item.
