### ISSUE TITLE
The user cannot verify his stake due to 2FA not approving

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#640]
The user cannot verify his stake due to 2FA not approving for some reason.

 [mario.dragicevic7@gmail.com](mailto:mario.dragicevic7@gmail.com) tried from another phone, thesame problem

android, 7.2

to reproduce, please see video:

https://user-images.githubusercontent.com/93180831/171007412-bd977c77-50cd-40c8-ba2a-6a6259598a59.mp4

**Comment by eventang2015** [comment]
@Catherineanne91 you can reset his TOTP on profile page and let the user setup TOTP again. 
![image](https://user-images.githubusercontent.com/28645146/171083090-d2fe1175-82ad-422b-94b0-054c4cdb23c7.png)
