### ISSUE TITLE
Permanent fix for  Recurring Bugs in the App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#642]
1. Stakes that are still locked after 30 or 60 rewards
2. Loyalty level on wallet home screen shows incorrect tier for some users
3. Featured NFT will keep on showing back 10 NFTs (or less) , for Trending and Weekly as well 
4. Frequent cases of Failed ID verification
5. Errors in Credit card Deposits (bad user experience)

**Comment by eventang2015** [comment]
@Catherineanne91 can you verify the above issues again ?
