### ISSUE TITLE
User Can't Make an Offer on an NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#643]
Description:

Error appears when user tries to place an offer on an NFT

To reproduce:
1. Click on an NFT
2. Click "Make offer"
3. Enter amount
4. type pin

Error shows:
![IMG_20220531_055455_296 (1)](https://user-images.githubusercontent.com/93180831/171077513-54b626e1-5a39-4e93-8308-0eee64ca150d.jpg)

![IMG_20220531_055458_698 (1)](https://user-images.githubusercontent.com/93180831/171077522-e919ec19-c0c8-40ef-8732-c37c62eb2a74.jpg)

Android
V 7.3Ob161

**Comment by eventang2015** [comment]
@Catherineanne91 can you let the user update app to latest version ?
we updated the amount to USD PRICE now #616.  so in server, the amount will convert to XCUR amount.

**Comment by Catherineanne91** [comment]
problem still persist, one user has uninstalled the app the installed it again (now with the most recent issue)
https://admin.curate.style/product/884ba9c7ecca84ed6815606e/detail - this is the NFT the user is trying to put a bid on

**Comment by Catherineanne91** [comment]
Still on-going problem with "make offer" function

make offers  shows the offer in xcur but the actual sale is made in full dollar amounts, for example, a user makes  offer for 10 xcur and ended paying 10 dollars
