### ISSUE TITLE
Priced as USD during Mint but Posted in XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#644]
When minting NFT, user will type price in USD
When it gets approved and appear on user's profile, price is in XCUR

To reproduce

1. Mint NFT > Select image
2. Type Price **in USD**
3. Submit for approval 

Result:
When approved, NFT is priced in XCUR, in this case, I typed 10 usd but when it gets approved, it is sold at 10 xcur, or 1.1 USD
![285147861_582832409912638_1336625250679760489_n](https://user-images.githubusercontent.com/93180831/171425821-6cf87ab5-e739-4b8b-99b2-e3551aafc624.jpg)
![284023004_327738916183216_4015450361180915119_n](https://user-images.githubusercontent.com/93180831/171425838-d8cdbcf4-3c0f-404b-bb23-069adc90f3a2.jpg)

ANdroid
v7.3.0b161

**Comment by eventang2015** [comment]
@madtocc  should post usd_price
fullly payload:
`var FormData = require('form-data');
var fs = require('fs');
var data = new FormData();
data.append('name', 'MetaX');
data.append('title', 'Meta');
data.append('description', 'Meta');
data.append('price', '1');
data.append('usd_price', '1');
data.append('currency', 'XCURP');
data.append('tags', 'a,b,c,d');
data.append('main_image', fs.createReadStream('/C:/Users/EvenT/Desktop/avatars/avatar.jpg'));
data.append('images', fs.createReadStream('/path/to/file'));
data.append('videos', fs.createReadStream('/path/to/file'));
data.append('price_reserve', '40');
data.append('price_type', 'fixed');
data.append('proof_of_work', fs.createReadStream('/path/to/file'));
data.append('proof_of_work_description', 'proof_ of_ work_ description');
data.append('batch_lazy_mint', 'true');
data.append('accept_symbols', 'XCURP,SOSX,USDXC');
data.append('attributes', '[{\n    "key": "creator",\n    "value": "1upgaming.io"\n},{\n    "key": "stickers",\n    "value": "https://console.filebase.com/object/1upgaming/7F88E24583A9058431572748E48C87BF529F3EDE5F54124B5811638D3FFCA403.zip"\n}]');`
