### ISSUE TITLE
Error in Depositing USDC with Circle - Send USDC to User

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#645]
User tried to Deposit in Circle but always fail in transaction and ended up making 5 transactions on his credit card

to reproduce
1. Wallet
2. Deposit usdc
3, Click Circle
4. Enter deposit Details
5 Enter credit card details > click complete purchase

 White screen shows and nothing happens

User email : https://admin.curate.style/users/4a8b5b9cac25e2f4350597e359b8a3c714e5

Amount: 5 transactions of 53.00 and one for 48.00

The app version is v7.30b161 Android

![Screenshot_20220601-193224](https://user-images.githubusercontent.com/93180831/171524225-7f9c2a4d-9b6e-4a42-83ba-5d219daa8761.png)
![Screenshot_20220601-193204](https://user-images.githubusercontent.com/93180831/171524228-f6049e48-16cb-4320-89be-8c188702282b.png)

**Comment by eventang2015** [comment]
resolved.
