### ISSUE TITLE
Error when Updating Price (Android)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#646]
Cant change fixed price to auction price. 
The result will turn to fixed price without any price changes

To reproduce:
1. CLick nft
2. update
3. Change Listing type to Auction Price
4. Change price

Outcome: 
It will return to fixed price without any price changes. 

Note: the bug occurs when changes are made with minted NFT 
NFT bought from other user works fine

![IMG_20220603_190515](https://user-images.githubusercontent.com/93180831/171995751-f13205db-a2b2-40ba-a1b2-e9a09edaa9be.jpg)

![IMG_20220603_190558 (1)](https://user-images.githubusercontent.com/93180831/171995754-d1e75ea9-aee7-4ff6-9216-1c2cb87ddaf9.jpg)

![IMG_20220603_190616 (2)](https://user-images.githubusercontent.com/93180831/171995758-9b240738-f4ce-4b25-a29e-6c71398aabbc.jpg)

app version  v.7.30b161  - android

**Comment by eventang2015** [comment]
@madtocc calls which api ?
can you add one more textbox ?
like, 
![image](https://user-images.githubusercontent.com/28645146/172097371-528b5081-a847-475a-b4cb-c4f8c69fd89a.png)
