### ISSUE TITLE
User Can't Use his Stake Boosting NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#647]
User Can't use his stake boosting NFT: it does not appear when he tries to stake and shows "NONE"

NFT owned:
https://admin.curate.style/product/884ba9c7ecca84ed6815606e/detail

![photo_2022-06-03_14-18-01 (1)](https://user-images.githubusercontent.com/93180831/171995878-ec67f74b-a3e6-410f-9db4-fbc801af2140.jpg)

**Comment by eventang2015** [comment]
resolved.
