### ISSUE TITLE
Request for Information - Caezik NFT Drop - Requested Import Demo

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#649]
**Describe the issue**
Caezik is having trouble importing their 500 NFTs onto Curate and has kindly requested a demo from our dev team. They have been given 3 different methods for how to import and want clarification. 

Caezik are a book company and not used to this process, therefore need reassurance from us. 

**Expected behavior**
To see their 500 NFTs successfully drop on Curate. 

**Additional context**

Slack Conversation to date: 

[Roy] [3 Jun at 04:30](https://curateorg.slack.com/archives/C03EMKJUC95/p1654227021675299)
If you are asking for assistance with a particular issue, could you please work with Regan / Tomas on creating an ticket? so it goes in to our queue and we can respond accordingly
it is super important to provide as much detail as you can, ie, called this API, returned this response, and the expected result was this, and it returned this, please be as specific as possible

[Zeeshan Hanif] [3 days ago]
For one of the product on staging server, I received this data, it has two properties named 'main_image' and 'main_image_thumb'.
These properties have image url but that is incomplete, that's why I'm unable to load images.
I tried to add host prefix like this but it didn't worked
Original in JSON: products/assets/88b076f9-060b-408f-b9ad-5b788816ed47.png
Update with expectation to work:
https://stage.curateapi.io/products/assets/88b076f9-060b-408f-b9ad-5b788816ed47.png
But it return not found JSON
{
            "key": "40db542d91b9e9a47e1c463e",
            "name": "aaa",
            "title": "aaa",
            "description": "asdsde",
            "price": 0,
            "usd_price": 5,
            "tags": [
                "Collectibles",
                "Music"
            ],
            "type": "nft",
            "mode": "normal",
            "currency": "XCURP",
            "userkey": "27d83e7556e9fccbf78d3bd236dd701c0faf",
            "owner": "27d83e7556e9fccbf78d3bd236dd701c0faf",
            "owner_avatar": "avatars/avatar.jpg",
            "owner_verified": true,
            "main_image": "products/assets/88b076f9-060b-408f-b9ad-5b788816ed47.png",
            "main_image_thumb": "products/thumb/d24aef63-3351-4f7b-8588-401872d46726.png",
            "proofs_of_work": [],
            "proof_of_work_description": "",
            "images": [],
            "videos": [],
            "online": false,
            "price_type": "auction",
            "price_reserve": 0,
            "auction_start": 1653646260,
            "auction_end": 1653991860,
            "auction_active": true,
            "nft_token_id": 1745715881,
            "nft_key": "nft/images/1745715881.jpg",
            "status": "approved",
            "nft_type": "ERC721",
            "royalty": 0.025,
            "meta_data": null,
            "fave_count": 2,
            "quantity": 1,
            "batch_lazy_mint": false,
            "created": "2022-05-25T03:52:26.094Z",
            "modified": "2022-05-27T13:13:37.113Z",
            "removed": false,
            "mint_fee": 0,
            "mint_fee_locked": false,
            "mint_fee_paid": false,
            "pow_public": false,
            "accept_symbols": "XCURP,USDXC,SOSX",
            "reviewer": {
                "key": "27d83e7556e9fccbf78d3bd236dd701c0faf",
                "email": "l****[r@gmail.com](mailto:r@gmail.com)"
            },
            "sharing_url": "https://go.curate.style/nft/40db542d91b9e9a47e1c463e",
            "view_count": 7,
            "auction_topbid": null,
            "description_append": null,
            "index": 407,
            "creator_details": {
                "key": "27d83e7556e9fccbf78d3bd236dd701c0faf",
                "firstname": "locngo",
                "lastname": "",
                "email": "l****[r@gmail.com](mailto:r@gmail.com)",
                "phone": null,
                "avatar": "avatars/27d83e7556e9fccbf78d3bd236dd701c0faf_1653648021.jpg",
                "created": "2022-03-31T07:58:37.946Z",
                "chatname": "locngo7K",
                "commercial_verified": false,
                "sharing_url": "https://go.curate.style/user/27d83e7556e9fccbf78d3bd236dd701c0faf",
                "bio": "Bio",
                "instagram_url": "",
                "twitter_url": "đ",
                "total_trade": 97.65142066,
                "products_created": 1
            },
            "locked_quantity": 0
        },

go.curate.stylego.curate.style
(https://go.curate.style/nft/40db542d91b9e9a47e1c463e)

https://go.curate.style/user/27d83e7556e9fccbf78d3bd236dd701c0faf

[Roy]  [3 days ago]
Howdy, you can fetch Assets with a different root URL
https://assets.curateapi.io/products/assets/88b076f9-060b-408f-b9ad-5b788816ed47.png
these assets are not hosted on the server, they are hosted on the CDN
cheers!

**Comment by pellarboss** [comment]
To import NFTs, there are two methods:
- calling the create API multiple times (as per API documentation, and the conversation we've had in a previous call)
- add the NFTs via web / app multiple times - feel free to demonstrate as required

I am unsure what / how else we can support

The issue raised by them has been resolved (see my reply)
