### ISSUE TITLE
Withdrawl of XCUR

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#65]
Enabling of withdrawal of XCUR 

- _*To come after consolidation code is deployed into master wallet for eth and XCUR  *_

Users can request a withdrawal to an external wallet, Admin to manually approve each withdrawal from the admin dashboard 

Master wallet, upon approval to send the user requested funds

**Comment by pellarboss** [comment]
current withdraw does not have an approval workflow
do you still want to enable withdraw for non kyc?
we can add withdraw approval in the next release

**Comment by curateproject** [comment]
Yes disable KYC for withdrawals for now
