### ISSUE TITLE
User is charged after updating the price of 2NFTs

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#650]
User is charged after updating the price of 2NFTs

Email: nizar.zulfikar11@gmail.com
in the XCUR transfer log it says that the user has exported NFTs, but did not click any export button

Transaction keys: 
255a43602380c8d9383c48e302f2bb586ca0684dd9cc389d4bc9acf33cb2f612
0ddb0d1365043a5aa5f2735797657bfbfdd3d44a92dacae46cb7c4fec589fe0e

![IMG_20220607_115915_942](https://user-images.githubusercontent.com/93180831/172302266-9c88668e-b699-4d5b-9305-312f5c13f1b1.jpg)

Can we help him recover his funds? He did not intend to export. Price update does not have option to export NFT.

**Comment by eventang2015** [comment]
refunded 
txns : https://scan.curate.style/txn/105153c162b826588630d9b7f7a292ba04e290c843dcf284cb9f014caa5a32f9 ,
https://scan.curate.style/txn/84db31e32b11fe32d6da488720be386114c2c7eda755396893ab08eb07a1e139
