### ISSUE TITLE
Purchased NFT shows incorrect price, in xcur

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#652]
User :  jasonswircenski@yahoo.com

Bought the following items for 10-5-30 respectively but shows 3-2-5 (in xcur)

https://admin.curate.style/product/afbe5bca3ee23235ac8c4b47/detail

https://admin.curate.style/product/b0bbd320e6ea00d3c2040ebe/detail

https://admin.curate.style/product/dd7dc114e67b51d08b521d59/detail

Version 7.3 iOs

![price xcur](https://user-images.githubusercontent.com/93180831/172632916-e3bbb148-ca42-407e-87ef-5a8e14a591dc.jpg)

**Comment by TheMad-J-Hatter** [comment]
Hi @pellarboss, 

This has also happened to an artist who accepted several offers for 20 XCUR and the purchase went through for 2 XCUR. He has reached out to try and get this fixed. The artists wallet shows 2 XCUR, not the correct accepted offer price. 

Account: jehuty27@gmail.com

![image](https://user-images.githubusercontent.com/88379508/172904536-fdc84609-a5fb-40f6-8064-e987de095ccf.png)

![image](https://user-images.githubusercontent.com/88379508/172904574-e27953f3-350d-4ca0-8231-6982ec56b47b.png)


However, the correct sell price shows on the buyers account (below) 
 
![image](https://user-images.githubusercontent.com/88379508/172904728-9ec44e41-383d-496f-8298-2e830effef5f.png)

**Comment by eventang2015** [comment]
releated to the offer issues. @madtocc  FYI

**Comment by eventang2015** [comment]
resolved.
