### ISSUE TITLE
"Internal Error" When trying to purchase XCUR with SOL or ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#653]
User: grazvydaspp@gmail.com
App version: V732b164

To reproduce:

1. go to wallet
2. click xcur
3. Click buy
4. Select Eth or SOL
5. Enter amount > Review Purchase
6. Type Pin

The following error shows: 
![transaction history](https://user-images.githubusercontent.com/93180831/172758351-58993890-41a9-4794-8056-ae14d88bbf56.jpg)

**Comment by eventang2015** [comment]
there's a failed commit order. 
I'll reset to pending and wait bot sync the txn.

**Comment by eventang2015** [comment]
synced txn https://etherscan.io/tx/0x670f40018f1ab0f113e8b4b5872783c7e05949444c86cbfb367779af6c81a33f
