### ISSUE TITLE
Offer in XCUR but posted in USD

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#654]
NFT below was offered with 50 XCUR but posted in 50 USD

joeverlaque@gmail.com
![Screenshot_20220609-194540_CURATE](https://user-images.githubusercontent.com/93180831/173021777-a90df44a-869e-4ddb-a71d-47adec638c4c.jpg)

**Comment by eventang2015** [comment]
https://scan.curate.style/txn/df37b4f79c5bb5725e5813868095c86516b23fefd4fda5bd90c8a746267a4fb4
https://admin.curate.style/product/7d290335cf7c7cc1c9074a05/detail
https://admin.curate.style/products/purchase/c1cd3cbbf20c80c69faf1036/detail
actually, sent 50 xcur.  there's some issue on the page. @madtocc FYI

**Comment by eventang2015** [comment]
resolved.
