### ISSUE TITLE
Bug in amount of XCUR in User's Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#655]
Description:
User is seeing more Xcur in his wallet than theres should be in the app
Balance say its 2470 xcur but user has staked xcur

"MY STAKE" shows 56k

Email: cwebb02+curate@gmail.com 
https://admin.curate.style/users/71eeca9b7c73f290d6c69875fb82ef5b1fdd

User says his xcur should only be 30k

 he has stakes active
https://admin.curate.style/users/71eeca9b7c73f290d6c69875fb82ef5b1fdd/detail

https://admin.curate.style/stakes/7d54b21af9de963a

https://admin.curate.style/stakes/fb7e0d470ddb851c

But his wallet shows only
3818 xcur is locked 

![photo_2022-06-10_08-38-25](https://user-images.githubusercontent.com/93180831/173025612-7fe69704-7d04-4862-8a52-35e5393b62be.jpg)

![photo_2022-06-10_08-38-30](https://user-images.githubusercontent.com/93180831/173025636-9088c3aa-9df5-4690-83b2-cc65a4043332.jpg)

**Comment by eventang2015** [comment]
corrected the locked amount.
