### ISSUE TITLE
User Can't Withdraw USDC and Can't buy XCUR with USDC

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#658]
User Cant Withdraw USDC

1. go to wallet
2. click usdc > withdraw
3. Enter External address and withdrawal amount
4.  Verify withdraw

Error Shows:
![photo_2022-06-13_17-54-41](https://user-images.githubusercontent.com/93180831/173485080-2c459730-0c87-4eaf-87e3-2c6794d4f02e.jpg)

User Cant buy XCUR with usdc
1. go to wallet
2. click xcur
3. click buy
4. Use: USDC , Enter amount in usdc
5. Review purhase

Error shows:

![photo_2022-06-13_17-54-39](https://user-images.githubusercontent.com/93180831/173485232-125c2e9a-9d6c-44f3-b436-e4ebb433c43a.jpg)

user:[mhr9900@hotmail.com](mailto:mhr9900@hotmail.com)'
V7.3.3b167

**Comment by eventang2015** [comment]
needs admin to verify the withdraw - 
https://admin.curate.style/tasks/withdrawexts?status=notverified
