### ISSUE TITLE
Deposits completed but does not reflect in user's wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#659]
Deposits completed but does not reflect in user's wallet:
user deposited XCUR and made no withdrawals but there is nothing in his wallet.

**Comment by eventang2015** [comment]
which user ?

**Comment by Catherineanne91** [comment]
https://admin.curate.style/accounts/ca4658cd81158ec70be9d534ba25e26097c2

@eventang2015  - sorry missed pasting it here

**Comment by eventang2015** [comment]
https://scan.curate.style/txn/d701dd945d8328bfa1e8781d409b694409261f4e7d5280f065c6fcfba432b0cf 
deposited.

**Comment by Catherineanne91** [comment]
@eventang2015 i think this is a display issue. User cant see it from his wallet 
![2](https://user-images.githubusercontent.com/93180831/174014863-70341ced-8a5b-461a-abee-9729ea9471b2.jpg)
