### ISSUE TITLE
Please unlock user's stakes (Past end date)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#660]
Please unlock stakes

For thesame user:
https://admin.curate.style/stakes/28ffd0a8c70de727
https://admin.curate.style/stakes/62cc2ae89b734d44
https://admin.curate.style/stakes/2cc81827768178a3
https://admin.curate.style/stakes/eb57438ffc8d1a76

**Comment by eventang2015** [comment]
unlocked.
