### ISSUE TITLE
Internal Server Error Shows When User tries to Sell NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#661]
Internal Server Error shows When User tries to Sell NFT.
To reproduce

1. Go to Profile>NFT
2. Click an NFT
3. Scroll down and select "Sell"
4. Enter price in USD , Click "Sell NFT"
5. Enter Pin
Error Shows:

'internal error" 
![286856553_1253660745372283_7139645124668265858_n](https://user-images.githubusercontent.com/93180831/173977180-ca3b07b5-704a-40d5-8729-528ab7004fea.jpg)
![287925261_365658328996292_6902553544230091339_n](https://user-images.githubusercontent.com/93180831/173977195-6b773b8e-8e78-425a-8cfb-9bc1e43e96c0.jpg)
![286855057_3192798737628420_2785496206728605101_n](https://user-images.githubusercontent.com/93180831/173977201-0c5de826-c435-495b-ac5c-145272e8426e.jpg)

User: catherineanneporter@gmail.com
V7.3.3b167
Android

**Comment by eventang2015** [comment]
@Catherineanne91 please try again.

**Comment by Catherineanne91** [comment]
works now thanks even
