### ISSUE TITLE
NFT Desktop - Create Space for Banner

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#662]
**Describe the tweak**
In relation to #651, please create a space for a promotional banner at the top of the homepage, NFT page, and Auction page which can host banners of two different sizes to start. Please refer to the Figma file on issue #651 for visual reference. 

Curate will have several banners from different artists that we want to have on a short-timer, similar to what you'd see on Binance or Kucoin for example. Along with a short-timer, the banners should also have an arrow to the left or a horizontal scroll bar that allows the user to manually flick between the promotional banners. Please use our draft Curate stake boosting banner attached as an example. 

2 sizes of banners we will be including is:

- Large banner: 1240x200 pixles (1 across screen)
- Medium banner: 604x200 pixles (2 across screen)

**Screenshots**

![Banner](https://user-images.githubusercontent.com/88379508/173984057-14a4df13-47b9-4980-892f-5cac1bf2dd05.jpg)

**Additional context**
This should form part of the NFT Desktop launch end of June. 

Visual aspects are seen as a priority over including missing sections such as statistics. Please comment if you require more information surrounding this.

**Comment by TheMad-J-Hatter** [comment]
*Curate Official*
Collection: Stake Boosting NFTs
Collection Link: https://web.curate.style/collection/db3d2a350854f4b8ca293296
![Large](https://user-images.githubusercontent.com/88379508/177380132-688f73eb-6aa0-446a-8aba-b505f2910306.jpg)
![Small](https://user-images.githubusercontent.com/88379508/177380140-703236c7-c6c6-4d36-adb5-4d5d534f928f.jpg)


*CatGirl* 
Collection: Catgirl D20
Collection Link: /collection/05b09e97de3baee4ed246feb
![banner1240](https://user-images.githubusercontent.com/88379508/177369297-230c4710-cb12-40df-8aca-aaf950116235.jpg)
![banner604](https://user-images.githubusercontent.com/88379508/177369311-9211b546-5268-4f18-8803-795bec6db89f.jpg)


*Codyfied*
Collection: Skater Girlz
Collection link: https://web.curate.style/collection/9d19d8727b2141ad3110310e
![image1](https://user-images.githubusercontent.com/88379508/177369471-9e3ecf61-3274-4e70-a877-0592f77a4ca4.jpeg)
![image0](https://user-images.githubusercontent.com/88379508/177369477-c4b1f356-cfe4-4b2c-89f1-0bb95dc9fa68.jpeg)


*Skullmate*
Collection: Crazy Skull Club
Collection link: https://web.curate.style/collection/1055beded0258df3db76c65d
![22884300-7709-4C00-AD7A-E92F88B5DB7A](https://user-images.githubusercontent.com/88379508/177368970-db4fd776-58c7-40af-8969-411e21cb6125.png)
![78FAB54A-40D1-4E10-9CD8-A1B16AB21739](https://user-images.githubusercontent.com/88379508/177368996-510a8860-65df-4037-8ab3-eda9b6a528e8.jpeg)


*Dracattus*
Collection: Dracattus
Collection link: https://web.curate.style/collection/3a7947dafea201c7ccf3c654
![1240x200](https://user-images.githubusercontent.com/88379508/177374245-113961be-ee83-40a1-b00b-ea603326f79c.jpg)
![604x200](https://user-images.githubusercontent.com/88379508/177374263-f2797ca6-ded3-4907-a4b7-31a53f983bec.jpg)


*elmadigitalart*
Collection: Metaheroes Club
Collection link: https://web.curate.style/collection/adca9c7d0bee74335d37a1fa
![Large Banner](https://user-images.githubusercontent.com/88379508/178002245-1a6c98f1-0393-49b5-bba8-f4682adac93c.jpg)
![Medium Banner](https://user-images.githubusercontent.com/88379508/178002263-e84ba255-8ad6-4037-8aac-aeb5bbfca2e4.jpg)


*Netbit*
Collection: Netbit
Collection link: https://web.curate.style/collection/5936c84b503781fe25b457de
![image6](https://user-images.githubusercontent.com/88379508/177376712-af662828-670d-4242-b588-e2064ff99b82.jpeg)
![image7](https://user-images.githubusercontent.com/88379508/177376722-9cfdd275-c0a9-4f01-b40a-e1c3f498701f.jpeg)


*Rekt Wolf*
Collection: Rekt Wolf
Collection link: https://web.curate.style/profile/7718025759d66535c34bbcada189eedc3bea
![Large Banner](https://user-images.githubusercontent.com/88379508/177378601-99813504-783b-453d-9d81-b30a520e79b1.gif)
![Medium Banner](https://user-images.githubusercontent.com/88379508/177378630-abf62659-2b50-4546-a803-22b4cd80e824.gif)


*Style of Skull*
Collection: Style Of Skull
Collection link: https://web.curate.style/collection/2854a08b06d02312e7f490dd
![large banner ](https://user-images.githubusercontent.com/88379508/177378812-e000bf8a-fe69-4d98-aad0-019591229cc1.PNG)
![medium banner ](https://user-images.githubusercontent.com/88379508/177378825-1067357e-6519-4732-87fe-7c38085d9ee2.PNG)


*Syncco*
Collection: E-Mask Series
Collection link: https://web.curate.style/collection/02b433bc0db9f1517b3a5628
![Large banner](https://user-images.githubusercontent.com/88379508/177380032-d66ff96e-d102-48fb-9641-489b9bdf04f0.png)
![Medium banner](https://user-images.githubusercontent.com/88379508/177380043-803ce65a-93f4-468c-8589-f0802d3710bd.png)


*WannabeCrypto*
Collection: Wannabe Babes
Collection link: https://web.curate.style/collection/e759ab4db912e19d4bc1f90a
![Wannabebabes](https://user-images.githubusercontent.com/88379508/177380410-3d5a658f-b36d-4ec8-81ad-e6e67d1e69aa.png)
![Wannabebabes (1)](https://user-images.githubusercontent.com/88379508/177380427-484888ee-cc71-42c7-8503-adb3934b7281.png)

There are two more collections we are waiting for images to be updated. Will post here as soon as they are complete.

**Comment by TheMad-J-Hatter** [comment]
Shahid Mahmud (Caezik)
Collection: Robert A. Heinlein's Pursuit of the Pankera Limited Edition eBook
Collection link: https://web.curate.style/collection/72eb4d4b258ada1531a1bc64
![ezgif-2-772ba0531a](https://user-images.githubusercontent.com/88379508/177836985-6170ce56-a676-465b-86c8-d87a9ef7d221.gif)

**Comment by TheMad-J-Hatter** [comment]
Hi @pellarboss and @madtocc, we have been checking the code for the banners and there does not seem to be code that provides a URL link to the specific collection. It's important that each banner is clickable and redirects the user to the collection/user page. 

In the comments above, I have provided the end of the URL (collection ID) which each banner must direct to but as mentioned, Sam can't add any URL yet. 

Please advise.

**Comment by TheMad-J-Hatter** [comment]
Mortal Monsters
Collection: Legendary Mortal Monsters
Collection link: https://web.curate.style/collection/0c0df17ad2fbb90ce3db230c
![Mortal monsters curate banner large](https://user-images.githubusercontent.com/88379508/179269695-f32b4ed8-e7be-4a98-81bf-1eb5eb8d3393.png)
![New Curate Medium Banner](https://user-images.githubusercontent.com/88379508/179417607-11308672-6953-4bab-b656-20fb9be0d0a8.png)

**Comment by Pellar-Spike** [comment]
Done
