### ISSUE TITLE
 Users' Stakes are not Showing Correctly

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#663]
Users' Stakes not Showing Correctly

First User:

 leeju09@naver.com 
1. user Staked 311473 xcur but in his wallet it shows 31124 XCUR
2. His stake shows 311473.22 from the admin panel
3. His wallet shows only 31124.80 is locked

Stake: https://admin.curate.style/stakes/2a1003eac4ab5872
Screenshots (first user):
![unnamed (5)](https://user-images.githubusercontent.com/93180831/174517206-18f2ca22-f188-497e-a27a-180b19eb800d.jpg)
![w (1)](https://user-images.githubusercontent.com/93180831/174517218-8d627e4b-aaa9-4258-a109-0c02aac224f7.jpg)

Second User: travislroberson1992@gmail.com
1. Users' active stake is a total of 16184 from the admin panel
2 only 8661 xcur is shown locked in his wallet
https://admin.curate.style/stakes/7d86de24c82473b5
https://admin.curate.style/stakes/4c2ab8028c2b6f81
https://admin.curate.style/stakes/9a5aeacf5e65358e (still active passed end date)

Screenshots (Second user):
![IMG_4712](https://user-images.githubusercontent.com/93180831/174517273-62faacf9-0a09-485e-a289-ecf3bd9f0dca.jpg)

Third User:
dennisverdino@gmail.com
1. users active stake is about 21463 xcur
2 Only 7338 appears to be locked in his wallet for staking

Stakes:
https://admin.curate.style/stakes/8ca21a4be67d38b9
https://admin.curate.style/stakes/a1938e51145583a2
https://admin.curate.style/stakes/88cea5f924550ee7
https://admin.curate.style/stakes/dad0fcdac424697d
https://admin.curate.style/stakes/ddde7afa83640961 (still active past end date)

Android v7.3.3 (third user)

Screenshot (Third user):
![Screenshot_20220618-170532_CURATE](https://user-images.githubusercontent.com/93180831/174519392-acbd5819-04aa-47c7-8746-b0c89bc2465d.jpg)

![Screenshot_20220618-170518_CURATE](https://user-images.githubusercontent.com/93180831/174519395-937bca91-379b-40f2-b239-343d83d7c72c.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91  for some reason, the locked amount were incorrect, I have corrected the amounts,  also I have reverted 2 stakings for 1st and 3rd users. (due to the incorrect total balances.)
