### ISSUE TITLE
Unlock Stakes for User

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#664]
Unlock Stakes for User - stakes are already past scheduled end date and have completed 30 rewards distribution
**USER # 1:**
user email: cecil.robbins87@yahoo.com

Stakes:
https://admin.curate.style/stakes/2abc797fd89f1866
https://admin.curate.style/stakes/db3e978bedd8bf8c

**USER # 2**:
[bluemolson@gmail.com](https://admin.curate.style/users/81e77d17bf40501393542c56ddd239febd96/detail)

Stake:
https://admin.curate.style/stakes/1b296671162ac7cf

**Comment by eventang2015** [comment]
done

**Comment by Catherineanne91** [comment]
@eventang2015 

User: [dimitrovlazar@yahoo.com](mailto:dimitrovlazar@yahoo.com)
Stake: https://admin.curate.style/stakes/6ee32090253be8c4
