### ISSUE TITLE
Users NFT was sold and user did not receive XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#665]
User email: christopherjoseph464@gmail.com
Product: SOS # 270
NFT: https://admin.curate.style/product/d8eb83cad723dbed1f0ea0d0/detail

User:
https://admin.curate.style/users/c2830d1a130320b6100d774f1ac5b333a12c

Issue
1. User purchased  SOS # 270 for 247.75472282 XCUR
2. he did not sell it but the current owner is now  magar008@btinternet.com , according to purchased log, sold at the same amount of 247.75472282 XCUR
3, user christopherjoseph464@gmail.com - did not receive any payment

USER WANTS TO RECEIVE THE -247.75472282

**Comment by eventang2015** [comment]
current owner is nelsonsminer1@gmail.com (he bought  this NFT earlier) 
did refund for [magar008@btinternet.com](mailto:magar008@btinternet.com)

**Comment by Catherineanne91** [comment]
@eventang2015 
[christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com) reached out he didnt receive anything when the NFT was transferred to another user

**Comment by eventang2015** [comment]
I think it's not [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com).

**Comment by eventang2015** [comment]
[christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com)'s wallet - https://admin.curate.style/accounts/189151b2f321755ea280fa48a30e189ed50a

**Comment by Catherineanne91** [comment]
Hey @eventang2015 , yes it should be [nelsonsminer1@gmail.com](mailto:nelsonsminer1@gmail.com) - sorry
