### ISSUE TITLE
Staked XCUR tokens reduced

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#666]
**Describe the bug**
Staking bug:

On 15th June 311,473 XCUR was staked, but today the user checked and found out that it is reduced to 280,860.43 (see screenshots below):

**User ID**
leeju09@naver.com

Version:
On latest version i.e v7.3.3

![Uploading photo_20![Uploading photo_2022-06-20
![photo_2022-06-20 14 32 15](https://user-images.githubusercontent.com/51517619/174614535-e9e321a5-5430-449d-808f-2f6399a3cac5.jpeg)
 14.32.17.jpeg…]()

**Comment by eventang2015** [comment]
Hi @curateproject , this user's total balance is 318204.4986066 XCUR. due to the incorrect locked amount, he made 3 other stakings (3 X 280K xcur), I canceled them.

**Comment by TheOneXi** [comment]
Thanks

**Comment by TheOneXi** [comment]
Thanks
