### ISSUE TITLE
Error When adding Card to Circle

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#667]
Error When adding Card to Circle

To reproduce
1. Go to wallet > Click USDC > Deposit
2. Type amount > Click Deposit
3. Add credit Card details > Click "Complete Purchase"

Error Occurs:
![photo_2022-06-21_09-52-03 (1)](https://user-images.githubusercontent.com/93180831/174750437-05e92781-07fb-4081-bd49-933514be645d.jpg)

User email: [mhr9900@hotmail.com](mailto:mhr9900@hotmail.com)

**Comment by eventang2015** [comment]
@madtocc wrong field ?

**Comment by madtocc** [comment]
Address is the user address not his email address.
