### ISSUE TITLE
Bug in staking Display

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#668]
User: se7s2000@gmail.com

The app duplicates that amount of Curate tokens staked
Everyday, when user opens the app, 2420 has been stake and a balance of 7489
User Claims that he is staking 7498

(his total stake is still 7498 from the admin panel but breaking it into 4 separate stakes)

se7s2000@gmail.com
version no. 7.3.3 of the Android app.

**Comment by eventang2015** [comment]
CANCELED the 2 duplicate stakings.  his balance should be 2676.30173056, not 7489
