### ISSUE TITLE
Peer to peer XCUR and ETH transfers

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#67]
Option to send XCU or ETH in the app to another users wallet in the app address.

If Gasless not possible I.e a front end UX update then we can add a spread to cover the consolidation fee in the backend

**Comment by DefiHunter** [comment]
We could do internal transfers on the “X - chain” , and use a wrapped version of ETG

**Comment by DefiHunter** [comment]
ETH*

**Comment by pellarboss** [comment]
XCUR XC20 is possible
fee less from a technical perspective
you guys can add a 0.5 flat fee or something to Profit from it
Please let us know

ETH is not currently wrapped, so eveyrthing will go through the network, ie, Withdraw is the same as a "Send / Transfer"

Wrapping ETH is a much longer conversation, lets prioritise the requirements accordingly

**Comment by curateproject** [comment]
Let's enable feeess transfer of XCUR XC20 between users please
