### ISSUE TITLE
"Internal Error" When Exporting NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#670]
Issue: Internal Error Shows when user tries to Export NFT
To reproduce:
1. Profile
2. Export NFT
3. Enter Chain and External account address 
4. Click "export"
5. the following error shows:

![C2 (1)](https://user-images.githubusercontent.com/93180831/175846422-b20f488f-6b82-445e-b2cd-c3de2b06c4d9.jpeg)

Version: 7.3.3b166 iOS
User Email: giannilari@inwind.it

**Comment by eventang2015** [comment]
is this NFT https://admin.curate.style/product/83b77a91ccb62a609cf0fb5b/detail ? shows exported. 
https://etherscan.io/tx/0xf570c70023f7ed587937fd3f83a910869f915fb1f23511f8c3602704f01998bb
https://scan.curate.style/txn/697db91d83890b0d3a759363990a87178eb10bcc28b93460c7f761a1b6e449e7

**Comment by Catherineanne91** [comment]
okay thanks @eventang2015

**Comment by eventang2015** [comment]
there was a bug related to private matadata, I have fixed it. @Catherineanne91

**Comment by Catherineanne91** [comment]
I will inform the user. thank you
