### ISSUE TITLE
Please Unlock Users' Staked Funds

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#671]
Email: yetukuri.vt@gmail.com

User's stake has already completed but according to user, it is still locked from his  wallet.  
https://admin.curate.style/stakes/d90799cd9432edd9
![Screenshot_2022-06-29-08-17-45-60_328ee62e69e3c4a023eeeb2fbe723d58](https://user-images.githubusercontent.com/93180831/176343182-beb0ec9c-f56f-424c-888e-fb155f759d6b.jpg)

**Comment by eventang2015** [comment]
unlocked, @Catherineanne91
