### ISSUE TITLE
NFT keeps on changing Price 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#672]
user email: curkkuppm@gmail.com
This NFT is set at a price of 2 USD
User claims that when viewed from his profile, it shows 0 usd but when you click to view the NFT, the price shows at 1.99 USD

NFT: 
https://admin.curate.style/product/8667cce93e871616e7d7b8b3/detail

![Screenshot_2022-06-29-11-10-10-786_app wallet curate (3)](https://user-images.githubusercontent.com/93180831/176365143-f0004dca-0940-4891-92b3-d2834378111b.jpg)
![Screenshot_2022-06-29-11-09-55-419_app wallet curate (1)](https://user-images.githubusercontent.com/93180831/176365148-f5808e0f-3acc-4911-926e-88b2eb4326e5.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 I checked the logs - you updated the price~

**Comment by eventang2015** [comment]
![image](https://user-images.githubusercontent.com/28645146/177334279-2cac6850-8064-4574-bbe1-ba5c05974a46.png)
