### ISSUE TITLE
Owner of Dracattus collection wants to airdrop an NFT to his Buyer

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#675]
Owner of Dracattus collection wants to airdrop an NFT to his Buyer of Dracattus #357

Sender/ Seller/Owner:  colemanjeff@mac.com
recepient/Buyer:  mmm265418@gmail.com
Username:  jorge-5DBB
Purchased Product key:  7e5d5ec2c333e8c32bd9f97c
Purchased Product Name: Dracattus #357

NFT to airdrop: https://admin.curate.style/product/05ba82bb17d90d6ab65bf8c9/detail

**Comment by eventang2015** [comment]
issued.
