### ISSUE TITLE
User sent ETH from Coinbase to his  Curate USDC Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#676]
Aidan.j.wendorf@gmail.com 
version 7.3.3b167 android

From 0xeb2629a2734e272bcc07bda959863f316f4bd4cf
To 0xe4ebdc26eb47dc00d2f05aa02300853a3bd0f734

https://etherscan.io/tx/0x067a00eedf6eaf1519878c1282cee6f7fa77c8ffecfab89e58cd10e096aa7db2

User wants his ETH on this address: 0x621E89371cc531Cd5f54d28E826d762091e24B38

Question: How much will it cost us to recover his funds? Or can we still recover them?

Thanks

**Comment by eventang2015** [comment]
@Catherineanne91 since the receipent address: 0xe4ebdc26eb47dc00d2f05aa02300853a3bd0f734 is not in our system , we cant send back.

**Comment by eventang2015** [comment]
sent to 0x621E89371cc531Cd5f54d28E826d762091e24B38
txn: https://etherscan.io/tx/0x3383a9d452e62764a24cdd05cf31447c065a5a46522edf46b630da9fe039f0ac

**Comment by Catherineanne91** [comment]
thanks
