### ISSUE TITLE
Reset sync did not unlock Deposited funds

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#677]
Reset sync time from the admin panel did not unlock funds
User Sent 197 XCUR to XCUR wallet

User:
https://admin.curate.style/users/349d4efae68ad3c08aecff13cbbc56129a52

Transaction:https://bscscan.com/tx/0xc81853d13a04a37a8fc1e6fa925d0257c7b9de4dfed493da6ab44b617ea68272

**Comment by eventang2015** [comment]
deposited xcur into his xcurp address. 
https://admin.curate.style/accounts/fa60a00ba98cf7959c82a4c8a60a8e995028

**Comment by Catherineanne91** [comment]
thank you even
