### ISSUE TITLE
Caezik NFT Drop - NFTs and Data spreadsheet

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#679]
**Describe the drop**
This is the Caezik NFT drop happening on Monday 11th July, but they wanted to see them uploaded to check everything is working before the 11th. 

Please see the dropbox links to all 500 full-size NFTs. The file sizes are large so please allow time to download/upload. 

Please upload only the first **100 NFTs**. The first 100 should be: 

- Auction
- Price starts should be $30
- Starting on Monday 11th @ 00:01:00 UTC +1.
- Duration of 1 week

- **Please assign NFT number 100 as 'Buy Now' for them to buy and test before 11th July.** 

Please see below for the dropbox links and the spreadsheet. This drop will utilise our new 'Private Metadata' feature in the app. Buyers of the NFT should be able to see the hidden content and access the unique link inside. This data exists on the attached spreadsheet under the column 'Private'. 

**User ID**
user key
shahid@arcmanor.com

**Additional context**
[Pankera Details (1).xlsx](https://github.com/pellartech/curate/files/9056497/Pankera.Details.1.xlsx)

(https://www.dropbox.com/s/uug067audyx76a7/Set-1%20PNG_%281-150%29.zip?dl=0
https://www.dropbox.com/s/6ppph31nhyuw6jf/Set-2%20PNG_%28151-300%29.zip?dl=0
https://www.dropbox.com/s/np76ukh9un0n9bz/Set-3%20PNG_%28301-450%29.zip?dl=0
https://www.dropbox.com/s/swixs8or107osla/Set-4%20PNG_%28451-500%29.zip?dl=0)

**Comment by eventang2015** [comment]
@TheMad-J-Hatter @curateproject I have imported 2 NFTs, please check https://admin.curate.style/products/user/cf8b1e04772571eb3e55c486fd0900389992/nft. 
if you ok will them , please let me know , I will import the others. 
also I created a temp collection :https://admin.curate.style/collections/72eb4d4b258ada1531a1bc64 , please ask the owner upload LOGO and Background imgs , will generate deep links for the collection and NFTs later.

**Comment by TheMad-J-Hatter** [comment]
Hey @eventang2015, Thanks for getting the Caezik drop sorted, they are happy all are up and ready for the drop. However, I noticed a slight issue, the two metadata fields are actualIy the wrong way round.

They have two metadata types, Boarder color top and boarder color bottom. The top colour shows as Boarder  color bottom and visa versa. Is this a quick fix?

**Comment by eventang2015** [comment]
![image](https://user-images.githubusercontent.com/28645146/178089905-c184731c-02fd-4f2f-8c52-c8a7de6bcc7d.png)
do you mean these two attributes  are opposite ? @TheMad-J-Hatter

**Comment by TheMad-J-Hatter** [comment]
They seem to have come in that way yes. Check my screen recording attached.

 https://user-images.githubusercontent.com/88379508/178091021-48e1626c-7f9e-4bfd-84d9-74397785c275.mp4

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015 , we have another small issue with the private metadata field.

We have manually set number 24, 32, 44, 82 and 96 to Buy Now for Caesik to buy and test. However, when we set them to Buy Now, the https link in the private metadata disappeared.

We then tried to manually input it back in but it didn't allow us. Can you please amend this to allow manual input please 👍

**Comment by eventang2015** [comment]
https://admin.curate.style/product/f95d188109a7e850c2a1c256/edit 
the metaData became to 
![image](https://user-images.githubusercontent.com/28645146/178143677-485b705f-fcd6-4509-8234-cf3e3d4b2289.png)
but I can reset the mata data tomorrow.

**Comment by TheMad-J-Hatter** [comment]
Thanks, if you can add this back in tomorrow, that would be good.

As you can see it has deleted the private metadata when we switched from Auction to Buy Now. Any way that you can allow manual input of a https:// link.

This would avoid us having to contact the devs each time.

**Comment by eventang2015** [comment]
updated, please let me know when I can import the orther 400 NFTs.

**Comment by TheMad-J-Hatter** [comment]
Thank you @eventang2015.

I will check tomorrow morning, is currently Sunday night here 👍

In regards to the other 400, I'll let you know. Caezik want to see how the first 100 sell first 👌

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015, 

A few issues and amendments for the Caezik drop. 

1. The private metadata link doesn't seem to work very well. They have provided a new link that needs to be pushed to all their 100 NFTs. This link is: https://bit.ly/3P2alkad43HeinleinNFTDownload

2. The Metadata against each NFT is still showing the wrong way around. As you can see the metadata colours are incorrect. Please switch around.

'Boarder Color Bottom' is currently spelt 'BottoN', please amend. 

<img width="946" alt="image" src="https://user-images.githubusercontent.com/88379508/179547161-a5f58a68-4e49-4864-9bde-e8609da93275.png">

**Comment by eventang2015** [comment]
@TheMad-J-Hatter please let me know when i can import others

**Comment by TheMad-J-Hatter** [comment]
I don't believe Caezik will want the other 400 to be uploaded based on the lack of sales generated. Consider this issue closed.
