### ISSUE TITLE
Display Bug in App for NFT Attribute

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#680]
There display bug under the nft attribute. it should be a place for price updates, stats and others but it becomes a very long gray bo
![Screenshot_20220707_102440](https://user-images.githubusercontent.com/93180831/177685450-ffe12820-5d7a-4928-a608-63c20bb14403.jpg)
x

V.7.4.0 Android

![73952F5B-84FD-49BF-9A4F-CE410FD0142A](https://user-images.githubusercontent.com/93180831/177687088-df2f1d5b-123c-4c84-a071-da841d206bff.png)

![44C6017A-1FAB-4E4D-948D-97F2E0F4F069](https://user-images.githubusercontent.com/93180831/177687104-96c4c99a-3080-4016-8a38-6c56ccaa61fc.png)

![E4594D50-F4C1-4CB6-B94F-079F96A4564B](https://user-images.githubusercontent.com/93180831/177687239-963b550b-45c3-43bb-b613-e08dcd24e8ce.png)

![5BCE25AD-0CB9-4FB1-A668-5491671B582E](https://user-images.githubusercontent.com/93180831/177687243-1fbf6273-4cf0-410a-b00b-f67eb0ad6d90.png)

Metaheroes Club #304
Kongdo Club #40
Metaheroes Club #106
Kongdo Club #41

**Comment by Catherineanne91** [comment]
https://user-images.githubusercontent.com/93180831/178044282-aa70a91e-0f97-40d3-8bc4-d478ca6ad595.mp4

**Comment by eventang2015** [comment]
will take some time to upload to app stores.

**Comment by Catherineanne91** [comment]
noted on this. take you @eventang2015  will inform users
