### ISSUE TITLE
User's stake does not reflect actual amount

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#681]
User claims to have a total stake of 9700 xcur 
but complains that his total stakes that appears on wallet is 4568

Actual Active Stakes from admin panel: TOTAL 1654
Amount xcur in wallet: 211.95
Amount locked in wallet : 123.148

https://admin.curate.style/stakes/28ff3a7fd96007bc
https://admin.curate.style/stakes/1ef3a394108eb699
https://admin.curate.style/stakes/1d34a1bda6a0f660
https://admin.curate.style/stakes/01324ad2475b01c7
https://admin.curate.style/stakes/aab52f3a4480486c
https://admin.curate.style/stakes/b722f2196b8458eb
https://admin.curate.style/stakes/2b2633aac1c73b3a
https://admin.curate.style/stakes/d1915ecb0e14fdc1
https://admin.curate.style/stakes/48e2447f17739df6
https://admin.curate.style/stakes/74b81650340a3b2d
https://admin.curate.style/stakes/95a533b7e62cbaf2

Email: malanxsuben@gmail.com

Note: Not sure why he think he have a total of 9700 xcur staked.

**Comment by eventang2015** [comment]
corrected balance.
`{
    "total_staked": 14354.98699222,
    "total_reward": 158.76763156,
    "completed_stake_amount": 12699.87699222,
    "completed_reward_amount": 147.31184418,
    "staking_amount": 1655.11,
    "staking_reward": 11.45578738
}`

**Comment by Catherineanne91** [comment]
@eventang2015 the user wants his stakes from february to show, is it possible? His stakes history only shows up to june (that is, his past 20 stakes)

**Comment by eventang2015** [comment]
currently, show 1st page only, will add paging in app.

**Comment by Catherineanne91** [comment]
@eventang2015 , the user complains that his funds are unlocked from staking but is not reflecting in his wallet. he is specifically referring to these stakes:



https://admin.curate.style/users/e77fc553030c3992fa25f3144ea660d84ac5/detail
https://admin.curate.style/users/e77fc553030c3992fa25f3144ea660d84ac5/detail

The are two 2k xcur that was unlocked on July 7 and 8 - but did not arrive in his wallet.

**Comment by Catherineanne91** [comment]
@eventang2015 , same user, he input his password once, and he app locks him

![unnamed](https://user-images.githubusercontent.com/93180831/179450102-5e1ef5eb-3e44-47ce-9535-f10d3eba87c4.jpg)

**Comment by eventang2015** [comment]
seems he forgot his pin code.

**Comment by Catherineanne91** [comment]
@eventang2015 , yes but the user insist he only tried to type his pin once. 

I also need help on this one, https://github.com/pellartech/curate/issues/681#issuecomment-1185846094

**Comment by eventang2015** [comment]
I think he loged in. the login attempts reset to 0 .

**Comment by Catherineanne91** [comment]
@eventang2015  https://github.com/pellartech/curate/issues/681#issuecomment-1185846094
can u help me with this one. 

The user is emailing back

**Comment by eventang2015** [comment]
due to the previous negative locked amount issue, I've compensated him some xucr .
`[
    {
        "type" : "DEPOSIT_XCURP",
        "count" : 2.0,
        "total" : NumberDecimal("2436.33679264")
    },
    {
        "type" : "WITHDRAW_XCURP",
        "count" : 9.0,
        "total" : NumberDecimal("-3322.37")
    },
    {
        "type" : "COMMIT_XCUR",
        "count" : 8.0,
        "total" : NumberDecimal("753.97973924")
    },
    {
        "type" : "LAZY_MINT",
        "count" : 1.0,
        "total" : NumberDecimal("-8.43408345")
    },
    {
        "type" : "BONUS",
        "count" : 1.0,
        "total" : NumberDecimal("205.90916744")
    },
    {
        "type" : "REFERRAL_AMOUNT_REFERRER",
        "count" : 1.0,
        "total" : NumberDecimal("1.52718387")
    },
    {
        "type" : "TRANSFER",
        "count" : 18.0,
        "total" : NumberDecimal("-147.73599529")
    },
    {
        "type" : "REWARD",
        "count" : 15.0,
        "total" : NumberDecimal("1.97185039")
    }
]`

**Comment by Catherineanne91** [comment]
![paint](https://user-images.githubusercontent.com/93180831/180014835-f25af208-bfdb-42d8-8fd2-04157826402c.jpg)
@eventang2015 , 

Im totally lost with this one. he is insisting he still has 5k XCUR. 
I tried to explain to him the above items 
(his total deposits, total stakes and rewards, and withdrawn xcur, etc.)

**Comment by eventang2015** [comment]
I will give you a .csv file with his all transactions.

**Comment by eventang2015** [comment]
@Catherineanne91 FYI

[Thu Jul 21 2022 09_04_38 GMT+0800_txns.csv](https://github.com/pellartech/curate/files/9155367/Thu.Jul.21.2022.09_04_38.GMT%2B0800_txns.csv)
