### ISSUE TITLE
Transfer NFTS to User A and send Funds to User B

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#683]
USER A - [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com)
USER B [jehuty27@gmail.com](mailto:jehuty27@gmail.com)

Metaheroes Club # 301 -  20.95 XCUR  https://admin.curate.style/product/ad03eddbf11ef15a041f66f9/detail
Metaheroes Club # 307 -20.95 XCUR - https://admin.curate.style/product/eb02d84cc87b337653680187/detail
Metaheroes Club # 302 - 20.95 XCUR - https://admin.curate.style/product/cb73e659b36f8a23722db661/detail
Metaheroes Club # 300 - 19.04 XCUR - https://admin.curate.style/product/0d05fc6f524b09f8f5569141/detail
Metaheroes Club # 290 - 19.04 XCUR  -https://admin.curate.style/product/c0096a5fceaf90802cfb875f/detail
Metaheroes Club # 293 - 19.04 XCUR-  https://admin.curate.style/product/6f24dbf637e8f23640ce8d70/detail
Metaheroes Club # 285 - 19.04 XCUR  -https://admin.curate.style/product/d1b79a4c435d4d2ba0349348/detail
Metaheroes Club # 263 -19.04 XCUR-https://admin.curate.style/product/5b18703399572f0069715084/detail
Metaheroes Club # 260 -47.61 XCUR-https://admin.curate.style/product/81ab4eeb0616c26583bb6385/detail
Metaheroes Club # 261 - 19.04 XCUR -https://admin.curate.style/product/0ca54e2ab4b87d9f332549b1/detail

transfer 224.7 XCUR to be added to account jehuty27@gmail.com

Users who have the NFTs [jehuty27@gmail.com](mailto:jehuty27@gmail.com)
User who has XCUR [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com)
Take XCUR from [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com) 224.7, and send to [jehuty27@gmail.com](mailto:jehuty27@gmail.com)
Then, take noted nfts (10) from [jehuty27@gmail.com](mailto:jehuty27@gmail.com) and send to [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com)

**Comment by eventang2015** [comment]
@Catherineanne91  can you clarify this ? [christopherjoseph464@gmail.com](mailto:christopherjoseph464@gmail.com) send 281.84 XCUR to [jehuty27@gmail.com](mailto:jehuty27@gmail.com) ?

**Comment by Catherineanne91** [comment]
@eventang2015 , i apologize but it has to be 224.7 XCUR

**Comment by Catherineanne91** [comment]
and yes , take xcur from christopherjoseph464@gmail.com and send to jehuty27@gmail.com

**Comment by eventang2015** [comment]
here's txn: https://scan.curate.style/txn/6ac2550640a2dcae30c0f6ac4fcabae18dd5b41cdbd13936ec16a0dce019bdc3

**Comment by Catherineanne91** [comment]
@eventang2015 can you please transfer the NFTs as well? 


Metaheroes Club # 301 - 20.95 XCUR https://admin.curate.style/product/ad03eddbf11ef15a041f66f9/detail
Metaheroes Club # 307 -20.95 XCUR - https://admin.curate.style/product/eb02d84cc87b337653680187/detail
Metaheroes Club # 302 - 20.95 XCUR - https://admin.curate.style/product/cb73e659b36f8a23722db661/detail
Metaheroes Club # 300 - 19.04 XCUR - https://admin.curate.style/product/0d05fc6f524b09f8f5569141/detail
Metaheroes Club # 290 - 19.04 XCUR -https://admin.curate.style/product/c0096a5fceaf90802cfb875f/detail
Metaheroes Club # 293 - 19.04 XCUR- https://admin.curate.style/product/6f24dbf637e8f23640ce8d70/detail
Metaheroes Club # 285 - 19.04 XCUR -https://admin.curate.style/product/d1b79a4c435d4d2ba0349348/detail
Metaheroes Club # 263 -19.04 XCUR-https://admin.curate.style/product/5b18703399572f0069715084/detail
Metaheroes Club # 260 -47.61 XCUR-https://admin.curate.style/product/81ab4eeb0616c26583bb6385/detail
Metaheroes Club # 261 - 19.04 XCUR -https://admin.curate.style/product/0ca54e2ab4b87d9f332549b1/detail


they have to be sent to [christopherjoseph464@gmail.com])

**Comment by eventang2015** [comment]
sent @Catherineanne91
