### ISSUE TITLE
"Transfer Fails" When user transfers 0.25 SOL from Curate Wallet to an External Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#685]
User can not transfer SOL to external wallet. 
Amount SOL in wallet - 0.25

1. Go to wallet
2. Click SOL
3.  Click Withdraw
4. Enter External SOL address and Amount > Verify Withdraw
5. Complete verification

Error shows" Transfer fails"

![unnamed (2)](https://user-images.githubusercontent.com/93180831/178662640-6104051a-5e16-499c-8bdf-1b039fd569af.png)

My email address for my account is: [adm0055@gmail.com](mailto:adm0055@gmail.com)
The wallet version I’m using is: 7.4.0b168 iOS''

**Comment by eventang2015** [comment]
synced txn - https://solscan.io/account/GYLkkMvf5qdVm8LsgXjzv5oFFrFESRKYBUaUEyseSBHb
https://admin.curate.style/accounts/945c4a11373d31489328b605e7a31ac6c6c7
