### ISSUE TITLE
"Transaction Failed" When Purchasing XCUR using ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#686]
User- [zeeshanhanif@gmail.com](mailto:zeeshanhanif@gmail.com)
Transaction fails everytime User tries to convert ETH to XCUR
User has two failed transactions:
https://admin.curate.style/accounts/572255f58a1b6e92b5659b9c57dc1ca072f2

Note: 

- Can we just take his ETH and send him equivalent XCUR as an immediate/temporary fix? User needs his funds as user will be dropping collections by monday.
- Convert all his ETH in his wallet to XCUR

**Comment by eventang2015** [comment]
synced txn  https://etherscan.io/tx/0x58a7a449a387ffeb393d2c036274305d146f8da282987a4db4e923d9510ac4aa
https://admin.curate.style/accounts/7e21ddb0480751c322b102d1af3ce5726766
