### ISSUE TITLE
Desktop - Private Metadata Feature

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#687]
**Describe the Feature**
Please add a button on NFT page which allows the buyer (owner) to view the private metadata of that NFT. 

This allows the artist/seller to embed text, link or attribute for buyers to view once purchased.  This would also involve a field in the mint page that allows the entry of Private Metadata. 

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/88379508/179433725-0249103f-5702-4da2-8721-93afb876d1a5.png">

**Comment by eventang2015** [comment]
it's resolved.

**Comment by TheMad-J-Hatter** [comment]
Completed.
