### ISSUE TITLE
Approve XCUR Withdrawal

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#689]
Please help the user to complete his withdrawal of 31366 XCUR

https://admin.curate.style/users/ee704e6791b7f82210ef288b11cb0dc2731c

-> [leeju09@naver.com](mailto:leeju09@naver.com)

->Android (v7.4.1b169)

**Comment by eventang2015** [comment]
@Catherineanne91  approve withdraw on
https://admin.curate.style/tasks/withdrawexts?status=notverified
