### ISSUE TITLE
Web App - PIN box needs contrast

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#691]
Can you make the surrounding 4 digit PIN box more clear on the desktop web app please (UX issue)

![Screenshot 2022-07-18 at 12 26 28](https://user-images.githubusercontent.com/51517619/179501784-5d06de86-8371-4916-a27a-099a697651ff.png)

**Comment by pellarboss** [comment]
@TheMad-J-Hatter 

seems like Sam made this change, could you please ask him to be a bit careful about implementing global changes?

<img width="1002" alt="Screen Shot 2022-07-20 at 11 46 23 am" src="https://user-images.githubusercontent.com/24906507/179878075-0c806ee6-760c-4e51-a00c-d8010d1b5f13.png">

**Comment by Pellar-Spike** [comment]
Done
