### ISSUE TITLE
User is prompted Insufficient funds when making a bid (has 900 xcur in wallet)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#693]
Buyer:isaac.n.e.payne@gmail.com

NFT:
https://admin.curate.style/product/1ff226d575cf2a90240a50e1/detail

User is prompted everytime he makes a bid that he has "insufficient funds"

User has 900+Xcur in his wallet.

**Comment by eventang2015** [comment]
can he provide a video ? @Catherineanne91

**Comment by eventang2015** [comment]
@Catherineanne91   hotfixed, please try again.
