### ISSUE TITLE
User Imported NFT from Opensea to Wrong Address

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#694]
User: scofield01@gmx.net

NFT address:0x645670add376f19c3d2c9bdd62dd4190c8fad988

Token ID: Token id : 1515
User sent to: 0x025B8140D5630D24A85016E91974d04CafcaC00D

NFT: Took Squad

**Can we recover his NFT?**

![293453028_761373331770853_7561337363089427581_n](https://user-images.githubusercontent.com/93180831/179630679-a73762f6-2694-4967-9ef3-4d7d7f4413ef.jpg)
![293303708_821598418778962_6277185951376838351_n](https://user-images.githubusercontent.com/93180831/179630683-05236571-17c7-4bc6-99e2-90be67ed5aff.jpg)

**Comment by eventang2015** [comment]
he imported the NFT into his eth wallet ,  the wallet has no balance .

**Comment by pellarboss** [comment]
@Catherineanne91 this NFT is lost
