### ISSUE TITLE
User Stakes Completed but still locked

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#697]
Stakes:
https://admin.curate.style/stakes/0f94ef72f2664e13

User:  wwwprzemek1@gmail.com

Due Date: July 19 2022

Note: please unlock

**Comment by eventang2015** [comment]
staking didn't change the total balance, just locked the staking amount. 
available amount = wallet total balance - locked amount.
corrected the locked amount.

**Comment by Catherineanne91** [comment]
@eventang2015 

User is looking for missing about 3k XCUR from his wallet - i think he meant that XCUR unlocked from this stakes

https://admin.curate.style/stakes/f51fe7ea42303f3e
https://admin.curate.style/stakes/0f94ef72f2664e13
