### ISSUE TITLE
User Stakes and Funds Does not Show in his Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#698]
User Stakes and Funds Does not Show in his Wallet

Email: gonzaloalonso241101@gmail.com
7.40b168 ios

https://admin.curate.style/stakes/494350b4349ec9ff
https://admin.curate.style/stakes/c646f6b2ce4036cf

User: https://admin.curate.style/users/358544fb661cae6f99aff14f91fdbe4d761a

![293608716_415185470560779_6221137141171985830_n (1)](https://user-images.githubusercontent.com/93180831/180017547-3fa47755-d83c-4a3c-9f66-68354f8382cf.jpg)

**Comment by eventang2015** [comment]
his stakings are completed. unlocked staking amount.
