### ISSUE TITLE
Mobile Notifications for NFT Offers and Sold in-app.

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#700]
**Describe the enhancement**
This enhancement will add mobile notifications for specific events like an offer made or NFT sold. Emails can quite often be missed or take time to view.

**Comment by eventang2015** [comment]
please enable notifications in app. @TheMad-J-Hatter 
![image](https://user-images.githubusercontent.com/28645146/180132554-44226b34-3e4f-4cd7-91d0-9c569a3e2c4a.png)
