### ISSUE TITLE
Staking rewards and functions seem incorrect/non-responsive

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#702]
**Describe the bug**
This seems to be a recurring issue that I'd really like sorted across the board. 

I have provided my own account as a reference for this issue. I see 2 issues which are: 

1. My staking rewards month on month are incorrect. 
2. My staking restarted for another 30 days even when I did not have auto-renew or compound on. 

**Expected behavior**
I'd like this issue fixed for everyone, this may be the reason we have such a high amount of staked XCUR. Not saying that is a bad thing but if folks can't withdraw their XCUR when at the end of the 30 lock-up period, it's an issue. 

**Screenshots**
1. 

- On May 27th, I staked 4277.96 XCUR @ 16% with a 2 x stake boost. My interest was 113.9 XCUR. 
- On June 27th, the staked amount was higher (4391.91 XCUR), yet the interest was lower at 89.41. Please explain this logic? 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/88379508/180232048-7b292f1b-93c0-4176-8e8a-bf928e3e5d1b.png">

2. The bigger issue is that I have never turned on auto-renew or compound before or during my staking. My staking auto-renewed without me asking. We need to resolve this issue and ensure that all users who have this option de-selected is able to access their funds after the 30-day lock up. Please advise. 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/88379508/180232921-337044c6-77a4-4dc9-b14b-8c258dfc4d90.png">

**User ID**
user key
user email: joeverlaque@gmail.com

**Comment by eventang2015** [comment]
![image](https://user-images.githubusercontent.com/28645146/180395909-023e5d06-4116-4fc0-afb2-be7e97ae4f7d.png)
1. https://admin.curate.style/stakes/97bfb7c0ba45d017 is completed, and renew=true, compound=true
2. after 1st stake is completed (renew), we create a 2nd staking staking amount = 4277.96+113.95832483 = 4,391.91832483 XCUR
3. 2nd staking is a sub staking, can't renew again.

**Comment by TheMad-J-Hatter** [comment]
Thank you @eventang2015
