### ISSUE TITLE
Users Stakes Has completed but does not reflect on the user's wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#703]
dimitrovlazar@yahoo.com

Stakes has already completed but does not show in his wallet

The user's last stake:

https://admin.curate.style/stakes/735c5d5eadc25d3c

Still appears to be locked from user's wallet:
https://admin.curate.style/users/6520c0758fbb0a95f325fc6fee0d24b5cd11/detail

![photo_2022-07-22_09-12-49](https://user-images.githubusercontent.com/93180831/180388732-30f79fd6-7618-4f52-a585-ace31059c358.jpg)
![photo_2022-07-22_09-12-46](https://user-images.githubusercontent.com/93180831/180388741-4477a621-03d0-405e-8b8c-d9b6c2047516.jpg)
![photo_2022-07-22_09-12-32](https://user-images.githubusercontent.com/93180831/180388744-99ef2852-d06b-456f-822c-7092af4439ce.jpg)

**Comment by eventang2015** [comment]
unlocked
