### ISSUE TITLE
User's Wallet do no show correct amount after stakes are completed

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#705]
User's Wallet do no show correct amount after stakes are completed
gonzaloalonso241101@gmail.com
https://admin.curate.style/stakes/494350b4349ec9ff
https://admin.curate.style/users/358544fb661cae6f99aff14f91fdbe4d761a/detail

**Comment by eventang2015** [comment]
https://algoexplorer.io/address/BVXCINKX6OMU3KJVFUB6SYHDMN7QE5VOGX656UM5TN2FEOMUVGDXEIW2DU 
` message: 'TransactionPool.Remember: transaction CF4PVVDIKUPHOK2MSL2HRTXKJNHOG5N5MOWBKPDOFBSRZDTB6ZGQ: account BVXCINKX6OMU3KJVFUB6SYHDMN7QE5VOGX656UM5TN2FEOMUVGDXEIW2DU balance 76 below min 100000 (0 assets)'` 
please try to keep some balance (0.1 ALGO) in his account, try 3.8 or 3.9.
