### ISSUE TITLE
User gets "Internal Server Error" When purchasing XCUR with Algo and withdrawing Algo

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#706]
User gets "Internal Server Error" When purchasing XCUR with Algo and withdrawing Algo

User:  basseyb424@gmail.com
https://admin.curate.style/accounts/e90cfc3359e9b439696ba5c5bf726b1f5c4e

This occur when
1. Purchasing XCUR with Algo 
After confirming purchase (upon entering pin)

2. When withdrawing Algorand
After confirming withdrawal (upon entering pin)

**Comment by eventang2015** [comment]
https://algoexplorer.io/address/BVXCINKX6OMU3KJVFUB6SYHDMN7QE5VOGX656UM5TN2FEOMUVGDXEIW2DU  
message: 'TransactionPool.Remember: transaction CF4PVVDIKUPHOK2MSL2HRTXKJNHOG5N5MOWBKPDOFBSRZDTB6ZGQ: account BVXCINKX6OMU3KJVFUB6SYHDMN7QE5VOGX656UM5TN2FEOMUVGDXEIW2DU balance 76 below min 100000 (0 assets)'  
please try to keep some balance (0.1 ALGO) in his account, try 3.8 or 3.9.
