### ISSUE TITLE
No image showing after exporting NFT

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#707]
User testing the export feature for his two NFTS:

1 item is okay or successfully exported
04ec3d6e57d99fb73f617af4 /	SOS #237
1 item arrived with no image- Product key: e830bb879e710e7debc065cb  / NetBit #509

User tried to import back to Curate but all stuck. These are the NFTs:

FIRST NFT:
https://scan.curate.style/txn/752b265ff2908187f12802f8361abc40daeb703c1fe108beb07e58bd7bc6ffa4
product key: 04ec3d6e57d99fb73f617af4 /	SOS #237

SECOND NFT:

https://scan.curate.style/txn/102116ff09394f78e3f509db28e4bedb6db304ebcf54c31d01d99e7ba49b4fa1

Product key: e830bb879e710e7debc065cb NetBit #509

Android v7.50b221971831

Please see image below
![2 (1)](https://user-images.githubusercontent.com/93180831/180934569-65b7ddff-700b-498c-8b12-ac5f44bee36b.jpg)

![sd](https://user-images.githubusercontent.com/93180831/180934651-44447ffa-2d24-41c0-a047-65879424a513.jpg)

**Comment by eventang2015** [comment]
https://admin.curate.style/product/04ec3d6e57d99fb73f617af4/detail
https://admin.curate.style/product/e830bb879e710e7debc065cb/detail
the both  have imgs.

**Comment by Catherineanne91** [comment]
Hi @eventang2015 , got a message from the user:

_Ok, so here is the image showing the transaction where i exported a token into my trust wallet, the next images shows what the nft looked like it was SOS # 237, then the 3rd empty image with the curate logo is what i ended up with after i sent it to my trust wallet then imported it back expecting that it would fix it but it didn't, so the nft was damaged while being exported out of curate, is there a way to restore it?''_

@eventang2015 , he exported it then imported it back and now its not showing in the app.

**Comment by eventang2015** [comment]
https://opensea.io/assets/ethereum/0x93f5e1d82cf74844bdf4913b118f868df06dd8ec/1739382288 
hmm, can he fix this NFT? then I'll re-sync it . 
https://admin.curate.style/product/79e665feafedd7446523ceed/detail
