### ISSUE TITLE
Private Metadata showing when not logged in. 

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#708]
**Describe the bug**
Private Metadata showing when not logged in but viewing the NFT on desktop.

**Screenshots**
<img width="974" alt="image" src="https://user-images.githubusercontent.com/88379508/181637301-dd9c8bab-e8b8-405a-a5b8-8c26bcf1d544.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/88379508/181637358-ba73911f-1046-4a35-869c-a1da21ffa897.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave Browser
 - Version

**Comment by eventang2015** [comment]
fixed, please try again. @TheMad-J-Hatter

**Comment by TheMad-J-Hatter** [comment]
Fixed, thank you.
