### ISSUE TITLE
User tried to Deposit via Circle but USDC did not arrive

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#709]
francyx12@gmail.com
Address wallet: 0xaCcd5B7A1981dC23305f6b009bBa8Abddf4F76f8
Ammount sent: 5 euros 

User:
https://admin.curate.style/users/f2330c1a8d8c8fd9ca72e362cfd98fab22b0

**Comment by eventang2015** [comment]
@Catherineanne91 can you confirm this circle payment is successed ?
id: 57fedea7-a851-4ffc-bf25-f3fd921bf24a
amount: 5 usd.
I can send him xcur.

**Comment by eventang2015** [comment]
SENT him 59.090909 XCUR = 4.55 USD (5USD - 0.45 USD - fee) * 12.98701299 (USDXCUR rate)

**Comment by eventang2015** [comment]
ref to circle payment log -  
`
"data" : {
            "id" : "57fedea7-a851-4ffc-bf25-f3fd921bf24a",
            "type" : "payment",
            "status" : "confirmed",
            "description" : "Merchant Payment",
            "amount" : {
                "amount" : "5.00",
                "currency" : "USD"
            },
            "fees" : {
                "amount" : "0.45",
                "currency" : "USD"
            },
            "createDate" : "2022-07-26T05:35:37.871Z",
            "updateDate" : "2022-07-26T05:35:45.897343Z",
            "merchantId" : "cb69d84a-b068-4d3b-84c4-2fd8071edbf3",
            "merchantWalletId" : "146603682",
            "source" : {
                "id" : "1d3f2228-2986-40a9-9473-e0453c03d85f",
                "type" : "card"
            },
            "refunds" : [],
            "verification" : {
                "cvv" : "pass",
                "avs" : "S",
                "threeDSecure" : "pass"
            },
            "metadata" : {
                "email" : "francyx12@gmail.com"
            }
        }
    }`
