### ISSUE TITLE
Two stakes completed but only one appears on wallet 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#711]
Stake 1 has unlocked and appeared on his wallet:
https://admin.curate.style/stakes/52661e006b578ee2

Stake 2 has completed but rewards and initial staked not on his wallet
https://admin.curate.style/stakes/a349a6abe1771aab

User:https://admin.curate.style/users/9efc1b8db3087642274e2a685f614fc487c3/detail
emechlin@hotmail.com

**Comment by eventang2015** [comment]
same issue as #681 @Catherineanne91 ，the bug is fixed in JUL.

**Comment by eventang2015** [comment]
can download csv on https://admin.curate.style/accounts/5880806343ec45ed230fa45ffa8e139b1bf8
