### ISSUE TITLE
Imported NFTS from Opensea has not arrived in User's Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#712]
User has imported 2 NFTs opensea but has not arrived in his account
Username: unexpectedbrosclub@gmail.com

Import keys:
6c3062866999e310d889dbf5 
Token ID: 22798236187098425693584590075043655826243423296378410126044184572445310582884

4789200e040ee4fecd850e56
Token ID: 	22798236187098425693584590075043655826243423296378410126044184634017961738241

https://mail.google.com/mail/u/2/#inbox/FMfcgzGpHHWjrbClJnSHwlxKnnGHXQbd

**Comment by eventang2015** [comment]
https://admin.curate.style/products/user/a4cf813b43833885fde7dd423e901ad8ecd7/import/logs
they're in pending status.  did he send these 2 NFTs to master account?
are they the following 2 NFTs? 
 **DOESN'T SUPPORT ERC-1155**
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/22798236187098425693584590075043655826243423296378410126044184572445310582884
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/22798236187098425693584590075043655826243423296378410126044184634017961738241
