### ISSUE TITLE
Enable Update or Cancel Auto-renew status of Stakes in the Web-app

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#713]
In the web app there is no option to cancel or update the auto renew status of the stakes. it's only available in the mobile version.

![Screenshot_20220801_203257](https://user-images.githubusercontent.com/93180831/182159925-27673460-9280-4f0b-8840-771a736f8ddc.jpg)

**Comment by Pellar-Spike** [comment]
done

**Comment by Catherineanne91** [comment]
@Pellar-LocNgo can you help me find where in the webapp i can update the status of my stake? For example, id like to auto-renew my existing stakes? 
![stake](https://user-images.githubusercontent.com/93180831/182283754-f4d309b4-9542-4d75-a2a6-b98efec4d6a9.jpg)


Like how we do it in the mobile app: 

https://user-images.githubusercontent.com/93180831/182283877-06670ada-61a9-4769-9fe4-18b29f332303.mp4

**Comment by Pellar-Spike** [comment]
Added. When you click on the record of stakes, there will be a modal for you to update renew stake
