### ISSUE TITLE
Desktop Marketplace Down - Chrome & Edge

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#714]
**Describe the bug**
Desktop Marketplace seems to be down on Google Chrome and MS Edge. I have tested on Brave and Edge from where I am located (Nicaragua) but we are having reports from other locations that the site is down. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/182227873-13b88254-3305-4551-9d49-2cb9cdd4844d.png)

**Desktop (please complete the following information):**
 - OS:
 - Browser: Chrome/Edge
 - Version

**Additional context**

**Comment by doles2** [comment]
During an attack we implemented new firewall rules, please ask the users to try again
