### ISSUE TITLE
Offer is asked in XCUR but priced in USD

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#716]
Android v7.5.0b221971831
email: Catherineanneporter@gmail.com

To reproduce
1. Make an offer on a specific NFT
2. Type the amount in XCUR (10 XCUR)
![296473884_601513897991501_8385301181162023502_n (1)](https://user-images.githubusercontent.com/93180831/182538808-027fba5e-7726-4b63-b659-da91919cddf9.jpg)

4. Go to profile and check "offers made"
5. Offer is priced in USD (126 xcur) instead of 10 xcur
![295900216_472587967554598_1424982545803088208_n (1)](https://user-images.githubusercontent.com/93180831/182538828-85524080-d5bb-4f7a-a143-ddb4ddd2d273.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 make offer will not change NFT's price. your account log:
`{
    "_id" : ObjectId("62ea115d138475105633ab35"),
    "created" : ISODate("2022-08-03T06:10:37.365Z"),
    "account_key" : "d04773792d902143cdbb16db3e9f2610b5ad",
    "type" : "ACCOUNT.LOCK_AMOUNT",
    "amount" : 10,
    "userkey" : "b5a01185138a98cb9192c5d015c2c8a2694c",
    "ip" : "2001:fd8:f099:6aa8:acdb:c262:6d85:a95e, 162.158.178.228, 10.10.2.250",
    "agent" : "Dart/2.16 (dart:io)",
    "operator" : {
        "key" : "b5a01185138a98cb9192c5d015c2c8a2694c",
        "email" : "catherineanneporter@gmail.com"
    },
    "details" : {
        "type" : "Make Offer",
        "amount_locked" : 10,
        "productkey" : "3235b75863b65486057e8b23"
    }
}`
