### ISSUE TITLE
Minimum NFT Price

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#717]
**Describe the enhancement**
Can we please implement a minimum purchase price of $2.50 on all new NFTs please? We are trying to avoid folks accepting offers for 5 XCUR which provides no real commission value to Curate. 

I understand that NFTs that have already been minted and price set might be more difficult to change. However, we can implement a minimum offer price of $2.50. 

I have confirmed this with @curateproject.

**Comment by eventang2015** [comment]
@TheMad-J-Hatter you can update min amount (xcur) on settings page
https://admin.curate.style/settings
![image](https://user-images.githubusercontent.com/28645146/182785775-24af48b2-d037-4c6b-b1a1-73e39f8c5a04.png)

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015, I appreciate this setting is there however, it's only in XCUR. We need something more stable such as setting a value in USD. 

I could set an XCUR price equivalent to $2.5 and next week it could be drastically different. 

Is there a possibility of adding USD values here?

**Comment by TheMad-J-Hatter** [comment]
@eventang2015 any update on this?
