### ISSUE TITLE
User Can't proceed with Staking (APY keeps loading)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#718]
This page keeps loading (apy and stake multiplier)
User can't proceed with stake 
![Image from iOS](https://user-images.githubusercontent.com/93180831/182788254-4b110a51-3c96-446a-9cb7-e6646f575e2c.jpg)

User:[gadithomason1@gmail.com](mailto:gadithomason1@gmail.com)
Android:  v7.50b221971831

**Comment by eventang2015** [comment]
I can get apy and boost value via api (admin user)
` "stake": {
        "enabled": true,
        "apy": 10,
        "min_amount": 50,
        "max_amount": 500000
    },
    "boost": 1.5,
    "boost_product": {
        "key": "df4030ca7de43b4b8377ebf6"
        }`

**Comment by madtocc** [comment]
I am unable to reproduce

https://user-images.githubusercontent.com/12486417/183510238-fce84b33-c425-4088-b9f7-31359e11af07.MP4

**Comment by Catherineanne91** [comment]
thanks @madtocc 
will check again with user if he is still experiencing the issue
