### ISSUE TITLE
Imported NFTs from Opensea is not Showing up in the Collection

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#719]
'The following NFTS should show in this collection:

1.) Divine Anarchy - Spirit Animals ( Key: 88eaa3fe932378f8f5bda167 )

For the following products:

ab2db7d7fd56f83252aad619
249904fdb8d93df783746b9a
620e5a4cb20a473a5e5de3db
f74e5e25b8d050e4cfaf44ae
605c16b23f93f730e8696f40
faceaf2e2f0f2c01cf51eb40
abfc7774f5baed58e3be11a3
f27ea99e2e6aaa8b26a3e20d
521e3676e8d2a02b0d608991
a0b08baac1bd2a18d39cdf43
aa9b2ede87f9dd875953297b
24566fed78c327d1bf6e140b
554e6b9b25d27c11b0809295
c20eb8442e169e8d5879285a
38fdd62c3a31d6f1de499926

**Comment by eventang2015** [comment]
https://admin.curate.style/collections/88eaa3fe932378f8f5bda167

**Comment by Catherineanne91** [comment]
@eventang2015 
Currently, there are two divine anarchy Spirit Animals:

**Collection No. 1:**  Divine Anarchy - Spirit Animals ( Key: 88eaa3fe932378f8f5bda167 )
**Collection No. 2:** Divine Anarch - Spirit Animals ( Key: 9898365bfae55c6162b46bdf ) (edited) 


collection number 1 is the one that contains nfts and should appear on their profile which contains the NFT.
collection number 2 is the one that appears at the moment and doesn't contain nfts.

![collection 1](https://user-images.githubusercontent.com/93180831/183541599-25ecd6af-bc56-420e-9a2b-a0eac96e7f22.jpg)


![collection 2](https://user-images.githubusercontent.com/93180831/183541606-2cd20b36-c76b-4d82-bed7-a4494b42fade.jpg)


Note: Collection no.1 is the collection that should appear (but is currently not showing in user's profile)
1.) Divine Anarchy - Spirit Animals ( Key: 88eaa3fe932378f8f5bda167 )

**Comment by eventang2015** [comment]
assigned colletion no.1 to user https://admin.curate.style/users/530d22cad0284bcebeffd0879f03e30d5abc
