### ISSUE TITLE
Allow an Option for User to set NFT for Sale Upon minting

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#721]
Give user the option to automatically list the NFT in the marketplace once it is approved after submission
it could be a check mark button in the mint page

![Screenshot_20220808-121331_CURATE](https://user-images.githubusercontent.com/93180831/183338007-6996a1c1-312b-4aa1-8dac-45d8897cd433.jpg)

**Comment by eventang2015** [comment]
@madtocc added new field - auto_on_market(bool) when minting .

**Comment by eventang2015** [comment]
@Pellar-LocNgo please add the checkbox on mint page
