### ISSUE TITLE
Exported NFT show in very poor quality

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#722]
Email:  <jorgemmq14@gmail.com>

Exported NFT: 
https://admin.curate.style/product/5f276ade31d2030317acee51/detail

opensea:
https://opensea.io/assets/ethereum/0x93f5e1d82cf74844bdf4913b118f868df06dd8ec/1649968533

User wants the NFT to be of 
![Screenshot_20220807-151357](https://user-images.githubusercontent.com/93180831/183341791-bb76a29a-f41b-4bd4-a32a-cb2d1091559d.jpg)
thesame quality, however, it appears damaged after export. 

![Screenshot_20220807-151603](https://user-images.githubusercontent.com/93180831/183341785-b0298c44-3dbc-4d0f-81f3-e94f841f6142.jpg)

**Comment by eventang2015** [comment]
hmm, for GIF, we didn't do compression.

**Comment by Catherineanne91** [comment]
The user still experiencing thesame problem with resolution @eventang2015 , how can we help him> or is it an issue with opensea?

**Comment by Catherineanne91** [comment]
hi @eventang2015 , according to the user, he does not have a copy of the exported NFT's

" i can't download it because it's got a watermark is there a chance you can extract it from that location without the watermark?"

![Screenshot_20220815-074816](https://user-images.githubusercontent.com/93180831/184790067-645b39df-ac9c-4ae0-ae52-34e743678b38.jpg)
![Screenshot_20220815-074624](https://user-images.githubusercontent.com/93180831/184790068-14300ec2-aa80-4987-a6f2-0bce77dd288c.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 the original creator ?

**Comment by eventang2015** [comment]
@Catherineanne91 refreshed. https://opensea.io/assets/ethereum/0x93f5e1d82cf74844bdf4913b118f868df06dd8ec/1649968533

**Comment by Catherineanne91** [comment]
Thank you even
