### ISSUE TITLE
User purchased USDC via Circle but did not receive token

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#723]
USER  NO. 1
The user bought $25 worth of USDC but never got them
Email: [grazvydaspp@gmail.com](mailto:grazvydaspp@gmail.com)

Money was already deducted from his account

Funds not in the user's wallet: 
https://admin.curate.style/users/e4975bd2d69507e5fd43618b810af3e317e9
![s](https://user-images.githubusercontent.com/93180831/183350705-3ec03b42-e55f-49d1-bbef-c81f4971cc5f.jpg)
![2 (2)](https://user-images.githubusercontent.com/93180831/183350722-3e752021-db76-44c6-8774-f9489377518d.jpg)

USER NO.2
[francyx12@gmail.com](mailto:francyx12@gmail.com)
8 euros
user made a transaction for 8 euros but did not receive any amount, but they deducted the amount from user's account
![Untitled](https://user-images.githubusercontent.com/93180831/183577461-b40b7062-aca2-431d-91e0-18bc9321a722.png)

**Comment by eventang2015** [comment]
@Catherineanne91 can you confirm that the payment id:fece2f0d-3942-42a8-8577-6b8313c5b1ee is confirmed ? 
I checked logs and status is pending / action_required. 
can send him xcur after you confirm the order.

**Comment by eventang2015** [comment]
I can't verify it via api : https://api.circle.com/v1/payments/fece2f0d-3942-42a8-8577-6b8313c5b1ee 
i'm not sure wether the bearer token is expired.

**Comment by eventang2015** [comment]
1. $25 usd
https://scan.curate.style/txn/39d3c36a01e55c9cf25f52a95216a0a15884091d9c2429a2e7ecbabbbb03932c
2. $7 usd
https://scan.curate.style/txn/5c7bcd787c1ff4cc464dd1f298f38351ccd104b9279439b701820f911f1253d6
