### ISSUE TITLE
Please unlock stake for this user

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#724]
[emechlin@hotmail.com](mailto:emechlin@hotmail.com)
User: https://admin.curate.style/users/9efc1b8db3087642274e2a685f614fc487c3/detail

**Comment by eventang2015** [comment]
@Catherineanne91 his stakes are all completed.
![image](https://user-images.githubusercontent.com/28645146/183576730-2d3536aa-ff1e-4b19-acbc-c63ab26eed69.png)
do you mean unlock the remaining locked amount (123.91597867 XCUR)?

**Comment by Catherineanne91** [comment]
@eventang2015 , he has 1037 and 1139 XCUR stakes. he is looking for the 1139 as he claims only the 1037 stake appeared on his wallet

**Comment by eventang2015** [comment]
here's his txns

[Tue Aug 09 2022 14_13_07 GMT+0800_tasks.csv](https://github.com/pellartech/curate/files/9287435/Tue.Aug.09.2022.14_13_07.GMT%2B0800_tasks.csv)
 he deposited 1000 XCUR only.
 staking - lock balance only, won't deduct balance. 
 
![image](https://user-images.githubusercontent.com/28645146/183577877-b7c35b2a-5b2f-4d63-ac89-6e7ff3e097b3.png)

**Comment by Catherineanne91** [comment]
@eventang2015 , why does it show two separate stakes of 1037 and 1139?

**Comment by eventang2015** [comment]
I think I have told you there was a locked amount issue in the last month ~, it has been fixed.
