### ISSUE TITLE
Auction time keeps extending when new offer is made 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#725]
1. when someone clicks on the make offer button, the auction duration increases.
for example the auction of SOS #300, in the first screenshot the auction will end in 16 minutes, in the second screenshot it becomes 46 minutes.
2. it also says that the auction ended, but the duration is still running.

![IMG_20220808_212353_571](https://user-images.githubusercontent.com/93180831/183540066-1835c9a7-aee5-4d61-a52e-2f02c16103f7.jpg)
![IMG_20220808_212348_382](https://user-images.githubusercontent.com/93180831/183540068-d28d9c36-7627-4f17-a8ad-18c42479c6f7.jpg)
![Screenshot_20220808_212324](https://user-images.githubusercontent.com/93180831/183540272-721afc5f-98d4-4a66-b586-4f3790748d42.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91  https://github.com/pellartech/curate/issues/158
make offer doesn't extending bid end time. 
and auction is  ended. https://admin.curate.style/product/666f6d3691014e8e8f0f4f79/edit

**Comment by Catherineanne91** [comment]
@eventang2015 

https://user-images.githubusercontent.com/93180831/183675212-bc8b1341-fa99-4b4e-9d42-31abecac6db5.mp4
