### ISSUE TITLE
NFTS  from Opensea does not appear on User's Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#727]
NFTS from Opensea does not appear on User's Wallet

. User has two ETH nfts which was airdropped to him. The following are the NFTS: 

Titles:  "metal water canister" and "construction tools"

https://opensea.io/assets/ethereum/0x2d87a399b21906ba2689cb334ac77dfa01b76361/3647

https://opensea.io/assets/ethereum/0x2d87a399b21906ba2689cb334ac77dfa01b76361/12356

However, it does not appear on his wallet 
User email: [mmm265418@gmail.com](mailto:mmm265418@gmail.com)

**Comment by eventang2015** [comment]
@Catherineanne91 they're pending and belong the user. 
https://admin.curate.style/product/cdf7a63dd27a73e12f10288a/detail
https://admin.curate.style/product/816b75dbb95fa0e070de0db7/detail
