### ISSUE TITLE
User Stakes Reduced from 9.8k XCUR to 8.9k XCUR

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#728]
This user initially staked 9800 XCUR tokens,
now it is showing only 8900XCUR

User: https://admin.curate.style/users/a7c34d48656571bd1017b53c29eff30b7a9f
Email: [Patnifurkan007@gmail.com](mailto:Patnifurkan007@gmail.com)

Stake (9k XCUR)
https://admin.curate.style/stakes/4448c96771fd7aa1

Total deopost:
8501.866 + 871 (BONUS)  + 135

**Comment by eventang2015** [comment]
@Catherineanne91 it doen't make sense . his last stake amount is 8976.89. 
histories:
![image](https://user-images.githubusercontent.com/28645146/184818287-bcabf80d-6de7-475c-9e89-d6c25a00f86c.png)

**Comment by Catherineanne91** [comment]
@eventang2015 , how can we explain to user? I mean what happened to the 9.7k after stake was completed? he withdraw?, he only had one withdrawal of 130 xcur on March 13

**Comment by eventang2015** [comment]
@Catherineanne91 the last stake:
```
{
    "_id" : ObjectId("62cfa6b8bd13f93a4501eef0"),
    "created" : ISODate("2022-07-14T05:16:40.848Z"),
    "account_key" : "e75b60d6a1145d220b278b22fa962a34b7f7",
    "type" : "ACCOUNT.STAKE_LOCK_AMOUNT",
    "amount" : 8976.89,
    "userkey" : "a7c34d48656571bd1017b53c29eff30b7a9f",
    "ip" : "43.242.116.19, 172.70.191.187, 10.10.4.144",
    "agent" : "Dart/2.16 (dart:io)",
    "operator" : {
        "key" : "a7c34d48656571bd1017b53c29eff30b7a9f",
    },
    "details" : {
        "type" : "Create Stake",
        "product" : null,
        "amount_locked" : 8976.89,
        "auto_renewal" : false,
        "renewal_period" : 0,
        "renewal_compound" : false
    }
}
```

**Comment by eventang2015** [comment]
there was a staked amount = 9748.83
