### ISSUE TITLE
User locked for Failed Login attempts that he didn't do

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#729]
The user received an email , notifying that he have exceeded login attempts and account is locked for an hour even if he says he did not have any failed log in attempts:

EMAIL: sujithpaul@gmail.com

Dear user,

You have received a reminder for the following reason: You have exceeded the limit of your login attempts (5 attempts).

Your account is now locked for 1 hour.

If you believe this is a mistake, please e-mail us a proof-of-work at support@curate.style.

Sincerely,
The CURATE Team

**Comment by eventang2015** [comment]
@Catherineanne91 user's email?

**Comment by Catherineanne91** [comment]
Another user:
gyansadow@gmail.com

Dear user,

You have received a reminder for the following reason: You have exceeded the limit of your login attempts (5 attempts).

Your account is now locked for 1 hour.

If you believe this is a mistake, please e-mail us a proof-of-work at support@curate.style.

Sincerely,
The CURATE Team

**Comment by Catherineanne91** [comment]
@eventang2015 , updated. sorry i missed the email

**Comment by Catherineanne91** [comment]
Another user; lukeepope@gmail.com

Dear user,

You have received a reminder for the following reason: You have exceeded the limit of your login attempts (5 attempts).

Your account is now locked for 1 hour.

If you believe this is a mistake, please e-mail us a proof-of-work at support@curate.style.

Sincerely,
The CURATE Team

**Comment by eventang2015** [comment]
I think they provide invalid login credentials . @Catherineanne91 
they can try login 1 hour later.

**Comment by Catherineanne91** [comment]
@eventang2015 , its just odd coz all three users claim they didnt  log in with wrong credentials. okay i will let them know

**Comment by Catherineanne91** [comment]
kellileigh123@gmail.com - another user

**Comment by eventang2015** [comment]
can they reset password if can't login ?
