### ISSUE TITLE
[System] Withdraw needing approval

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#73]
WIthdraws more than a certain amount > 24 hours will require admin approval

Suggested amount:
ETH: 0.25
XCUR: 1000

@DefiHunter - confirmed

@Even2015 please action once approved - note XCUR ERC20 withdraw comes from master

@madtocc test UI (the response for this withdraw is different)

**Comment by DefiHunter** [comment]
Sounds good 

One better would be if we could make it configurable on the backend
