### ISSUE TITLE
ETH deposit did not arrive

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#730]
User: https://admin.curate.style/users/26dde7703124dd01edb5588241c71b34467a
Email: mlsb777@yahoo.com
Version v7.5.0
IOS 

AMOUNT:   0.5 ETH
(already reset sync time) 
![unnamed (3)](https://user-images.githubusercontent.com/93180831/185038051-71fc381c-d661-4094-9961-35ae7781fbf6.png)

**Comment by eventang2015** [comment]
https://etherscan.io/address/0x226e1671628c47539dd9153e4a92d2dbda060df7#internaltx 
it's an internal txn.

**Comment by Catherineanne91** [comment]
Thanks @eventang2015 , what can i tell the user?

**Comment by eventang2015** [comment]
I will manually sync it tomorrow.

**Comment by Catherineanne91** [comment]
Hi Even. Let me know if synced. Thanks!

**Comment by eventang2015** [comment]
@Catherineanne91 Done.
https://admin.curate.style/accounts/f20b5591631223b910313b5d77d64c1599c2
