### ISSUE TITLE
Failed Purchase of XCUR using USDC

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#731]
Email [a126865762@gmail.com](mailto:a126865762@gmail.com)

Device iOS

App version V7.5.0

Failed purchase of XCUR using USDC

Tried in both mobile app and webapp.

In his account EXT USDC is locked and
Prime USDXC is not locked but both are showing the same amount.
![Image from iOS (4)](https://user-images.githubusercontent.com/93180831/185040618-16788abf-1e1e-4f42-94c1-d7f53b7ae514.jpg)

![Image from iOS (3)](https://user-images.githubusercontent.com/93180831/185040622-7c0082f1-add4-40ee-bc22-f93b8ce6f541.jpg)
![Image from iOS (2)](https://user-images.githubusercontent.com/93180831/185040623-f5ad57d2-3c71-4a86-bd2b-9926b77bd208.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/93180831/185040626-873bd93b-36ff-4875-a41f-6592d6d87405.jpg)

**Comment by eventang2015** [comment]
needs to approve his withdraw @Catherineanne91 
https://admin.curate.style/tasks/withdrawexts?status=notverified

**Comment by Catherineanne91** [comment]
Thanks @eventang2015
