### ISSUE TITLE
Unlock Stake For User (Past Unlock Date)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#732]
Unlock Stake for User:

Email: mihail-114@yandex.ru
Link: https://admin.curate.style/users/68eb20d396d8c686bd16a6e2e03c07c79c7d/detail

stake: https://admin.curate.style/stakes/68737eade3a0f117

Staking Page :
![Screenshot_2022-08-13-15-43-54-536_app wallet curate](https://user-images.githubusercontent.com/93180831/185286850-65ea4363-fb34-4e32-ad1b-fa78496b7d0b.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91 Done.
