### ISSUE TITLE
User Stake Still Locked (Past scheduled unlock date)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#733]
User:
https://admin.curate.style/users/24f9411be29e60376f6d415838907eab5675
Email: nikok@live.ca

Stake: https://admin.curate.style/stakes/239a1f52458fdcf6
Amount locked: 1571.47762488

![1 (1)](https://user-images.githubusercontent.com/93180831/185304923-9e41680f-1e9e-46ac-9ec2-c37138da173d.jpg)

**Comment by eventang2015** [comment]
unlocked.
