### ISSUE TITLE
Data - APY Info

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#734]
https://docs.google.com/spreadsheets/d/1tArs2NJPprMneuJvzjjjryHMofg87TTkBiz5KDahhBg/edit?usp=sharing

>  I have a data request; can you please provide the data for rows 11-17 of the APY tab on the Google sheet above?
>  We need to build a baseline based on the historical data to identify and develop a trend line to forecast growth which we’ll make into a variable as well as a burn curve since it makes sense that tokens won't be staked forever so at some price there will be an expectation of some threshold where we’ll want to slow down for the overall staking program.
> Then we split that number by 1/6 which accounts for each tier (6 tiers) but the tiers percentage being a fixed rate of the staking program wallet e.g.
> Diamond is always 30% of the staking program wallet, Platinum is 24%, etc.,. Higher tiers would reduce its APYs slower than than lower tiers. Joe and I talked that we want to put a hard cap at the top and bottom of each the tiers e.g.
> Diamond 16%-12% APY  in October but then 15%-11% in December because the price has dropped which is eating into the rewards so the APY for that tier reflects that. The Silver tier APY range would drop faster than the Diamond tier APY because we want to reward holders of larger amounts of XCUR.
> Since we already have the math done inside the tiers, we can work out the math between the tiers and then tie it all together. Hope that all makes sense.

**Comment by eventang2015** [comment]
completed in https://github.com/pellartech/curate/issues/737
