### ISSUE TITLE
SOL Deposit did not arrive

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#735]
User:menn25296@gmail.com 
https://admin.curate.style/users/688b3f191dbfd6c76ef7ac858edb70a98522
Amount: 0.12 SOL

https://solscan.io/token/Hm7pNLNhjZFdXQR7Jo8VkhWsoMEH1raefbVf8reogsyS

**Comment by eventang2015** [comment]
received . @Catherineanne91 
https://admin.curate.style/accounts/3ea74ee07729d8690e1062caf3bd35440421
