### ISSUE TITLE
XCUR Missing in Staking

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#736]
Description: User has a total locked amount in wallet is  1258.93322522  XCUR , but total staked is only 1119.87
User has not made any withdrawals

User: https://admin.curate.style/users/b4c92e586551d55301b09f297214475a5497
Email:  florian.corolleur@gmail.com

Locked amount in Admin Panel is 1258.93322522
But active stake is  1119.87 
Stake: https://admin.curate.style/stakes/b768114d19792202

User's total Deposit 1098 
plus bonus 110

Username : florian-RYW
App : 7.5.Ob170 iOS
Adress: 0xA85803EB90aFC9fE9259e9CA76678778A0430a01
![image0 (1)](https://user-images.githubusercontent.com/93180831/185842472-52163555-3149-4056-b7ba-338939da41a5.jpeg)

**Comment by eventang2015** [comment]
@Catherineanne91 adjusted locked amount.
