### ISSUE TITLE
Request for Information - Staking Data for Dynamic Tiers

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#737]
**Describe the Request**

I'm in need of some data from our staking history, please. I will require the data from the beginning of us introducing the 10% base APY. 

If possible, I will require the following in spreadsheet format please:

- Amount of staked xcur month on month
- Total number of user staking each
- Number of user per tier each month
- Total amount of XCUR rewards each month
- Amount of XCUR rewards per tier each month
- Number and type of stake boosters in use each month
- Which tier is the owner in and which type of stake boosting NFTs they are using (in-use NFTs only)

**Additional context**
I am trying to populate this table for Dynamic APY calculations. 

<img width="824" alt="image" src="https://user-images.githubusercontent.com/88379508/185886376-fe37c4a5-13b2-495d-a998-4e0a8cb4bad7.png">

**Comment by eventang2015** [comment]
1. monthly staked and rewards 
```
db.getCollection('stakes').aggregate([
      { $match: { removed:false} },
      {
        $group: {
          _id: { date: { $dateToString: { format: "%Y-%m", date: "$created" } } },
          total_staked: { $sum: "$amount" }, total_rewards: { $sum: "$interest_returns" },total_number_of_stakings: { $sum: 1 },
        }
      },
      { $project: { _id: 0, date: "$_id.date", total_staked: "$total_staked", total_rewards: "$total_rewards" ,total_number_of_stakings: "$total_number_of_stakings" } },
      { $sort: { _id: -1 } },]).toArray();
```
>
```
[
    {
        "date" : "2022-08",
        "total_staked" : NumberDecimal("2043508.76842585"),
        "total_rewards" : NumberDecimal("14759.55567266"),
        "total_number_of_stakings" : 284.0
    },
    {
        "date" : "2022-06",
        "total_staked" : NumberDecimal("3537818.39718384"),
        "total_rewards" : NumberDecimal("99061.43802132"),
        "total_number_of_stakings" : 445.0
    },
    {
        "date" : "2022-01",
        "total_staked" : NumberDecimal("303628.6719"),
        "total_rewards" : NumberDecimal("7881.37979852"),
        "total_number_of_stakings" : 155.0
    },
    {
        "date" : "2022-05",
        "total_staked" : NumberDecimal("1876186.96123496"),
        "total_rewards" : NumberDecimal("47417.63929391"),
        "total_number_of_stakings" : 330.0
    },
    {
        "date" : "2022-02",
        "total_staked" : NumberDecimal("48358.74"),
        "total_rewards" : NumberDecimal("549.37794915"),
        "total_number_of_stakings" : 56.0
    },
    {
        "date" : "2021-12",
        "total_staked" : NumberDecimal("8162.9"),
        "total_rewards" : NumberDecimal("135.27493053"),
        "total_number_of_stakings" : 7.0
    },
    {
        "date" : "2022-04",
        "total_staked" : NumberDecimal("1691424.80"),
        "total_rewards" : NumberDecimal("36000.41784584"),
        "total_number_of_stakings" : 263.0
    },
    {
        "date" : "2022-03",
        "total_staked" : NumberDecimal("10118.89"),
        "total_rewards" : NumberDecimal("69.83009112"),
        "total_number_of_stakings" : 11.0
    },
    {
        "date" : "2022-07",
        "total_staked" : NumberDecimal("2990944.23381166"),
        "total_rewards" : NumberDecimal("71502.79591813"),
        "total_number_of_stakings" : 418.0
    }
]
```

**Comment by eventang2015** [comment]
2.  group by apy -sample 
```
db.getCollection('stakes').aggregate([{ $match: { removed:false,  created: { $gte: ISODate("2022-08-01T00:00:00.000Z"), $lt: ISODate("2022-09-01T00:00:00.000Z") } } },
        {
          $group: {
            _id: { apy: '$apy' },
            total_staked:{ $sum: '$amount'},
            total_number_of_stakings: { $sum: 1 },
            total_rewards: { $sum: "$interest_returns" }
          }
        }]).toArray()
```
group by boost value - sample 
```
db.getCollection('stakes').aggregate([{ $match: { removed:false,apy:20,  created: { $gte: ISODate("2022-08-01T00:00:00.000Z"), $lt: ISODate("2022-09-01T00:00:00.000Z") } } },
        {
          $group: {
            _id: { boost: '$boost' },
            total_staked:{ $sum: '$amount'},
            total_number_of_stakings: { $sum: 1 },
            total_rewards: { $sum: "$interest_returns" }
          }
        }]).toArray()
```

**Comment by eventang2015** [comment]
@TheMad-J-Hatter please check file 
[Copy of Dynamic Tiers - XCUR.xlsx](https://github.com/pellartech/curate/files/9399961/Copy.of.Dynamic.Tiers.-.XCUR.xlsx)

**Comment by TheMad-J-Hatter** [comment]
Hey @eventang2015, thanks for this data, very helpful. I have a few questions. 

In the image: 

1. In Columns C & D, do we have the **total** staked amount of XCUR and total users currently staking? 

Are the figures you have provided new XCUR staked/new users each month or are they compounded month-on-month? I guess I expected to see a compounded total XCUR staked of 12,529,000 (as per our dashboard) for this last month. 

2. I noticed that columns F & K seem to have identical data for Diamond and Platinum for 'Total XCUR Rewards' (28,874.81); is this correct? 

<img width="937" alt="image" src="https://user-images.githubusercontent.com/88379508/186130978-24737f61-3c65-4d5f-970d-a7701c05cb8a.png">

**Comment by eventang2015** [comment]
@TheMad-J-Hatter 
1 . the XCUR Staked on dashboard = all staked amount since staking was enabled.
2 .  the 2ed value should be 2771.65853983
