### ISSUE TITLE
Desktop Web App - Homepage broken

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#738]
**Describe the bug**
The desktop web app homepage appears to be broken. NFTs are not showing in the correct location and in weekly pics, there is no NFT at all.  

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/185898994-dcd38c94-5397-4a33-b6a3-41d4151ff17c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version

**Comment by Pellar-Spike** [comment]
Please review

**Comment by TheMad-J-Hatter** [comment]
Hey @Pellar-LocNgo, thanks for reviewing. 

It appears we still have the weekly pics section showing slightly incorrect. Please can you check this section again please? 

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/88379508/186120410-103e8c8d-bf2b-4dd6-a7df-f58b0e38fbc7.png">

**Comment by TheMad-J-Hatter** [comment]
@Pellar-LocNgo, please can you double check the weekly pics section as there are still only 5 NFTs that are visible. Something doesn't look quite right here. 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/88379508/187722688-d22508e1-4f4e-46d0-90ba-8220c44ccdf5.png">

**Comment by TheMad-J-Hatter** [comment]
@TheOneXi, please see above for reference.

**Comment by TheOneXi** [comment]
@pellarboss can you have a look please?

**Comment by pellarboss** [comment]
this is now resolved

weekly picks was empty (hence it was empty)

please ensure you do weekly picks :)
