### ISSUE TITLE
User Purchased 18 NFTs but only 1 appeared on his account

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#739]
User Purchased 18 NFTs but only 1 appeared on his account.

Buyer:
jasonswircenski@yahoo.com
https://admin.curate.style/users/38c98639bbc67faf2bc768830f92ac57a24b

Seller:
https://admin.curate.style/users/0afb6f8db09d2ea26ae066618c43df7d83bb

Items purchased

Ape Lazy #13
https://admin.curate.style/product/d2e19bff75478d86386d82e0/detail

ape lazy #3
https://admin.curate.style/product/25ae92e1b9158c5c00d55c54/detail

ape lazy #4
https://admin.curate.style/product/ffe60b371922cb039d70773f/detail

ape lazy #7
https://admin.curate.style/product/f2cc168cd545a4f2430648f1/detail

ape lazy #11
https://admin.curate.style/product/f2cc168cd545a4f2430648f1/detail

ape lazy #12
https://admin.curate.style/product/43991e2360513c78a0e36164/detail

ape lazy #13
https://admin.curate.style/product/d2e19bff75478d86386d82e0/detail

ape lazy #14
https://admin.curate.style/product/5f1af4ade849679d74eb089e/detail

ape lazy #15
https://admin.curate.style/product/3229c5749bb4d4d5c8b1401b/detail

ape lazy new 02
https://admin.curate.style/product/48c2deb0257ecd5059363f71/detail

ape lazy new #03
https://admin.curate.style/product/f6c90757e2975a69dc2a1330/detail

https://admin.curate.style/product/af4b37ccb13916f36a309071/detail

https://admin.curate.style/product/e8dd8ea2f9b36d9080e51ee3/detail

https://admin.curate.style/product/93fb47dccdd2b6c77f313cb1/detail

https://admin.curate.style/product/d10facdc91c59e9d600aa0f2/detail

https://admin.curate.style/product/2ad3acbda6aa52d9f2ee94da/detail

https://admin.curate.style/product/adcea54751935bf341263034/detail

https://admin.curate.style/product/f6ce969ebb164963da429f63/detail

https://admin.curate.style/product/f6c90757e2975a69dc2a1330/detail

**Comment by eventang2015** [comment]
@Catherineanne91  his last order is purchased this nft - https://admin.curate.style/product/32e1cf9b98a5e7e31257f763/detail 
I didn't see any **Ownership Logs** against the above NFTs.

**Comment by Catherineanne91** [comment]
@eventang2015  this is a bug. 
he gets notified that his purchase is successful but nothing happens
![300665558_1521729208260056_1551491819090382966_n](https://user-images.githubusercontent.com/93180831/186350347-be8c6f17-aa1d-4092-9aef-f9bc38994d0c.jpg)
![299768472_1240958330077242_8848976745841435622_n](https://user-images.githubusercontent.com/93180831/186350355-d96fec07-1ed1-4343-995d-c1927a7eedfb.jpg)

https://user-images.githubusercontent.com/93180831/186350361-e76e522a-728d-4df5-952a-02c9ed65950b.mp4

**Comment by eventang2015** [comment]
@Catherineanne91  purchase - create a queue in background, and then process the order.
seems the amount doesn't match the NFT's price $6.7 USD. 
https://admin.curate.style/product/25ae92e1b9158c5c00d55c54/detail

**Comment by Catherineanne91** [comment]
@eventang2015. he has 63 xcur remaining and the item is worth more. Ill advise user to fund wallet before purchasing. 
but why is he prompted sale was successful though?

**Comment by eventang2015** [comment]
I think $6.7USD > 63 xcur.
@madtocc can you verify the balance in app and prevent submitting if Insufficient funds.

**Comment by Catherineanne91** [comment]
@eventang2015  @madtocc 
he cant purchase items from https://admin.curate.style/users/0afb6f8db09d2ea26ae066618c43df7d83bb
currently, user has 307 xcur..to buy the NFTs, he would need 179 xcur

**Comment by eventang2015** [comment]
his oreders : 
https://admin.curate.style/products/user/38c98639bbc67faf2bc768830f92ac57a24b/purchase/logs?ordertype=bought

**Comment by Catherineanne91** [comment]
@eventang2015 his problem is that he cant buy from this user https://admin.curate.style/users/0afb6f8db09d2ea26ae066618c43df7d83bb
