### ISSUE TITLE
Notification messages content

### ISSUE THREAD

**Issue by madtocc** [pellartech/curate#74]
Review and ensure all notifications are displayed with a proper msg (user friendly).

e.g
You are the winner of the Auction - ID 
should be
Congrats! You've won the auction - NAME of item

**Comment by pellarboss** [comment]
Here are the notifications, please review and amend:

**Bought an item**
Title: Purchase Item
Message: You have purchased item {name}.

**Sold an item**
T: Item Sold
M: Your item - {name} has been sold.

**Outbid**
T: Out Bidded
M: You have been out bidded by another user

**Item Approved**
T: Item Approved
M: You item {id} has been approved

**Item Denied**
T: Item Denied
M: You listing {key} has been denied

**ID verified**
T: ID Verified
M: Your {type} has successfully been verified

**Auction Ended - Unsold**
T: Auction Ended
M: Your item was not successfully sold in the auction

**Auction Ended - Won - Buyer**
T: Auction Completed
M: You are the winner of your auction - {id}

**Auction Ended - Won - Seller**
T: Auction Completed
M: Your item was successfully sold - {id}

**Deposits XCUR**
T: Funds Received
M: We have received {amount} in your XCUR account

**Deposits ETH**
T: Funds Received
M: We have received {amount} in your ETH account

**BUY XCUR**
T: Funds Processed
M: Your XCUR order has successfully been completed

**Withdraw XCUR**
T: XCUR Withdraw Processed
M: Your withdrawal of {amount} XCUR is now complete

**Withdraw ETH**
T: ETH Withdraw Processed
M: Your withdrawal of {amount} ETH is now complete

**Comment by DefiHunter** [comment]
Outbid
T: OutBid !
M: You have been outbid by another user

**Comment by pellarboss** [comment]
@DefiHunter could you please review all the messages and provide adjustments in one go?

**Comment by curateproject** [comment]
Auction Ended - Won - Buyer
T: Auction Completed
M: You are the winner of your auction - {name of NFT}

Auction Ended - Won - Seller
T: Auction Completed
M: Your item was successfully sold - {name of NFT}

**Comment by curateproject** [comment]
Rest all fine

**Comment by DefiHunter** [comment]
@curateproject pls review
