### ISSUE TITLE
User keeps receiving notification (grey page appears when clicked)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#741]
mohammadkhantomani@gmail.com
Android  V7.5.0b221971831

Issue: User keeps receiving notifications on his phone but when he clicks the notification, a grey page appears when clicked
![22](https://user-images.githubusercontent.com/93180831/186545383-3e7249e9-db84-4909-8762-407dce033881.png)
![11](https://user-images.githubusercontent.com/93180831/186545388-6bd8641c-8231-4a5b-8aad-8ca94b0ac13d.png)

**Comment by eventang2015** [comment]
@madtocc please  take a look.
