### ISSUE TITLE
Buy & Sell Bot = Create Volume

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#743]
Can you create a bot on the marketplace that buys and sells NFTs from itself to create volume on the marketplace

**Comment by eventang2015** [comment]
@TheOneXi do you mean ? 
can view these on profile page.  https://admin-stage.curateapi.io/users/4bcd04d3b4f58c17f947bee4a1b9218d7211
![image](https://user-images.githubusercontent.com/28645146/188582104-a74f6212-6cf0-44a5-9de0-38b97ec7b6dd.png)
