### ISSUE TITLE
Allow Admins to switch any NFT to 'Buy Now' status. 

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#744]
**Describe the feature**
Currently, there is no button or feature that allows Curate admin to change an NFT to 'Buy Now' status. This feature would be very useful.

**Comment by eventang2015** [comment]
@TheMad-J-Hatter 
added a new button on detail page (approved only)
![image](https://user-images.githubusercontent.com/28645146/188581338-d6f46043-113c-49de-b7f3-7a660244675f.png)
