### ISSUE TITLE
Desktop - NFT video is cut short when being viewed on desktop.

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#745]
**Describe the bug**
The NFT video shown is meant to achieve a 360-degree turn, this is shown correctly on the mobile app but not on the desktop. On desktop, the video is cut short and only goes around 45 degrees until it's reset. Please ensure that the video NFT completes its length before resetting.

I'm aware that there are certain formats that don't work in HTML 5 but these videos are MP4 format. We need a fix for this otherwise we will have to burn the NFTs for the artist. 

User Key: f129010ae8ce30b8bdff63a68040bdb169d5
Collection Key: [bf4f1d02a7fad6436ec9fb5c] (https://admin.curate.style/collections/bf4f1d02a7fad6436ec9fb5c)

**Screenshots**

https://user-images.githubusercontent.com/88379508/187724302-bc69d34e-2f64-47c2-b1a7-d474308420e2.mov

https://user-images.githubusercontent.com/88379508/187724317-83fd0e7b-6457-4ec9-8888-affb6116aae5.mov

**Comment by eventang2015** [comment]
@TheMad-J-Hatter these're .gif , not videos.

**Comment by TheMad-J-Hatter** [comment]
@eventang2015 

Even if they are Gifs, the gifs on the mobile app rotate all the way around and the ones on the desktop do not. How can we fix this?
