### ISSUE TITLE
Set NFTs to 'Buy Now' on the mint page. 

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#748]
**Describe the enhancement**
Similar to issue #744, please can you add a check box to the mint page which allows artists to set their NFT to Buy Now status following their mint. This should also be available when minting multiple through the API. 

Please make this available for desktop and mobile. 

**Screenshots**
Checkbox saying 'Set NFT to 'Buy Now'. 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/88379508/188854945-0aa54569-fe27-41b1-bd1c-26998e7eea27.png">

**Comment by eventang2015** [comment]
@TheMad-J-Hatter it's duplicate ? https://github.com/pellartech/curate/issues/721

**Comment by TheMad-J-Hatter** [comment]
ahhh my apologies, I didn't realise that Catherine had already logged the issue. Please ensure that this function is available for desktop minting as well. Thanks @eventang2015
