### ISSUE TITLE
Allow copy/paste tx hash ID

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#75]
![20210702_124713](https://user-images.githubusercontent.com/51517619/124270140-b451b200-db33-11eb-985b-1606f5ff86ac.jpg)

Please display the full hash ID and allow copy and paste  so users can check the status.

**Comment by pellarboss** [comment]
should also allow user to visit etherscan (for ETH / ERC20 related txns)

**Comment by curateproject** [comment]
Yes please
