### ISSUE TITLE
Error shows when User tried to buy XCUR with ETH

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#750]
**Describe the bug**Email: John_manzanilla_10@hotmail.com
https://scan.curate.style/txn/0x8a89aafe6514bc9e7d8f80cf63d4dcfdb2c64f21de9fc45e7aabd618de3deee4
 7.5.0b170 iOS

Error shows when User tried to buy XCUR with ETH

To reproduce
1. Go to wallet
2. Click Xcur
3. Click Buy
4. Select ETH > Review purchase
5. Follow security prompt

Error Shows:

![2 (5)](https://user-images.githubusercontent.com/93180831/189826302-92e67433-1b43-48ee-b550-e65cc9255cb0.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91  resolved. 
https://etherscan.io/address/0xe9a7adc96d339776b217b1d8f22988623414f017
https://admin.curate.style/accounts/5a436ca17a969876ed0b1112f0ff3af6f7a0
