### ISSUE TITLE
NFT's appearing on Curate and Opensea

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#751]
**Describe the bug**

These four NFTs are appearing both in Curate's marketplace and Opensea (with offers made). These NFTs have both been import and export. Why are we still seeing the NFT on our platform if it's been exported?

https://admin.curate.style/product/b70ffafafc710e7c2123dfe2/detail
https://admin.curate.style/product/4418f886d9aa7f8eb57a868f/detail
https://admin.curate.style/product/16a11fefbf2ceab3241585c4/detail
https://admin.curate.style/product/f8f51775a9d713466e1f8816/detail

**Comment by eventang2015** [comment]
updated status to export_completed.
