### ISSUE TITLE
Update algorithm for Weekly Picks

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#753]
Current algorithm for Weekly picks : nft's bid count and favorite count

Please add: NFT's with offer 

![307639894_2715441051926177_1724239847388077049_n](https://user-images.githubusercontent.com/93180831/191668949-dfd82714-b005-4b45-bb00-b151410f7084.jpg)

**Comment by eventang2015** [comment]
@Catherineanne91  I can't see the picture. can you re-upload it ?

**Comment by Catherineanne91** [comment]
@eventang2015 , just a screenshot of the weeklypicks.

**Comment by eventang2015** [comment]
@Catherineanne91 updated.
