### ISSUE TITLE
Error Occurs when Updating Stake

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#754]
Error Occurs when user tries to update stake 

To reproduce:
1. go to wallet
2. Click Xcur
3. Staking
4. click "view stakes"
5. Click active stake
6. update autorenewal status,

This error shows:

![photo_2022-09-20_16-52-15 (1)](https://user-images.githubusercontent.com/93180831/191399618-77a36dec-74ea-46de-9078-85c28d7e3c4b.jpg)

User: [floris@wiepking.org](https://admin.curate.style/users/f8203655e9fe1d58fcd32926715d3e5b0d1d/detail)
https://admin.curate.style/users/f8203655e9fe1d58fcd32926715d3e5b0d1d/detail

Stake: https://admin.curate.style/stakes/894282276e2aa595

**Comment by eventang2015** [comment]
@Catherineanne91 can only renew staking once. and can't renew sub staking (renewed)
