### ISSUE TITLE
User's Stake does not show

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#755]
Username: David-Maier

Email: [david.maier17@gmx.at](mailto:david.maier17@gmx.at)

User's current locked xcur is 579 xcur
but his active stake is only 233 xcur

Stake:
https://admin.curate.style/stakes/283cf1668fcea7d2

![image0](https://user-images.githubusercontent.com/93180831/191670374-b97bc0ba-a045-457e-bb6a-5bbe88bbee07.png)

![image1](https://user-images.githubusercontent.com/93180831/191670381-4dd76628-04ec-4cd1-99f6-348f6484e646.png)

**Comment by eventang2015** [comment]
corrected the balance. @Catherineanne91
