### ISSUE TITLE
Buy NFTs on Curate with any Token

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#756]
**Describe the Feature**
Following our roadmap, we would like the ability for users to buy an NFT using any of our integrated tokens. I understand that there are issues surrounding this so I'd like to see if we can find a solution without having to wrap all the tokens.

**Comment by TheOneXi** [comment]
Ideas:

Only allow supported tokens accepted by the seller first as payment for NFTs i.e on sell page they checkbox which tokens they want to accept

OR

Add a new item on the setting menu 'Accepted Payments' allowing sellers to apply their accepted tokens as payment for all listings (active or future)

Let me know the easier integration @pellarboss @madtocc
