### ISSUE TITLE
Phase 1 - Moonbeam (GLMR) Token Integration

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#757]
**Describe the Integration**
Please can we commence the Moonbeam (GLMR) Token integration as per our Roadmap. This is phase 1 and listing their token on our marketplace is the current expectation. Import/Export will commence in Phase 2 in 2023.

**Comment by TheOneXi** [comment]
You can find network info here:

https://docs.moonbeam.network/

@pellarboss
