### ISSUE TITLE
Phase 2 - ALGO Import/Export and Mint NFT Integration

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#758]
**Describe the Integration**
Please build the ALGO import/export and mint NFT functionality into the Curate app.

**Comment by TheOneXi** [comment]
Similar functionality and UX with the solana NFT import/export and mint functionality

**Comment by TheOneXi** [comment]
Would be great to get started on this if we can @pellarboss (once governance is done)
