### ISSUE TITLE
Price Does not change after user has updated it

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#760]
1. User has updated the Price successfully. 
2.  If seen from the admin panel, the price is already 5000k xcur
3. From the app, it shows 607 xcur

User:   bposh.in.ex@gmail.com
https://admin.curate.style/users/d6d7288c2d530e51fa2dfa46901ae6cc8cc3

NFT: https://admin.curate.style/product/6b459146ce34d3a1e9040e78/detail

![301994279_1102614983721012_1353438897999710334_n](https://user-images.githubusercontent.com/93180831/192949200-2b2a7b79-7481-47eb-9541-5c2bf8cb6512.jpg)
![309511499_493460959040126_667115244185081813_n](https://user-images.githubusercontent.com/93180831/192949208-8feb3a5b-eca9-4164-b94c-2d9e764453b7.jpg)
![299152902_1028552921171069_8024572108126881907_n](https://user-images.githubusercontent.com/93180831/192949210-f7a9c972-286e-4f38-938e-6463df0068e3.jpg)
![image (4)](https://user-images.githubusercontent.com/93180831/192949215-56bf8d48-1d00-4dfd-83df-6a63a33e5ee1.png)

**Comment by eventang2015** [comment]
@madtocc he should update the USD price ,no text box ?

**Comment by Catherineanne91** [comment]
@eventang2015  @madtocc 
7.5.0b170 ios - version of the app

user still experiencing problem
