### ISSUE TITLE
XCUR deposit did not arrive 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#761]
XCURB deposit never arrived
resynced time - still thesame

TxN hash : 0x4ec6665a63e6090c9c357247e089fb82b37bc09fa3ee90f5cc73b0b26bf85793

User: https://admin.curate.style/users/8137fb536edde1f9e8b0d64dfc7864169220

kahchuen@protonmail.com

XCURB Account: 
https://admin.curate.style/accounts/71ac1aecd8f244dc7f203f6388f36b57db74

**Comment by eventang2015** [comment]
https://scan.curate.style/txn/d82ce6a920a5582f6a15cca2c6cda40bfd304064375f9d8309b91f7fbadcea46
resolved . @Catherineanne91
