### ISSUE TITLE
Update weekly picks algirithm

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#762]
Due to inactivity in the app, lets change the algorithm 
from:
picks = (bid count + offers count + fave count ) /2 in the past 24 hours

to:
picks = (bid count + offers count + fave count ) /2 in the **past 7 days**

image below: in the weekly pics below, no image was displayed because there isnt much activity in the app in the past 24 hours
<img width="1071" alt="image (5)" src="https://user-images.githubusercontent.com/93180831/194201205-f238f4bf-ae84-4e38-bc8e-d5a82570df6c.png">

**Comment by eventang2015** [comment]
@Catherineanne91 already updated it.
