### ISSUE TITLE
XCUR staked does not show correct amount

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#763]
User: https://admin.curate.style/users/d3984476f233a6565085cc69741931bf628e
HE staked 595
but his stakes showing only 505
His stake: https://admin.curate.style/stakes/ff1f3f8e296d8631
![Screenshot_20221006-124720](https://user-images.githubusercontent.com/93180831/194699889-bcb1570a-92a6-4583-87ce-3cfd186d9e70.png)

![Screenshot_20221006-124728](https://user-images.githubusercontent.com/93180831/194699894-98eda28f-2f4c-476c-b8a7-96ff785ed7a5.png)

**Comment by eventang2015** [comment]
@Catherineanne91 corrected the locked amount.
