### ISSUE TITLE
User wants to change email - verification email does not arrive to new one

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#764]
User: https://admin.curate.style/users/39846d98bd74141b295c1daa88f33004e85a
previous email:  thesaurabh78@gmail.com

new email: [saurabhpatil0112@gmail.com](mailto:saurabhpatil0112@gmail.com)

**Comment by eventang2015** [comment]
@Catherineanne91  I didn't see the email code in the list below 
![image](https://user-images.githubusercontent.com/28645146/196085474-1d9155a0-25f2-4bd6-abdf-91d55a3c9ab1.png)
can he try again ?
