### ISSUE TITLE
XCUR withdrawal did not arrive

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#765]
https://scan.curate.style/txn/11486d480fe1928af719728e0ab3975c9096fa83bf192bb2ef79de55aa1f21f3

user withdrawed 10 xcur but never arrived. And he didnt receive any notification that it failed or he cant transfer a small amount. Is it because the XCUR is too small?

**Comment by eventang2015** [comment]
https://bscscan.com/address/0xd82a0ec8412f1823bd5ea3fb77dce44c7a3aa5cb#tokentxns

**Comment by eventang2015** [comment]
@Catherineanne91 it's succeed
