### ISSUE TITLE
Governance - Rejected Proposal Reason

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#771]
**Describe the bug**
Please include a text box that shows when a proposal is rejected in the admin portal. This will need to show up in-app to give the community understanding why a proposal was rejected.

**Comment by kane-harry** [comment]
Add reject reason for proposal
![Screenshot from 2022-10-28 10-33-47](https://user-images.githubusercontent.com/104408527/198496438-4fd987db-8ea2-44a3-b20e-3189e0f46774.png)
