### ISSUE TITLE
Governance - Create a 'Pending' button in Admin portal

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#772]
**Describe the bug**
Please provide a 'Pending' button in the Admin portal which will allow Curate to review/edit before a proposal goes live.

Once Curate has reviewed and amended any information/spelling mistakes etc., Curate will set the proposal to Pending, at which point it will appear in-app. 

**Screenshots**
![](https://files.slack.com/files-pri/T01SARMTAQP-F048J2JMJ0Z/image.png)

**Comment by TheMad-J-Hatter** [comment]
![image](https://user-images.githubusercontent.com/88379508/198244690-b94ff879-aaa8-44ec-9aa2-8ac907fcda73.png)

**Comment by kane-harry** [comment]
I will add "Edit" button

**Comment by kane-harry** [comment]
![Kazam_screenshot_00095](https://user-images.githubusercontent.com/104408527/198496657-aedf4d66-2bfb-4dc0-b71b-021c693e82a4.png)
