### ISSUE TITLE
Governance - Proposal Fee

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#773]
**Describe the bug**
In reference and mentioned in issue #633 response to Even's questions, please can you develop a fee mechanism for all proposals. Each proposal should cost $50 worth of XCUR at the time of submission. 

Please include a confirmation tickbox at the bottom before they submit that says,  

'I understand that **XXX** XCUR will be taken from my account for the Proposal fee. I understand that if the proposal is rejected, the XCUR will be debited back into my account.'

If the Proposal is rejected, the XCUR will need to be debited back into the Diamond user's account. 

**Screenshots**
<img width="713" alt="image" src="https://user-images.githubusercontent.com/88379508/198245020-38c4dc95-4fa3-4db5-a2ec-5625277e2213.png">

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/203210291-861b143d-6f8c-4a2c-b727-8ecc0a484b7d.png)
