### ISSUE TITLE
Missing Xcur in User's Wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#777]
[basseyb424@gmail.com](mailto:basseyb424@gmail.com) - 
user should have 106.96899531 in his wallet 

Instead, it has 10.43 and 96.53380388 locked

![photo_2022-10-18_12-05-25 (2)](https://user-images.githubusercontent.com/93180831/199143527-011cfaa1-687c-4f07-9390-ca264db09d08.jpg)

**Comment by eventang2015** [comment]
unlocked for him.
