### ISSUE TITLE
NFT (Curate Hoodie) Purchase didnt Push through (Buyer has enough funds)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#778]
User bought Curate Hoodie, but the transaction didnt push through (Buyer has enough XCUR)
buyer has been notified that the purchase was successful

NFT owner email [Dylanverhage@hotmail.com](mailto:Dylanverhage@hotmail.com)
NFT name: Curate hoodie NFT-2
Buyer email  [oyola16@gmail.com](mailto:oyola16@gmail.com)
The buyer has enough balance. https://admin.curate.style/accounts/8d378be822d74acd73df74f5f5f1001ffbd9

![photo_2022-10-31_14-51-17](https://user-images.githubusercontent.com/93180831/199144524-7faa91b5-5b61-4fab-93ca-0971e99de536.jpg)
![photo_2022-10-31_14-51-14](https://user-images.githubusercontent.com/93180831/199144527-2d4fc53e-8772-47c0-a49c-7d8b60a4574f.jpg)

**Comment by eventang2015** [comment]
the NFT was locked, can he try again ? @Catherineanne91
