### ISSUE TITLE
The App does not approve user's 2FA

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#779]
The user wants to stake [oyola16@gmail.com](mailto:oyola16@gmail.com) but app does not approve his 2fa
Please check video

https://user-images.githubusercontent.com/93180831/199513528-1bd84dc3-a5cc-4f62-bfe0-150726c6cf80.mp4

**Comment by eventang2015** [comment]
@Catherineanne91 it's 2FA code, not  PIN, and he didn't set TOTP.
