### ISSUE TITLE
Documentation for KuCoin

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#78]
compile technical info for KuCoin

**Comment by DefiHunter** [comment]
-Sucirty audit of the code 
-Technical documentation for integration of X-Chain into KuCoin

**Comment by pellarboss** [comment]
Part of BugCrowd tasks

**Comment by curateproject** [comment]
Yes, that's right, is this on track for Sept v3.0 @pellarboss i.e bugcrowd audit?
