### ISSUE TITLE
User's Deposit did not arrive in his wallet

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#780]
User sent 17,386 ($1,035.93) XCUR
https://bscscan.com/tx/0xdeab639a03738fcf76a0dda6b622c1ba2a626847e7263db0bd370d23fa13624d
To his wallet. , but did not arrive

User email: 
 elmaoujoud@gmail.com.

**Comment by eventang2015** [comment]
https://admin.curate.style/accounts/aeac36416df2c62823737b95b516cf783ad8
already received
