### ISSUE TITLE
Governance - Add time zone to closing date/time

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#781]
**Describe the bug**

Please add the UTC Time zone to each proposal closing date/time. We will close on UK timing (UTC +0)

**Comment by kane-harry** [comment]
@TheMad-J-Hatter current end date is ISO string format, ie "2022-11-12T11:54:56.054Z"
about format, nothing to change
i'll change code:
- start_date: open on next day (UTC+0)
- end_date = start_date + 15 days:  close on UTC+0

**Comment by kane-harry** [comment]
Pull https://github.com/pellartech/pellar-federation/pull/1173
