### ISSUE TITLE
Update trustwallet 

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#782]
Can you update the smart contract to the latest xcur address for BEP20 in trustwallet?

- @madtocc you did it last time via commit to their git, let me know the bnb fees if any thanks

**Comment by TheOneXi** [comment]
i e add curate logo onto new smart contract token BEP20 for trust wallet

**Comment by Nanimustshine** [comment]
> i e add curate logo onto new smart contract token BEP20 for trust wallet 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
> i e add curate logo onto new smart contract token BEP20 for trust wallet

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Usernamethoma** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
