### ISSUE TITLE
Credit Card Deposit Did not arrive (Circle)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#783]
User Deposit via credit card did not arrive
Payment
from: Piliušenka Gražvydas Banko sąskaita, LT68 7044 0009 9061 0019
Kam: CIRCLE PYMNTS *CURATE\Wework, 131 Finsbury Pavement\London\EC2A 1NT GBRGBR,
Suma: 31,26 EUR
Data: 2022-11-04 09:26''

Email: [grazvydaspp@gmail.com](mailto:grazvydaspp@gmail.com)

**Comment by eventang2015** [comment]
sent him 904.4317155 XCUR, rate = 30.14772385,  also disabled circle deposit at James's request.

**Comment by Catherineanne91** [comment]
thank you

**Comment by Catherineanne91** [comment]
@eventang2015 , can you please take out his XCUR and give him USDC instead? user asks for USDC ,. thanks
