### ISSUE TITLE
App is not showing User the Correct Stake Booster Tier

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#784]
user: Wannabetrades@gmail.com

UI issue. User has boosting nft and is platinum but shows different in wallet 

![photo_2022-11-10_20-13-14](https://user-images.githubusercontent.com/93180831/201538215-b4c63e1d-ca0a-415c-b258-45e3cef03444.jpg)
![photo_2022-11-10_20-13-07](https://user-images.githubusercontent.com/93180831/201538218-d996a2ad-b918-4eae-b655-f89827eebbdf.jpg)

**Comment by eventang2015** [comment]
he has 2 boost nft and the boost value =1.5X
