### ISSUE TITLE
Deposit does not show in User's Wallet (TWO USERS)

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#785]
USER1: 
user: [Pav7477@gmail.com]
https://admin.curate.style/accounts/f4504ccd1f444e8235ec22f80a93fc08cd61
TXN ID: 0x797f0a15cb1c0a994a82faaaaca198d613556be9e25c7284a2eee1344381ebb2

![photo_2022-11-12_10-07-29 (1)](https://user-images.githubusercontent.com/93180831/201538326-8257881e-51df-451b-b197-673d23696a41.jpg)

User 2:
[victordib1@gmail.com](mailto:victordib1@gmail.com)
https://admin.curate.style/accounts/745bef34e50554404988a1c0dbe756d23a6b
TXN ID: 0xef5b5ccc263a3a0ffe52bbdb6a8b4eab97f31198768090df1b3970feec6bc691 

![photo_2022-11-12_10-29-36](https://user-images.githubusercontent.com/93180831/201538363-ee8517a1-1564-48ac-8a01-98ce321a09de.jpg)

**Comment by eventang2015** [comment]
resolved. @Catherineanne91
