### ISSUE TITLE
Update staking page with new minimum requirement and APYs

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#787]
Diamond: 700,000 XCUR | 15% APY Staking 
Platinum: 550,000 | 12.5% APY Staking 
Gold: 400,000 | 10% APY Staking
Silver: 250,000 | 8% APY Staking 
Bronze: 50,000 | 6% APY Staking 
Standard: 14,300 | 4.5% APY Staking

**Comment by eventang2015** [comment]
updated for production , https://federation.curateapi.io/site/utility/tiers
@madtocc FYI
