### ISSUE TITLE
Completed stakes did not appear in these users wallets

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#788]
Completed stakes did not appear in these users wallets:

tntsport74@gmail.com
muthamizh87@gmail.com

**Comment by eventang2015** [comment]
![image](https://user-images.githubusercontent.com/28645146/204513711-4a23d314-f151-463d-b09e-f8127755ebac.png)
![image](https://user-images.githubusercontent.com/28645146/204513759-cb4db650-23ec-4650-b195-ed2f11435e02.png)
do they have snapshots ? @Catherineanne91
