### ISSUE TITLE
Governance - Links box

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#789]
**Describe the bug**
As per issue #775, the links box has been added but does not save the link when you pull the screen down or select 'Done' in-app. Please fix and ensure the link text appears in the admin panel. This also needs to be a hyperlink for any user viewing the proposal links in-app. 

**Screenshots**

![image](https://user-images.githubusercontent.com/88379508/204495530-c101be60-97a4-4ff1-a8b6-e4df3d12a5cb.png)

**Comment by madtocc** [comment]
Follow the format in the hint. You should input a full url format. https://www.curate.style

**Comment by TheMad-J-Hatter** [comment]
Can you please add 'https://' in each link box by default please. 

Even though it's in the hint, it's not clear that it is needed and therefore I presumed it wasn't working when testing.
