### ISSUE TITLE
Governance - Reviewing proposals in the admin panel

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#790]
**Describe the bug**
As per issue #772 , we still require a 'Pending' button in the admin panel with the ability to choose a future start date; there is only Edit, Accept or Reject. 

When a new proposal comes in, we will review, edit it (if necessary), and then set it to 'Pending' with a start date in the future. This will allow the community to view the proposal before it goes live. 

Snapshot - I presume that the snapshot is taken on the start date (29-11-2022 @ 00:00:00); if this is the case, a pending start date will coincide with the snapshot. Yesterday (28-11-2022) I created a test proposal, it showed the start date was in the past (see screenshot 2) so I was unsure as to how the snapshot correctly recorded everyone's accounts at the time the proposal went live. 

**Screenshots**

1 - There needs to be a 'Pending' where we can set a future start date. Once set to 'Pending' it will be visible in-app.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/88379508/204499858-e95ddf6e-1af7-4d45-84e2-d4b3827c7a9a.png">

2 - The start date was in the past from when I accepted the proposal and therefore how does the snapshot accurately record at the time the proposal goes live? 

![image](https://user-images.githubusercontent.com/88379508/204499639-62f4675b-ea4c-4718-b273-6241a0af6ea1.png)

**Comment by kane-harry** [comment]
Some changes need discuss on admin panel:
- Allow choosing start date and end date (by date picker)
- Add draft to status: draft => pending => active => completed

**Comment by TheMad-J-Hatter** [comment]
Hi @kane-harry, 

Just testing out the Pending button for upcoming proposals. 

When a proposal is set to 'Pending', it does not show up in-app as a Pending proposal. Is there a reason for this? 

Secondly, when choosing a date from the date picker, you cannot 'update' the proposal from the admin panel. Instead when hitting 'update', it deleted the chosen dates. 

Please advise.
