### ISSUE TITLE
Governance - Word Tweak

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#791]
**Describe the bug**
Please amend the transaction to say 'Governance Fee' instead of just 'Fee'. 

**Screenshots**

![image](https://user-images.githubusercontent.com/88379508/204501219-5f2b561a-0fcb-4ea7-b237-63a308e60355.png)

**Comment by kane-harry** [comment]
I'm working on @madtocc on this issue

**Comment by madtocc** [comment]
![image](https://user-images.githubusercontent.com/12486417/205059513-f2d26339-0f62-4913-924a-121d82eddcb7.png)
