### ISSUE TITLE
Governance - Proposal Submittal Note Amendment

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#792]
**Describe the bug**
Please change the note that is displayed at the bottom of the Proposal section. We would also like you to include a tick box that the user has to check before he/she can submit. This shows they have read the information beforehand. 

Please include this note: 

**- I understand that 'XXXX' XCUR ($50), will be taken from my account for the Proposal fee.

- I understand that there will be a maximum of 6 proposals for the upcoming quarter and if my proposal is rejected, the XCUR will be transferred into the Community Governance Reserve.

- I understand that if my proposal is accepted, it will be set to 'Pending' in-app and be given a future start date. The $50 fee will be refunded with an additional $50 rewarded for accepted proposals.**

**Additional Information**
There has been an amendment to the method we will be charging fees for proposals. 

A fee of $50 of XCUR to each user who submits a proposal (Silver Tier and above), but any rejected proposals funds will be transferred into the Community Governance Reserve. Any accepted proposals will get their $50 refund plus another $50 of XCUR as a reward (taken from the Community Governance Reserve). 

**Screenshots**

![image](https://user-images.githubusercontent.com/88379508/204773800-e2f4d3f1-8dd7-4600-8700-153413380d3e.png)

**Comment by madtocc** [comment]
The text was too long, I have added as this:
![image](https://user-images.githubusercontent.com/12486417/205083241-8c4d1a47-8e91-4eef-805b-12bcd965da5b.png)
![image](https://user-images.githubusercontent.com/12486417/205083269-641d5d0f-f4ae-454c-93c0-c5eda7fd5e88.png)
