### ISSUE TITLE
Withdrawing funds

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#793]
The user is trying to withdraw his funds, without any success. With every try, the user receives ''Internal server error''.

Completed steps by the user: 
The app was re-installed and cleared safari data cookies, reset his phone.

Version 7.5.0b170, iOS
tuzelmeier@outlook.com

![2](https://user-images.githubusercontent.com/119655755/205576964-8f42a8d2-8a82-499c-be07-0f7b26275cec.png)

**Comment by eventang2015** [comment]
@Dimitrije52 
it seems that he has withdrawn. here's the txn : https://etherscan.io/tx/0xf5d95966e0f14aa2656e58c18b3561677dc42e510a9a90eb76ba4c8b32bef18b 
https://admin.curate.style/accounts/3e959005492542aaa247180bc2819eb46548

**Comment by Dimitrije52** [comment]
> @Dimitrije52 it seems that he has withdrawn. here's the txn : https://etherscan.io/tx/0xf5d95966e0f14aa2656e58c18b3561677dc42e510a9a90eb76ba4c8b32bef18b https://admin.curate.style/accounts/3e959005492542aaa247180bc2819eb46548

The user used the Desktop app instead, and it worked. Issue solved.
