### ISSUE TITLE
[Admin site] ALGO Asset Opt In

### ISSUE THREAD

**Issue by eventang2015** [pellartech/curate#796]
create a new page to opt-in algo asset for master account.

**Comment by kane-harry** [comment]
Admin site for opt in: https://github.com/pellartech/pellar-admin-web/pull/29
Wait federation for route `POST accounts/master/${key}/opt-in`

**Comment by kane-harry** [comment]
Route on federation: https://github.com/pellartech/pellar-federation/pull/1185
