### ISSUE TITLE
Governance - Vote/Proposal Tier Amendment

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#797]
**Describe the Tweak**
Please can you amend the graphical element in-app and the code to allow all tiers to vote on any proposal. Please can you also amend the ability for Silver Tier and above to create proposals. 

**Screenshots**
<img width="430" alt="image" src="https://user-images.githubusercontent.com/88379508/210339969-4836cef4-a94c-4329-8795-38dcf675fd30.png">

**Comment by TheMad-J-Hatter** [comment]
@pellarboss please confirm once this is complete. These new Tiers and Staking tiers have not yet been updated in the staging app which would be useful for testing before Governance goes live.

**Comment by eventang2015** [comment]
updated tiers in production
