### ISSUE TITLE
Issue with Auction

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#798]
The user jasonswircenski@yahoo.com has a problem with 4 of his auctions. 

All of his NFTs have bids on them and auctions are over, but the NFTs still remain in his wallet, and XCUR did not arrive. 

NFTs: 
Mushroom = 200 xcur 
Moonlight = 161.1863314 xcur
Adventure Awaits = 500 xcur 
Magic = 162 xcur

**Comment by Dimitrije52** [comment]
@pellarboss the user is waiting for the solution.

**Comment by eventang2015** [comment]
@Dimitrije52 just checked the above nfts, they're all fixed price in db.

**Comment by Dimitrije52** [comment]
@eventang2015 they all have bidders, but upon end of the auction, they all remain in the wallet?

**Comment by eventang2015** [comment]
oh, there were some negative bid price(already fixed), they didn't go throuth the application. these bids are cancled. 
could you ask the owner set auction again please ? 
@Dimitrije52
