### ISSUE TITLE
Collection issue

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#799]
The user jasonswircenski@yahoo.com has an issue with his collection ''Zombie University''. 

When the user tries to mint NFTs he wants to attach them to his collection, but it seems impossible for the user, as he has no option to choose this. 

''I created a new collection called Zombie University. Now when I try to mint a new NFT during the minting process it ask which collection you would like to add it to and that particular collection dosent appear I have tried both desktop & from mobile neither way does it come up.''

Version:  7.7.0b175 iOS
Link: https://web.curate.style/collection/4e7639b6677f59b92df58a23

**Comment by eventang2015** [comment]
@Dimitrije52 the imported NFTs are in the CURATE collection by default. can assign the nfts to users collections later.

**Comment by Dimitrije52** [comment]
@eventang2015 
''I have tried this and that collection still dosent show up as an option to pick. I also tried creating another new collection to see if it was just an error with that particular collection and the other new one won’t allow me to choose during minting process or after minting I can’t select either. Was wondering if maybe there is a field limit in collections. Right now I currently have 27 collections including the 2 new ones that I can’t assign any NFTs to so maybe desktop version has a field limit of 25? And the app has a field limit of 10? On the app I have never been able to see more then my first 10 collections during minting process. On the desktop version I can see the first 25 collections I created. Any help would be much appreciated''

**Comment by eventang2015** [comment]
@Dimitrije52 user can't select collection when importing NFTs.
1. user send the nft to master address
2. input the contract address and token id in app, 
3. bot will assign the nft to the user
4. user can update the nft's collection.

**Comment by Dimitrije52** [comment]
@eventang2015 He is minting. Is there a limit to number of collections?

''None are imported, it won’t show any new collections I create  to choose during minting process & also I tried minting a new NFT then assigning it to collection after minting and it’s live and it won’t show any of the new collections I created. So basically the way it is on desktop I can choose any of the first 25 collections I created then any collections after that it won’t show up. On the app it actually only lets me choose between the very first 10 collections I created. This is why I think there might be a field limit setting on the back side preventing from showing up that might be able to be adjusted''

**Comment by Dimitrije52** [comment]
@eventang2015 The user is waiting for an update.

**Comment by eventang2015** [comment]
@Dimitrije52 he should import NFTs into official collection first. https://github.com/pellartech/curate/issues/799#issuecomment-1380033441

**Comment by Dimitrije52** [comment]
@eventang2015 How should he import when he is minting, not importing?

**Comment by Dimitrije52** [comment]
@eventang2015 Can we do anything?

**Comment by Dimitrije52** [comment]
@eventang2015 Can we do anything, or should I inform the user we found no solution?

**Comment by eventang2015** [comment]
@Dimitrije52 any screenshots of minting ?  should be able to select collection on minting page. 
 https://admin.curate.style/collections/4e7639b6677f59b92df58a23
