### ISSUE TITLE
The user sent XCUR to USDC wallet by mistake

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#803]
The user sent XCUR by accident to USDC wallet on the app. 
Can we assist him in the solution?

Ryanmurphy83@hotmail.com

Xcur address  0x20FC5Cb8F011d46C26AdB603C134543eB988D506
Usdc address 0x20FC5Cb8F011d46C26AdB603C134543eB988D506
Send wallet 0x38C63Cf2EA1341327A668809Be68827073aA72Ac
2299.385 xcur

Hash 0x926bd49847b55921a50f792636c729cb1b95371aa719f305d8f7b527ff3bbb06

**Comment by eventang2015** [comment]
he deposited to xcur account
https://admin.curate.style/accounts/d89ebc6d5a323967b79b7f6233242f4c73e0
