### ISSUE TITLE
Governance - Proposal Fee Text - Minor Tweak

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#804]
**Describe the bug**
Please update the 'Proposal Fee' T&C Text. We will be only hosting 3 proposals per quarter instead of 6. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/211314324-39500f20-0eaa-49d3-b0fe-f3d3f02dacb8.png)

**Comment by eventang2015** [comment]
@madtocc please update the text

**Comment by madtocc** [comment]
This is hardcoded and requested [here](https://github.com/pellartech/curate/issues/792). This require re-submission of the app to the stores, can you confirm? it can take a few days to get approved...
