### ISSUE TITLE
The locked bid

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#805]
The user put a bid on an NFT that did not work out, so he bought it for the fixed price later, but now his bid remains locked. 

jasonswircenski@yahoo.com

''So I placed a bid of 278 xcur on Jan 14th on a NFT called the Cyborg copper lion. The auction ended and the NFT never transferred. The seller changed the exact NFT to fixed price sale and I purchased it from him but my bid of 278 xcur is still locked. If you can unlock the bid and return the XCUR to my account that would be great.''

**Comment by Dimitrije52** [comment]
@pellarboss

**Comment by eventang2015** [comment]
unlocked for him.
