### ISSUE TITLE
Delete collection and NFTs

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#807]
The user would want his whole collection with all of his NFTs in there deleted. 

880744d13d5b54d99f48924c

simondash24@gmail.com

**Comment by Dimitrije52** [comment]
@pellarboss

**Comment by eventang2015** [comment]
@Dimitrije52 what do you mean ? delete collection only ?
you can delete the collection on https://admin.curate.style/collections/880744d13d5b54d99f48924c .

**Comment by Dimitrije52** [comment]
@eventang2015 Delete all of the NFTs within the collection, with the collection as well. 

I cannot do that, as NFTs are in there.

**Comment by eventang2015** [comment]
Done.
