### ISSUE TITLE
Governance - Fee for accepted proposals

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#813]
**Describe the bug**
Governance Fee automation is not set up or working correctly. 

**Expected behavior**
When a user submits a proposal, $50 of XCUR is taken from their account. If rejected, the XCUR goes into the Community Governance Reserve, but if accepted, the user's XCUR is refunded along with $50 of XCUR from the Community Governance Reserve. 

When I created the first proposal through the admin panel, my personal account was debited $50 of XCUR, however, once accepted, I did not receive a refund or an extra $50 of XCUR from the community governance reserve. 

1. If a proposal is created through the admin panel, no fee/refund should be applied. 
2. Please ensure automation is set up to refund a user if their proposal is accepted. 
3. Please ensure automation is set up to withdraw $50 of XCUR from Community Governance Reserve and deposited in the user's wallet upon an accepted proposal. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/215077983-c3292055-b3fe-490d-a88d-376eb12d3afb.png)

**Comment by eventang2015** [comment]
currently, proposal fee = $50 USD, when a user submits a proposal, $50 of XCUR is locked from their account.If rejected , unlock the $50 of XCUR, if accepted, the XCUR goes into the master wallet. 
@TheMad-J-Hatter can you clarify the fee please ? 
` If rejected, the XCUR goes into the Community Governance Reserve` ??
 `if accepted, the user's XCUR is refunded` ??
 what is the role of this fee?

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015, I believe you have this the wrong way around. 

We asked a while back for the fee and note (in-app when submitting a proposal) to be amended. It should be: 

- If accepted, the fee is refunded plus an additional $50 in XCUR is rewarded from the community governance reserve. 
- If rejected, the fee goes into the community governance reserve. 

Can you make this change please?  

The role of the fee is to ensure that users make good proposals that are worthy of being voted on.

**Comment by eventang2015** [comment]
Done @TheMad-J-Hatter

**Comment by TheMad-J-Hatter** [comment]
Thank you @eventang2015. I will test it out next week for the next proposal submission to see if everything is in working order.
