### ISSUE TITLE
Governance - Voting with available and staked XCUR. 

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#814]
**Describe the bug**
Currently, only users that have available XCUR in their wallet can cast their vote. Nobody who is staking can vote at all.

**Expected behavior**
We would like all XCUR whether it be available or staked to be used for voting. This may involve the snapshot covering staked XCUR as well.

**Comment by TheMad-J-Hatter** [comment]
@eventang2015 please focus on this issue first.

**Comment by TheMad-J-Hatter** [comment]
@eventang2015, please advise on the completion time.

**Comment by eventang2015** [comment]
done @TheMad-J-Hatter
