### ISSUE TITLE
Governance - Tiers calculation amendment

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#815]
**Describe the bug**
The tiers in-app are only based on the amount of XCUR a user is staking. 

**Expected behavior**
We would like the user's tier to cover both staked and available XCUR based on the amount staked AND/OR the amount of XCUR available in a user's wallet. This makes it much fairer. 

Please note: We tested this out in the official Curate account and this account had 250k XCUR (not staked) but remained at Base tier. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88379508/215081729-6b2087ae-b741-4009-af3e-97283356a3b1.png)

**Comment by eventang2015** [comment]
@TheMad-J-Hatter hmm, do you mean if a user has 750000 xcur, no matter how much xcur he stakes, the apy is 15% ?
```
    "tier" : "diamond",
    "required_tokens" : 700000,
    "apy" : 15,
```

**Comment by eventang2015** [comment]
just checked code, voting tier invlove staking/locked amount.

**Comment by TheMad-J-Hatter** [comment]
Hi @eventang2015,  

I mean that a users tier (see screenshot), should reflect the amount of XCUR they are: 

1. Staking 
AND
3. Available inside their wallet

The screenshot clearly shows that the account has enough XCUR to be a Silver Tier BUT their tier is Base. 

![image](https://user-images.githubusercontent.com/88379508/216015854-e1d8d83c-00e7-4227-a900-d1acc9d4c677.png)

**Comment by eventang2015** [comment]
there're 2 different tiers - staking tier and governance tier. 
staking tier > depends on the amount of staked XCUR. 
governance tier > total XCUR amount.

**Comment by TheMad-J-Hatter** [comment]
ok I understand. 

I would like to see the Governance Tier reflected in the wallet section in-app. If a user has 100,000 staked and 150,000 available in their wallet, they will be 'Silver' tier (250,000 XCUR).

If they are Silver Tier, they should also have:  

- 8% APY for Staking.   
- 2.5% Commission Fee
- Ability to create a Governance proposal

**Comment by eventang2015** [comment]
there's a endpoint to get user's governance tier `/users/:key/governance/tier`. 
and `/users/:key/utility/tier` to get staking tier. I didn't update the APY logic for staking , means staking tier relates to the stake amount. and governance relates to the XCUR's total balance.
