### ISSUE TITLE
Auction Issue

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#818]
The user's auction ended, but now his NFTs seem bugged. 

''Hi,

I've just run a short auction, and now that it's ended I can't seem to update price or relist in a standard sale, or do anything much with them really.

Is it possible to get them reset, and change the price to $5?  I will list them below:-

Vera #0002 through to Vera #0010
Vera #0025 - Vera #0029
Vera #0031 - Vera #0100
Vera #0563 - Vera #0571

It's quite frustrating not having the option to do this myself yet, but your help will be greatly appreciated. 

Cheers,

Mick''

**Comment by Dimitrije52** [comment]
@eventang2015

**Comment by eventang2015** [comment]
@Dimitrije52 I didn't understand this. user want to reset price to $5? can do it in admin site ?

**Comment by Dimitrije52** [comment]
I can change the price, but this is a bug that needs to be solved. @eventang2015

**Comment by Dimitrije52** [comment]
@eventang2015 are we able to check what the issue is? 
Otherwise, I will have to manually chance the price, but there is really a lot of NFTs.

**Comment by eventang2015** [comment]
made a fix for bid ext bot, I'll monitor it. @Dimitrije52

**Comment by eventang2015** [comment]
@Dimitrije52 this should be fixed.
