### ISSUE TITLE
Username requirement for new and existing users

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#82]
Force users to logout and require all existing users on next login to enter a username and require all new users on registration to select a username.

Would like the profile discovery/ search feature to be by username and name of person

And the share URL for profiles to have the username in the URL

**Comment by pellarboss** [comment]
Forcing users to log out isn't so nice, here are some alternatives:
- check point on action - ie, if you want to buy, withdraw = must have a username in place
- OR, curate can email all users without username and asking them to do something

All new users should have username already

**Comment by curateproject** [comment]
Yes let's do a check point for existing users

**Comment by pellarboss** [comment]
@madtocc if user does not have a username, please ask them to create one when selling / withdrawing / buying item / buying xcur

**Comment by DefiHunter** [comment]
I like that @pellarboss , Lets also show the total # of registered usernames on the dashboard, 

This could be a good indicator of active users and active users growing +

**Comment by pellarboss** [comment]
all users now have usernames :)

Marco suggested a brilliant solution, this is now in production
