### ISSUE TITLE
NFT Desktop Banners - Update

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#825]
**Describe the update**
Please can you upload these 4 different banners into the existing NFT desktop banner selection? Can you please use the collection hyperlinks when a user clicks on the banners: 

**The Forgotten:** https://web.curate.style/collection/3c24da03b824f29f9b85880b
**The Time Travelling Vikings**: https://web.curate.style/collection/e133a59bb92566e42e558bc8

**Banners**

1. Large Banner
![Large Banner The Forgotten 1240x200](https://user-images.githubusercontent.com/88379508/223750777-5f896c89-bf9b-42ff-8d9d-6cb12b3e3240.JPG)

2. Large Banner 
![The Time Traveling Vikings Large Banner 1240x200](https://user-images.githubusercontent.com/88379508/223750793-4b54eebc-248d-4641-bf29-4472933fe7ed.JPG)

3. Medium Banner 
![Medium Banner The Forgotten 6040x2000](https://user-images.githubusercontent.com/88379508/223751351-4c6bc35f-3355-47c5-a00c-361b3614d11d.JPG)

4. Medium Banner
![The Time Traveling Vikings Medium Banner 6040x2000](https://user-images.githubusercontent.com/88379508/223751390-6a5e1dff-5714-4abd-b475-769bd0f89f6b.jpg)

**Comment by mason-bee-dev** [comment]
I added it to the site, check in staging, please @TheMad-J-Hatter
