### ISSUE TITLE
Sync the master balance

### ISSUE THREAD

**Issue by Dimitrije52** [pellartech/curate#826]
Can we sync the master account balance in order for staking/withdrawals to properly continue.

**Comment by Dimitrije52** [comment]
@eventang2015 @pellarboss

**Comment by eventang2015** [comment]
https://goto.bscscan.com/token/0xd52669712f253cd6b2fe8a8638f66ed726cb770c?a=0x03D3049c50a2dDeD5425717e3cec338AE5542EeB
@Dimitrije52 ONLY 23.59937529 XCUR in master wallet
