### ISSUE TITLE
[APP] NFT Creator tag

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#85]
On the resale market it is hard to determine who the particular creator of that certain NFT is 

Under the owner title and name 

There should be another title called "Creator" with the username of the person who minted or imported the NFT

**Comment by DefiHunter** [comment]
James review and add comments

**Comment by curateproject** [comment]
Creator tag should be clickable which takes you to their profile page - creator name should always be with the NFT in the app i.e under owners tab but rename this to 'creator' and only show the original creator and mint date (remove the history of owners)

**Comment by DefiHunter** [comment]
@madtocc When designing this feel free to get creative
