### ISSUE TITLE
User dashboard - Selling info

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#88]
Ability for users to view past sales and details of past sales in the My collection tab 

I'll open this for discussion to determine the most user friendly way to present this and if any features I'm missing 

Sale details 
Date sold
Amount 
Buyer

**Comment by pellarboss** [comment]
Where is the info displayed?
In the list - My Collection?
OR in the actual item detail page?

Sales details - what exact info is displayed?
Date sold - previous sales right? 
Amount - previous sold price?
Buyer - previous owners?

**Comment by DefiHunter** [comment]
@curateproject  need help with some suggestions as to how we can easily show users they purchase/sale history

**Comment by DefiHunter** [comment]
@curateproject @pellarboss any suggestions on how best we could present this info to the users and where ?

**Comment by DefiHunter** [comment]
@madtocc would love ur input from a UI perspective too

**Comment by curateproject** [comment]
See answers below @pellarboss @madtocc @DefiHunter @toomingos 

Where is the info displayed?
Ans) My collection page, create a new tab 'Minted NFTs' and display history of minted NFTs and mark if sold and who sold to was.

Sales details - what exact info is displayed?
Ans) Price and buyer username (username feature needs to be added)

Date sold - previous sales right?
Ans) Yes

Amount - previous sold price? 
Yes

Buyer - previous owners?
Just the buyer who bought the item

**Comment by madtocc** [comment]
I guess we should either add an entry to the menu or add a tab, however adding a new tab will need a scroll and I guess the current layout with that segmented control style will be a little bit weird. I guess something like this tab style will be better
![image](https://user-images.githubusercontent.com/12486417/124604812-b4a6c180-de41-11eb-8c9d-5be09cc80616.png). Nevertheless this will be slightly complex page, so I guess it maybe should have a dedicated section.

Regarding the sales I guess it should have a tab to shown the active listings and the ones that are sold.  just the photo + who bought + price + date, ordered by date, for active auction we can show current bid as well (if any). Upon click we can show extra details like previous prices & owners all together or with tabs as we did previously (for sold nfts) and option to cancel/edit listing when it is active.

**Comment by curateproject** [comment]
OK let's go with your suggestions, I do like your UX eye :) @madtocc

**Comment by curateproject** [comment]
Also can you list the NFTs under 'My Collection' tab in 2 or 3 column please so it's similar to the marketplace layout (1 NFT column looks to big)
