### ISSUE TITLE
Affiliate Programme

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#9]
referral links - $100 off your first purchase

**Comment by DefiHunter** [comment]
https://docs.google.com/spreadsheets/d/1lKXa8PuIhluLLp2D93bCnN83Cu-WobQuPrZzGULWmYc/edit?usp=sharing

First Tab is outline for affiliate programme

**Comment by DefiHunter** [comment]
Possible for Sprint 5 @pellarboss

**Comment by pellarboss** [comment]
Let discuss this:
- is this a priority for Sprint 5
- typically each user has a unique referral code
- new users can enter a referral code as a part of the registration
- some incentive is given on the referrer and referred

key element here is how to prevent gaming the system, we've seen in the past, huge bot farms deployed to game the system, ie creating automated signs ups to get the incentive since there are no need for verifications in place. We've also seen bots able to automate email & sms verifications

**Comment by curateproject** [comment]
Hi Roy, yes this is a priority for Sprint 5

Essentially 2 parts:

1) Affiliate

A reward ($10 in XCUR) will be added to their balance after their first purchase or perhaps easier, they get 25% of their first purchase

requirements:
1. KYC approved
2. Promo reward unlocked after 30 days if we go with the cash option

The person making the referrals earns 2% commission on tx from their referred user

2) Promo codes

For us to run discounts during holidays etc which is configurable and enabled/disabled in the admin panel and entered in the settings page in the app.

Codes to start with and their actions:

10% off all purchases = valid once per user 

Let me know your thoughts

**Comment by DefiHunter** [comment]
I like the $10 in xcur after first purchase, Thoughts on locking the reward for 2 weeks after receiving to keep the user on the platform ?

**Comment by curateproject** [comment]
Referrer (person who makes a referral) gets 2% commission on their users sales.

Referrer (person who gets referree) gets $10 in XCUR after their 1st purchase, unlocked after 30 days (i.e show a pending tx in the wallet page 'Unlocked after 30 days')

**Comment by pellarboss** [comment]
the 2% commission, where does it come out from? system fees? ie who is getting less, system or seller?

**Comment by DefiHunter** [comment]
System

**Comment by DefiHunter** [comment]
Roy could we make referrer fee configurable , 

and maybe lets start it at 1.25% instead of 2%

**Comment by DefiHunter** [comment]
Possible alternative model :

Referrer- Receives $15-$25 for each user they refer that makes a purchase 

Referee - receives $15 in XCUR after their first purchase 

@curateproject @pellarboss Thoughts ?

**Comment by DefiHunter** [comment]
New Tab on Admin Dashboard "Affiliate"

Metrics to View 

"Total referred"

"Top referrers"

# of user signed up for each link and the creator of the affiliate link (Name and surname on app)


# of users who made a purchase through each link 


Basically if someone in marketing uses the link, we'd like to measure the success of his campaign through this metrics 

I.e the conversions , the amount of sign ups, the amount of ppl who made a purchase

**Comment by DefiHunter** [comment]
Referrer- Receives 15 XCUR for each user they refer that makes a purchase above 100 XCUR 


Referee - receives 15 XCUR after their first purchase and it is locked for 2 weeks

T&C Purchase has to be 100 XCUR or higher for the referee to receive his 15 in XCUR, Referee 15 XCUR cannot be withdrawn for 3 months. 

User example 

User A refers User B, User B signs up and buys an NFT valued at 50 XCUR, User A does not receive 15 XCUR

User A refers User C, User C purchases an NFT valued at 100 XCUR, User A receves 15 XCUR into his Curate app wallet and User C received 15 XCUR too and can immediately spend it, however User C cannot with draw the 15 XCUR for 3 months.

**Comment by pellarboss** [comment]
I presume the XCUR comes from the master wallet?

The logic is a bit complex, this will take a few more days to build (ETA next week)

**Comment by curateproject** [comment]
Still on track for this for 1.5 @pellarboss?
