### ISSUE TITLE
[APP] Sharing feature - profile

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#94]
from James
> And the share URL for profiles to have the username in the URL

Please investigate and implement

**Comment by madtocc** [comment]
**This feature does not have anything related to the app itself and won't need an update in the app side.**

Due the short time we are using Firebase Dynamic links at the moment which creates the link and deliver different outputs (redirects to a curate style website if it is opened in a desktop, redirects to the store if the app is not installed or opens up the app). Unfortunately it is not possible to create a custom url programmatically using this service. It is possible to create using the console tho, but this will involve manual labour (add id, add website, add application url and package name for each platform for each **user/product**) or using some workaround like using selenium to automate this task.
So we have a few options,
implement our own solution for handling dynamic links
use another service ($)
keep with the existing solution which is free and add the verified ones manually and work on some automation script to create a link for a user/product. We would need another script to go through all the existing users and products and call it every time a new product/user is created.

So either if we change or keep existing one it is not possible to deliver this feature for this sprint.
