### ISSUE TITLE
Third-Party KYC implementation

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#95]
~~Integrating Onfido as our KYC partner
https://onfido.com/signup-thank-you/
Discussion is open~~

RH: More details below

**Comment by curateproject** [comment]
Yes this is something I looked into last week and it's best automated solution

**Comment by pellarboss** [comment]
we also support
https://www.frankieone.com

here are the countries it supports

[Datasources_FrankieOne_(External).xlsx](https://github.com/pellartech/curate/files/6781171/Datasources_FrankieOne_.External.xlsx)

**Comment by DefiHunter** [comment]
Onfido Documentation - https://onfido.mxelm.com/602108d3ac23de18ef3bc714/l/nZiyTpr3rLHbPjHLn?messageId=XCZ66a8XuNAgnxDfp&rn=i0WayJXYDBSZv1kI&re=iUGb5R3cuUGdhJXdjBUZv1mI&sc=false

**Comment by DefiHunter** [comment]
We have decided to go with Jumio 

Frontend Integrations:
Android SDK:  https://github.com/Jumio/mobile-sdk-ios
iOS SDK:  https://github.com/Jumio/mobile-sdk-ios
 
Frontend Customisation:
Android SDK:  https://jumio.github.io/surface-android/
iOS SDK:  https://jumio.github.io/surface-ios/
 
Backend Result Retrieval:
Callback (Push method) -  Https://github.com/Jumio/implementation-guides/blob/master/netverify/callback.md
Retrieval API (Pull method) -  https://github.com/Jumio/implementation-guides/blob/master/netverify/netverify-retrieval-api.md
Customer Portal: https://github.com/Jumio/implementation-guides/blob/master/netverify/portal-settings.md


Please see above API documentation @pellarboss

**Comment by pellarboss** [comment]
Please provide account access ASAP

Please determine which verifications you wish to support, currently we have these user states with:
User ID Verified
and
User Address Verified

Please create a KYC policy document, describing what is required for which action, for example:
- Deposit USDC - ID and Address verification is required
- Withdrawing ETH - ID and Address verification is NOT required

These are the places where we can add checks:
- Depositing USDC
- Withdrawing ETH
- Withdrawing XCUR
- Minting NFT
- Buying XCUR with ETH
- Buying XCUR with USDXC
- Selling NFT
- Buying NFT

Thanks!

**Comment by DefiHunter** [comment]
Places to implement KYC

-Deposit USDC 
- Withdraw USDC

**Comment by pellarboss** [comment]
outcome from yesterdays meeting with Jumio:
1 - Only Identity and Face Match (selfie) is available for Curate - no documentation verification
2 - This means there is only One Stage of verification for users, ID Verified
3 - The data center is to be located in EU

**Comment by curateproject** [comment]
So only passport/driving license/ ID card verification against the face @pellarboss ?

**Comment by pellarboss** [comment]
correct

Address (document) verification does not really exist in Jumio and is not part of your package (as they said over the call)
