### ISSUE TITLE
ERC-1155s

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#99]
Alllowing users to mint ERC-1155 NFTs 

Featured capabilities 

Selling collections 
E.g.
1/50 of a specific collection 

User A have 50 pieces, he mints a Collection to sell his NFT as 1/50 at a fixed price for all the NFTs 

UI 

On users listing page to display 1/50 or 2/50 etc.

**Comment by DefiHunter** [comment]
Open for discussion

**Comment by DefiHunter** [comment]
UI experience -Mint screen

- Chose erc 721 or 1155 

If chose 1155 , new option for Quantity

**Comment by curateproject** [comment]
I agree with this
